import React from "react";
import SVGMapsDinnerDining_20_outlined from '../../svg/maps/MapsDinnerDining/20_outlined.svg';
import SVGMapsDinnerDining_24_outlined from '../../svg/maps/MapsDinnerDining/24_outlined.svg';
import SVGMapsDinnerDining_20_twotone from '../../svg/maps/MapsDinnerDining/20_twotone.svg';
import SVGMapsDinnerDining_24_twotone from '../../svg/maps/MapsDinnerDining/24_twotone.svg';
import SVGMapsDinnerDining_20_sharp from '../../svg/maps/MapsDinnerDining/20_sharp.svg';
import SVGMapsDinnerDining_24_sharp from '../../svg/maps/MapsDinnerDining/24_sharp.svg';
import SVGMapsDinnerDining_20_filled from '../../svg/maps/MapsDinnerDining/20_filled.svg';
import SVGMapsDinnerDining_24_filled from '../../svg/maps/MapsDinnerDining/24_filled.svg';
import SVGMapsDinnerDining_20_round from '../../svg/maps/MapsDinnerDining/20_round.svg';
import SVGMapsDinnerDining_24_round from '../../svg/maps/MapsDinnerDining/24_round.svg';

export const IconMapsDinnerDining20outlined = () => <SVGMapsDinnerDining_20_outlined />;
export const IconMapsDinnerDining24outlined = () => <SVGMapsDinnerDining_24_outlined />;
export const IconMapsDinnerDining20twotone = () => <SVGMapsDinnerDining_20_twotone />;
export const IconMapsDinnerDining24twotone = () => <SVGMapsDinnerDining_24_twotone />;
export const IconMapsDinnerDining20sharp = () => <SVGMapsDinnerDining_20_sharp />;
export const IconMapsDinnerDining24sharp = () => <SVGMapsDinnerDining_24_sharp />;
export const IconMapsDinnerDining20filled = () => <SVGMapsDinnerDining_20_filled />;
export const IconMapsDinnerDining24filled = () => <SVGMapsDinnerDining_24_filled />;
export const IconMapsDinnerDining20round = () => <SVGMapsDinnerDining_20_round />;
export const IconMapsDinnerDining24round = () => <SVGMapsDinnerDining_24_round />;
