import React from "react";
import SVGMapsRamenDining_20_outlined from '../../svg/maps/MapsRamenDining/20_outlined.svg';
import SVGMapsRamenDining_24_outlined from '../../svg/maps/MapsRamenDining/24_outlined.svg';
import SVGMapsRamenDining_20_twotone from '../../svg/maps/MapsRamenDining/20_twotone.svg';
import SVGMapsRamenDining_24_twotone from '../../svg/maps/MapsRamenDining/24_twotone.svg';
import SVGMapsRamenDining_20_sharp from '../../svg/maps/MapsRamenDining/20_sharp.svg';
import SVGMapsRamenDining_24_sharp from '../../svg/maps/MapsRamenDining/24_sharp.svg';
import SVGMapsRamenDining_20_filled from '../../svg/maps/MapsRamenDining/20_filled.svg';
import SVGMapsRamenDining_24_filled from '../../svg/maps/MapsRamenDining/24_filled.svg';
import SVGMapsRamenDining_20_round from '../../svg/maps/MapsRamenDining/20_round.svg';
import SVGMapsRamenDining_24_round from '../../svg/maps/MapsRamenDining/24_round.svg';

export const IconMapsRamenDining20outlined = () => <SVGMapsRamenDining_20_outlined />;
export const IconMapsRamenDining24outlined = () => <SVGMapsRamenDining_24_outlined />;
export const IconMapsRamenDining20twotone = () => <SVGMapsRamenDining_20_twotone />;
export const IconMapsRamenDining24twotone = () => <SVGMapsRamenDining_24_twotone />;
export const IconMapsRamenDining20sharp = () => <SVGMapsRamenDining_20_sharp />;
export const IconMapsRamenDining24sharp = () => <SVGMapsRamenDining_24_sharp />;
export const IconMapsRamenDining20filled = () => <SVGMapsRamenDining_20_filled />;
export const IconMapsRamenDining24filled = () => <SVGMapsRamenDining_24_filled />;
export const IconMapsRamenDining20round = () => <SVGMapsRamenDining_20_round />;
export const IconMapsRamenDining24round = () => <SVGMapsRamenDining_24_round />;
