import React from "react";
import SVGMapsMinorCrash_20_outlined from '../../svg/maps/MapsMinorCrash/20_outlined.svg';
import SVGMapsMinorCrash_24_outlined from '../../svg/maps/MapsMinorCrash/24_outlined.svg';
import SVGMapsMinorCrash_20_twotone from '../../svg/maps/MapsMinorCrash/20_twotone.svg';
import SVGMapsMinorCrash_24_twotone from '../../svg/maps/MapsMinorCrash/24_twotone.svg';
import SVGMapsMinorCrash_20_sharp from '../../svg/maps/MapsMinorCrash/20_sharp.svg';
import SVGMapsMinorCrash_24_sharp from '../../svg/maps/MapsMinorCrash/24_sharp.svg';
import SVGMapsMinorCrash_20_filled from '../../svg/maps/MapsMinorCrash/20_filled.svg';
import SVGMapsMinorCrash_24_filled from '../../svg/maps/MapsMinorCrash/24_filled.svg';
import SVGMapsMinorCrash_20_round from '../../svg/maps/MapsMinorCrash/20_round.svg';
import SVGMapsMinorCrash_24_round from '../../svg/maps/MapsMinorCrash/24_round.svg';

export const IconMapsMinorCrash20outlined = () => <SVGMapsMinorCrash_20_outlined />;
export const IconMapsMinorCrash24outlined = () => <SVGMapsMinorCrash_24_outlined />;
export const IconMapsMinorCrash20twotone = () => <SVGMapsMinorCrash_20_twotone />;
export const IconMapsMinorCrash24twotone = () => <SVGMapsMinorCrash_24_twotone />;
export const IconMapsMinorCrash20sharp = () => <SVGMapsMinorCrash_20_sharp />;
export const IconMapsMinorCrash24sharp = () => <SVGMapsMinorCrash_24_sharp />;
export const IconMapsMinorCrash20filled = () => <SVGMapsMinorCrash_20_filled />;
export const IconMapsMinorCrash24filled = () => <SVGMapsMinorCrash_24_filled />;
export const IconMapsMinorCrash20round = () => <SVGMapsMinorCrash_20_round />;
export const IconMapsMinorCrash24round = () => <SVGMapsMinorCrash_24_round />;
