import React from "react";
import SVGMapsRampRight_20_outlined from '../../svg/maps/MapsRampRight/20_outlined.svg';
import SVGMapsRampRight_24_outlined from '../../svg/maps/MapsRampRight/24_outlined.svg';
import SVGMapsRampRight_20_twotone from '../../svg/maps/MapsRampRight/20_twotone.svg';
import SVGMapsRampRight_24_twotone from '../../svg/maps/MapsRampRight/24_twotone.svg';
import SVGMapsRampRight_20_sharp from '../../svg/maps/MapsRampRight/20_sharp.svg';
import SVGMapsRampRight_24_sharp from '../../svg/maps/MapsRampRight/24_sharp.svg';
import SVGMapsRampRight_20_filled from '../../svg/maps/MapsRampRight/20_filled.svg';
import SVGMapsRampRight_24_filled from '../../svg/maps/MapsRampRight/24_filled.svg';
import SVGMapsRampRight_20_round from '../../svg/maps/MapsRampRight/20_round.svg';
import SVGMapsRampRight_24_round from '../../svg/maps/MapsRampRight/24_round.svg';

export const IconMapsRampRight20outlined = () => <SVGMapsRampRight_20_outlined />;
export const IconMapsRampRight24outlined = () => <SVGMapsRampRight_24_outlined />;
export const IconMapsRampRight20twotone = () => <SVGMapsRampRight_20_twotone />;
export const IconMapsRampRight24twotone = () => <SVGMapsRampRight_24_twotone />;
export const IconMapsRampRight20sharp = () => <SVGMapsRampRight_20_sharp />;
export const IconMapsRampRight24sharp = () => <SVGMapsRampRight_24_sharp />;
export const IconMapsRampRight20filled = () => <SVGMapsRampRight_20_filled />;
export const IconMapsRampRight24filled = () => <SVGMapsRampRight_24_filled />;
export const IconMapsRampRight20round = () => <SVGMapsRampRight_20_round />;
export const IconMapsRampRight24round = () => <SVGMapsRampRight_24_round />;
