import React from "react";
import SVGMapsDeliveryDining_20_outlined from '../../svg/maps/MapsDeliveryDining/20_outlined.svg';
import SVGMapsDeliveryDining_24_outlined from '../../svg/maps/MapsDeliveryDining/24_outlined.svg';
import SVGMapsDeliveryDining_20_twotone from '../../svg/maps/MapsDeliveryDining/20_twotone.svg';
import SVGMapsDeliveryDining_24_twotone from '../../svg/maps/MapsDeliveryDining/24_twotone.svg';
import SVGMapsDeliveryDining_20_sharp from '../../svg/maps/MapsDeliveryDining/20_sharp.svg';
import SVGMapsDeliveryDining_24_sharp from '../../svg/maps/MapsDeliveryDining/24_sharp.svg';
import SVGMapsDeliveryDining_20_filled from '../../svg/maps/MapsDeliveryDining/20_filled.svg';
import SVGMapsDeliveryDining_24_filled from '../../svg/maps/MapsDeliveryDining/24_filled.svg';
import SVGMapsDeliveryDining_20_round from '../../svg/maps/MapsDeliveryDining/20_round.svg';
import SVGMapsDeliveryDining_24_round from '../../svg/maps/MapsDeliveryDining/24_round.svg';

export const IconMapsDeliveryDining20outlined = () => <SVGMapsDeliveryDining_20_outlined />;
export const IconMapsDeliveryDining24outlined = () => <SVGMapsDeliveryDining_24_outlined />;
export const IconMapsDeliveryDining20twotone = () => <SVGMapsDeliveryDining_20_twotone />;
export const IconMapsDeliveryDining24twotone = () => <SVGMapsDeliveryDining_24_twotone />;
export const IconMapsDeliveryDining20sharp = () => <SVGMapsDeliveryDining_20_sharp />;
export const IconMapsDeliveryDining24sharp = () => <SVGMapsDeliveryDining_24_sharp />;
export const IconMapsDeliveryDining20filled = () => <SVGMapsDeliveryDining_20_filled />;
export const IconMapsDeliveryDining24filled = () => <SVGMapsDeliveryDining_24_filled />;
export const IconMapsDeliveryDining20round = () => <SVGMapsDeliveryDining_20_round />;
export const IconMapsDeliveryDining24round = () => <SVGMapsDeliveryDining_24_round />;
