import React from "react";
import SVGMapsMosque_20_outlined from '../../svg/maps/MapsMosque/20_outlined.svg';
import SVGMapsMosque_24_outlined from '../../svg/maps/MapsMosque/24_outlined.svg';
import SVGMapsMosque_20_twotone from '../../svg/maps/MapsMosque/20_twotone.svg';
import SVGMapsMosque_24_twotone from '../../svg/maps/MapsMosque/24_twotone.svg';
import SVGMapsMosque_20_sharp from '../../svg/maps/MapsMosque/20_sharp.svg';
import SVGMapsMosque_24_sharp from '../../svg/maps/MapsMosque/24_sharp.svg';
import SVGMapsMosque_20_filled from '../../svg/maps/MapsMosque/20_filled.svg';
import SVGMapsMosque_24_filled from '../../svg/maps/MapsMosque/24_filled.svg';
import SVGMapsMosque_20_round from '../../svg/maps/MapsMosque/20_round.svg';
import SVGMapsMosque_24_round from '../../svg/maps/MapsMosque/24_round.svg';

export const IconMapsMosque20outlined = () => <SVGMapsMosque_20_outlined />;
export const IconMapsMosque24outlined = () => <SVGMapsMosque_24_outlined />;
export const IconMapsMosque20twotone = () => <SVGMapsMosque_20_twotone />;
export const IconMapsMosque24twotone = () => <SVGMapsMosque_24_twotone />;
export const IconMapsMosque20sharp = () => <SVGMapsMosque_20_sharp />;
export const IconMapsMosque24sharp = () => <SVGMapsMosque_24_sharp />;
export const IconMapsMosque20filled = () => <SVGMapsMosque_20_filled />;
export const IconMapsMosque24filled = () => <SVGMapsMosque_24_filled />;
export const IconMapsMosque20round = () => <SVGMapsMosque_20_round />;
export const IconMapsMosque24round = () => <SVGMapsMosque_24_round />;
