import React from "react";
import SVGMapsNoCrash_20_outlined from '../../svg/maps/MapsNoCrash/20_outlined.svg';
import SVGMapsNoCrash_24_outlined from '../../svg/maps/MapsNoCrash/24_outlined.svg';
import SVGMapsNoCrash_20_twotone from '../../svg/maps/MapsNoCrash/20_twotone.svg';
import SVGMapsNoCrash_24_twotone from '../../svg/maps/MapsNoCrash/24_twotone.svg';
import SVGMapsNoCrash_20_sharp from '../../svg/maps/MapsNoCrash/20_sharp.svg';
import SVGMapsNoCrash_24_sharp from '../../svg/maps/MapsNoCrash/24_sharp.svg';
import SVGMapsNoCrash_20_filled from '../../svg/maps/MapsNoCrash/20_filled.svg';
import SVGMapsNoCrash_24_filled from '../../svg/maps/MapsNoCrash/24_filled.svg';
import SVGMapsNoCrash_20_round from '../../svg/maps/MapsNoCrash/20_round.svg';
import SVGMapsNoCrash_24_round from '../../svg/maps/MapsNoCrash/24_round.svg';

export const IconMapsNoCrash20outlined = () => <SVGMapsNoCrash_20_outlined />;
export const IconMapsNoCrash24outlined = () => <SVGMapsNoCrash_24_outlined />;
export const IconMapsNoCrash20twotone = () => <SVGMapsNoCrash_20_twotone />;
export const IconMapsNoCrash24twotone = () => <SVGMapsNoCrash_24_twotone />;
export const IconMapsNoCrash20sharp = () => <SVGMapsNoCrash_20_sharp />;
export const IconMapsNoCrash24sharp = () => <SVGMapsNoCrash_24_sharp />;
export const IconMapsNoCrash20filled = () => <SVGMapsNoCrash_20_filled />;
export const IconMapsNoCrash24filled = () => <SVGMapsNoCrash_24_filled />;
export const IconMapsNoCrash20round = () => <SVGMapsNoCrash_20_round />;
export const IconMapsNoCrash24round = () => <SVGMapsNoCrash_24_round />;
