import React from "react";
import SVGMapsFestival_20_outlined from '../../svg/maps/MapsFestival/20_outlined.svg';
import SVGMapsFestival_24_outlined from '../../svg/maps/MapsFestival/24_outlined.svg';
import SVGMapsFestival_20_twotone from '../../svg/maps/MapsFestival/20_twotone.svg';
import SVGMapsFestival_24_twotone from '../../svg/maps/MapsFestival/24_twotone.svg';
import SVGMapsFestival_20_sharp from '../../svg/maps/MapsFestival/20_sharp.svg';
import SVGMapsFestival_24_sharp from '../../svg/maps/MapsFestival/24_sharp.svg';
import SVGMapsFestival_20_filled from '../../svg/maps/MapsFestival/20_filled.svg';
import SVGMapsFestival_24_filled from '../../svg/maps/MapsFestival/24_filled.svg';
import SVGMapsFestival_20_round from '../../svg/maps/MapsFestival/20_round.svg';
import SVGMapsFestival_24_round from '../../svg/maps/MapsFestival/24_round.svg';

export const IconMapsFestival20outlined = () => <SVGMapsFestival_20_outlined />;
export const IconMapsFestival24outlined = () => <SVGMapsFestival_24_outlined />;
export const IconMapsFestival20twotone = () => <SVGMapsFestival_20_twotone />;
export const IconMapsFestival24twotone = () => <SVGMapsFestival_24_twotone />;
export const IconMapsFestival20sharp = () => <SVGMapsFestival_20_sharp />;
export const IconMapsFestival24sharp = () => <SVGMapsFestival_24_sharp />;
export const IconMapsFestival20filled = () => <SVGMapsFestival_20_filled />;
export const IconMapsFestival24filled = () => <SVGMapsFestival_24_filled />;
export const IconMapsFestival20round = () => <SVGMapsFestival_20_round />;
export const IconMapsFestival24round = () => <SVGMapsFestival_24_round />;
