import React from "react";
import SVGMapsConnectingAirports_20_outlined from '../../svg/maps/MapsConnectingAirports/20_outlined.svg';
import SVGMapsConnectingAirports_24_outlined from '../../svg/maps/MapsConnectingAirports/24_outlined.svg';
import SVGMapsConnectingAirports_20_twotone from '../../svg/maps/MapsConnectingAirports/20_twotone.svg';
import SVGMapsConnectingAirports_24_twotone from '../../svg/maps/MapsConnectingAirports/24_twotone.svg';
import SVGMapsConnectingAirports_20_sharp from '../../svg/maps/MapsConnectingAirports/20_sharp.svg';
import SVGMapsConnectingAirports_24_sharp from '../../svg/maps/MapsConnectingAirports/24_sharp.svg';
import SVGMapsConnectingAirports_20_filled from '../../svg/maps/MapsConnectingAirports/20_filled.svg';
import SVGMapsConnectingAirports_24_filled from '../../svg/maps/MapsConnectingAirports/24_filled.svg';
import SVGMapsConnectingAirports_20_round from '../../svg/maps/MapsConnectingAirports/20_round.svg';
import SVGMapsConnectingAirports_24_round from '../../svg/maps/MapsConnectingAirports/24_round.svg';

export const IconMapsConnectingAirports20outlined = () => <SVGMapsConnectingAirports_20_outlined />;
export const IconMapsConnectingAirports24outlined = () => <SVGMapsConnectingAirports_24_outlined />;
export const IconMapsConnectingAirports20twotone = () => <SVGMapsConnectingAirports_20_twotone />;
export const IconMapsConnectingAirports24twotone = () => <SVGMapsConnectingAirports_24_twotone />;
export const IconMapsConnectingAirports20sharp = () => <SVGMapsConnectingAirports_20_sharp />;
export const IconMapsConnectingAirports24sharp = () => <SVGMapsConnectingAirports_24_sharp />;
export const IconMapsConnectingAirports20filled = () => <SVGMapsConnectingAirports_20_filled />;
export const IconMapsConnectingAirports24filled = () => <SVGMapsConnectingAirports_24_filled />;
export const IconMapsConnectingAirports20round = () => <SVGMapsConnectingAirports_20_round />;
export const IconMapsConnectingAirports24round = () => <SVGMapsConnectingAirports_24_round />;
