import React from "react";
import SVGMapsTempleHindu_20_outlined from '../../svg/maps/MapsTempleHindu/20_outlined.svg';
import SVGMapsTempleHindu_24_outlined from '../../svg/maps/MapsTempleHindu/24_outlined.svg';
import SVGMapsTempleHindu_20_twotone from '../../svg/maps/MapsTempleHindu/20_twotone.svg';
import SVGMapsTempleHindu_24_twotone from '../../svg/maps/MapsTempleHindu/24_twotone.svg';
import SVGMapsTempleHindu_20_sharp from '../../svg/maps/MapsTempleHindu/20_sharp.svg';
import SVGMapsTempleHindu_24_sharp from '../../svg/maps/MapsTempleHindu/24_sharp.svg';
import SVGMapsTempleHindu_20_filled from '../../svg/maps/MapsTempleHindu/20_filled.svg';
import SVGMapsTempleHindu_24_filled from '../../svg/maps/MapsTempleHindu/24_filled.svg';
import SVGMapsTempleHindu_20_round from '../../svg/maps/MapsTempleHindu/20_round.svg';
import SVGMapsTempleHindu_24_round from '../../svg/maps/MapsTempleHindu/24_round.svg';

export const IconMapsTempleHindu20outlined = () => <SVGMapsTempleHindu_20_outlined />;
export const IconMapsTempleHindu24outlined = () => <SVGMapsTempleHindu_24_outlined />;
export const IconMapsTempleHindu20twotone = () => <SVGMapsTempleHindu_20_twotone />;
export const IconMapsTempleHindu24twotone = () => <SVGMapsTempleHindu_24_twotone />;
export const IconMapsTempleHindu20sharp = () => <SVGMapsTempleHindu_20_sharp />;
export const IconMapsTempleHindu24sharp = () => <SVGMapsTempleHindu_24_sharp />;
export const IconMapsTempleHindu20filled = () => <SVGMapsTempleHindu_20_filled />;
export const IconMapsTempleHindu24filled = () => <SVGMapsTempleHindu_24_filled />;
export const IconMapsTempleHindu20round = () => <SVGMapsTempleHindu_20_round />;
export const IconMapsTempleHindu24round = () => <SVGMapsTempleHindu_24_round />;
