import React from "react";
import SVGMapsBrunchDining_20_outlined from '../../svg/maps/MapsBrunchDining/20_outlined.svg';
import SVGMapsBrunchDining_24_outlined from '../../svg/maps/MapsBrunchDining/24_outlined.svg';
import SVGMapsBrunchDining_20_twotone from '../../svg/maps/MapsBrunchDining/20_twotone.svg';
import SVGMapsBrunchDining_24_twotone from '../../svg/maps/MapsBrunchDining/24_twotone.svg';
import SVGMapsBrunchDining_20_sharp from '../../svg/maps/MapsBrunchDining/20_sharp.svg';
import SVGMapsBrunchDining_24_sharp from '../../svg/maps/MapsBrunchDining/24_sharp.svg';
import SVGMapsBrunchDining_20_filled from '../../svg/maps/MapsBrunchDining/20_filled.svg';
import SVGMapsBrunchDining_24_filled from '../../svg/maps/MapsBrunchDining/24_filled.svg';
import SVGMapsBrunchDining_20_round from '../../svg/maps/MapsBrunchDining/20_round.svg';
import SVGMapsBrunchDining_24_round from '../../svg/maps/MapsBrunchDining/24_round.svg';

export const IconMapsBrunchDining20outlined = () => <SVGMapsBrunchDining_20_outlined />;
export const IconMapsBrunchDining24outlined = () => <SVGMapsBrunchDining_24_outlined />;
export const IconMapsBrunchDining20twotone = () => <SVGMapsBrunchDining_20_twotone />;
export const IconMapsBrunchDining24twotone = () => <SVGMapsBrunchDining_24_twotone />;
export const IconMapsBrunchDining20sharp = () => <SVGMapsBrunchDining_20_sharp />;
export const IconMapsBrunchDining24sharp = () => <SVGMapsBrunchDining_24_sharp />;
export const IconMapsBrunchDining20filled = () => <SVGMapsBrunchDining_20_filled />;
export const IconMapsBrunchDining24filled = () => <SVGMapsBrunchDining_24_filled />;
export const IconMapsBrunchDining20round = () => <SVGMapsBrunchDining_20_round />;
export const IconMapsBrunchDining24round = () => <SVGMapsBrunchDining_24_round />;
