import React from "react";
import SVGMapsFireTruck_20_outlined from '../../svg/maps/MapsFireTruck/20_outlined.svg';
import SVGMapsFireTruck_24_outlined from '../../svg/maps/MapsFireTruck/24_outlined.svg';
import SVGMapsFireTruck_20_twotone from '../../svg/maps/MapsFireTruck/20_twotone.svg';
import SVGMapsFireTruck_24_twotone from '../../svg/maps/MapsFireTruck/24_twotone.svg';
import SVGMapsFireTruck_20_sharp from '../../svg/maps/MapsFireTruck/20_sharp.svg';
import SVGMapsFireTruck_24_sharp from '../../svg/maps/MapsFireTruck/24_sharp.svg';
import SVGMapsFireTruck_20_filled from '../../svg/maps/MapsFireTruck/20_filled.svg';
import SVGMapsFireTruck_24_filled from '../../svg/maps/MapsFireTruck/24_filled.svg';
import SVGMapsFireTruck_20_round from '../../svg/maps/MapsFireTruck/20_round.svg';
import SVGMapsFireTruck_24_round from '../../svg/maps/MapsFireTruck/24_round.svg';

export const IconMapsFireTruck20outlined = () => <SVGMapsFireTruck_20_outlined />;
export const IconMapsFireTruck24outlined = () => <SVGMapsFireTruck_24_outlined />;
export const IconMapsFireTruck20twotone = () => <SVGMapsFireTruck_20_twotone />;
export const IconMapsFireTruck24twotone = () => <SVGMapsFireTruck_24_twotone />;
export const IconMapsFireTruck20sharp = () => <SVGMapsFireTruck_20_sharp />;
export const IconMapsFireTruck24sharp = () => <SVGMapsFireTruck_24_sharp />;
export const IconMapsFireTruck20filled = () => <SVGMapsFireTruck_20_filled />;
export const IconMapsFireTruck24filled = () => <SVGMapsFireTruck_24_filled />;
export const IconMapsFireTruck20round = () => <SVGMapsFireTruck_20_round />;
export const IconMapsFireTruck24round = () => <SVGMapsFireTruck_24_round />;
