import React from "react";
import SVGMapsMedicalInformation_20_outlined from '../../svg/maps/MapsMedicalInformation/20_outlined.svg';
import SVGMapsMedicalInformation_24_outlined from '../../svg/maps/MapsMedicalInformation/24_outlined.svg';
import SVGMapsMedicalInformation_20_twotone from '../../svg/maps/MapsMedicalInformation/20_twotone.svg';
import SVGMapsMedicalInformation_24_twotone from '../../svg/maps/MapsMedicalInformation/24_twotone.svg';
import SVGMapsMedicalInformation_20_sharp from '../../svg/maps/MapsMedicalInformation/20_sharp.svg';
import SVGMapsMedicalInformation_24_sharp from '../../svg/maps/MapsMedicalInformation/24_sharp.svg';
import SVGMapsMedicalInformation_20_filled from '../../svg/maps/MapsMedicalInformation/20_filled.svg';
import SVGMapsMedicalInformation_24_filled from '../../svg/maps/MapsMedicalInformation/24_filled.svg';
import SVGMapsMedicalInformation_20_round from '../../svg/maps/MapsMedicalInformation/20_round.svg';
import SVGMapsMedicalInformation_24_round from '../../svg/maps/MapsMedicalInformation/24_round.svg';

export const IconMapsMedicalInformation20outlined = () => <SVGMapsMedicalInformation_20_outlined />;
export const IconMapsMedicalInformation24outlined = () => <SVGMapsMedicalInformation_24_outlined />;
export const IconMapsMedicalInformation20twotone = () => <SVGMapsMedicalInformation_20_twotone />;
export const IconMapsMedicalInformation24twotone = () => <SVGMapsMedicalInformation_24_twotone />;
export const IconMapsMedicalInformation20sharp = () => <SVGMapsMedicalInformation_20_sharp />;
export const IconMapsMedicalInformation24sharp = () => <SVGMapsMedicalInformation_24_sharp />;
export const IconMapsMedicalInformation20filled = () => <SVGMapsMedicalInformation_20_filled />;
export const IconMapsMedicalInformation24filled = () => <SVGMapsMedicalInformation_24_filled />;
export const IconMapsMedicalInformation20round = () => <SVGMapsMedicalInformation_20_round />;
export const IconMapsMedicalInformation24round = () => <SVGMapsMedicalInformation_24_round />;
