import React from "react";
import SVGMapsLiquor_20_outlined from '../../svg/maps/MapsLiquor/20_outlined.svg';
import SVGMapsLiquor_24_outlined from '../../svg/maps/MapsLiquor/24_outlined.svg';
import SVGMapsLiquor_20_twotone from '../../svg/maps/MapsLiquor/20_twotone.svg';
import SVGMapsLiquor_24_twotone from '../../svg/maps/MapsLiquor/24_twotone.svg';
import SVGMapsLiquor_20_sharp from '../../svg/maps/MapsLiquor/20_sharp.svg';
import SVGMapsLiquor_24_sharp from '../../svg/maps/MapsLiquor/24_sharp.svg';
import SVGMapsLiquor_20_filled from '../../svg/maps/MapsLiquor/20_filled.svg';
import SVGMapsLiquor_24_filled from '../../svg/maps/MapsLiquor/24_filled.svg';
import SVGMapsLiquor_20_round from '../../svg/maps/MapsLiquor/20_round.svg';
import SVGMapsLiquor_24_round from '../../svg/maps/MapsLiquor/24_round.svg';

export const IconMapsLiquor20outlined = () => <SVGMapsLiquor_20_outlined />;
export const IconMapsLiquor24outlined = () => <SVGMapsLiquor_24_outlined />;
export const IconMapsLiquor20twotone = () => <SVGMapsLiquor_20_twotone />;
export const IconMapsLiquor24twotone = () => <SVGMapsLiquor_24_twotone />;
export const IconMapsLiquor20sharp = () => <SVGMapsLiquor_20_sharp />;
export const IconMapsLiquor24sharp = () => <SVGMapsLiquor_24_sharp />;
export const IconMapsLiquor20filled = () => <SVGMapsLiquor_20_filled />;
export const IconMapsLiquor24filled = () => <SVGMapsLiquor_24_filled />;
export const IconMapsLiquor20round = () => <SVGMapsLiquor_20_round />;
export const IconMapsLiquor24round = () => <SVGMapsLiquor_24_round />;
