import React from "react";
import SVGMapsAddBusiness_20_outlined from '../../svg/maps/MapsAddBusiness/20_outlined.svg';
import SVGMapsAddBusiness_24_outlined from '../../svg/maps/MapsAddBusiness/24_outlined.svg';
import SVGMapsAddBusiness_20_twotone from '../../svg/maps/MapsAddBusiness/20_twotone.svg';
import SVGMapsAddBusiness_24_twotone from '../../svg/maps/MapsAddBusiness/24_twotone.svg';
import SVGMapsAddBusiness_20_sharp from '../../svg/maps/MapsAddBusiness/20_sharp.svg';
import SVGMapsAddBusiness_24_sharp from '../../svg/maps/MapsAddBusiness/24_sharp.svg';
import SVGMapsAddBusiness_20_filled from '../../svg/maps/MapsAddBusiness/20_filled.svg';
import SVGMapsAddBusiness_24_filled from '../../svg/maps/MapsAddBusiness/24_filled.svg';
import SVGMapsAddBusiness_20_round from '../../svg/maps/MapsAddBusiness/20_round.svg';
import SVGMapsAddBusiness_24_round from '../../svg/maps/MapsAddBusiness/24_round.svg';

export const IconMapsAddBusiness20outlined = () => <SVGMapsAddBusiness_20_outlined />;
export const IconMapsAddBusiness24outlined = () => <SVGMapsAddBusiness_24_outlined />;
export const IconMapsAddBusiness20twotone = () => <SVGMapsAddBusiness_20_twotone />;
export const IconMapsAddBusiness24twotone = () => <SVGMapsAddBusiness_24_twotone />;
export const IconMapsAddBusiness20sharp = () => <SVGMapsAddBusiness_20_sharp />;
export const IconMapsAddBusiness24sharp = () => <SVGMapsAddBusiness_24_sharp />;
export const IconMapsAddBusiness20filled = () => <SVGMapsAddBusiness_20_filled />;
export const IconMapsAddBusiness24filled = () => <SVGMapsAddBusiness_24_filled />;
export const IconMapsAddBusiness20round = () => <SVGMapsAddBusiness_20_round />;
export const IconMapsAddBusiness24round = () => <SVGMapsAddBusiness_24_round />;
