import React from "react";
import SVGMapsStraight_20_outlined from '../../svg/maps/MapsStraight/20_outlined.svg';
import SVGMapsStraight_24_outlined from '../../svg/maps/MapsStraight/24_outlined.svg';
import SVGMapsStraight_20_twotone from '../../svg/maps/MapsStraight/20_twotone.svg';
import SVGMapsStraight_24_twotone from '../../svg/maps/MapsStraight/24_twotone.svg';
import SVGMapsStraight_20_sharp from '../../svg/maps/MapsStraight/20_sharp.svg';
import SVGMapsStraight_24_sharp from '../../svg/maps/MapsStraight/24_sharp.svg';
import SVGMapsStraight_20_filled from '../../svg/maps/MapsStraight/20_filled.svg';
import SVGMapsStraight_24_filled from '../../svg/maps/MapsStraight/24_filled.svg';
import SVGMapsStraight_20_round from '../../svg/maps/MapsStraight/20_round.svg';
import SVGMapsStraight_24_round from '../../svg/maps/MapsStraight/24_round.svg';

export const IconMapsStraight20outlined = () => <SVGMapsStraight_20_outlined />;
export const IconMapsStraight24outlined = () => <SVGMapsStraight_24_outlined />;
export const IconMapsStraight20twotone = () => <SVGMapsStraight_20_twotone />;
export const IconMapsStraight24twotone = () => <SVGMapsStraight_24_twotone />;
export const IconMapsStraight20sharp = () => <SVGMapsStraight_20_sharp />;
export const IconMapsStraight24sharp = () => <SVGMapsStraight_24_sharp />;
export const IconMapsStraight20filled = () => <SVGMapsStraight_20_filled />;
export const IconMapsStraight24filled = () => <SVGMapsStraight_24_filled />;
export const IconMapsStraight20round = () => <SVGMapsStraight_20_round />;
export const IconMapsStraight24round = () => <SVGMapsStraight_24_round />;
