import React from "react";
import SVGMapsDiamond_20_outlined from '../../svg/maps/MapsDiamond/20_outlined.svg';
import SVGMapsDiamond_24_outlined from '../../svg/maps/MapsDiamond/24_outlined.svg';
import SVGMapsDiamond_20_twotone from '../../svg/maps/MapsDiamond/20_twotone.svg';
import SVGMapsDiamond_24_twotone from '../../svg/maps/MapsDiamond/24_twotone.svg';
import SVGMapsDiamond_20_sharp from '../../svg/maps/MapsDiamond/20_sharp.svg';
import SVGMapsDiamond_24_sharp from '../../svg/maps/MapsDiamond/24_sharp.svg';
import SVGMapsDiamond_20_filled from '../../svg/maps/MapsDiamond/20_filled.svg';
import SVGMapsDiamond_24_filled from '../../svg/maps/MapsDiamond/24_filled.svg';
import SVGMapsDiamond_20_round from '../../svg/maps/MapsDiamond/20_round.svg';
import SVGMapsDiamond_24_round from '../../svg/maps/MapsDiamond/24_round.svg';

export const IconMapsDiamond20outlined = () => <SVGMapsDiamond_20_outlined />;
export const IconMapsDiamond24outlined = () => <SVGMapsDiamond_24_outlined />;
export const IconMapsDiamond20twotone = () => <SVGMapsDiamond_20_twotone />;
export const IconMapsDiamond24twotone = () => <SVGMapsDiamond_24_twotone />;
export const IconMapsDiamond20sharp = () => <SVGMapsDiamond_20_sharp />;
export const IconMapsDiamond24sharp = () => <SVGMapsDiamond_24_sharp />;
export const IconMapsDiamond20filled = () => <SVGMapsDiamond_20_filled />;
export const IconMapsDiamond24filled = () => <SVGMapsDiamond_24_filled />;
export const IconMapsDiamond20round = () => <SVGMapsDiamond_20_round />;
export const IconMapsDiamond24round = () => <SVGMapsDiamond_24_round />;
