import React from "react";
import SVGMapsCarRental_20_outlined from '../../svg/maps/MapsCarRental/20_outlined.svg';
import SVGMapsCarRental_24_outlined from '../../svg/maps/MapsCarRental/24_outlined.svg';
import SVGMapsCarRental_20_twotone from '../../svg/maps/MapsCarRental/20_twotone.svg';
import SVGMapsCarRental_24_twotone from '../../svg/maps/MapsCarRental/24_twotone.svg';
import SVGMapsCarRental_20_sharp from '../../svg/maps/MapsCarRental/20_sharp.svg';
import SVGMapsCarRental_24_sharp from '../../svg/maps/MapsCarRental/24_sharp.svg';
import SVGMapsCarRental_20_filled from '../../svg/maps/MapsCarRental/20_filled.svg';
import SVGMapsCarRental_24_filled from '../../svg/maps/MapsCarRental/24_filled.svg';
import SVGMapsCarRental_20_round from '../../svg/maps/MapsCarRental/20_round.svg';
import SVGMapsCarRental_24_round from '../../svg/maps/MapsCarRental/24_round.svg';

export const IconMapsCarRental20outlined = () => <SVGMapsCarRental_20_outlined />;
export const IconMapsCarRental24outlined = () => <SVGMapsCarRental_24_outlined />;
export const IconMapsCarRental20twotone = () => <SVGMapsCarRental_20_twotone />;
export const IconMapsCarRental24twotone = () => <SVGMapsCarRental_24_twotone />;
export const IconMapsCarRental20sharp = () => <SVGMapsCarRental_20_sharp />;
export const IconMapsCarRental24sharp = () => <SVGMapsCarRental_24_sharp />;
export const IconMapsCarRental20filled = () => <SVGMapsCarRental_20_filled />;
export const IconMapsCarRental24filled = () => <SVGMapsCarRental_24_filled />;
export const IconMapsCarRental20round = () => <SVGMapsCarRental_20_round />;
export const IconMapsCarRental24round = () => <SVGMapsCarRental_24_round />;
