import React from "react";
import SVGMapsZoomInMap_20_outlined from '../../svg/maps/MapsZoomInMap/20_outlined.svg';
import SVGMapsZoomInMap_24_outlined from '../../svg/maps/MapsZoomInMap/24_outlined.svg';
import SVGMapsZoomInMap_20_twotone from '../../svg/maps/MapsZoomInMap/20_twotone.svg';
import SVGMapsZoomInMap_24_twotone from '../../svg/maps/MapsZoomInMap/24_twotone.svg';
import SVGMapsZoomInMap_20_sharp from '../../svg/maps/MapsZoomInMap/20_sharp.svg';
import SVGMapsZoomInMap_24_sharp from '../../svg/maps/MapsZoomInMap/24_sharp.svg';
import SVGMapsZoomInMap_20_filled from '../../svg/maps/MapsZoomInMap/20_filled.svg';
import SVGMapsZoomInMap_24_filled from '../../svg/maps/MapsZoomInMap/24_filled.svg';
import SVGMapsZoomInMap_20_round from '../../svg/maps/MapsZoomInMap/20_round.svg';
import SVGMapsZoomInMap_24_round from '../../svg/maps/MapsZoomInMap/24_round.svg';

export const IconMapsZoomInMap20outlined = () => <SVGMapsZoomInMap_20_outlined />;
export const IconMapsZoomInMap24outlined = () => <SVGMapsZoomInMap_24_outlined />;
export const IconMapsZoomInMap20twotone = () => <SVGMapsZoomInMap_20_twotone />;
export const IconMapsZoomInMap24twotone = () => <SVGMapsZoomInMap_24_twotone />;
export const IconMapsZoomInMap20sharp = () => <SVGMapsZoomInMap_20_sharp />;
export const IconMapsZoomInMap24sharp = () => <SVGMapsZoomInMap_24_sharp />;
export const IconMapsZoomInMap20filled = () => <SVGMapsZoomInMap_20_filled />;
export const IconMapsZoomInMap24filled = () => <SVGMapsZoomInMap_24_filled />;
export const IconMapsZoomInMap20round = () => <SVGMapsZoomInMap_20_round />;
export const IconMapsZoomInMap24round = () => <SVGMapsZoomInMap_24_round />;
