import React from "react";
import SVGMapsChurch_20_outlined from '../../svg/maps/MapsChurch/20_outlined.svg';
import SVGMapsChurch_24_outlined from '../../svg/maps/MapsChurch/24_outlined.svg';
import SVGMapsChurch_20_twotone from '../../svg/maps/MapsChurch/20_twotone.svg';
import SVGMapsChurch_24_twotone from '../../svg/maps/MapsChurch/24_twotone.svg';
import SVGMapsChurch_20_sharp from '../../svg/maps/MapsChurch/20_sharp.svg';
import SVGMapsChurch_24_sharp from '../../svg/maps/MapsChurch/24_sharp.svg';
import SVGMapsChurch_20_filled from '../../svg/maps/MapsChurch/20_filled.svg';
import SVGMapsChurch_24_filled from '../../svg/maps/MapsChurch/24_filled.svg';
import SVGMapsChurch_20_round from '../../svg/maps/MapsChurch/20_round.svg';
import SVGMapsChurch_24_round from '../../svg/maps/MapsChurch/24_round.svg';

export const IconMapsChurch20outlined = () => <SVGMapsChurch_20_outlined />;
export const IconMapsChurch24outlined = () => <SVGMapsChurch_24_outlined />;
export const IconMapsChurch20twotone = () => <SVGMapsChurch_20_twotone />;
export const IconMapsChurch24twotone = () => <SVGMapsChurch_24_twotone />;
export const IconMapsChurch20sharp = () => <SVGMapsChurch_20_sharp />;
export const IconMapsChurch24sharp = () => <SVGMapsChurch_24_sharp />;
export const IconMapsChurch20filled = () => <SVGMapsChurch_20_filled />;
export const IconMapsChurch24filled = () => <SVGMapsChurch_24_filled />;
export const IconMapsChurch20round = () => <SVGMapsChurch_20_round />;
export const IconMapsChurch24round = () => <SVGMapsChurch_24_round />;
