import React from "react";
import SVGMapsSynagogue_20_outlined from '../../svg/maps/MapsSynagogue/20_outlined.svg';
import SVGMapsSynagogue_24_outlined from '../../svg/maps/MapsSynagogue/24_outlined.svg';
import SVGMapsSynagogue_20_twotone from '../../svg/maps/MapsSynagogue/20_twotone.svg';
import SVGMapsSynagogue_24_twotone from '../../svg/maps/MapsSynagogue/24_twotone.svg';
import SVGMapsSynagogue_20_sharp from '../../svg/maps/MapsSynagogue/20_sharp.svg';
import SVGMapsSynagogue_24_sharp from '../../svg/maps/MapsSynagogue/24_sharp.svg';
import SVGMapsSynagogue_20_filled from '../../svg/maps/MapsSynagogue/20_filled.svg';
import SVGMapsSynagogue_24_filled from '../../svg/maps/MapsSynagogue/24_filled.svg';
import SVGMapsSynagogue_20_round from '../../svg/maps/MapsSynagogue/20_round.svg';
import SVGMapsSynagogue_24_round from '../../svg/maps/MapsSynagogue/24_round.svg';

export const IconMapsSynagogue20outlined = () => <SVGMapsSynagogue_20_outlined />;
export const IconMapsSynagogue24outlined = () => <SVGMapsSynagogue_24_outlined />;
export const IconMapsSynagogue20twotone = () => <SVGMapsSynagogue_20_twotone />;
export const IconMapsSynagogue24twotone = () => <SVGMapsSynagogue_24_twotone />;
export const IconMapsSynagogue20sharp = () => <SVGMapsSynagogue_20_sharp />;
export const IconMapsSynagogue24sharp = () => <SVGMapsSynagogue_24_sharp />;
export const IconMapsSynagogue20filled = () => <SVGMapsSynagogue_20_filled />;
export const IconMapsSynagogue24filled = () => <SVGMapsSynagogue_24_filled />;
export const IconMapsSynagogue20round = () => <SVGMapsSynagogue_20_round />;
export const IconMapsSynagogue24round = () => <SVGMapsSynagogue_24_round />;
