import React from "react";
import SVGMapsEmergency_20_outlined from '../../svg/maps/MapsEmergency/20_outlined.svg';
import SVGMapsEmergency_24_outlined from '../../svg/maps/MapsEmergency/24_outlined.svg';
import SVGMapsEmergency_20_twotone from '../../svg/maps/MapsEmergency/20_twotone.svg';
import SVGMapsEmergency_24_twotone from '../../svg/maps/MapsEmergency/24_twotone.svg';
import SVGMapsEmergency_20_sharp from '../../svg/maps/MapsEmergency/20_sharp.svg';
import SVGMapsEmergency_24_sharp from '../../svg/maps/MapsEmergency/24_sharp.svg';
import SVGMapsEmergency_20_filled from '../../svg/maps/MapsEmergency/20_filled.svg';
import SVGMapsEmergency_24_filled from '../../svg/maps/MapsEmergency/24_filled.svg';
import SVGMapsEmergency_20_round from '../../svg/maps/MapsEmergency/20_round.svg';
import SVGMapsEmergency_24_round from '../../svg/maps/MapsEmergency/24_round.svg';

export const IconMapsEmergency20outlined = () => <SVGMapsEmergency_20_outlined />;
export const IconMapsEmergency24outlined = () => <SVGMapsEmergency_24_outlined />;
export const IconMapsEmergency20twotone = () => <SVGMapsEmergency_20_twotone />;
export const IconMapsEmergency24twotone = () => <SVGMapsEmergency_24_twotone />;
export const IconMapsEmergency20sharp = () => <SVGMapsEmergency_20_sharp />;
export const IconMapsEmergency24sharp = () => <SVGMapsEmergency_24_sharp />;
export const IconMapsEmergency20filled = () => <SVGMapsEmergency_20_filled />;
export const IconMapsEmergency24filled = () => <SVGMapsEmergency_24_filled />;
export const IconMapsEmergency20round = () => <SVGMapsEmergency_20_round />;
export const IconMapsEmergency24round = () => <SVGMapsEmergency_24_round />;
