import React from "react";
import SVGMapsPestControlRodent_20_outlined from '../../svg/maps/MapsPestControlRodent/20_outlined.svg';
import SVGMapsPestControlRodent_24_outlined from '../../svg/maps/MapsPestControlRodent/24_outlined.svg';
import SVGMapsPestControlRodent_20_twotone from '../../svg/maps/MapsPestControlRodent/20_twotone.svg';
import SVGMapsPestControlRodent_24_twotone from '../../svg/maps/MapsPestControlRodent/24_twotone.svg';
import SVGMapsPestControlRodent_20_sharp from '../../svg/maps/MapsPestControlRodent/20_sharp.svg';
import SVGMapsPestControlRodent_24_sharp from '../../svg/maps/MapsPestControlRodent/24_sharp.svg';
import SVGMapsPestControlRodent_20_filled from '../../svg/maps/MapsPestControlRodent/20_filled.svg';
import SVGMapsPestControlRodent_24_filled from '../../svg/maps/MapsPestControlRodent/24_filled.svg';
import SVGMapsPestControlRodent_20_round from '../../svg/maps/MapsPestControlRodent/20_round.svg';
import SVGMapsPestControlRodent_24_round from '../../svg/maps/MapsPestControlRodent/24_round.svg';

export const IconMapsPestControlRodent20outlined = () => <SVGMapsPestControlRodent_20_outlined />;
export const IconMapsPestControlRodent24outlined = () => <SVGMapsPestControlRodent_24_outlined />;
export const IconMapsPestControlRodent20twotone = () => <SVGMapsPestControlRodent_20_twotone />;
export const IconMapsPestControlRodent24twotone = () => <SVGMapsPestControlRodent_24_twotone />;
export const IconMapsPestControlRodent20sharp = () => <SVGMapsPestControlRodent_20_sharp />;
export const IconMapsPestControlRodent24sharp = () => <SVGMapsPestControlRodent_24_sharp />;
export const IconMapsPestControlRodent20filled = () => <SVGMapsPestControlRodent_20_filled />;
export const IconMapsPestControlRodent24filled = () => <SVGMapsPestControlRodent_24_filled />;
export const IconMapsPestControlRodent20round = () => <SVGMapsPestControlRodent_20_round />;
export const IconMapsPestControlRodent24round = () => <SVGMapsPestControlRodent_24_round />;
