import React from "react";
import SVGMapsForkRight_20_outlined from '../../svg/maps/MapsForkRight/20_outlined.svg';
import SVGMapsForkRight_24_outlined from '../../svg/maps/MapsForkRight/24_outlined.svg';
import SVGMapsForkRight_20_twotone from '../../svg/maps/MapsForkRight/20_twotone.svg';
import SVGMapsForkRight_24_twotone from '../../svg/maps/MapsForkRight/24_twotone.svg';
import SVGMapsForkRight_20_sharp from '../../svg/maps/MapsForkRight/20_sharp.svg';
import SVGMapsForkRight_24_sharp from '../../svg/maps/MapsForkRight/24_sharp.svg';
import SVGMapsForkRight_20_filled from '../../svg/maps/MapsForkRight/20_filled.svg';
import SVGMapsForkRight_24_filled from '../../svg/maps/MapsForkRight/24_filled.svg';
import SVGMapsForkRight_20_round from '../../svg/maps/MapsForkRight/20_round.svg';
import SVGMapsForkRight_24_round from '../../svg/maps/MapsForkRight/24_round.svg';

export const IconMapsForkRight20outlined = () => <SVGMapsForkRight_20_outlined />;
export const IconMapsForkRight24outlined = () => <SVGMapsForkRight_24_outlined />;
export const IconMapsForkRight20twotone = () => <SVGMapsForkRight_20_twotone />;
export const IconMapsForkRight24twotone = () => <SVGMapsForkRight_24_twotone />;
export const IconMapsForkRight20sharp = () => <SVGMapsForkRight_20_sharp />;
export const IconMapsForkRight24sharp = () => <SVGMapsForkRight_24_sharp />;
export const IconMapsForkRight20filled = () => <SVGMapsForkRight_20_filled />;
export const IconMapsForkRight24filled = () => <SVGMapsForkRight_24_filled />;
export const IconMapsForkRight20round = () => <SVGMapsForkRight_20_round />;
export const IconMapsForkRight24round = () => <SVGMapsForkRight_24_round />;
