import React from "react";
import SVGMapsElectricRickshaw_20_outlined from '../../svg/maps/MapsElectricRickshaw/20_outlined.svg';
import SVGMapsElectricRickshaw_24_outlined from '../../svg/maps/MapsElectricRickshaw/24_outlined.svg';
import SVGMapsElectricRickshaw_20_twotone from '../../svg/maps/MapsElectricRickshaw/20_twotone.svg';
import SVGMapsElectricRickshaw_24_twotone from '../../svg/maps/MapsElectricRickshaw/24_twotone.svg';
import SVGMapsElectricRickshaw_20_sharp from '../../svg/maps/MapsElectricRickshaw/20_sharp.svg';
import SVGMapsElectricRickshaw_24_sharp from '../../svg/maps/MapsElectricRickshaw/24_sharp.svg';
import SVGMapsElectricRickshaw_20_filled from '../../svg/maps/MapsElectricRickshaw/20_filled.svg';
import SVGMapsElectricRickshaw_24_filled from '../../svg/maps/MapsElectricRickshaw/24_filled.svg';
import SVGMapsElectricRickshaw_20_round from '../../svg/maps/MapsElectricRickshaw/20_round.svg';
import SVGMapsElectricRickshaw_24_round from '../../svg/maps/MapsElectricRickshaw/24_round.svg';

export const IconMapsElectricRickshaw20outlined = () => <SVGMapsElectricRickshaw_20_outlined />;
export const IconMapsElectricRickshaw24outlined = () => <SVGMapsElectricRickshaw_24_outlined />;
export const IconMapsElectricRickshaw20twotone = () => <SVGMapsElectricRickshaw_20_twotone />;
export const IconMapsElectricRickshaw24twotone = () => <SVGMapsElectricRickshaw_24_twotone />;
export const IconMapsElectricRickshaw20sharp = () => <SVGMapsElectricRickshaw_20_sharp />;
export const IconMapsElectricRickshaw24sharp = () => <SVGMapsElectricRickshaw_24_sharp />;
export const IconMapsElectricRickshaw20filled = () => <SVGMapsElectricRickshaw_20_filled />;
export const IconMapsElectricRickshaw24filled = () => <SVGMapsElectricRickshaw_24_filled />;
export const IconMapsElectricRickshaw20round = () => <SVGMapsElectricRickshaw_20_round />;
export const IconMapsElectricRickshaw24round = () => <SVGMapsElectricRickshaw_24_round />;
