import React from "react";
import SVGMapsAirlines_20_outlined from '../../svg/maps/MapsAirlines/20_outlined.svg';
import SVGMapsAirlines_24_outlined from '../../svg/maps/MapsAirlines/24_outlined.svg';
import SVGMapsAirlines_20_twotone from '../../svg/maps/MapsAirlines/20_twotone.svg';
import SVGMapsAirlines_24_twotone from '../../svg/maps/MapsAirlines/24_twotone.svg';
import SVGMapsAirlines_20_sharp from '../../svg/maps/MapsAirlines/20_sharp.svg';
import SVGMapsAirlines_24_sharp from '../../svg/maps/MapsAirlines/24_sharp.svg';
import SVGMapsAirlines_20_filled from '../../svg/maps/MapsAirlines/20_filled.svg';
import SVGMapsAirlines_24_filled from '../../svg/maps/MapsAirlines/24_filled.svg';
import SVGMapsAirlines_20_round from '../../svg/maps/MapsAirlines/20_round.svg';
import SVGMapsAirlines_24_round from '../../svg/maps/MapsAirlines/24_round.svg';

export const IconMapsAirlines20outlined = () => <SVGMapsAirlines_20_outlined />;
export const IconMapsAirlines24outlined = () => <SVGMapsAirlines_24_outlined />;
export const IconMapsAirlines20twotone = () => <SVGMapsAirlines_20_twotone />;
export const IconMapsAirlines24twotone = () => <SVGMapsAirlines_24_twotone />;
export const IconMapsAirlines20sharp = () => <SVGMapsAirlines_20_sharp />;
export const IconMapsAirlines24sharp = () => <SVGMapsAirlines_24_sharp />;
export const IconMapsAirlines20filled = () => <SVGMapsAirlines_20_filled />;
export const IconMapsAirlines24filled = () => <SVGMapsAirlines_24_filled />;
export const IconMapsAirlines20round = () => <SVGMapsAirlines_20_round />;
export const IconMapsAirlines24round = () => <SVGMapsAirlines_24_round />;
