import React from "react";
import SVGMapsTempleBuddhist_20_outlined from '../../svg/maps/MapsTempleBuddhist/20_outlined.svg';
import SVGMapsTempleBuddhist_24_outlined from '../../svg/maps/MapsTempleBuddhist/24_outlined.svg';
import SVGMapsTempleBuddhist_20_twotone from '../../svg/maps/MapsTempleBuddhist/20_twotone.svg';
import SVGMapsTempleBuddhist_24_twotone from '../../svg/maps/MapsTempleBuddhist/24_twotone.svg';
import SVGMapsTempleBuddhist_20_sharp from '../../svg/maps/MapsTempleBuddhist/20_sharp.svg';
import SVGMapsTempleBuddhist_24_sharp from '../../svg/maps/MapsTempleBuddhist/24_sharp.svg';
import SVGMapsTempleBuddhist_20_filled from '../../svg/maps/MapsTempleBuddhist/20_filled.svg';
import SVGMapsTempleBuddhist_24_filled from '../../svg/maps/MapsTempleBuddhist/24_filled.svg';
import SVGMapsTempleBuddhist_20_round from '../../svg/maps/MapsTempleBuddhist/20_round.svg';
import SVGMapsTempleBuddhist_24_round from '../../svg/maps/MapsTempleBuddhist/24_round.svg';

export const IconMapsTempleBuddhist20outlined = () => <SVGMapsTempleBuddhist_20_outlined />;
export const IconMapsTempleBuddhist24outlined = () => <SVGMapsTempleBuddhist_24_outlined />;
export const IconMapsTempleBuddhist20twotone = () => <SVGMapsTempleBuddhist_20_twotone />;
export const IconMapsTempleBuddhist24twotone = () => <SVGMapsTempleBuddhist_24_twotone />;
export const IconMapsTempleBuddhist20sharp = () => <SVGMapsTempleBuddhist_20_sharp />;
export const IconMapsTempleBuddhist24sharp = () => <SVGMapsTempleBuddhist_24_sharp />;
export const IconMapsTempleBuddhist20filled = () => <SVGMapsTempleBuddhist_20_filled />;
export const IconMapsTempleBuddhist24filled = () => <SVGMapsTempleBuddhist_24_filled />;
export const IconMapsTempleBuddhist20round = () => <SVGMapsTempleBuddhist_20_round />;
export const IconMapsTempleBuddhist24round = () => <SVGMapsTempleBuddhist_24_round />;
