import React from "react";
import SVGMapsRemoveRoad_20_outlined from '../../svg/maps/MapsRemoveRoad/20_outlined.svg';
import SVGMapsRemoveRoad_24_outlined from '../../svg/maps/MapsRemoveRoad/24_outlined.svg';
import SVGMapsRemoveRoad_20_twotone from '../../svg/maps/MapsRemoveRoad/20_twotone.svg';
import SVGMapsRemoveRoad_24_twotone from '../../svg/maps/MapsRemoveRoad/24_twotone.svg';
import SVGMapsRemoveRoad_20_sharp from '../../svg/maps/MapsRemoveRoad/20_sharp.svg';
import SVGMapsRemoveRoad_24_sharp from '../../svg/maps/MapsRemoveRoad/24_sharp.svg';
import SVGMapsRemoveRoad_20_filled from '../../svg/maps/MapsRemoveRoad/20_filled.svg';
import SVGMapsRemoveRoad_24_filled from '../../svg/maps/MapsRemoveRoad/24_filled.svg';
import SVGMapsRemoveRoad_20_round from '../../svg/maps/MapsRemoveRoad/20_round.svg';
import SVGMapsRemoveRoad_24_round from '../../svg/maps/MapsRemoveRoad/24_round.svg';

export const IconMapsRemoveRoad20outlined = () => <SVGMapsRemoveRoad_20_outlined />;
export const IconMapsRemoveRoad24outlined = () => <SVGMapsRemoveRoad_24_outlined />;
export const IconMapsRemoveRoad20twotone = () => <SVGMapsRemoveRoad_20_twotone />;
export const IconMapsRemoveRoad24twotone = () => <SVGMapsRemoveRoad_24_twotone />;
export const IconMapsRemoveRoad20sharp = () => <SVGMapsRemoveRoad_20_sharp />;
export const IconMapsRemoveRoad24sharp = () => <SVGMapsRemoveRoad_24_sharp />;
export const IconMapsRemoveRoad20filled = () => <SVGMapsRemoveRoad_20_filled />;
export const IconMapsRemoveRoad24filled = () => <SVGMapsRemoveRoad_24_filled />;
export const IconMapsRemoveRoad20round = () => <SVGMapsRemoveRoad_20_round />;
export const IconMapsRemoveRoad24round = () => <SVGMapsRemoveRoad_24_round />;
