import React from "react";
import SVGMapsNightlife_20_outlined from '../../svg/maps/MapsNightlife/20_outlined.svg';
import SVGMapsNightlife_24_outlined from '../../svg/maps/MapsNightlife/24_outlined.svg';
import SVGMapsNightlife_20_twotone from '../../svg/maps/MapsNightlife/20_twotone.svg';
import SVGMapsNightlife_24_twotone from '../../svg/maps/MapsNightlife/24_twotone.svg';
import SVGMapsNightlife_20_sharp from '../../svg/maps/MapsNightlife/20_sharp.svg';
import SVGMapsNightlife_24_sharp from '../../svg/maps/MapsNightlife/24_sharp.svg';
import SVGMapsNightlife_20_filled from '../../svg/maps/MapsNightlife/20_filled.svg';
import SVGMapsNightlife_24_filled from '../../svg/maps/MapsNightlife/24_filled.svg';
import SVGMapsNightlife_20_round from '../../svg/maps/MapsNightlife/20_round.svg';
import SVGMapsNightlife_24_round from '../../svg/maps/MapsNightlife/24_round.svg';

export const IconMapsNightlife20outlined = () => <SVGMapsNightlife_20_outlined />;
export const IconMapsNightlife24outlined = () => <SVGMapsNightlife_24_outlined />;
export const IconMapsNightlife20twotone = () => <SVGMapsNightlife_20_twotone />;
export const IconMapsNightlife24twotone = () => <SVGMapsNightlife_24_twotone />;
export const IconMapsNightlife20sharp = () => <SVGMapsNightlife_20_sharp />;
export const IconMapsNightlife24sharp = () => <SVGMapsNightlife_24_sharp />;
export const IconMapsNightlife20filled = () => <SVGMapsNightlife_20_filled />;
export const IconMapsNightlife24filled = () => <SVGMapsNightlife_24_filled />;
export const IconMapsNightlife20round = () => <SVGMapsNightlife_20_round />;
export const IconMapsNightlife24round = () => <SVGMapsNightlife_24_round />;
