import React from "react";
import SVGMapsCrisisAlert_20_outlined from '../../svg/maps/MapsCrisisAlert/20_outlined.svg';
import SVGMapsCrisisAlert_24_outlined from '../../svg/maps/MapsCrisisAlert/24_outlined.svg';
import SVGMapsCrisisAlert_20_twotone from '../../svg/maps/MapsCrisisAlert/20_twotone.svg';
import SVGMapsCrisisAlert_24_twotone from '../../svg/maps/MapsCrisisAlert/24_twotone.svg';
import SVGMapsCrisisAlert_20_sharp from '../../svg/maps/MapsCrisisAlert/20_sharp.svg';
import SVGMapsCrisisAlert_24_sharp from '../../svg/maps/MapsCrisisAlert/24_sharp.svg';
import SVGMapsCrisisAlert_20_filled from '../../svg/maps/MapsCrisisAlert/20_filled.svg';
import SVGMapsCrisisAlert_24_filled from '../../svg/maps/MapsCrisisAlert/24_filled.svg';
import SVGMapsCrisisAlert_20_round from '../../svg/maps/MapsCrisisAlert/20_round.svg';
import SVGMapsCrisisAlert_24_round from '../../svg/maps/MapsCrisisAlert/24_round.svg';

export const IconMapsCrisisAlert20outlined = () => <SVGMapsCrisisAlert_20_outlined />;
export const IconMapsCrisisAlert24outlined = () => <SVGMapsCrisisAlert_24_outlined />;
export const IconMapsCrisisAlert20twotone = () => <SVGMapsCrisisAlert_20_twotone />;
export const IconMapsCrisisAlert24twotone = () => <SVGMapsCrisisAlert_24_twotone />;
export const IconMapsCrisisAlert20sharp = () => <SVGMapsCrisisAlert_20_sharp />;
export const IconMapsCrisisAlert24sharp = () => <SVGMapsCrisisAlert_24_sharp />;
export const IconMapsCrisisAlert20filled = () => <SVGMapsCrisisAlert_20_filled />;
export const IconMapsCrisisAlert24filled = () => <SVGMapsCrisisAlert_24_filled />;
export const IconMapsCrisisAlert20round = () => <SVGMapsCrisisAlert_20_round />;
export const IconMapsCrisisAlert24round = () => <SVGMapsCrisisAlert_24_round />;
