import React from "react";
import SVGMapsHardware_20_outlined from '../../svg/maps/MapsHardware/20_outlined.svg';
import SVGMapsHardware_24_outlined from '../../svg/maps/MapsHardware/24_outlined.svg';
import SVGMapsHardware_20_twotone from '../../svg/maps/MapsHardware/20_twotone.svg';
import SVGMapsHardware_24_twotone from '../../svg/maps/MapsHardware/24_twotone.svg';
import SVGMapsHardware_20_sharp from '../../svg/maps/MapsHardware/20_sharp.svg';
import SVGMapsHardware_24_sharp from '../../svg/maps/MapsHardware/24_sharp.svg';
import SVGMapsHardware_20_filled from '../../svg/maps/MapsHardware/20_filled.svg';
import SVGMapsHardware_24_filled from '../../svg/maps/MapsHardware/24_filled.svg';
import SVGMapsHardware_20_round from '../../svg/maps/MapsHardware/20_round.svg';
import SVGMapsHardware_24_round from '../../svg/maps/MapsHardware/24_round.svg';

export const IconMapsHardware20outlined = () => <SVGMapsHardware_20_outlined />;
export const IconMapsHardware24outlined = () => <SVGMapsHardware_24_outlined />;
export const IconMapsHardware20twotone = () => <SVGMapsHardware_20_twotone />;
export const IconMapsHardware24twotone = () => <SVGMapsHardware_24_twotone />;
export const IconMapsHardware20sharp = () => <SVGMapsHardware_20_sharp />;
export const IconMapsHardware24sharp = () => <SVGMapsHardware_24_sharp />;
export const IconMapsHardware20filled = () => <SVGMapsHardware_20_filled />;
export const IconMapsHardware24filled = () => <SVGMapsHardware_24_filled />;
export const IconMapsHardware20round = () => <SVGMapsHardware_20_round />;
export const IconMapsHardware24round = () => <SVGMapsHardware_24_round />;
