import React from "react";
import SVGMapsFactory_20_outlined from '../../svg/maps/MapsFactory/20_outlined.svg';
import SVGMapsFactory_24_outlined from '../../svg/maps/MapsFactory/24_outlined.svg';
import SVGMapsFactory_20_twotone from '../../svg/maps/MapsFactory/20_twotone.svg';
import SVGMapsFactory_24_twotone from '../../svg/maps/MapsFactory/24_twotone.svg';
import SVGMapsFactory_20_sharp from '../../svg/maps/MapsFactory/20_sharp.svg';
import SVGMapsFactory_24_sharp from '../../svg/maps/MapsFactory/24_sharp.svg';
import SVGMapsFactory_20_filled from '../../svg/maps/MapsFactory/20_filled.svg';
import SVGMapsFactory_24_filled from '../../svg/maps/MapsFactory/24_filled.svg';
import SVGMapsFactory_20_round from '../../svg/maps/MapsFactory/20_round.svg';
import SVGMapsFactory_24_round from '../../svg/maps/MapsFactory/24_round.svg';

export const IconMapsFactory20outlined = () => <SVGMapsFactory_20_outlined />;
export const IconMapsFactory24outlined = () => <SVGMapsFactory_24_outlined />;
export const IconMapsFactory20twotone = () => <SVGMapsFactory_20_twotone />;
export const IconMapsFactory24twotone = () => <SVGMapsFactory_24_twotone />;
export const IconMapsFactory20sharp = () => <SVGMapsFactory_20_sharp />;
export const IconMapsFactory24sharp = () => <SVGMapsFactory_24_sharp />;
export const IconMapsFactory20filled = () => <SVGMapsFactory_20_filled />;
export const IconMapsFactory24filled = () => <SVGMapsFactory_24_filled />;
export const IconMapsFactory20round = () => <SVGMapsFactory_20_round />;
export const IconMapsFactory24round = () => <SVGMapsFactory_24_round />;
