import React from "react";
import SVGMapsElectricMoped_20_outlined from '../../svg/maps/MapsElectricMoped/20_outlined.svg';
import SVGMapsElectricMoped_24_outlined from '../../svg/maps/MapsElectricMoped/24_outlined.svg';
import SVGMapsElectricMoped_20_twotone from '../../svg/maps/MapsElectricMoped/20_twotone.svg';
import SVGMapsElectricMoped_24_twotone from '../../svg/maps/MapsElectricMoped/24_twotone.svg';
import SVGMapsElectricMoped_20_sharp from '../../svg/maps/MapsElectricMoped/20_sharp.svg';
import SVGMapsElectricMoped_24_sharp from '../../svg/maps/MapsElectricMoped/24_sharp.svg';
import SVGMapsElectricMoped_20_filled from '../../svg/maps/MapsElectricMoped/20_filled.svg';
import SVGMapsElectricMoped_24_filled from '../../svg/maps/MapsElectricMoped/24_filled.svg';
import SVGMapsElectricMoped_20_round from '../../svg/maps/MapsElectricMoped/20_round.svg';
import SVGMapsElectricMoped_24_round from '../../svg/maps/MapsElectricMoped/24_round.svg';

export const IconMapsElectricMoped20outlined = () => <SVGMapsElectricMoped_20_outlined />;
export const IconMapsElectricMoped24outlined = () => <SVGMapsElectricMoped_24_outlined />;
export const IconMapsElectricMoped20twotone = () => <SVGMapsElectricMoped_20_twotone />;
export const IconMapsElectricMoped24twotone = () => <SVGMapsElectricMoped_24_twotone />;
export const IconMapsElectricMoped20sharp = () => <SVGMapsElectricMoped_20_sharp />;
export const IconMapsElectricMoped24sharp = () => <SVGMapsElectricMoped_24_sharp />;
export const IconMapsElectricMoped20filled = () => <SVGMapsElectricMoped_20_filled />;
export const IconMapsElectricMoped24filled = () => <SVGMapsElectricMoped_24_filled />;
export const IconMapsElectricMoped20round = () => <SVGMapsElectricMoped_20_round />;
export const IconMapsElectricMoped24round = () => <SVGMapsElectricMoped_24_round />;
