import React from "react";
import SVGMapsRoute_20_outlined from '../../svg/maps/MapsRoute/20_outlined.svg';
import SVGMapsRoute_24_outlined from '../../svg/maps/MapsRoute/24_outlined.svg';
import SVGMapsRoute_20_twotone from '../../svg/maps/MapsRoute/20_twotone.svg';
import SVGMapsRoute_24_twotone from '../../svg/maps/MapsRoute/24_twotone.svg';
import SVGMapsRoute_20_sharp from '../../svg/maps/MapsRoute/20_sharp.svg';
import SVGMapsRoute_24_sharp from '../../svg/maps/MapsRoute/24_sharp.svg';
import SVGMapsRoute_20_filled from '../../svg/maps/MapsRoute/20_filled.svg';
import SVGMapsRoute_24_filled from '../../svg/maps/MapsRoute/24_filled.svg';
import SVGMapsRoute_20_round from '../../svg/maps/MapsRoute/20_round.svg';
import SVGMapsRoute_24_round from '../../svg/maps/MapsRoute/24_round.svg';

export const IconMapsRoute20outlined = () => <SVGMapsRoute_20_outlined />;
export const IconMapsRoute24outlined = () => <SVGMapsRoute_24_outlined />;
export const IconMapsRoute20twotone = () => <SVGMapsRoute_20_twotone />;
export const IconMapsRoute24twotone = () => <SVGMapsRoute_24_twotone />;
export const IconMapsRoute20sharp = () => <SVGMapsRoute_20_sharp />;
export const IconMapsRoute24sharp = () => <SVGMapsRoute_24_sharp />;
export const IconMapsRoute20filled = () => <SVGMapsRoute_20_filled />;
export const IconMapsRoute24filled = () => <SVGMapsRoute_24_filled />;
export const IconMapsRoute20round = () => <SVGMapsRoute_20_round />;
export const IconMapsRoute24round = () => <SVGMapsRoute_24_round />;
