import React from "react";
import SVGMapsSafetyCheck_20_outlined from '../../svg/maps/MapsSafetyCheck/20_outlined.svg';
import SVGMapsSafetyCheck_24_outlined from '../../svg/maps/MapsSafetyCheck/24_outlined.svg';
import SVGMapsSafetyCheck_20_twotone from '../../svg/maps/MapsSafetyCheck/20_twotone.svg';
import SVGMapsSafetyCheck_24_twotone from '../../svg/maps/MapsSafetyCheck/24_twotone.svg';
import SVGMapsSafetyCheck_20_sharp from '../../svg/maps/MapsSafetyCheck/20_sharp.svg';
import SVGMapsSafetyCheck_24_sharp from '../../svg/maps/MapsSafetyCheck/24_sharp.svg';
import SVGMapsSafetyCheck_20_filled from '../../svg/maps/MapsSafetyCheck/20_filled.svg';
import SVGMapsSafetyCheck_24_filled from '../../svg/maps/MapsSafetyCheck/24_filled.svg';
import SVGMapsSafetyCheck_20_round from '../../svg/maps/MapsSafetyCheck/20_round.svg';
import SVGMapsSafetyCheck_24_round from '../../svg/maps/MapsSafetyCheck/24_round.svg';

export const IconMapsSafetyCheck20outlined = () => <SVGMapsSafetyCheck_20_outlined />;
export const IconMapsSafetyCheck24outlined = () => <SVGMapsSafetyCheck_24_outlined />;
export const IconMapsSafetyCheck20twotone = () => <SVGMapsSafetyCheck_20_twotone />;
export const IconMapsSafetyCheck24twotone = () => <SVGMapsSafetyCheck_24_twotone />;
export const IconMapsSafetyCheck20sharp = () => <SVGMapsSafetyCheck_20_sharp />;
export const IconMapsSafetyCheck24sharp = () => <SVGMapsSafetyCheck_24_sharp />;
export const IconMapsSafetyCheck20filled = () => <SVGMapsSafetyCheck_20_filled />;
export const IconMapsSafetyCheck24filled = () => <SVGMapsSafetyCheck_24_filled />;
export const IconMapsSafetyCheck20round = () => <SVGMapsSafetyCheck_20_round />;
export const IconMapsSafetyCheck24round = () => <SVGMapsSafetyCheck_24_round />;
