import React from "react";
import SVGNotificationRunningWithErrors_20_outlined from '../../svg/notification/NotificationRunningWithErrors/20_outlined.svg';
import SVGNotificationRunningWithErrors_24_outlined from '../../svg/notification/NotificationRunningWithErrors/24_outlined.svg';
import SVGNotificationRunningWithErrors_20_twotone from '../../svg/notification/NotificationRunningWithErrors/20_twotone.svg';
import SVGNotificationRunningWithErrors_24_twotone from '../../svg/notification/NotificationRunningWithErrors/24_twotone.svg';
import SVGNotificationRunningWithErrors_20_sharp from '../../svg/notification/NotificationRunningWithErrors/20_sharp.svg';
import SVGNotificationRunningWithErrors_24_sharp from '../../svg/notification/NotificationRunningWithErrors/24_sharp.svg';
import SVGNotificationRunningWithErrors_20_filled from '../../svg/notification/NotificationRunningWithErrors/20_filled.svg';
import SVGNotificationRunningWithErrors_24_filled from '../../svg/notification/NotificationRunningWithErrors/24_filled.svg';
import SVGNotificationRunningWithErrors_20_round from '../../svg/notification/NotificationRunningWithErrors/20_round.svg';
import SVGNotificationRunningWithErrors_24_round from '../../svg/notification/NotificationRunningWithErrors/24_round.svg';

export const IconNotificationRunningWithErrors20outlined = () => <SVGNotificationRunningWithErrors_20_outlined />;
export const IconNotificationRunningWithErrors24outlined = () => <SVGNotificationRunningWithErrors_24_outlined />;
export const IconNotificationRunningWithErrors20twotone = () => <SVGNotificationRunningWithErrors_20_twotone />;
export const IconNotificationRunningWithErrors24twotone = () => <SVGNotificationRunningWithErrors_24_twotone />;
export const IconNotificationRunningWithErrors20sharp = () => <SVGNotificationRunningWithErrors_20_sharp />;
export const IconNotificationRunningWithErrors24sharp = () => <SVGNotificationRunningWithErrors_24_sharp />;
export const IconNotificationRunningWithErrors20filled = () => <SVGNotificationRunningWithErrors_20_filled />;
export const IconNotificationRunningWithErrors24filled = () => <SVGNotificationRunningWithErrors_24_filled />;
export const IconNotificationRunningWithErrors20round = () => <SVGNotificationRunningWithErrors_20_round />;
export const IconNotificationRunningWithErrors24round = () => <SVGNotificationRunningWithErrors_24_round />;
