import React from "react";
import SVGNotificationPhoneLocked_20_outlined from '../../svg/notification/NotificationPhoneLocked/20_outlined.svg';
import SVGNotificationPhoneLocked_24_outlined from '../../svg/notification/NotificationPhoneLocked/24_outlined.svg';
import SVGNotificationPhoneLocked_20_twotone from '../../svg/notification/NotificationPhoneLocked/20_twotone.svg';
import SVGNotificationPhoneLocked_24_twotone from '../../svg/notification/NotificationPhoneLocked/24_twotone.svg';
import SVGNotificationPhoneLocked_20_sharp from '../../svg/notification/NotificationPhoneLocked/20_sharp.svg';
import SVGNotificationPhoneLocked_24_sharp from '../../svg/notification/NotificationPhoneLocked/24_sharp.svg';
import SVGNotificationPhoneLocked_20_filled from '../../svg/notification/NotificationPhoneLocked/20_filled.svg';
import SVGNotificationPhoneLocked_24_filled from '../../svg/notification/NotificationPhoneLocked/24_filled.svg';
import SVGNotificationPhoneLocked_20_round from '../../svg/notification/NotificationPhoneLocked/20_round.svg';
import SVGNotificationPhoneLocked_24_round from '../../svg/notification/NotificationPhoneLocked/24_round.svg';

export const IconNotificationPhoneLocked20outlined = () => <SVGNotificationPhoneLocked_20_outlined />;
export const IconNotificationPhoneLocked24outlined = () => <SVGNotificationPhoneLocked_24_outlined />;
export const IconNotificationPhoneLocked20twotone = () => <SVGNotificationPhoneLocked_20_twotone />;
export const IconNotificationPhoneLocked24twotone = () => <SVGNotificationPhoneLocked_24_twotone />;
export const IconNotificationPhoneLocked20sharp = () => <SVGNotificationPhoneLocked_20_sharp />;
export const IconNotificationPhoneLocked24sharp = () => <SVGNotificationPhoneLocked_24_sharp />;
export const IconNotificationPhoneLocked20filled = () => <SVGNotificationPhoneLocked_20_filled />;
export const IconNotificationPhoneLocked24filled = () => <SVGNotificationPhoneLocked_24_filled />;
export const IconNotificationPhoneLocked20round = () => <SVGNotificationPhoneLocked_20_round />;
export const IconNotificationPhoneLocked24round = () => <SVGNotificationPhoneLocked_24_round />;
