import React from "react";
import SVGAvVideoFile_24_round from '../svg/AvVideoFile/24_round.svg';
import SVGAvVideoFile_20_round from '../svg/AvVideoFile/20_round.svg';
import SVGAvVideoFile_24_twotone from '../svg/AvVideoFile/24_twotone.svg';
import SVGAvVideoFile_20_twotone from '../svg/AvVideoFile/20_twotone.svg';
import SVGAvVideoFile_24_filled from '../svg/AvVideoFile/24_filled.svg';
import SVGAvVideoFile_20_filled from '../svg/AvVideoFile/20_filled.svg';
import SVGAvVideoFile_24_outlined from '../svg/AvVideoFile/24_outlined.svg';
import SVGAvVideoFile_20_outlined from '../svg/AvVideoFile/20_outlined.svg';
import SVGAvVideoFile_24_sharp from '../svg/AvVideoFile/24_sharp.svg';
import SVGAvVideoFile_20_sharp from '../svg/AvVideoFile/20_sharp.svg';

export const IconAvVideoFile24round = () => <SVGAvVideoFile_24_round />;
export const IconAvVideoFile20round = () => <SVGAvVideoFile_20_round />;
export const IconAvVideoFile24twotone = () => <SVGAvVideoFile_24_twotone />;
export const IconAvVideoFile20twotone = () => <SVGAvVideoFile_20_twotone />;
export const IconAvVideoFile24filled = () => <SVGAvVideoFile_24_filled />;
export const IconAvVideoFile20filled = () => <SVGAvVideoFile_20_filled />;
export const IconAvVideoFile24outlined = () => <SVGAvVideoFile_24_outlined />;
export const IconAvVideoFile20outlined = () => <SVGAvVideoFile_20_outlined />;
export const IconAvVideoFile24sharp = () => <SVGAvVideoFile_24_sharp />;
export const IconAvVideoFile20sharp = () => <SVGAvVideoFile_20_sharp />;
