import React from "react";
import SVGDeviceBattery0Bar_20_outlined from '../../svg/device/DeviceBattery0Bar/20_outlined.svg';
import SVGDeviceBattery0Bar_24_outlined from '../../svg/device/DeviceBattery0Bar/24_outlined.svg';
import SVGDeviceBattery0Bar_20_twotone from '../../svg/device/DeviceBattery0Bar/20_twotone.svg';
import SVGDeviceBattery0Bar_24_twotone from '../../svg/device/DeviceBattery0Bar/24_twotone.svg';
import SVGDeviceBattery0Bar_20_sharp from '../../svg/device/DeviceBattery0Bar/20_sharp.svg';
import SVGDeviceBattery0Bar_24_sharp from '../../svg/device/DeviceBattery0Bar/24_sharp.svg';
import SVGDeviceBattery0Bar_20_filled from '../../svg/device/DeviceBattery0Bar/20_filled.svg';
import SVGDeviceBattery0Bar_24_filled from '../../svg/device/DeviceBattery0Bar/24_filled.svg';
import SVGDeviceBattery0Bar_20_round from '../../svg/device/DeviceBattery0Bar/20_round.svg';
import SVGDeviceBattery0Bar_24_round from '../../svg/device/DeviceBattery0Bar/24_round.svg';

export const IconDeviceBattery0Bar20outlined = () => <SVGDeviceBattery0Bar_20_outlined />;
export const IconDeviceBattery0Bar24outlined = () => <SVGDeviceBattery0Bar_24_outlined />;
export const IconDeviceBattery0Bar20twotone = () => <SVGDeviceBattery0Bar_20_twotone />;
export const IconDeviceBattery0Bar24twotone = () => <SVGDeviceBattery0Bar_24_twotone />;
export const IconDeviceBattery0Bar20sharp = () => <SVGDeviceBattery0Bar_20_sharp />;
export const IconDeviceBattery0Bar24sharp = () => <SVGDeviceBattery0Bar_24_sharp />;
export const IconDeviceBattery0Bar20filled = () => <SVGDeviceBattery0Bar_20_filled />;
export const IconDeviceBattery0Bar24filled = () => <SVGDeviceBattery0Bar_24_filled />;
export const IconDeviceBattery0Bar20round = () => <SVGDeviceBattery0Bar_20_round />;
export const IconDeviceBattery0Bar24round = () => <SVGDeviceBattery0Bar_24_round />;
