import React from "react";
import SVGDeviceLightMode_20_outlined from '../../svg/device/DeviceLightMode/20_outlined.svg';
import SVGDeviceLightMode_24_outlined from '../../svg/device/DeviceLightMode/24_outlined.svg';
import SVGDeviceLightMode_20_twotone from '../../svg/device/DeviceLightMode/20_twotone.svg';
import SVGDeviceLightMode_24_twotone from '../../svg/device/DeviceLightMode/24_twotone.svg';
import SVGDeviceLightMode_20_sharp from '../../svg/device/DeviceLightMode/20_sharp.svg';
import SVGDeviceLightMode_24_sharp from '../../svg/device/DeviceLightMode/24_sharp.svg';
import SVGDeviceLightMode_20_filled from '../../svg/device/DeviceLightMode/20_filled.svg';
import SVGDeviceLightMode_24_filled from '../../svg/device/DeviceLightMode/24_filled.svg';
import SVGDeviceLightMode_20_round from '../../svg/device/DeviceLightMode/20_round.svg';
import SVGDeviceLightMode_24_round from '../../svg/device/DeviceLightMode/24_round.svg';

export const IconDeviceLightMode20outlined = () => <SVGDeviceLightMode_20_outlined />;
export const IconDeviceLightMode24outlined = () => <SVGDeviceLightMode_24_outlined />;
export const IconDeviceLightMode20twotone = () => <SVGDeviceLightMode_20_twotone />;
export const IconDeviceLightMode24twotone = () => <SVGDeviceLightMode_24_twotone />;
export const IconDeviceLightMode20sharp = () => <SVGDeviceLightMode_20_sharp />;
export const IconDeviceLightMode24sharp = () => <SVGDeviceLightMode_24_sharp />;
export const IconDeviceLightMode20filled = () => <SVGDeviceLightMode_20_filled />;
export const IconDeviceLightMode24filled = () => <SVGDeviceLightMode_24_filled />;
export const IconDeviceLightMode20round = () => <SVGDeviceLightMode_20_round />;
export const IconDeviceLightMode24round = () => <SVGDeviceLightMode_24_round />;
