import React from "react";
import SVGDeviceMonitorHeart_20_outlined from '../../svg/device/DeviceMonitorHeart/20_outlined.svg';
import SVGDeviceMonitorHeart_24_outlined from '../../svg/device/DeviceMonitorHeart/24_outlined.svg';
import SVGDeviceMonitorHeart_20_twotone from '../../svg/device/DeviceMonitorHeart/20_twotone.svg';
import SVGDeviceMonitorHeart_24_twotone from '../../svg/device/DeviceMonitorHeart/24_twotone.svg';
import SVGDeviceMonitorHeart_20_sharp from '../../svg/device/DeviceMonitorHeart/20_sharp.svg';
import SVGDeviceMonitorHeart_24_sharp from '../../svg/device/DeviceMonitorHeart/24_sharp.svg';
import SVGDeviceMonitorHeart_20_filled from '../../svg/device/DeviceMonitorHeart/20_filled.svg';
import SVGDeviceMonitorHeart_24_filled from '../../svg/device/DeviceMonitorHeart/24_filled.svg';
import SVGDeviceMonitorHeart_20_round from '../../svg/device/DeviceMonitorHeart/20_round.svg';
import SVGDeviceMonitorHeart_24_round from '../../svg/device/DeviceMonitorHeart/24_round.svg';

export const IconDeviceMonitorHeart20outlined = () => <SVGDeviceMonitorHeart_20_outlined />;
export const IconDeviceMonitorHeart24outlined = () => <SVGDeviceMonitorHeart_24_outlined />;
export const IconDeviceMonitorHeart20twotone = () => <SVGDeviceMonitorHeart_20_twotone />;
export const IconDeviceMonitorHeart24twotone = () => <SVGDeviceMonitorHeart_24_twotone />;
export const IconDeviceMonitorHeart20sharp = () => <SVGDeviceMonitorHeart_20_sharp />;
export const IconDeviceMonitorHeart24sharp = () => <SVGDeviceMonitorHeart_24_sharp />;
export const IconDeviceMonitorHeart20filled = () => <SVGDeviceMonitorHeart_20_filled />;
export const IconDeviceMonitorHeart24filled = () => <SVGDeviceMonitorHeart_24_filled />;
export const IconDeviceMonitorHeart20round = () => <SVGDeviceMonitorHeart_20_round />;
export const IconDeviceMonitorHeart24round = () => <SVGDeviceMonitorHeart_24_round />;
