import React from "react";
import SVGDeviceSignalCellularAlt2Bar_20_outlined from '../../svg/device/DeviceSignalCellularAlt2Bar/20_outlined.svg';
import SVGDeviceSignalCellularAlt2Bar_24_outlined from '../../svg/device/DeviceSignalCellularAlt2Bar/24_outlined.svg';
import SVGDeviceSignalCellularAlt2Bar_20_twotone from '../../svg/device/DeviceSignalCellularAlt2Bar/20_twotone.svg';
import SVGDeviceSignalCellularAlt2Bar_24_twotone from '../../svg/device/DeviceSignalCellularAlt2Bar/24_twotone.svg';
import SVGDeviceSignalCellularAlt2Bar_20_sharp from '../../svg/device/DeviceSignalCellularAlt2Bar/20_sharp.svg';
import SVGDeviceSignalCellularAlt2Bar_24_sharp from '../../svg/device/DeviceSignalCellularAlt2Bar/24_sharp.svg';
import SVGDeviceSignalCellularAlt2Bar_20_filled from '../../svg/device/DeviceSignalCellularAlt2Bar/20_filled.svg';
import SVGDeviceSignalCellularAlt2Bar_24_filled from '../../svg/device/DeviceSignalCellularAlt2Bar/24_filled.svg';
import SVGDeviceSignalCellularAlt2Bar_20_round from '../../svg/device/DeviceSignalCellularAlt2Bar/20_round.svg';
import SVGDeviceSignalCellularAlt2Bar_24_round from '../../svg/device/DeviceSignalCellularAlt2Bar/24_round.svg';

export const IconDeviceSignalCellularAlt2Bar20outlined = () => <SVGDeviceSignalCellularAlt2Bar_20_outlined />;
export const IconDeviceSignalCellularAlt2Bar24outlined = () => <SVGDeviceSignalCellularAlt2Bar_24_outlined />;
export const IconDeviceSignalCellularAlt2Bar20twotone = () => <SVGDeviceSignalCellularAlt2Bar_20_twotone />;
export const IconDeviceSignalCellularAlt2Bar24twotone = () => <SVGDeviceSignalCellularAlt2Bar_24_twotone />;
export const IconDeviceSignalCellularAlt2Bar20sharp = () => <SVGDeviceSignalCellularAlt2Bar_20_sharp />;
export const IconDeviceSignalCellularAlt2Bar24sharp = () => <SVGDeviceSignalCellularAlt2Bar_24_sharp />;
export const IconDeviceSignalCellularAlt2Bar20filled = () => <SVGDeviceSignalCellularAlt2Bar_20_filled />;
export const IconDeviceSignalCellularAlt2Bar24filled = () => <SVGDeviceSignalCellularAlt2Bar_24_filled />;
export const IconDeviceSignalCellularAlt2Bar20round = () => <SVGDeviceSignalCellularAlt2Bar_20_round />;
export const IconDeviceSignalCellularAlt2Bar24round = () => <SVGDeviceSignalCellularAlt2Bar_24_round />;
