import React from "react";
import SVGDeviceBattery5Bar_20_outlined from '../../svg/device/DeviceBattery5Bar/20_outlined.svg';
import SVGDeviceBattery5Bar_24_outlined from '../../svg/device/DeviceBattery5Bar/24_outlined.svg';
import SVGDeviceBattery5Bar_20_twotone from '../../svg/device/DeviceBattery5Bar/20_twotone.svg';
import SVGDeviceBattery5Bar_24_twotone from '../../svg/device/DeviceBattery5Bar/24_twotone.svg';
import SVGDeviceBattery5Bar_20_sharp from '../../svg/device/DeviceBattery5Bar/20_sharp.svg';
import SVGDeviceBattery5Bar_24_sharp from '../../svg/device/DeviceBattery5Bar/24_sharp.svg';
import SVGDeviceBattery5Bar_20_filled from '../../svg/device/DeviceBattery5Bar/20_filled.svg';
import SVGDeviceBattery5Bar_24_filled from '../../svg/device/DeviceBattery5Bar/24_filled.svg';
import SVGDeviceBattery5Bar_20_round from '../../svg/device/DeviceBattery5Bar/20_round.svg';
import SVGDeviceBattery5Bar_24_round from '../../svg/device/DeviceBattery5Bar/24_round.svg';

export const IconDeviceBattery5Bar20outlined = () => <SVGDeviceBattery5Bar_20_outlined />;
export const IconDeviceBattery5Bar24outlined = () => <SVGDeviceBattery5Bar_24_outlined />;
export const IconDeviceBattery5Bar20twotone = () => <SVGDeviceBattery5Bar_20_twotone />;
export const IconDeviceBattery5Bar24twotone = () => <SVGDeviceBattery5Bar_24_twotone />;
export const IconDeviceBattery5Bar20sharp = () => <SVGDeviceBattery5Bar_20_sharp />;
export const IconDeviceBattery5Bar24sharp = () => <SVGDeviceBattery5Bar_24_sharp />;
export const IconDeviceBattery5Bar20filled = () => <SVGDeviceBattery5Bar_20_filled />;
export const IconDeviceBattery5Bar24filled = () => <SVGDeviceBattery5Bar_24_filled />;
export const IconDeviceBattery5Bar20round = () => <SVGDeviceBattery5Bar_20_round />;
export const IconDeviceBattery5Bar24round = () => <SVGDeviceBattery5Bar_24_round />;
