import React from "react";
import SVGDeviceWifi2Bar_20_outlined from '../../svg/device/DeviceWifi2Bar/20_outlined.svg';
import SVGDeviceWifi2Bar_24_outlined from '../../svg/device/DeviceWifi2Bar/24_outlined.svg';
import SVGDeviceWifi2Bar_20_twotone from '../../svg/device/DeviceWifi2Bar/20_twotone.svg';
import SVGDeviceWifi2Bar_24_twotone from '../../svg/device/DeviceWifi2Bar/24_twotone.svg';
import SVGDeviceWifi2Bar_20_sharp from '../../svg/device/DeviceWifi2Bar/20_sharp.svg';
import SVGDeviceWifi2Bar_24_sharp from '../../svg/device/DeviceWifi2Bar/24_sharp.svg';
import SVGDeviceWifi2Bar_20_filled from '../../svg/device/DeviceWifi2Bar/20_filled.svg';
import SVGDeviceWifi2Bar_24_filled from '../../svg/device/DeviceWifi2Bar/24_filled.svg';
import SVGDeviceWifi2Bar_20_round from '../../svg/device/DeviceWifi2Bar/20_round.svg';
import SVGDeviceWifi2Bar_24_round from '../../svg/device/DeviceWifi2Bar/24_round.svg';

export const IconDeviceWifi2Bar20outlined = () => <SVGDeviceWifi2Bar_20_outlined />;
export const IconDeviceWifi2Bar24outlined = () => <SVGDeviceWifi2Bar_24_outlined />;
export const IconDeviceWifi2Bar20twotone = () => <SVGDeviceWifi2Bar_20_twotone />;
export const IconDeviceWifi2Bar24twotone = () => <SVGDeviceWifi2Bar_24_twotone />;
export const IconDeviceWifi2Bar20sharp = () => <SVGDeviceWifi2Bar_20_sharp />;
export const IconDeviceWifi2Bar24sharp = () => <SVGDeviceWifi2Bar_24_sharp />;
export const IconDeviceWifi2Bar20filled = () => <SVGDeviceWifi2Bar_20_filled />;
export const IconDeviceWifi2Bar24filled = () => <SVGDeviceWifi2Bar_24_filled />;
export const IconDeviceWifi2Bar20round = () => <SVGDeviceWifi2Bar_20_round />;
export const IconDeviceWifi2Bar24round = () => <SVGDeviceWifi2Bar_24_round />;
