import React from "react";
import SVGDeviceWifi1Bar_20_outlined from '../../svg/device/DeviceWifi1Bar/20_outlined.svg';
import SVGDeviceWifi1Bar_24_outlined from '../../svg/device/DeviceWifi1Bar/24_outlined.svg';
import SVGDeviceWifi1Bar_20_twotone from '../../svg/device/DeviceWifi1Bar/20_twotone.svg';
import SVGDeviceWifi1Bar_24_twotone from '../../svg/device/DeviceWifi1Bar/24_twotone.svg';
import SVGDeviceWifi1Bar_20_sharp from '../../svg/device/DeviceWifi1Bar/20_sharp.svg';
import SVGDeviceWifi1Bar_24_sharp from '../../svg/device/DeviceWifi1Bar/24_sharp.svg';
import SVGDeviceWifi1Bar_20_filled from '../../svg/device/DeviceWifi1Bar/20_filled.svg';
import SVGDeviceWifi1Bar_24_filled from '../../svg/device/DeviceWifi1Bar/24_filled.svg';
import SVGDeviceWifi1Bar_20_round from '../../svg/device/DeviceWifi1Bar/20_round.svg';
import SVGDeviceWifi1Bar_24_round from '../../svg/device/DeviceWifi1Bar/24_round.svg';

export const IconDeviceWifi1Bar20outlined = () => <SVGDeviceWifi1Bar_20_outlined />;
export const IconDeviceWifi1Bar24outlined = () => <SVGDeviceWifi1Bar_24_outlined />;
export const IconDeviceWifi1Bar20twotone = () => <SVGDeviceWifi1Bar_20_twotone />;
export const IconDeviceWifi1Bar24twotone = () => <SVGDeviceWifi1Bar_24_twotone />;
export const IconDeviceWifi1Bar20sharp = () => <SVGDeviceWifi1Bar_20_sharp />;
export const IconDeviceWifi1Bar24sharp = () => <SVGDeviceWifi1Bar_24_sharp />;
export const IconDeviceWifi1Bar20filled = () => <SVGDeviceWifi1Bar_20_filled />;
export const IconDeviceWifi1Bar24filled = () => <SVGDeviceWifi1Bar_24_filled />;
export const IconDeviceWifi1Bar20round = () => <SVGDeviceWifi1Bar_20_round />;
export const IconDeviceWifi1Bar24round = () => <SVGDeviceWifi1Bar_24_round />;
