import React from "react";
import SVGDeviceBattery3Bar_20_outlined from '../../svg/device/DeviceBattery3Bar/20_outlined.svg';
import SVGDeviceBattery3Bar_24_outlined from '../../svg/device/DeviceBattery3Bar/24_outlined.svg';
import SVGDeviceBattery3Bar_20_twotone from '../../svg/device/DeviceBattery3Bar/20_twotone.svg';
import SVGDeviceBattery3Bar_24_twotone from '../../svg/device/DeviceBattery3Bar/24_twotone.svg';
import SVGDeviceBattery3Bar_20_sharp from '../../svg/device/DeviceBattery3Bar/20_sharp.svg';
import SVGDeviceBattery3Bar_24_sharp from '../../svg/device/DeviceBattery3Bar/24_sharp.svg';
import SVGDeviceBattery3Bar_20_filled from '../../svg/device/DeviceBattery3Bar/20_filled.svg';
import SVGDeviceBattery3Bar_24_filled from '../../svg/device/DeviceBattery3Bar/24_filled.svg';
import SVGDeviceBattery3Bar_20_round from '../../svg/device/DeviceBattery3Bar/20_round.svg';
import SVGDeviceBattery3Bar_24_round from '../../svg/device/DeviceBattery3Bar/24_round.svg';

export const IconDeviceBattery3Bar20outlined = () => <SVGDeviceBattery3Bar_20_outlined />;
export const IconDeviceBattery3Bar24outlined = () => <SVGDeviceBattery3Bar_24_outlined />;
export const IconDeviceBattery3Bar20twotone = () => <SVGDeviceBattery3Bar_20_twotone />;
export const IconDeviceBattery3Bar24twotone = () => <SVGDeviceBattery3Bar_24_twotone />;
export const IconDeviceBattery3Bar20sharp = () => <SVGDeviceBattery3Bar_20_sharp />;
export const IconDeviceBattery3Bar24sharp = () => <SVGDeviceBattery3Bar_24_sharp />;
export const IconDeviceBattery3Bar20filled = () => <SVGDeviceBattery3Bar_20_filled />;
export const IconDeviceBattery3Bar24filled = () => <SVGDeviceBattery3Bar_24_filled />;
export const IconDeviceBattery3Bar20round = () => <SVGDeviceBattery3Bar_20_round />;
export const IconDeviceBattery3Bar24round = () => <SVGDeviceBattery3Bar_24_round />;
