import React from "react";
import SVGDeviceDarkMode_20_outlined from '../../svg/device/DeviceDarkMode/20_outlined.svg';
import SVGDeviceDarkMode_24_outlined from '../../svg/device/DeviceDarkMode/24_outlined.svg';
import SVGDeviceDarkMode_20_twotone from '../../svg/device/DeviceDarkMode/20_twotone.svg';
import SVGDeviceDarkMode_24_twotone from '../../svg/device/DeviceDarkMode/24_twotone.svg';
import SVGDeviceDarkMode_20_sharp from '../../svg/device/DeviceDarkMode/20_sharp.svg';
import SVGDeviceDarkMode_24_sharp from '../../svg/device/DeviceDarkMode/24_sharp.svg';
import SVGDeviceDarkMode_20_filled from '../../svg/device/DeviceDarkMode/20_filled.svg';
import SVGDeviceDarkMode_24_filled from '../../svg/device/DeviceDarkMode/24_filled.svg';
import SVGDeviceDarkMode_20_round from '../../svg/device/DeviceDarkMode/20_round.svg';
import SVGDeviceDarkMode_24_round from '../../svg/device/DeviceDarkMode/24_round.svg';

export const IconDeviceDarkMode20outlined = () => <SVGDeviceDarkMode_20_outlined />;
export const IconDeviceDarkMode24outlined = () => <SVGDeviceDarkMode_24_outlined />;
export const IconDeviceDarkMode20twotone = () => <SVGDeviceDarkMode_20_twotone />;
export const IconDeviceDarkMode24twotone = () => <SVGDeviceDarkMode_24_twotone />;
export const IconDeviceDarkMode20sharp = () => <SVGDeviceDarkMode_20_sharp />;
export const IconDeviceDarkMode24sharp = () => <SVGDeviceDarkMode_24_sharp />;
export const IconDeviceDarkMode20filled = () => <SVGDeviceDarkMode_20_filled />;
export const IconDeviceDarkMode24filled = () => <SVGDeviceDarkMode_24_filled />;
export const IconDeviceDarkMode20round = () => <SVGDeviceDarkMode_20_round />;
export const IconDeviceDarkMode24round = () => <SVGDeviceDarkMode_24_round />;
