import React from "react";
import SVGDeviceNetworkWifi3Bar_20_outlined from '../../svg/device/DeviceNetworkWifi3Bar/20_outlined.svg';
import SVGDeviceNetworkWifi3Bar_24_outlined from '../../svg/device/DeviceNetworkWifi3Bar/24_outlined.svg';
import SVGDeviceNetworkWifi3Bar_20_twotone from '../../svg/device/DeviceNetworkWifi3Bar/20_twotone.svg';
import SVGDeviceNetworkWifi3Bar_24_twotone from '../../svg/device/DeviceNetworkWifi3Bar/24_twotone.svg';
import SVGDeviceNetworkWifi3Bar_20_sharp from '../../svg/device/DeviceNetworkWifi3Bar/20_sharp.svg';
import SVGDeviceNetworkWifi3Bar_24_sharp from '../../svg/device/DeviceNetworkWifi3Bar/24_sharp.svg';
import SVGDeviceNetworkWifi3Bar_20_filled from '../../svg/device/DeviceNetworkWifi3Bar/20_filled.svg';
import SVGDeviceNetworkWifi3Bar_24_filled from '../../svg/device/DeviceNetworkWifi3Bar/24_filled.svg';
import SVGDeviceNetworkWifi3Bar_20_round from '../../svg/device/DeviceNetworkWifi3Bar/20_round.svg';
import SVGDeviceNetworkWifi3Bar_24_round from '../../svg/device/DeviceNetworkWifi3Bar/24_round.svg';

export const IconDeviceNetworkWifi3Bar20outlined = () => <SVGDeviceNetworkWifi3Bar_20_outlined />;
export const IconDeviceNetworkWifi3Bar24outlined = () => <SVGDeviceNetworkWifi3Bar_24_outlined />;
export const IconDeviceNetworkWifi3Bar20twotone = () => <SVGDeviceNetworkWifi3Bar_20_twotone />;
export const IconDeviceNetworkWifi3Bar24twotone = () => <SVGDeviceNetworkWifi3Bar_24_twotone />;
export const IconDeviceNetworkWifi3Bar20sharp = () => <SVGDeviceNetworkWifi3Bar_20_sharp />;
export const IconDeviceNetworkWifi3Bar24sharp = () => <SVGDeviceNetworkWifi3Bar_24_sharp />;
export const IconDeviceNetworkWifi3Bar20filled = () => <SVGDeviceNetworkWifi3Bar_20_filled />;
export const IconDeviceNetworkWifi3Bar24filled = () => <SVGDeviceNetworkWifi3Bar_24_filled />;
export const IconDeviceNetworkWifi3Bar20round = () => <SVGDeviceNetworkWifi3Bar_20_round />;
export const IconDeviceNetworkWifi3Bar24round = () => <SVGDeviceNetworkWifi3Bar_24_round />;
