import React from "react";
import SVGDeviceSignalCellularAlt1Bar_20_outlined from '../../svg/device/DeviceSignalCellularAlt1Bar/20_outlined.svg';
import SVGDeviceSignalCellularAlt1Bar_24_outlined from '../../svg/device/DeviceSignalCellularAlt1Bar/24_outlined.svg';
import SVGDeviceSignalCellularAlt1Bar_20_twotone from '../../svg/device/DeviceSignalCellularAlt1Bar/20_twotone.svg';
import SVGDeviceSignalCellularAlt1Bar_24_twotone from '../../svg/device/DeviceSignalCellularAlt1Bar/24_twotone.svg';
import SVGDeviceSignalCellularAlt1Bar_20_sharp from '../../svg/device/DeviceSignalCellularAlt1Bar/20_sharp.svg';
import SVGDeviceSignalCellularAlt1Bar_24_sharp from '../../svg/device/DeviceSignalCellularAlt1Bar/24_sharp.svg';
import SVGDeviceSignalCellularAlt1Bar_20_filled from '../../svg/device/DeviceSignalCellularAlt1Bar/20_filled.svg';
import SVGDeviceSignalCellularAlt1Bar_24_filled from '../../svg/device/DeviceSignalCellularAlt1Bar/24_filled.svg';
import SVGDeviceSignalCellularAlt1Bar_20_round from '../../svg/device/DeviceSignalCellularAlt1Bar/20_round.svg';
import SVGDeviceSignalCellularAlt1Bar_24_round from '../../svg/device/DeviceSignalCellularAlt1Bar/24_round.svg';

export const IconDeviceSignalCellularAlt1Bar20outlined = () => <SVGDeviceSignalCellularAlt1Bar_20_outlined />;
export const IconDeviceSignalCellularAlt1Bar24outlined = () => <SVGDeviceSignalCellularAlt1Bar_24_outlined />;
export const IconDeviceSignalCellularAlt1Bar20twotone = () => <SVGDeviceSignalCellularAlt1Bar_20_twotone />;
export const IconDeviceSignalCellularAlt1Bar24twotone = () => <SVGDeviceSignalCellularAlt1Bar_24_twotone />;
export const IconDeviceSignalCellularAlt1Bar20sharp = () => <SVGDeviceSignalCellularAlt1Bar_20_sharp />;
export const IconDeviceSignalCellularAlt1Bar24sharp = () => <SVGDeviceSignalCellularAlt1Bar_24_sharp />;
export const IconDeviceSignalCellularAlt1Bar20filled = () => <SVGDeviceSignalCellularAlt1Bar_20_filled />;
export const IconDeviceSignalCellularAlt1Bar24filled = () => <SVGDeviceSignalCellularAlt1Bar_24_filled />;
export const IconDeviceSignalCellularAlt1Bar20round = () => <SVGDeviceSignalCellularAlt1Bar_20_round />;
export const IconDeviceSignalCellularAlt1Bar24round = () => <SVGDeviceSignalCellularAlt1Bar_24_round />;
