import React from "react";
import SVGDeviceWifiLock_20_outlined from '../../svg/device/DeviceWifiLock/20_outlined.svg';
import SVGDeviceWifiLock_24_outlined from '../../svg/device/DeviceWifiLock/24_outlined.svg';
import SVGDeviceWifiLock_20_twotone from '../../svg/device/DeviceWifiLock/20_twotone.svg';
import SVGDeviceWifiLock_24_twotone from '../../svg/device/DeviceWifiLock/24_twotone.svg';
import SVGDeviceWifiLock_20_sharp from '../../svg/device/DeviceWifiLock/20_sharp.svg';
import SVGDeviceWifiLock_24_sharp from '../../svg/device/DeviceWifiLock/24_sharp.svg';
import SVGDeviceWifiLock_20_filled from '../../svg/device/DeviceWifiLock/20_filled.svg';
import SVGDeviceWifiLock_24_filled from '../../svg/device/DeviceWifiLock/24_filled.svg';
import SVGDeviceWifiLock_20_round from '../../svg/device/DeviceWifiLock/20_round.svg';
import SVGDeviceWifiLock_24_round from '../../svg/device/DeviceWifiLock/24_round.svg';

export const IconDeviceWifiLock20outlined = () => <SVGDeviceWifiLock_20_outlined />;
export const IconDeviceWifiLock24outlined = () => <SVGDeviceWifiLock_24_outlined />;
export const IconDeviceWifiLock20twotone = () => <SVGDeviceWifiLock_20_twotone />;
export const IconDeviceWifiLock24twotone = () => <SVGDeviceWifiLock_24_twotone />;
export const IconDeviceWifiLock20sharp = () => <SVGDeviceWifiLock_20_sharp />;
export const IconDeviceWifiLock24sharp = () => <SVGDeviceWifiLock_24_sharp />;
export const IconDeviceWifiLock20filled = () => <SVGDeviceWifiLock_20_filled />;
export const IconDeviceWifiLock24filled = () => <SVGDeviceWifiLock_24_filled />;
export const IconDeviceWifiLock20round = () => <SVGDeviceWifiLock_20_round />;
export const IconDeviceWifiLock24round = () => <SVGDeviceWifiLock_24_round />;
