import React from "react";
import SVGDeviceSignalCellularConnectedNoInternet4Bar_20_outlined from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/20_outlined.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_24_outlined from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/24_outlined.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_20_twotone from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/20_twotone.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_24_twotone from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/24_twotone.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_20_sharp from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/20_sharp.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_24_sharp from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/24_sharp.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_20_filled from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/20_filled.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_24_filled from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/24_filled.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_20_round from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/20_round.svg';
import SVGDeviceSignalCellularConnectedNoInternet4Bar_24_round from '../../svg/device/DeviceSignalCellularConnectedNoInternet4Bar/24_round.svg';

export const IconDeviceSignalCellularConnectedNoInternet4Bar20outlined = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_20_outlined />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar24outlined = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_24_outlined />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar20twotone = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_20_twotone />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar24twotone = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_24_twotone />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar20sharp = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_20_sharp />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar24sharp = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_24_sharp />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar20filled = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_20_filled />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar24filled = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_24_filled />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar20round = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_20_round />;
export const IconDeviceSignalCellularConnectedNoInternet4Bar24round = () => <SVGDeviceSignalCellularConnectedNoInternet4Bar_24_round />;
