import React from "react";
import SVGDeviceNetworkWifi2Bar_20_outlined from '../../svg/device/DeviceNetworkWifi2Bar/20_outlined.svg';
import SVGDeviceNetworkWifi2Bar_24_outlined from '../../svg/device/DeviceNetworkWifi2Bar/24_outlined.svg';
import SVGDeviceNetworkWifi2Bar_20_twotone from '../../svg/device/DeviceNetworkWifi2Bar/20_twotone.svg';
import SVGDeviceNetworkWifi2Bar_24_twotone from '../../svg/device/DeviceNetworkWifi2Bar/24_twotone.svg';
import SVGDeviceNetworkWifi2Bar_20_sharp from '../../svg/device/DeviceNetworkWifi2Bar/20_sharp.svg';
import SVGDeviceNetworkWifi2Bar_24_sharp from '../../svg/device/DeviceNetworkWifi2Bar/24_sharp.svg';
import SVGDeviceNetworkWifi2Bar_20_filled from '../../svg/device/DeviceNetworkWifi2Bar/20_filled.svg';
import SVGDeviceNetworkWifi2Bar_24_filled from '../../svg/device/DeviceNetworkWifi2Bar/24_filled.svg';
import SVGDeviceNetworkWifi2Bar_20_round from '../../svg/device/DeviceNetworkWifi2Bar/20_round.svg';
import SVGDeviceNetworkWifi2Bar_24_round from '../../svg/device/DeviceNetworkWifi2Bar/24_round.svg';

export const IconDeviceNetworkWifi2Bar20outlined = () => <SVGDeviceNetworkWifi2Bar_20_outlined />;
export const IconDeviceNetworkWifi2Bar24outlined = () => <SVGDeviceNetworkWifi2Bar_24_outlined />;
export const IconDeviceNetworkWifi2Bar20twotone = () => <SVGDeviceNetworkWifi2Bar_20_twotone />;
export const IconDeviceNetworkWifi2Bar24twotone = () => <SVGDeviceNetworkWifi2Bar_24_twotone />;
export const IconDeviceNetworkWifi2Bar20sharp = () => <SVGDeviceNetworkWifi2Bar_20_sharp />;
export const IconDeviceNetworkWifi2Bar24sharp = () => <SVGDeviceNetworkWifi2Bar_24_sharp />;
export const IconDeviceNetworkWifi2Bar20filled = () => <SVGDeviceNetworkWifi2Bar_20_filled />;
export const IconDeviceNetworkWifi2Bar24filled = () => <SVGDeviceNetworkWifi2Bar_24_filled />;
export const IconDeviceNetworkWifi2Bar20round = () => <SVGDeviceNetworkWifi2Bar_20_round />;
export const IconDeviceNetworkWifi2Bar24round = () => <SVGDeviceNetworkWifi2Bar_24_round />;
