import React from "react";
import SVGHardwareKeyboardDoubleArrowRight_20_outlined from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/20_outlined.svg';
import SVGHardwareKeyboardDoubleArrowRight_24_outlined from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/24_outlined.svg';
import SVGHardwareKeyboardDoubleArrowRight_20_twotone from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/20_twotone.svg';
import SVGHardwareKeyboardDoubleArrowRight_24_twotone from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/24_twotone.svg';
import SVGHardwareKeyboardDoubleArrowRight_20_sharp from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/20_sharp.svg';
import SVGHardwareKeyboardDoubleArrowRight_24_sharp from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/24_sharp.svg';
import SVGHardwareKeyboardDoubleArrowRight_20_filled from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/20_filled.svg';
import SVGHardwareKeyboardDoubleArrowRight_24_filled from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/24_filled.svg';
import SVGHardwareKeyboardDoubleArrowRight_20_round from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/20_round.svg';
import SVGHardwareKeyboardDoubleArrowRight_24_round from '../../svg/hardware/HardwareKeyboardDoubleArrowRight/24_round.svg';

export const IconHardwareKeyboardDoubleArrowRight20outlined = () => <SVGHardwareKeyboardDoubleArrowRight_20_outlined />;
export const IconHardwareKeyboardDoubleArrowRight24outlined = () => <SVGHardwareKeyboardDoubleArrowRight_24_outlined />;
export const IconHardwareKeyboardDoubleArrowRight20twotone = () => <SVGHardwareKeyboardDoubleArrowRight_20_twotone />;
export const IconHardwareKeyboardDoubleArrowRight24twotone = () => <SVGHardwareKeyboardDoubleArrowRight_24_twotone />;
export const IconHardwareKeyboardDoubleArrowRight20sharp = () => <SVGHardwareKeyboardDoubleArrowRight_20_sharp />;
export const IconHardwareKeyboardDoubleArrowRight24sharp = () => <SVGHardwareKeyboardDoubleArrowRight_24_sharp />;
export const IconHardwareKeyboardDoubleArrowRight20filled = () => <SVGHardwareKeyboardDoubleArrowRight_20_filled />;
export const IconHardwareKeyboardDoubleArrowRight24filled = () => <SVGHardwareKeyboardDoubleArrowRight_24_filled />;
export const IconHardwareKeyboardDoubleArrowRight20round = () => <SVGHardwareKeyboardDoubleArrowRight_20_round />;
export const IconHardwareKeyboardDoubleArrowRight24round = () => <SVGHardwareKeyboardDoubleArrowRight_24_round />;
