import React from "react";
import SVGHardwareToys_20_outlined from '../../svg/hardware/HardwareToys/20_outlined.svg';
import SVGHardwareToys_24_outlined from '../../svg/hardware/HardwareToys/24_outlined.svg';
import SVGHardwareToys_20_twotone from '../../svg/hardware/HardwareToys/20_twotone.svg';
import SVGHardwareToys_24_twotone from '../../svg/hardware/HardwareToys/24_twotone.svg';
import SVGHardwareToys_20_sharp from '../../svg/hardware/HardwareToys/20_sharp.svg';
import SVGHardwareToys_24_sharp from '../../svg/hardware/HardwareToys/24_sharp.svg';
import SVGHardwareToys_20_filled from '../../svg/hardware/HardwareToys/20_filled.svg';
import SVGHardwareToys_24_filled from '../../svg/hardware/HardwareToys/24_filled.svg';
import SVGHardwareToys_20_round from '../../svg/hardware/HardwareToys/20_round.svg';
import SVGHardwareToys_24_round from '../../svg/hardware/HardwareToys/24_round.svg';

export const IconHardwareToys20outlined = () => <SVGHardwareToys_20_outlined />;
export const IconHardwareToys24outlined = () => <SVGHardwareToys_24_outlined />;
export const IconHardwareToys20twotone = () => <SVGHardwareToys_20_twotone />;
export const IconHardwareToys24twotone = () => <SVGHardwareToys_24_twotone />;
export const IconHardwareToys20sharp = () => <SVGHardwareToys_20_sharp />;
export const IconHardwareToys24sharp = () => <SVGHardwareToys_24_sharp />;
export const IconHardwareToys20filled = () => <SVGHardwareToys_20_filled />;
export const IconHardwareToys24filled = () => <SVGHardwareToys_24_filled />;
export const IconHardwareToys20round = () => <SVGHardwareToys_20_round />;
export const IconHardwareToys24round = () => <SVGHardwareToys_24_round />;
