import React from "react";
import SVGHardwareVideogameAssetOff_20_outlined from '../../svg/hardware/HardwareVideogameAssetOff/20_outlined.svg';
import SVGHardwareVideogameAssetOff_24_outlined from '../../svg/hardware/HardwareVideogameAssetOff/24_outlined.svg';
import SVGHardwareVideogameAssetOff_20_twotone from '../../svg/hardware/HardwareVideogameAssetOff/20_twotone.svg';
import SVGHardwareVideogameAssetOff_24_twotone from '../../svg/hardware/HardwareVideogameAssetOff/24_twotone.svg';
import SVGHardwareVideogameAssetOff_20_sharp from '../../svg/hardware/HardwareVideogameAssetOff/20_sharp.svg';
import SVGHardwareVideogameAssetOff_24_sharp from '../../svg/hardware/HardwareVideogameAssetOff/24_sharp.svg';
import SVGHardwareVideogameAssetOff_20_filled from '../../svg/hardware/HardwareVideogameAssetOff/20_filled.svg';
import SVGHardwareVideogameAssetOff_24_filled from '../../svg/hardware/HardwareVideogameAssetOff/24_filled.svg';
import SVGHardwareVideogameAssetOff_20_round from '../../svg/hardware/HardwareVideogameAssetOff/20_round.svg';
import SVGHardwareVideogameAssetOff_24_round from '../../svg/hardware/HardwareVideogameAssetOff/24_round.svg';

export const IconHardwareVideogameAssetOff20outlined = () => <SVGHardwareVideogameAssetOff_20_outlined />;
export const IconHardwareVideogameAssetOff24outlined = () => <SVGHardwareVideogameAssetOff_24_outlined />;
export const IconHardwareVideogameAssetOff20twotone = () => <SVGHardwareVideogameAssetOff_20_twotone />;
export const IconHardwareVideogameAssetOff24twotone = () => <SVGHardwareVideogameAssetOff_24_twotone />;
export const IconHardwareVideogameAssetOff20sharp = () => <SVGHardwareVideogameAssetOff_20_sharp />;
export const IconHardwareVideogameAssetOff24sharp = () => <SVGHardwareVideogameAssetOff_24_sharp />;
export const IconHardwareVideogameAssetOff20filled = () => <SVGHardwareVideogameAssetOff_20_filled />;
export const IconHardwareVideogameAssetOff24filled = () => <SVGHardwareVideogameAssetOff_24_filled />;
export const IconHardwareVideogameAssetOff20round = () => <SVGHardwareVideogameAssetOff_20_round />;
export const IconHardwareVideogameAssetOff24round = () => <SVGHardwareVideogameAssetOff_24_round />;
