import React from "react";
import SVGHardwareKeyboardDoubleArrowUp_20_outlined from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/20_outlined.svg';
import SVGHardwareKeyboardDoubleArrowUp_24_outlined from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/24_outlined.svg';
import SVGHardwareKeyboardDoubleArrowUp_20_twotone from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/20_twotone.svg';
import SVGHardwareKeyboardDoubleArrowUp_24_twotone from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/24_twotone.svg';
import SVGHardwareKeyboardDoubleArrowUp_20_sharp from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/20_sharp.svg';
import SVGHardwareKeyboardDoubleArrowUp_24_sharp from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/24_sharp.svg';
import SVGHardwareKeyboardDoubleArrowUp_20_filled from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/20_filled.svg';
import SVGHardwareKeyboardDoubleArrowUp_24_filled from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/24_filled.svg';
import SVGHardwareKeyboardDoubleArrowUp_20_round from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/20_round.svg';
import SVGHardwareKeyboardDoubleArrowUp_24_round from '../../svg/hardware/HardwareKeyboardDoubleArrowUp/24_round.svg';

export const IconHardwareKeyboardDoubleArrowUp20outlined = () => <SVGHardwareKeyboardDoubleArrowUp_20_outlined />;
export const IconHardwareKeyboardDoubleArrowUp24outlined = () => <SVGHardwareKeyboardDoubleArrowUp_24_outlined />;
export const IconHardwareKeyboardDoubleArrowUp20twotone = () => <SVGHardwareKeyboardDoubleArrowUp_20_twotone />;
export const IconHardwareKeyboardDoubleArrowUp24twotone = () => <SVGHardwareKeyboardDoubleArrowUp_24_twotone />;
export const IconHardwareKeyboardDoubleArrowUp20sharp = () => <SVGHardwareKeyboardDoubleArrowUp_20_sharp />;
export const IconHardwareKeyboardDoubleArrowUp24sharp = () => <SVGHardwareKeyboardDoubleArrowUp_24_sharp />;
export const IconHardwareKeyboardDoubleArrowUp20filled = () => <SVGHardwareKeyboardDoubleArrowUp_20_filled />;
export const IconHardwareKeyboardDoubleArrowUp24filled = () => <SVGHardwareKeyboardDoubleArrowUp_24_filled />;
export const IconHardwareKeyboardDoubleArrowUp20round = () => <SVGHardwareKeyboardDoubleArrowUp_20_round />;
export const IconHardwareKeyboardDoubleArrowUp24round = () => <SVGHardwareKeyboardDoubleArrowUp_24_round />;
