import React from "react";
import SVGHardwareKeyboardCommandKey_20_outlined from '../../svg/hardware/HardwareKeyboardCommandKey/20_outlined.svg';
import SVGHardwareKeyboardCommandKey_24_outlined from '../../svg/hardware/HardwareKeyboardCommandKey/24_outlined.svg';
import SVGHardwareKeyboardCommandKey_20_twotone from '../../svg/hardware/HardwareKeyboardCommandKey/20_twotone.svg';
import SVGHardwareKeyboardCommandKey_24_twotone from '../../svg/hardware/HardwareKeyboardCommandKey/24_twotone.svg';
import SVGHardwareKeyboardCommandKey_20_sharp from '../../svg/hardware/HardwareKeyboardCommandKey/20_sharp.svg';
import SVGHardwareKeyboardCommandKey_24_sharp from '../../svg/hardware/HardwareKeyboardCommandKey/24_sharp.svg';
import SVGHardwareKeyboardCommandKey_20_filled from '../../svg/hardware/HardwareKeyboardCommandKey/20_filled.svg';
import SVGHardwareKeyboardCommandKey_24_filled from '../../svg/hardware/HardwareKeyboardCommandKey/24_filled.svg';
import SVGHardwareKeyboardCommandKey_20_round from '../../svg/hardware/HardwareKeyboardCommandKey/20_round.svg';
import SVGHardwareKeyboardCommandKey_24_round from '../../svg/hardware/HardwareKeyboardCommandKey/24_round.svg';

export const IconHardwareKeyboardCommandKey20outlined = () => <SVGHardwareKeyboardCommandKey_20_outlined />;
export const IconHardwareKeyboardCommandKey24outlined = () => <SVGHardwareKeyboardCommandKey_24_outlined />;
export const IconHardwareKeyboardCommandKey20twotone = () => <SVGHardwareKeyboardCommandKey_20_twotone />;
export const IconHardwareKeyboardCommandKey24twotone = () => <SVGHardwareKeyboardCommandKey_24_twotone />;
export const IconHardwareKeyboardCommandKey20sharp = () => <SVGHardwareKeyboardCommandKey_20_sharp />;
export const IconHardwareKeyboardCommandKey24sharp = () => <SVGHardwareKeyboardCommandKey_24_sharp />;
export const IconHardwareKeyboardCommandKey20filled = () => <SVGHardwareKeyboardCommandKey_20_filled />;
export const IconHardwareKeyboardCommandKey24filled = () => <SVGHardwareKeyboardCommandKey_24_filled />;
export const IconHardwareKeyboardCommandKey20round = () => <SVGHardwareKeyboardCommandKey_20_round />;
export const IconHardwareKeyboardCommandKey24round = () => <SVGHardwareKeyboardCommandKey_24_round />;
