import React from "react";
import SVGHardwareBrowserNotSupported_20_outlined from '../../svg/hardware/HardwareBrowserNotSupported/20_outlined.svg';
import SVGHardwareBrowserNotSupported_24_outlined from '../../svg/hardware/HardwareBrowserNotSupported/24_outlined.svg';
import SVGHardwareBrowserNotSupported_20_twotone from '../../svg/hardware/HardwareBrowserNotSupported/20_twotone.svg';
import SVGHardwareBrowserNotSupported_24_twotone from '../../svg/hardware/HardwareBrowserNotSupported/24_twotone.svg';
import SVGHardwareBrowserNotSupported_20_sharp from '../../svg/hardware/HardwareBrowserNotSupported/20_sharp.svg';
import SVGHardwareBrowserNotSupported_24_sharp from '../../svg/hardware/HardwareBrowserNotSupported/24_sharp.svg';
import SVGHardwareBrowserNotSupported_20_filled from '../../svg/hardware/HardwareBrowserNotSupported/20_filled.svg';
import SVGHardwareBrowserNotSupported_24_filled from '../../svg/hardware/HardwareBrowserNotSupported/24_filled.svg';
import SVGHardwareBrowserNotSupported_20_round from '../../svg/hardware/HardwareBrowserNotSupported/20_round.svg';
import SVGHardwareBrowserNotSupported_24_round from '../../svg/hardware/HardwareBrowserNotSupported/24_round.svg';

export const IconHardwareBrowserNotSupported20outlined = () => <SVGHardwareBrowserNotSupported_20_outlined />;
export const IconHardwareBrowserNotSupported24outlined = () => <SVGHardwareBrowserNotSupported_24_outlined />;
export const IconHardwareBrowserNotSupported20twotone = () => <SVGHardwareBrowserNotSupported_20_twotone />;
export const IconHardwareBrowserNotSupported24twotone = () => <SVGHardwareBrowserNotSupported_24_twotone />;
export const IconHardwareBrowserNotSupported20sharp = () => <SVGHardwareBrowserNotSupported_20_sharp />;
export const IconHardwareBrowserNotSupported24sharp = () => <SVGHardwareBrowserNotSupported_24_sharp />;
export const IconHardwareBrowserNotSupported20filled = () => <SVGHardwareBrowserNotSupported_20_filled />;
export const IconHardwareBrowserNotSupported24filled = () => <SVGHardwareBrowserNotSupported_24_filled />;
export const IconHardwareBrowserNotSupported20round = () => <SVGHardwareBrowserNotSupported_20_round />;
export const IconHardwareBrowserNotSupported24round = () => <SVGHardwareBrowserNotSupported_24_round />;
