import React from "react";
import SVGFileWorkspaces_20_outlined from '../../svg/file/FileWorkspaces/20_outlined.svg';
import SVGFileWorkspaces_24_outlined from '../../svg/file/FileWorkspaces/24_outlined.svg';
import SVGFileWorkspaces_20_twotone from '../../svg/file/FileWorkspaces/20_twotone.svg';
import SVGFileWorkspaces_24_twotone from '../../svg/file/FileWorkspaces/24_twotone.svg';
import SVGFileWorkspaces_20_sharp from '../../svg/file/FileWorkspaces/20_sharp.svg';
import SVGFileWorkspaces_24_sharp from '../../svg/file/FileWorkspaces/24_sharp.svg';
import SVGFileWorkspaces_20_filled from '../../svg/file/FileWorkspaces/20_filled.svg';
import SVGFileWorkspaces_24_filled from '../../svg/file/FileWorkspaces/24_filled.svg';
import SVGFileWorkspaces_20_round from '../../svg/file/FileWorkspaces/20_round.svg';
import SVGFileWorkspaces_24_round from '../../svg/file/FileWorkspaces/24_round.svg';

export const IconFileWorkspaces20outlined = () => <SVGFileWorkspaces_20_outlined />;
export const IconFileWorkspaces24outlined = () => <SVGFileWorkspaces_24_outlined />;
export const IconFileWorkspaces20twotone = () => <SVGFileWorkspaces_20_twotone />;
export const IconFileWorkspaces24twotone = () => <SVGFileWorkspaces_24_twotone />;
export const IconFileWorkspaces20sharp = () => <SVGFileWorkspaces_20_sharp />;
export const IconFileWorkspaces24sharp = () => <SVGFileWorkspaces_24_sharp />;
export const IconFileWorkspaces20filled = () => <SVGFileWorkspaces_20_filled />;
export const IconFileWorkspaces24filled = () => <SVGFileWorkspaces_24_filled />;
export const IconFileWorkspaces20round = () => <SVGFileWorkspaces_20_round />;
export const IconFileWorkspaces24round = () => <SVGFileWorkspaces_24_round />;
