import React from "react";
import SVGFileNewspaper_20_outlined from '../../svg/file/FileNewspaper/20_outlined.svg';
import SVGFileNewspaper_24_outlined from '../../svg/file/FileNewspaper/24_outlined.svg';
import SVGFileNewspaper_20_twotone from '../../svg/file/FileNewspaper/20_twotone.svg';
import SVGFileNewspaper_24_twotone from '../../svg/file/FileNewspaper/24_twotone.svg';
import SVGFileNewspaper_20_sharp from '../../svg/file/FileNewspaper/20_sharp.svg';
import SVGFileNewspaper_24_sharp from '../../svg/file/FileNewspaper/24_sharp.svg';
import SVGFileNewspaper_20_filled from '../../svg/file/FileNewspaper/20_filled.svg';
import SVGFileNewspaper_24_filled from '../../svg/file/FileNewspaper/24_filled.svg';
import SVGFileNewspaper_20_round from '../../svg/file/FileNewspaper/20_round.svg';
import SVGFileNewspaper_24_round from '../../svg/file/FileNewspaper/24_round.svg';

export const IconFileNewspaper20outlined = () => <SVGFileNewspaper_20_outlined />;
export const IconFileNewspaper24outlined = () => <SVGFileNewspaper_24_outlined />;
export const IconFileNewspaper20twotone = () => <SVGFileNewspaper_20_twotone />;
export const IconFileNewspaper24twotone = () => <SVGFileNewspaper_24_twotone />;
export const IconFileNewspaper20sharp = () => <SVGFileNewspaper_20_sharp />;
export const IconFileNewspaper24sharp = () => <SVGFileNewspaper_24_sharp />;
export const IconFileNewspaper20filled = () => <SVGFileNewspaper_20_filled />;
export const IconFileNewspaper24filled = () => <SVGFileNewspaper_24_filled />;
export const IconFileNewspaper20round = () => <SVGFileNewspaper_20_round />;
export const IconFileNewspaper24round = () => <SVGFileNewspaper_24_round />;
