import React from "react";
import SVGFileFolderZip_20_outlined from '../../svg/file/FileFolderZip/20_outlined.svg';
import SVGFileFolderZip_24_outlined from '../../svg/file/FileFolderZip/24_outlined.svg';
import SVGFileFolderZip_20_twotone from '../../svg/file/FileFolderZip/20_twotone.svg';
import SVGFileFolderZip_24_twotone from '../../svg/file/FileFolderZip/24_twotone.svg';
import SVGFileFolderZip_20_sharp from '../../svg/file/FileFolderZip/20_sharp.svg';
import SVGFileFolderZip_24_sharp from '../../svg/file/FileFolderZip/24_sharp.svg';
import SVGFileFolderZip_20_filled from '../../svg/file/FileFolderZip/20_filled.svg';
import SVGFileFolderZip_24_filled from '../../svg/file/FileFolderZip/24_filled.svg';
import SVGFileFolderZip_20_round from '../../svg/file/FileFolderZip/20_round.svg';
import SVGFileFolderZip_24_round from '../../svg/file/FileFolderZip/24_round.svg';

export const IconFileFolderZip20outlined = () => <SVGFileFolderZip_20_outlined />;
export const IconFileFolderZip24outlined = () => <SVGFileFolderZip_24_outlined />;
export const IconFileFolderZip20twotone = () => <SVGFileFolderZip_20_twotone />;
export const IconFileFolderZip24twotone = () => <SVGFileFolderZip_24_twotone />;
export const IconFileFolderZip20sharp = () => <SVGFileFolderZip_20_sharp />;
export const IconFileFolderZip24sharp = () => <SVGFileFolderZip_24_sharp />;
export const IconFileFolderZip20filled = () => <SVGFileFolderZip_20_filled />;
export const IconFileFolderZip24filled = () => <SVGFileFolderZip_24_filled />;
export const IconFileFolderZip20round = () => <SVGFileFolderZip_20_round />;
export const IconFileFolderZip24round = () => <SVGFileFolderZip_24_round />;
