import React from "react";
import SVGFileDriveFileMoveRtl_20_outlined from '../../svg/file/FileDriveFileMoveRtl/20_outlined.svg';
import SVGFileDriveFileMoveRtl_24_outlined from '../../svg/file/FileDriveFileMoveRtl/24_outlined.svg';
import SVGFileDriveFileMoveRtl_20_twotone from '../../svg/file/FileDriveFileMoveRtl/20_twotone.svg';
import SVGFileDriveFileMoveRtl_24_twotone from '../../svg/file/FileDriveFileMoveRtl/24_twotone.svg';
import SVGFileDriveFileMoveRtl_20_sharp from '../../svg/file/FileDriveFileMoveRtl/20_sharp.svg';
import SVGFileDriveFileMoveRtl_24_sharp from '../../svg/file/FileDriveFileMoveRtl/24_sharp.svg';
import SVGFileDriveFileMoveRtl_20_filled from '../../svg/file/FileDriveFileMoveRtl/20_filled.svg';
import SVGFileDriveFileMoveRtl_24_filled from '../../svg/file/FileDriveFileMoveRtl/24_filled.svg';
import SVGFileDriveFileMoveRtl_20_round from '../../svg/file/FileDriveFileMoveRtl/20_round.svg';
import SVGFileDriveFileMoveRtl_24_round from '../../svg/file/FileDriveFileMoveRtl/24_round.svg';

export const IconFileDriveFileMoveRtl20outlined = () => <SVGFileDriveFileMoveRtl_20_outlined />;
export const IconFileDriveFileMoveRtl24outlined = () => <SVGFileDriveFileMoveRtl_24_outlined />;
export const IconFileDriveFileMoveRtl20twotone = () => <SVGFileDriveFileMoveRtl_20_twotone />;
export const IconFileDriveFileMoveRtl24twotone = () => <SVGFileDriveFileMoveRtl_24_twotone />;
export const IconFileDriveFileMoveRtl20sharp = () => <SVGFileDriveFileMoveRtl_20_sharp />;
export const IconFileDriveFileMoveRtl24sharp = () => <SVGFileDriveFileMoveRtl_24_sharp />;
export const IconFileDriveFileMoveRtl20filled = () => <SVGFileDriveFileMoveRtl_20_filled />;
export const IconFileDriveFileMoveRtl24filled = () => <SVGFileDriveFileMoveRtl_24_filled />;
export const IconFileDriveFileMoveRtl20round = () => <SVGFileDriveFileMoveRtl_20_round />;
export const IconFileDriveFileMoveRtl24round = () => <SVGFileDriveFileMoveRtl_24_round />;
