import React from "react";
import SVGPlacesBathtub_20_outlined from '../../svg/places/PlacesBathtub/20_outlined.svg';
import SVGPlacesBathtub_24_outlined from '../../svg/places/PlacesBathtub/24_outlined.svg';
import SVGPlacesBathtub_20_twotone from '../../svg/places/PlacesBathtub/20_twotone.svg';
import SVGPlacesBathtub_24_twotone from '../../svg/places/PlacesBathtub/24_twotone.svg';
import SVGPlacesBathtub_20_sharp from '../../svg/places/PlacesBathtub/20_sharp.svg';
import SVGPlacesBathtub_24_sharp from '../../svg/places/PlacesBathtub/24_sharp.svg';
import SVGPlacesBathtub_20_filled from '../../svg/places/PlacesBathtub/20_filled.svg';
import SVGPlacesBathtub_24_filled from '../../svg/places/PlacesBathtub/24_filled.svg';
import SVGPlacesBathtub_20_round from '../../svg/places/PlacesBathtub/20_round.svg';
import SVGPlacesBathtub_24_round from '../../svg/places/PlacesBathtub/24_round.svg';

export const IconPlacesBathtub20outlined = () => <SVGPlacesBathtub_20_outlined />;
export const IconPlacesBathtub24outlined = () => <SVGPlacesBathtub_24_outlined />;
export const IconPlacesBathtub20twotone = () => <SVGPlacesBathtub_20_twotone />;
export const IconPlacesBathtub24twotone = () => <SVGPlacesBathtub_24_twotone />;
export const IconPlacesBathtub20sharp = () => <SVGPlacesBathtub_20_sharp />;
export const IconPlacesBathtub24sharp = () => <SVGPlacesBathtub_24_sharp />;
export const IconPlacesBathtub20filled = () => <SVGPlacesBathtub_20_filled />;
export const IconPlacesBathtub24filled = () => <SVGPlacesBathtub_24_filled />;
export const IconPlacesBathtub20round = () => <SVGPlacesBathtub_20_round />;
export const IconPlacesBathtub24round = () => <SVGPlacesBathtub_24_round />;
