import React from "react";
import SVGPlacesDesk_20_outlined from '../../svg/places/PlacesDesk/20_outlined.svg';
import SVGPlacesDesk_24_outlined from '../../svg/places/PlacesDesk/24_outlined.svg';
import SVGPlacesDesk_20_twotone from '../../svg/places/PlacesDesk/20_twotone.svg';
import SVGPlacesDesk_24_twotone from '../../svg/places/PlacesDesk/24_twotone.svg';
import SVGPlacesDesk_20_sharp from '../../svg/places/PlacesDesk/20_sharp.svg';
import SVGPlacesDesk_24_sharp from '../../svg/places/PlacesDesk/24_sharp.svg';
import SVGPlacesDesk_20_filled from '../../svg/places/PlacesDesk/20_filled.svg';
import SVGPlacesDesk_24_filled from '../../svg/places/PlacesDesk/24_filled.svg';
import SVGPlacesDesk_20_round from '../../svg/places/PlacesDesk/20_round.svg';
import SVGPlacesDesk_24_round from '../../svg/places/PlacesDesk/24_round.svg';

export const IconPlacesDesk20outlined = () => <SVGPlacesDesk_20_outlined />;
export const IconPlacesDesk24outlined = () => <SVGPlacesDesk_24_outlined />;
export const IconPlacesDesk20twotone = () => <SVGPlacesDesk_20_twotone />;
export const IconPlacesDesk24twotone = () => <SVGPlacesDesk_24_twotone />;
export const IconPlacesDesk20sharp = () => <SVGPlacesDesk_20_sharp />;
export const IconPlacesDesk24sharp = () => <SVGPlacesDesk_24_sharp />;
export const IconPlacesDesk20filled = () => <SVGPlacesDesk_20_filled />;
export const IconPlacesDesk24filled = () => <SVGPlacesDesk_24_filled />;
export const IconPlacesDesk20round = () => <SVGPlacesDesk_20_round />;
export const IconPlacesDesk24round = () => <SVGPlacesDesk_24_round />;
