import React from "react";
import SVGPlacesCrib_20_outlined from '../../svg/places/PlacesCrib/20_outlined.svg';
import SVGPlacesCrib_24_outlined from '../../svg/places/PlacesCrib/24_outlined.svg';
import SVGPlacesCrib_20_twotone from '../../svg/places/PlacesCrib/20_twotone.svg';
import SVGPlacesCrib_24_twotone from '../../svg/places/PlacesCrib/24_twotone.svg';
import SVGPlacesCrib_20_sharp from '../../svg/places/PlacesCrib/20_sharp.svg';
import SVGPlacesCrib_24_sharp from '../../svg/places/PlacesCrib/24_sharp.svg';
import SVGPlacesCrib_20_filled from '../../svg/places/PlacesCrib/20_filled.svg';
import SVGPlacesCrib_24_filled from '../../svg/places/PlacesCrib/24_filled.svg';
import SVGPlacesCrib_20_round from '../../svg/places/PlacesCrib/20_round.svg';
import SVGPlacesCrib_24_round from '../../svg/places/PlacesCrib/24_round.svg';

export const IconPlacesCrib20outlined = () => <SVGPlacesCrib_20_outlined />;
export const IconPlacesCrib24outlined = () => <SVGPlacesCrib_24_outlined />;
export const IconPlacesCrib20twotone = () => <SVGPlacesCrib_20_twotone />;
export const IconPlacesCrib24twotone = () => <SVGPlacesCrib_24_twotone />;
export const IconPlacesCrib20sharp = () => <SVGPlacesCrib_20_sharp />;
export const IconPlacesCrib24sharp = () => <SVGPlacesCrib_24_sharp />;
export const IconPlacesCrib20filled = () => <SVGPlacesCrib_20_filled />;
export const IconPlacesCrib24filled = () => <SVGPlacesCrib_24_filled />;
export const IconPlacesCrib20round = () => <SVGPlacesCrib_20_round />;
export const IconPlacesCrib24round = () => <SVGPlacesCrib_24_round />;
