import React from "react";
import SVGPlacesVapingRooms_20_outlined from '../../svg/places/PlacesVapingRooms/20_outlined.svg';
import SVGPlacesVapingRooms_24_outlined from '../../svg/places/PlacesVapingRooms/24_outlined.svg';
import SVGPlacesVapingRooms_20_twotone from '../../svg/places/PlacesVapingRooms/20_twotone.svg';
import SVGPlacesVapingRooms_24_twotone from '../../svg/places/PlacesVapingRooms/24_twotone.svg';
import SVGPlacesVapingRooms_20_sharp from '../../svg/places/PlacesVapingRooms/20_sharp.svg';
import SVGPlacesVapingRooms_24_sharp from '../../svg/places/PlacesVapingRooms/24_sharp.svg';
import SVGPlacesVapingRooms_20_filled from '../../svg/places/PlacesVapingRooms/20_filled.svg';
import SVGPlacesVapingRooms_24_filled from '../../svg/places/PlacesVapingRooms/24_filled.svg';
import SVGPlacesVapingRooms_20_round from '../../svg/places/PlacesVapingRooms/20_round.svg';
import SVGPlacesVapingRooms_24_round from '../../svg/places/PlacesVapingRooms/24_round.svg';

export const IconPlacesVapingRooms20outlined = () => <SVGPlacesVapingRooms_20_outlined />;
export const IconPlacesVapingRooms24outlined = () => <SVGPlacesVapingRooms_24_outlined />;
export const IconPlacesVapingRooms20twotone = () => <SVGPlacesVapingRooms_20_twotone />;
export const IconPlacesVapingRooms24twotone = () => <SVGPlacesVapingRooms_24_twotone />;
export const IconPlacesVapingRooms20sharp = () => <SVGPlacesVapingRooms_20_sharp />;
export const IconPlacesVapingRooms24sharp = () => <SVGPlacesVapingRooms_24_sharp />;
export const IconPlacesVapingRooms20filled = () => <SVGPlacesVapingRooms_20_filled />;
export const IconPlacesVapingRooms24filled = () => <SVGPlacesVapingRooms_24_filled />;
export const IconPlacesVapingRooms20round = () => <SVGPlacesVapingRooms_20_round />;
export const IconPlacesVapingRooms24round = () => <SVGPlacesVapingRooms_24_round />;
