import React from "react";
import SVGCommunicationVpnKeyOff_20_outlined from '../../svg/communication/CommunicationVpnKeyOff/20_outlined.svg';
import SVGCommunicationVpnKeyOff_24_outlined from '../../svg/communication/CommunicationVpnKeyOff/24_outlined.svg';
import SVGCommunicationVpnKeyOff_20_twotone from '../../svg/communication/CommunicationVpnKeyOff/20_twotone.svg';
import SVGCommunicationVpnKeyOff_24_twotone from '../../svg/communication/CommunicationVpnKeyOff/24_twotone.svg';
import SVGCommunicationVpnKeyOff_20_sharp from '../../svg/communication/CommunicationVpnKeyOff/20_sharp.svg';
import SVGCommunicationVpnKeyOff_24_sharp from '../../svg/communication/CommunicationVpnKeyOff/24_sharp.svg';
import SVGCommunicationVpnKeyOff_20_filled from '../../svg/communication/CommunicationVpnKeyOff/20_filled.svg';
import SVGCommunicationVpnKeyOff_24_filled from '../../svg/communication/CommunicationVpnKeyOff/24_filled.svg';
import SVGCommunicationVpnKeyOff_20_round from '../../svg/communication/CommunicationVpnKeyOff/20_round.svg';
import SVGCommunicationVpnKeyOff_24_round from '../../svg/communication/CommunicationVpnKeyOff/24_round.svg';

export const IconCommunicationVpnKeyOff20outlined = () => <SVGCommunicationVpnKeyOff_20_outlined />;
export const IconCommunicationVpnKeyOff24outlined = () => <SVGCommunicationVpnKeyOff_24_outlined />;
export const IconCommunicationVpnKeyOff20twotone = () => <SVGCommunicationVpnKeyOff_20_twotone />;
export const IconCommunicationVpnKeyOff24twotone = () => <SVGCommunicationVpnKeyOff_24_twotone />;
export const IconCommunicationVpnKeyOff20sharp = () => <SVGCommunicationVpnKeyOff_20_sharp />;
export const IconCommunicationVpnKeyOff24sharp = () => <SVGCommunicationVpnKeyOff_24_sharp />;
export const IconCommunicationVpnKeyOff20filled = () => <SVGCommunicationVpnKeyOff_20_filled />;
export const IconCommunicationVpnKeyOff24filled = () => <SVGCommunicationVpnKeyOff_24_filled />;
export const IconCommunicationVpnKeyOff20round = () => <SVGCommunicationVpnKeyOff_20_round />;
export const IconCommunicationVpnKeyOff24round = () => <SVGCommunicationVpnKeyOff_24_round />;
