import React from "react";
import SVGCommunicationForwardToInbox_20_outlined from '../../svg/communication/CommunicationForwardToInbox/20_outlined.svg';
import SVGCommunicationForwardToInbox_24_outlined from '../../svg/communication/CommunicationForwardToInbox/24_outlined.svg';
import SVGCommunicationForwardToInbox_20_twotone from '../../svg/communication/CommunicationForwardToInbox/20_twotone.svg';
import SVGCommunicationForwardToInbox_24_twotone from '../../svg/communication/CommunicationForwardToInbox/24_twotone.svg';
import SVGCommunicationForwardToInbox_20_sharp from '../../svg/communication/CommunicationForwardToInbox/20_sharp.svg';
import SVGCommunicationForwardToInbox_24_sharp from '../../svg/communication/CommunicationForwardToInbox/24_sharp.svg';
import SVGCommunicationForwardToInbox_20_filled from '../../svg/communication/CommunicationForwardToInbox/20_filled.svg';
import SVGCommunicationForwardToInbox_24_filled from '../../svg/communication/CommunicationForwardToInbox/24_filled.svg';
import SVGCommunicationForwardToInbox_20_round from '../../svg/communication/CommunicationForwardToInbox/20_round.svg';
import SVGCommunicationForwardToInbox_24_round from '../../svg/communication/CommunicationForwardToInbox/24_round.svg';

export const IconCommunicationForwardToInbox20outlined = () => <SVGCommunicationForwardToInbox_20_outlined />;
export const IconCommunicationForwardToInbox24outlined = () => <SVGCommunicationForwardToInbox_24_outlined />;
export const IconCommunicationForwardToInbox20twotone = () => <SVGCommunicationForwardToInbox_20_twotone />;
export const IconCommunicationForwardToInbox24twotone = () => <SVGCommunicationForwardToInbox_24_twotone />;
export const IconCommunicationForwardToInbox20sharp = () => <SVGCommunicationForwardToInbox_20_sharp />;
export const IconCommunicationForwardToInbox24sharp = () => <SVGCommunicationForwardToInbox_24_sharp />;
export const IconCommunicationForwardToInbox20filled = () => <SVGCommunicationForwardToInbox_20_filled />;
export const IconCommunicationForwardToInbox24filled = () => <SVGCommunicationForwardToInbox_24_filled />;
export const IconCommunicationForwardToInbox20round = () => <SVGCommunicationForwardToInbox_20_round />;
export const IconCommunicationForwardToInbox24round = () => <SVGCommunicationForwardToInbox_24_round />;
