import React from "react";
import SVGCommunicationHub_20_outlined from '../../svg/communication/CommunicationHub/20_outlined.svg';
import SVGCommunicationHub_24_outlined from '../../svg/communication/CommunicationHub/24_outlined.svg';
import SVGCommunicationHub_20_twotone from '../../svg/communication/CommunicationHub/20_twotone.svg';
import SVGCommunicationHub_24_twotone from '../../svg/communication/CommunicationHub/24_twotone.svg';
import SVGCommunicationHub_20_sharp from '../../svg/communication/CommunicationHub/20_sharp.svg';
import SVGCommunicationHub_24_sharp from '../../svg/communication/CommunicationHub/24_sharp.svg';
import SVGCommunicationHub_20_filled from '../../svg/communication/CommunicationHub/20_filled.svg';
import SVGCommunicationHub_24_filled from '../../svg/communication/CommunicationHub/24_filled.svg';
import SVGCommunicationHub_20_round from '../../svg/communication/CommunicationHub/20_round.svg';
import SVGCommunicationHub_24_round from '../../svg/communication/CommunicationHub/24_round.svg';

export const IconCommunicationHub20outlined = () => <SVGCommunicationHub_20_outlined />;
export const IconCommunicationHub24outlined = () => <SVGCommunicationHub_24_outlined />;
export const IconCommunicationHub20twotone = () => <SVGCommunicationHub_20_twotone />;
export const IconCommunicationHub24twotone = () => <SVGCommunicationHub_24_twotone />;
export const IconCommunicationHub20sharp = () => <SVGCommunicationHub_20_sharp />;
export const IconCommunicationHub24sharp = () => <SVGCommunicationHub_24_sharp />;
export const IconCommunicationHub20filled = () => <SVGCommunicationHub_20_filled />;
export const IconCommunicationHub24filled = () => <SVGCommunicationHub_24_filled />;
export const IconCommunicationHub20round = () => <SVGCommunicationHub_20_round />;
export const IconCommunicationHub24round = () => <SVGCommunicationHub_24_round />;
