import React from "react";
import SVGNavigationDoubleArrow_20_outlined from '../../svg/navigation/NavigationDoubleArrow/20_outlined.svg';
import SVGNavigationDoubleArrow_24_outlined from '../../svg/navigation/NavigationDoubleArrow/24_outlined.svg';
import SVGNavigationDoubleArrow_20_twotone from '../../svg/navigation/NavigationDoubleArrow/20_twotone.svg';
import SVGNavigationDoubleArrow_24_twotone from '../../svg/navigation/NavigationDoubleArrow/24_twotone.svg';
import SVGNavigationDoubleArrow_20_sharp from '../../svg/navigation/NavigationDoubleArrow/20_sharp.svg';
import SVGNavigationDoubleArrow_24_sharp from '../../svg/navigation/NavigationDoubleArrow/24_sharp.svg';
import SVGNavigationDoubleArrow_20_filled from '../../svg/navigation/NavigationDoubleArrow/20_filled.svg';
import SVGNavigationDoubleArrow_24_filled from '../../svg/navigation/NavigationDoubleArrow/24_filled.svg';
import SVGNavigationDoubleArrow_20_round from '../../svg/navigation/NavigationDoubleArrow/20_round.svg';
import SVGNavigationDoubleArrow_24_round from '../../svg/navigation/NavigationDoubleArrow/24_round.svg';

export const IconNavigationDoubleArrow20outlined = () => <SVGNavigationDoubleArrow_20_outlined />;
export const IconNavigationDoubleArrow24outlined = () => <SVGNavigationDoubleArrow_24_outlined />;
export const IconNavigationDoubleArrow20twotone = () => <SVGNavigationDoubleArrow_20_twotone />;
export const IconNavigationDoubleArrow24twotone = () => <SVGNavigationDoubleArrow_24_twotone />;
export const IconNavigationDoubleArrow20sharp = () => <SVGNavigationDoubleArrow_20_sharp />;
export const IconNavigationDoubleArrow24sharp = () => <SVGNavigationDoubleArrow_24_sharp />;
export const IconNavigationDoubleArrow20filled = () => <SVGNavigationDoubleArrow_20_filled />;
export const IconNavigationDoubleArrow24filled = () => <SVGNavigationDoubleArrow_24_filled />;
export const IconNavigationDoubleArrow20round = () => <SVGNavigationDoubleArrow_20_round />;
export const IconNavigationDoubleArrow24round = () => <SVGNavigationDoubleArrow_24_round />;
