import React from "react";
import SVGNavigationAddHomeWork_20_outlined from '../../svg/navigation/NavigationAddHomeWork/20_outlined.svg';
import SVGNavigationAddHomeWork_24_outlined from '../../svg/navigation/NavigationAddHomeWork/24_outlined.svg';
import SVGNavigationAddHomeWork_20_twotone from '../../svg/navigation/NavigationAddHomeWork/20_twotone.svg';
import SVGNavigationAddHomeWork_24_twotone from '../../svg/navigation/NavigationAddHomeWork/24_twotone.svg';
import SVGNavigationAddHomeWork_20_sharp from '../../svg/navigation/NavigationAddHomeWork/20_sharp.svg';
import SVGNavigationAddHomeWork_24_sharp from '../../svg/navigation/NavigationAddHomeWork/24_sharp.svg';
import SVGNavigationAddHomeWork_20_filled from '../../svg/navigation/NavigationAddHomeWork/20_filled.svg';
import SVGNavigationAddHomeWork_24_filled from '../../svg/navigation/NavigationAddHomeWork/24_filled.svg';
import SVGNavigationAddHomeWork_20_round from '../../svg/navigation/NavigationAddHomeWork/20_round.svg';
import SVGNavigationAddHomeWork_24_round from '../../svg/navigation/NavigationAddHomeWork/24_round.svg';

export const IconNavigationAddHomeWork20outlined = () => <SVGNavigationAddHomeWork_20_outlined />;
export const IconNavigationAddHomeWork24outlined = () => <SVGNavigationAddHomeWork_24_outlined />;
export const IconNavigationAddHomeWork20twotone = () => <SVGNavigationAddHomeWork_20_twotone />;
export const IconNavigationAddHomeWork24twotone = () => <SVGNavigationAddHomeWork_24_twotone />;
export const IconNavigationAddHomeWork20sharp = () => <SVGNavigationAddHomeWork_20_sharp />;
export const IconNavigationAddHomeWork24sharp = () => <SVGNavigationAddHomeWork_24_sharp />;
export const IconNavigationAddHomeWork20filled = () => <SVGNavigationAddHomeWork_20_filled />;
export const IconNavigationAddHomeWork24filled = () => <SVGNavigationAddHomeWork_24_filled />;
export const IconNavigationAddHomeWork20round = () => <SVGNavigationAddHomeWork_20_round />;
export const IconNavigationAddHomeWork24round = () => <SVGNavigationAddHomeWork_24_round />;
