import React from "react";
import SVGNavigationExpandCircleDown_20_outlined from '../../svg/navigation/NavigationExpandCircleDown/20_outlined.svg';
import SVGNavigationExpandCircleDown_24_outlined from '../../svg/navigation/NavigationExpandCircleDown/24_outlined.svg';
import SVGNavigationExpandCircleDown_20_twotone from '../../svg/navigation/NavigationExpandCircleDown/20_twotone.svg';
import SVGNavigationExpandCircleDown_24_twotone from '../../svg/navigation/NavigationExpandCircleDown/24_twotone.svg';
import SVGNavigationExpandCircleDown_20_sharp from '../../svg/navigation/NavigationExpandCircleDown/20_sharp.svg';
import SVGNavigationExpandCircleDown_24_sharp from '../../svg/navigation/NavigationExpandCircleDown/24_sharp.svg';
import SVGNavigationExpandCircleDown_20_filled from '../../svg/navigation/NavigationExpandCircleDown/20_filled.svg';
import SVGNavigationExpandCircleDown_24_filled from '../../svg/navigation/NavigationExpandCircleDown/24_filled.svg';
import SVGNavigationExpandCircleDown_20_round from '../../svg/navigation/NavigationExpandCircleDown/20_round.svg';
import SVGNavigationExpandCircleDown_24_round from '../../svg/navigation/NavigationExpandCircleDown/24_round.svg';

export const IconNavigationExpandCircleDown20outlined = () => <SVGNavigationExpandCircleDown_20_outlined />;
export const IconNavigationExpandCircleDown24outlined = () => <SVGNavigationExpandCircleDown_24_outlined />;
export const IconNavigationExpandCircleDown20twotone = () => <SVGNavigationExpandCircleDown_20_twotone />;
export const IconNavigationExpandCircleDown24twotone = () => <SVGNavigationExpandCircleDown_24_twotone />;
export const IconNavigationExpandCircleDown20sharp = () => <SVGNavigationExpandCircleDown_20_sharp />;
export const IconNavigationExpandCircleDown24sharp = () => <SVGNavigationExpandCircleDown_24_sharp />;
export const IconNavigationExpandCircleDown20filled = () => <SVGNavigationExpandCircleDown_20_filled />;
export const IconNavigationExpandCircleDown24filled = () => <SVGNavigationExpandCircleDown_24_filled />;
export const IconNavigationExpandCircleDown20round = () => <SVGNavigationExpandCircleDown_20_round />;
export const IconNavigationExpandCircleDown24round = () => <SVGNavigationExpandCircleDown_24_round />;
