import React from "react";
import SVGNavigationArrowForwardIos_20_outlined from '../../svg/navigation/NavigationArrowForwardIos/20_outlined.svg';
import SVGNavigationArrowForwardIos_24_outlined from '../../svg/navigation/NavigationArrowForwardIos/24_outlined.svg';
import SVGNavigationArrowForwardIos_20_twotone from '../../svg/navigation/NavigationArrowForwardIos/20_twotone.svg';
import SVGNavigationArrowForwardIos_24_twotone from '../../svg/navigation/NavigationArrowForwardIos/24_twotone.svg';
import SVGNavigationArrowForwardIos_20_sharp from '../../svg/navigation/NavigationArrowForwardIos/20_sharp.svg';
import SVGNavigationArrowForwardIos_24_sharp from '../../svg/navigation/NavigationArrowForwardIos/24_sharp.svg';
import SVGNavigationArrowForwardIos_20_filled from '../../svg/navigation/NavigationArrowForwardIos/20_filled.svg';
import SVGNavigationArrowForwardIos_24_filled from '../../svg/navigation/NavigationArrowForwardIos/24_filled.svg';
import SVGNavigationArrowForwardIos_20_round from '../../svg/navigation/NavigationArrowForwardIos/20_round.svg';
import SVGNavigationArrowForwardIos_24_round from '../../svg/navigation/NavigationArrowForwardIos/24_round.svg';

export const IconNavigationArrowForwardIos20outlined = () => <SVGNavigationArrowForwardIos_20_outlined />;
export const IconNavigationArrowForwardIos24outlined = () => <SVGNavigationArrowForwardIos_24_outlined />;
export const IconNavigationArrowForwardIos20twotone = () => <SVGNavigationArrowForwardIos_20_twotone />;
export const IconNavigationArrowForwardIos24twotone = () => <SVGNavigationArrowForwardIos_24_twotone />;
export const IconNavigationArrowForwardIos20sharp = () => <SVGNavigationArrowForwardIos_20_sharp />;
export const IconNavigationArrowForwardIos24sharp = () => <SVGNavigationArrowForwardIos_24_sharp />;
export const IconNavigationArrowForwardIos20filled = () => <SVGNavigationArrowForwardIos_20_filled />;
export const IconNavigationArrowForwardIos24filled = () => <SVGNavigationArrowForwardIos_24_filled />;
export const IconNavigationArrowForwardIos20round = () => <SVGNavigationArrowForwardIos_20_round />;
export const IconNavigationArrowForwardIos24round = () => <SVGNavigationArrowForwardIos_24_round />;
