import React from "react";
import SVGImageCurrencyPound_20_outlined from '../../svg/image/ImageCurrencyPound/20_outlined.svg';
import SVGImageCurrencyPound_24_outlined from '../../svg/image/ImageCurrencyPound/24_outlined.svg';
import SVGImageCurrencyPound_20_twotone from '../../svg/image/ImageCurrencyPound/20_twotone.svg';
import SVGImageCurrencyPound_24_twotone from '../../svg/image/ImageCurrencyPound/24_twotone.svg';
import SVGImageCurrencyPound_20_sharp from '../../svg/image/ImageCurrencyPound/20_sharp.svg';
import SVGImageCurrencyPound_24_sharp from '../../svg/image/ImageCurrencyPound/24_sharp.svg';
import SVGImageCurrencyPound_20_filled from '../../svg/image/ImageCurrencyPound/20_filled.svg';
import SVGImageCurrencyPound_24_filled from '../../svg/image/ImageCurrencyPound/24_filled.svg';
import SVGImageCurrencyPound_20_round from '../../svg/image/ImageCurrencyPound/20_round.svg';
import SVGImageCurrencyPound_24_round from '../../svg/image/ImageCurrencyPound/24_round.svg';

export const IconImageCurrencyPound20outlined = () => <SVGImageCurrencyPound_20_outlined />;
export const IconImageCurrencyPound24outlined = () => <SVGImageCurrencyPound_24_outlined />;
export const IconImageCurrencyPound20twotone = () => <SVGImageCurrencyPound_20_twotone />;
export const IconImageCurrencyPound24twotone = () => <SVGImageCurrencyPound_24_twotone />;
export const IconImageCurrencyPound20sharp = () => <SVGImageCurrencyPound_20_sharp />;
export const IconImageCurrencyPound24sharp = () => <SVGImageCurrencyPound_24_sharp />;
export const IconImageCurrencyPound20filled = () => <SVGImageCurrencyPound_20_filled />;
export const IconImageCurrencyPound24filled = () => <SVGImageCurrencyPound_24_filled />;
export const IconImageCurrencyPound20round = () => <SVGImageCurrencyPound_20_round />;
export const IconImageCurrencyPound24round = () => <SVGImageCurrencyPound_24_round />;
