import React from "react";
import SVGImagePhotoAlbum_20_outlined from '../../svg/image/ImagePhotoAlbum/20_outlined.svg';
import SVGImagePhotoAlbum_24_outlined from '../../svg/image/ImagePhotoAlbum/24_outlined.svg';
import SVGImagePhotoAlbum_20_twotone from '../../svg/image/ImagePhotoAlbum/20_twotone.svg';
import SVGImagePhotoAlbum_24_twotone from '../../svg/image/ImagePhotoAlbum/24_twotone.svg';
import SVGImagePhotoAlbum_20_sharp from '../../svg/image/ImagePhotoAlbum/20_sharp.svg';
import SVGImagePhotoAlbum_24_sharp from '../../svg/image/ImagePhotoAlbum/24_sharp.svg';
import SVGImagePhotoAlbum_20_filled from '../../svg/image/ImagePhotoAlbum/20_filled.svg';
import SVGImagePhotoAlbum_24_filled from '../../svg/image/ImagePhotoAlbum/24_filled.svg';
import SVGImagePhotoAlbum_20_round from '../../svg/image/ImagePhotoAlbum/20_round.svg';
import SVGImagePhotoAlbum_24_round from '../../svg/image/ImagePhotoAlbum/24_round.svg';

export const IconImagePhotoAlbum20outlined = () => <SVGImagePhotoAlbum_20_outlined />;
export const IconImagePhotoAlbum24outlined = () => <SVGImagePhotoAlbum_24_outlined />;
export const IconImagePhotoAlbum20twotone = () => <SVGImagePhotoAlbum_20_twotone />;
export const IconImagePhotoAlbum24twotone = () => <SVGImagePhotoAlbum_24_twotone />;
export const IconImagePhotoAlbum20sharp = () => <SVGImagePhotoAlbum_20_sharp />;
export const IconImagePhotoAlbum24sharp = () => <SVGImagePhotoAlbum_24_sharp />;
export const IconImagePhotoAlbum20filled = () => <SVGImagePhotoAlbum_20_filled />;
export const IconImagePhotoAlbum24filled = () => <SVGImagePhotoAlbum_24_filled />;
export const IconImagePhotoAlbum20round = () => <SVGImagePhotoAlbum_20_round />;
export const IconImagePhotoAlbum24round = () => <SVGImagePhotoAlbum_24_round />;
