import React from "react";
import SVGImageEuro_20_outlined from '../../svg/image/ImageEuro/20_outlined.svg';
import SVGImageEuro_24_outlined from '../../svg/image/ImageEuro/24_outlined.svg';
import SVGImageEuro_20_twotone from '../../svg/image/ImageEuro/20_twotone.svg';
import SVGImageEuro_24_twotone from '../../svg/image/ImageEuro/24_twotone.svg';
import SVGImageEuro_20_sharp from '../../svg/image/ImageEuro/20_sharp.svg';
import SVGImageEuro_24_sharp from '../../svg/image/ImageEuro/24_sharp.svg';
import SVGImageEuro_20_filled from '../../svg/image/ImageEuro/20_filled.svg';
import SVGImageEuro_24_filled from '../../svg/image/ImageEuro/24_filled.svg';
import SVGImageEuro_20_round from '../../svg/image/ImageEuro/20_round.svg';
import SVGImageEuro_24_round from '../../svg/image/ImageEuro/24_round.svg';

export const IconImageEuro20outlined = () => <SVGImageEuro_20_outlined />;
export const IconImageEuro24outlined = () => <SVGImageEuro_24_outlined />;
export const IconImageEuro20twotone = () => <SVGImageEuro_20_twotone />;
export const IconImageEuro24twotone = () => <SVGImageEuro_24_twotone />;
export const IconImageEuro20sharp = () => <SVGImageEuro_20_sharp />;
export const IconImageEuro24sharp = () => <SVGImageEuro_24_sharp />;
export const IconImageEuro20filled = () => <SVGImageEuro_20_filled />;
export const IconImageEuro24filled = () => <SVGImageEuro_24_filled />;
export const IconImageEuro20round = () => <SVGImageEuro_20_round />;
export const IconImageEuro24round = () => <SVGImageEuro_24_round />;
