import React from "react";
import SVGImageCrop54_20_outlined from '../../svg/image/ImageCrop54/20_outlined.svg';
import SVGImageCrop54_24_outlined from '../../svg/image/ImageCrop54/24_outlined.svg';
import SVGImageCrop54_20_twotone from '../../svg/image/ImageCrop54/20_twotone.svg';
import SVGImageCrop54_24_twotone from '../../svg/image/ImageCrop54/24_twotone.svg';
import SVGImageCrop54_20_sharp from '../../svg/image/ImageCrop54/20_sharp.svg';
import SVGImageCrop54_24_sharp from '../../svg/image/ImageCrop54/24_sharp.svg';
import SVGImageCrop54_20_filled from '../../svg/image/ImageCrop54/20_filled.svg';
import SVGImageCrop54_24_filled from '../../svg/image/ImageCrop54/24_filled.svg';
import SVGImageCrop54_20_round from '../../svg/image/ImageCrop54/20_round.svg';
import SVGImageCrop54_24_round from '../../svg/image/ImageCrop54/24_round.svg';

export const IconImageCrop5420outlined = () => <SVGImageCrop54_20_outlined />;
export const IconImageCrop5424outlined = () => <SVGImageCrop54_24_outlined />;
export const IconImageCrop5420twotone = () => <SVGImageCrop54_20_twotone />;
export const IconImageCrop5424twotone = () => <SVGImageCrop54_24_twotone />;
export const IconImageCrop5420sharp = () => <SVGImageCrop54_20_sharp />;
export const IconImageCrop5424sharp = () => <SVGImageCrop54_24_sharp />;
export const IconImageCrop5420filled = () => <SVGImageCrop54_20_filled />;
export const IconImageCrop5424filled = () => <SVGImageCrop54_24_filled />;
export const IconImageCrop5420round = () => <SVGImageCrop54_20_round />;
export const IconImageCrop5424round = () => <SVGImageCrop54_24_round />;
