import React from "react";
import SVGImageCurrencyYen_20_outlined from '../../svg/image/ImageCurrencyYen/20_outlined.svg';
import SVGImageCurrencyYen_24_outlined from '../../svg/image/ImageCurrencyYen/24_outlined.svg';
import SVGImageCurrencyYen_20_twotone from '../../svg/image/ImageCurrencyYen/20_twotone.svg';
import SVGImageCurrencyYen_24_twotone from '../../svg/image/ImageCurrencyYen/24_twotone.svg';
import SVGImageCurrencyYen_20_sharp from '../../svg/image/ImageCurrencyYen/20_sharp.svg';
import SVGImageCurrencyYen_24_sharp from '../../svg/image/ImageCurrencyYen/24_sharp.svg';
import SVGImageCurrencyYen_20_filled from '../../svg/image/ImageCurrencyYen/20_filled.svg';
import SVGImageCurrencyYen_24_filled from '../../svg/image/ImageCurrencyYen/24_filled.svg';
import SVGImageCurrencyYen_20_round from '../../svg/image/ImageCurrencyYen/20_round.svg';
import SVGImageCurrencyYen_24_round from '../../svg/image/ImageCurrencyYen/24_round.svg';

export const IconImageCurrencyYen20outlined = () => <SVGImageCurrencyYen_20_outlined />;
export const IconImageCurrencyYen24outlined = () => <SVGImageCurrencyYen_24_outlined />;
export const IconImageCurrencyYen20twotone = () => <SVGImageCurrencyYen_20_twotone />;
export const IconImageCurrencyYen24twotone = () => <SVGImageCurrencyYen_24_twotone />;
export const IconImageCurrencyYen20sharp = () => <SVGImageCurrencyYen_20_sharp />;
export const IconImageCurrencyYen24sharp = () => <SVGImageCurrencyYen_24_sharp />;
export const IconImageCurrencyYen20filled = () => <SVGImageCurrencyYen_20_filled />;
export const IconImageCurrencyYen24filled = () => <SVGImageCurrencyYen_24_filled />;
export const IconImageCurrencyYen20round = () => <SVGImageCurrencyYen_20_round />;
export const IconImageCurrencyYen24round = () => <SVGImageCurrencyYen_24_round />;
