import React from "react";
import SVGImageImageNotSupported_20_outlined from '../../svg/image/ImageImageNotSupported/20_outlined.svg';
import SVGImageImageNotSupported_24_outlined from '../../svg/image/ImageImageNotSupported/24_outlined.svg';
import SVGImageImageNotSupported_20_twotone from '../../svg/image/ImageImageNotSupported/20_twotone.svg';
import SVGImageImageNotSupported_24_twotone from '../../svg/image/ImageImageNotSupported/24_twotone.svg';
import SVGImageImageNotSupported_20_sharp from '../../svg/image/ImageImageNotSupported/20_sharp.svg';
import SVGImageImageNotSupported_24_sharp from '../../svg/image/ImageImageNotSupported/24_sharp.svg';
import SVGImageImageNotSupported_20_filled from '../../svg/image/ImageImageNotSupported/20_filled.svg';
import SVGImageImageNotSupported_24_filled from '../../svg/image/ImageImageNotSupported/24_filled.svg';
import SVGImageImageNotSupported_20_round from '../../svg/image/ImageImageNotSupported/20_round.svg';
import SVGImageImageNotSupported_24_round from '../../svg/image/ImageImageNotSupported/24_round.svg';

export const IconImageImageNotSupported20outlined = () => <SVGImageImageNotSupported_20_outlined />;
export const IconImageImageNotSupported24outlined = () => <SVGImageImageNotSupported_24_outlined />;
export const IconImageImageNotSupported20twotone = () => <SVGImageImageNotSupported_20_twotone />;
export const IconImageImageNotSupported24twotone = () => <SVGImageImageNotSupported_24_twotone />;
export const IconImageImageNotSupported20sharp = () => <SVGImageImageNotSupported_20_sharp />;
export const IconImageImageNotSupported24sharp = () => <SVGImageImageNotSupported_24_sharp />;
export const IconImageImageNotSupported20filled = () => <SVGImageImageNotSupported_20_filled />;
export const IconImageImageNotSupported24filled = () => <SVGImageImageNotSupported_24_filled />;
export const IconImageImageNotSupported20round = () => <SVGImageImageNotSupported_20_round />;
export const IconImageImageNotSupported24round = () => <SVGImageImageNotSupported_24_round />;
