import React from "react";
import SVGImageCurrencyRuble_20_outlined from '../../svg/image/ImageCurrencyRuble/20_outlined.svg';
import SVGImageCurrencyRuble_24_outlined from '../../svg/image/ImageCurrencyRuble/24_outlined.svg';
import SVGImageCurrencyRuble_20_twotone from '../../svg/image/ImageCurrencyRuble/20_twotone.svg';
import SVGImageCurrencyRuble_24_twotone from '../../svg/image/ImageCurrencyRuble/24_twotone.svg';
import SVGImageCurrencyRuble_20_sharp from '../../svg/image/ImageCurrencyRuble/20_sharp.svg';
import SVGImageCurrencyRuble_24_sharp from '../../svg/image/ImageCurrencyRuble/24_sharp.svg';
import SVGImageCurrencyRuble_20_filled from '../../svg/image/ImageCurrencyRuble/20_filled.svg';
import SVGImageCurrencyRuble_24_filled from '../../svg/image/ImageCurrencyRuble/24_filled.svg';
import SVGImageCurrencyRuble_20_round from '../../svg/image/ImageCurrencyRuble/20_round.svg';
import SVGImageCurrencyRuble_24_round from '../../svg/image/ImageCurrencyRuble/24_round.svg';

export const IconImageCurrencyRuble20outlined = () => <SVGImageCurrencyRuble_20_outlined />;
export const IconImageCurrencyRuble24outlined = () => <SVGImageCurrencyRuble_24_outlined />;
export const IconImageCurrencyRuble20twotone = () => <SVGImageCurrencyRuble_20_twotone />;
export const IconImageCurrencyRuble24twotone = () => <SVGImageCurrencyRuble_24_twotone />;
export const IconImageCurrencyRuble20sharp = () => <SVGImageCurrencyRuble_20_sharp />;
export const IconImageCurrencyRuble24sharp = () => <SVGImageCurrencyRuble_24_sharp />;
export const IconImageCurrencyRuble20filled = () => <SVGImageCurrencyRuble_20_filled />;
export const IconImageCurrencyRuble24filled = () => <SVGImageCurrencyRuble_24_filled />;
export const IconImageCurrencyRuble20round = () => <SVGImageCurrencyRuble_20_round />;
export const IconImageCurrencyRuble24round = () => <SVGImageCurrencyRuble_24_round />;
