import React from "react";
import SVGImageRotate90DegreesCw_20_outlined from '../../svg/image/ImageRotate90DegreesCw/20_outlined.svg';
import SVGImageRotate90DegreesCw_24_outlined from '../../svg/image/ImageRotate90DegreesCw/24_outlined.svg';
import SVGImageRotate90DegreesCw_20_twotone from '../../svg/image/ImageRotate90DegreesCw/20_twotone.svg';
import SVGImageRotate90DegreesCw_24_twotone from '../../svg/image/ImageRotate90DegreesCw/24_twotone.svg';
import SVGImageRotate90DegreesCw_20_sharp from '../../svg/image/ImageRotate90DegreesCw/20_sharp.svg';
import SVGImageRotate90DegreesCw_24_sharp from '../../svg/image/ImageRotate90DegreesCw/24_sharp.svg';
import SVGImageRotate90DegreesCw_20_filled from '../../svg/image/ImageRotate90DegreesCw/20_filled.svg';
import SVGImageRotate90DegreesCw_24_filled from '../../svg/image/ImageRotate90DegreesCw/24_filled.svg';
import SVGImageRotate90DegreesCw_20_round from '../../svg/image/ImageRotate90DegreesCw/20_round.svg';
import SVGImageRotate90DegreesCw_24_round from '../../svg/image/ImageRotate90DegreesCw/24_round.svg';

export const IconImageRotate90DegreesCw20outlined = () => <SVGImageRotate90DegreesCw_20_outlined />;
export const IconImageRotate90DegreesCw24outlined = () => <SVGImageRotate90DegreesCw_24_outlined />;
export const IconImageRotate90DegreesCw20twotone = () => <SVGImageRotate90DegreesCw_20_twotone />;
export const IconImageRotate90DegreesCw24twotone = () => <SVGImageRotate90DegreesCw_24_twotone />;
export const IconImageRotate90DegreesCw20sharp = () => <SVGImageRotate90DegreesCw_20_sharp />;
export const IconImageRotate90DegreesCw24sharp = () => <SVGImageRotate90DegreesCw_24_sharp />;
export const IconImageRotate90DegreesCw20filled = () => <SVGImageRotate90DegreesCw_20_filled />;
export const IconImageRotate90DegreesCw24filled = () => <SVGImageRotate90DegreesCw_24_filled />;
export const IconImageRotate90DegreesCw20round = () => <SVGImageRotate90DegreesCw_20_round />;
export const IconImageRotate90DegreesCw24round = () => <SVGImageRotate90DegreesCw_24_round />;
