import React from "react";
import SVGImageBedtimeOff_20_outlined from '../../svg/image/ImageBedtimeOff/20_outlined.svg';
import SVGImageBedtimeOff_24_outlined from '../../svg/image/ImageBedtimeOff/24_outlined.svg';
import SVGImageBedtimeOff_20_twotone from '../../svg/image/ImageBedtimeOff/20_twotone.svg';
import SVGImageBedtimeOff_24_twotone from '../../svg/image/ImageBedtimeOff/24_twotone.svg';
import SVGImageBedtimeOff_20_sharp from '../../svg/image/ImageBedtimeOff/20_sharp.svg';
import SVGImageBedtimeOff_24_sharp from '../../svg/image/ImageBedtimeOff/24_sharp.svg';
import SVGImageBedtimeOff_20_filled from '../../svg/image/ImageBedtimeOff/20_filled.svg';
import SVGImageBedtimeOff_24_filled from '../../svg/image/ImageBedtimeOff/24_filled.svg';
import SVGImageBedtimeOff_20_round from '../../svg/image/ImageBedtimeOff/20_round.svg';
import SVGImageBedtimeOff_24_round from '../../svg/image/ImageBedtimeOff/24_round.svg';

export const IconImageBedtimeOff20outlined = () => <SVGImageBedtimeOff_20_outlined />;
export const IconImageBedtimeOff24outlined = () => <SVGImageBedtimeOff_24_outlined />;
export const IconImageBedtimeOff20twotone = () => <SVGImageBedtimeOff_20_twotone />;
export const IconImageBedtimeOff24twotone = () => <SVGImageBedtimeOff_24_twotone />;
export const IconImageBedtimeOff20sharp = () => <SVGImageBedtimeOff_20_sharp />;
export const IconImageBedtimeOff24sharp = () => <SVGImageBedtimeOff_24_sharp />;
export const IconImageBedtimeOff20filled = () => <SVGImageBedtimeOff_20_filled />;
export const IconImageBedtimeOff24filled = () => <SVGImageBedtimeOff_24_filled />;
export const IconImageBedtimeOff20round = () => <SVGImageBedtimeOff_20_round />;
export const IconImageBedtimeOff24round = () => <SVGImageBedtimeOff_24_round />;
