import React from "react";
import SVGImageCrop75_20_outlined from '../../svg/image/ImageCrop75/20_outlined.svg';
import SVGImageCrop75_24_outlined from '../../svg/image/ImageCrop75/24_outlined.svg';
import SVGImageCrop75_20_twotone from '../../svg/image/ImageCrop75/20_twotone.svg';
import SVGImageCrop75_24_twotone from '../../svg/image/ImageCrop75/24_twotone.svg';
import SVGImageCrop75_20_sharp from '../../svg/image/ImageCrop75/20_sharp.svg';
import SVGImageCrop75_24_sharp from '../../svg/image/ImageCrop75/24_sharp.svg';
import SVGImageCrop75_20_filled from '../../svg/image/ImageCrop75/20_filled.svg';
import SVGImageCrop75_24_filled from '../../svg/image/ImageCrop75/24_filled.svg';
import SVGImageCrop75_20_round from '../../svg/image/ImageCrop75/20_round.svg';
import SVGImageCrop75_24_round from '../../svg/image/ImageCrop75/24_round.svg';

export const IconImageCrop7520outlined = () => <SVGImageCrop75_20_outlined />;
export const IconImageCrop7524outlined = () => <SVGImageCrop75_24_outlined />;
export const IconImageCrop7520twotone = () => <SVGImageCrop75_20_twotone />;
export const IconImageCrop7524twotone = () => <SVGImageCrop75_24_twotone />;
export const IconImageCrop7520sharp = () => <SVGImageCrop75_20_sharp />;
export const IconImageCrop7524sharp = () => <SVGImageCrop75_24_sharp />;
export const IconImageCrop7520filled = () => <SVGImageCrop75_20_filled />;
export const IconImageCrop7524filled = () => <SVGImageCrop75_24_filled />;
export const IconImageCrop7520round = () => <SVGImageCrop75_20_round />;
export const IconImageCrop7524round = () => <SVGImageCrop75_24_round />;
