import React from "react";
import SVGHomeRollerShades_20_outlined from '../../svg/home/HomeRollerShades/20_outlined.svg';
import SVGHomeRollerShades_24_outlined from '../../svg/home/HomeRollerShades/24_outlined.svg';
import SVGHomeRollerShades_20_twotone from '../../svg/home/HomeRollerShades/20_twotone.svg';
import SVGHomeRollerShades_24_twotone from '../../svg/home/HomeRollerShades/24_twotone.svg';
import SVGHomeRollerShades_20_sharp from '../../svg/home/HomeRollerShades/20_sharp.svg';
import SVGHomeRollerShades_24_sharp from '../../svg/home/HomeRollerShades/24_sharp.svg';
import SVGHomeRollerShades_20_filled from '../../svg/home/HomeRollerShades/20_filled.svg';
import SVGHomeRollerShades_24_filled from '../../svg/home/HomeRollerShades/24_filled.svg';
import SVGHomeRollerShades_20_round from '../../svg/home/HomeRollerShades/20_round.svg';
import SVGHomeRollerShades_24_round from '../../svg/home/HomeRollerShades/24_round.svg';

export const IconHomeRollerShades20outlined = () => <SVGHomeRollerShades_20_outlined />;
export const IconHomeRollerShades24outlined = () => <SVGHomeRollerShades_24_outlined />;
export const IconHomeRollerShades20twotone = () => <SVGHomeRollerShades_20_twotone />;
export const IconHomeRollerShades24twotone = () => <SVGHomeRollerShades_24_twotone />;
export const IconHomeRollerShades20sharp = () => <SVGHomeRollerShades_20_sharp />;
export const IconHomeRollerShades24sharp = () => <SVGHomeRollerShades_24_sharp />;
export const IconHomeRollerShades20filled = () => <SVGHomeRollerShades_20_filled />;
export const IconHomeRollerShades24filled = () => <SVGHomeRollerShades_24_filled />;
export const IconHomeRollerShades20round = () => <SVGHomeRollerShades_20_round />;
export const IconHomeRollerShades24round = () => <SVGHomeRollerShades_24_round />;
