import React from "react";
import SVGHomeSensorDoor_20_outlined from '../../svg/home/HomeSensorDoor/20_outlined.svg';
import SVGHomeSensorDoor_24_outlined from '../../svg/home/HomeSensorDoor/24_outlined.svg';
import SVGHomeSensorDoor_20_twotone from '../../svg/home/HomeSensorDoor/20_twotone.svg';
import SVGHomeSensorDoor_24_twotone from '../../svg/home/HomeSensorDoor/24_twotone.svg';
import SVGHomeSensorDoor_20_sharp from '../../svg/home/HomeSensorDoor/20_sharp.svg';
import SVGHomeSensorDoor_24_sharp from '../../svg/home/HomeSensorDoor/24_sharp.svg';
import SVGHomeSensorDoor_20_filled from '../../svg/home/HomeSensorDoor/20_filled.svg';
import SVGHomeSensorDoor_24_filled from '../../svg/home/HomeSensorDoor/24_filled.svg';
import SVGHomeSensorDoor_20_round from '../../svg/home/HomeSensorDoor/20_round.svg';
import SVGHomeSensorDoor_24_round from '../../svg/home/HomeSensorDoor/24_round.svg';

export const IconHomeSensorDoor20outlined = () => <SVGHomeSensorDoor_20_outlined />;
export const IconHomeSensorDoor24outlined = () => <SVGHomeSensorDoor_24_outlined />;
export const IconHomeSensorDoor20twotone = () => <SVGHomeSensorDoor_20_twotone />;
export const IconHomeSensorDoor24twotone = () => <SVGHomeSensorDoor_24_twotone />;
export const IconHomeSensorDoor20sharp = () => <SVGHomeSensorDoor_20_sharp />;
export const IconHomeSensorDoor24sharp = () => <SVGHomeSensorDoor_24_sharp />;
export const IconHomeSensorDoor20filled = () => <SVGHomeSensorDoor_20_filled />;
export const IconHomeSensorDoor24filled = () => <SVGHomeSensorDoor_24_filled />;
export const IconHomeSensorDoor20round = () => <SVGHomeSensorDoor_20_round />;
export const IconHomeSensorDoor24round = () => <SVGHomeSensorDoor_24_round />;
