import React from "react";
import SVGHomeShieldMoon_20_outlined from '../../svg/home/HomeShieldMoon/20_outlined.svg';
import SVGHomeShieldMoon_24_outlined from '../../svg/home/HomeShieldMoon/24_outlined.svg';
import SVGHomeShieldMoon_20_twotone from '../../svg/home/HomeShieldMoon/20_twotone.svg';
import SVGHomeShieldMoon_24_twotone from '../../svg/home/HomeShieldMoon/24_twotone.svg';
import SVGHomeShieldMoon_20_sharp from '../../svg/home/HomeShieldMoon/20_sharp.svg';
import SVGHomeShieldMoon_24_sharp from '../../svg/home/HomeShieldMoon/24_sharp.svg';
import SVGHomeShieldMoon_20_filled from '../../svg/home/HomeShieldMoon/20_filled.svg';
import SVGHomeShieldMoon_24_filled from '../../svg/home/HomeShieldMoon/24_filled.svg';
import SVGHomeShieldMoon_20_round from '../../svg/home/HomeShieldMoon/20_round.svg';
import SVGHomeShieldMoon_24_round from '../../svg/home/HomeShieldMoon/24_round.svg';

export const IconHomeShieldMoon20outlined = () => <SVGHomeShieldMoon_20_outlined />;
export const IconHomeShieldMoon24outlined = () => <SVGHomeShieldMoon_24_outlined />;
export const IconHomeShieldMoon20twotone = () => <SVGHomeShieldMoon_20_twotone />;
export const IconHomeShieldMoon24twotone = () => <SVGHomeShieldMoon_24_twotone />;
export const IconHomeShieldMoon20sharp = () => <SVGHomeShieldMoon_20_sharp />;
export const IconHomeShieldMoon24sharp = () => <SVGHomeShieldMoon_24_sharp />;
export const IconHomeShieldMoon20filled = () => <SVGHomeShieldMoon_20_filled />;
export const IconHomeShieldMoon24filled = () => <SVGHomeShieldMoon_24_filled />;
export const IconHomeShieldMoon20round = () => <SVGHomeShieldMoon_20_round />;
export const IconHomeShieldMoon24round = () => <SVGHomeShieldMoon_24_round />;
