import React from "react";
import SVGHomeBroadcastOnPersonal_20_outlined from '../../svg/home/HomeBroadcastOnPersonal/20_outlined.svg';
import SVGHomeBroadcastOnPersonal_24_outlined from '../../svg/home/HomeBroadcastOnPersonal/24_outlined.svg';
import SVGHomeBroadcastOnPersonal_20_twotone from '../../svg/home/HomeBroadcastOnPersonal/20_twotone.svg';
import SVGHomeBroadcastOnPersonal_24_twotone from '../../svg/home/HomeBroadcastOnPersonal/24_twotone.svg';
import SVGHomeBroadcastOnPersonal_20_sharp from '../../svg/home/HomeBroadcastOnPersonal/20_sharp.svg';
import SVGHomeBroadcastOnPersonal_24_sharp from '../../svg/home/HomeBroadcastOnPersonal/24_sharp.svg';
import SVGHomeBroadcastOnPersonal_20_filled from '../../svg/home/HomeBroadcastOnPersonal/20_filled.svg';
import SVGHomeBroadcastOnPersonal_24_filled from '../../svg/home/HomeBroadcastOnPersonal/24_filled.svg';
import SVGHomeBroadcastOnPersonal_20_round from '../../svg/home/HomeBroadcastOnPersonal/20_round.svg';
import SVGHomeBroadcastOnPersonal_24_round from '../../svg/home/HomeBroadcastOnPersonal/24_round.svg';

export const IconHomeBroadcastOnPersonal20outlined = () => <SVGHomeBroadcastOnPersonal_20_outlined />;
export const IconHomeBroadcastOnPersonal24outlined = () => <SVGHomeBroadcastOnPersonal_24_outlined />;
export const IconHomeBroadcastOnPersonal20twotone = () => <SVGHomeBroadcastOnPersonal_20_twotone />;
export const IconHomeBroadcastOnPersonal24twotone = () => <SVGHomeBroadcastOnPersonal_24_twotone />;
export const IconHomeBroadcastOnPersonal20sharp = () => <SVGHomeBroadcastOnPersonal_20_sharp />;
export const IconHomeBroadcastOnPersonal24sharp = () => <SVGHomeBroadcastOnPersonal_24_sharp />;
export const IconHomeBroadcastOnPersonal20filled = () => <SVGHomeBroadcastOnPersonal_20_filled />;
export const IconHomeBroadcastOnPersonal24filled = () => <SVGHomeBroadcastOnPersonal_24_filled />;
export const IconHomeBroadcastOnPersonal20round = () => <SVGHomeBroadcastOnPersonal_20_round />;
export const IconHomeBroadcastOnPersonal24round = () => <SVGHomeBroadcastOnPersonal_24_round />;
