import React from "react";
import SVGHomeGasMeter_20_outlined from '../../svg/home/HomeGasMeter/20_outlined.svg';
import SVGHomeGasMeter_24_outlined from '../../svg/home/HomeGasMeter/24_outlined.svg';
import SVGHomeGasMeter_20_twotone from '../../svg/home/HomeGasMeter/20_twotone.svg';
import SVGHomeGasMeter_24_twotone from '../../svg/home/HomeGasMeter/24_twotone.svg';
import SVGHomeGasMeter_20_sharp from '../../svg/home/HomeGasMeter/20_sharp.svg';
import SVGHomeGasMeter_24_sharp from '../../svg/home/HomeGasMeter/24_sharp.svg';
import SVGHomeGasMeter_20_filled from '../../svg/home/HomeGasMeter/20_filled.svg';
import SVGHomeGasMeter_24_filled from '../../svg/home/HomeGasMeter/24_filled.svg';
import SVGHomeGasMeter_20_round from '../../svg/home/HomeGasMeter/20_round.svg';
import SVGHomeGasMeter_24_round from '../../svg/home/HomeGasMeter/24_round.svg';

export const IconHomeGasMeter20outlined = () => <SVGHomeGasMeter_20_outlined />;
export const IconHomeGasMeter24outlined = () => <SVGHomeGasMeter_24_outlined />;
export const IconHomeGasMeter20twotone = () => <SVGHomeGasMeter_20_twotone />;
export const IconHomeGasMeter24twotone = () => <SVGHomeGasMeter_24_twotone />;
export const IconHomeGasMeter20sharp = () => <SVGHomeGasMeter_20_sharp />;
export const IconHomeGasMeter24sharp = () => <SVGHomeGasMeter_24_sharp />;
export const IconHomeGasMeter20filled = () => <SVGHomeGasMeter_20_filled />;
export const IconHomeGasMeter24filled = () => <SVGHomeGasMeter_24_filled />;
export const IconHomeGasMeter20round = () => <SVGHomeGasMeter_20_round />;
export const IconHomeGasMeter24round = () => <SVGHomeGasMeter_24_round />;
