import React from "react";
import SVGHomeBlindsClosed_20_outlined from '../../svg/home/HomeBlindsClosed/20_outlined.svg';
import SVGHomeBlindsClosed_24_outlined from '../../svg/home/HomeBlindsClosed/24_outlined.svg';
import SVGHomeBlindsClosed_20_twotone from '../../svg/home/HomeBlindsClosed/20_twotone.svg';
import SVGHomeBlindsClosed_24_twotone from '../../svg/home/HomeBlindsClosed/24_twotone.svg';
import SVGHomeBlindsClosed_20_sharp from '../../svg/home/HomeBlindsClosed/20_sharp.svg';
import SVGHomeBlindsClosed_24_sharp from '../../svg/home/HomeBlindsClosed/24_sharp.svg';
import SVGHomeBlindsClosed_20_filled from '../../svg/home/HomeBlindsClosed/20_filled.svg';
import SVGHomeBlindsClosed_24_filled from '../../svg/home/HomeBlindsClosed/24_filled.svg';
import SVGHomeBlindsClosed_20_round from '../../svg/home/HomeBlindsClosed/20_round.svg';
import SVGHomeBlindsClosed_24_round from '../../svg/home/HomeBlindsClosed/24_round.svg';

export const IconHomeBlindsClosed20outlined = () => <SVGHomeBlindsClosed_20_outlined />;
export const IconHomeBlindsClosed24outlined = () => <SVGHomeBlindsClosed_24_outlined />;
export const IconHomeBlindsClosed20twotone = () => <SVGHomeBlindsClosed_20_twotone />;
export const IconHomeBlindsClosed24twotone = () => <SVGHomeBlindsClosed_24_twotone />;
export const IconHomeBlindsClosed20sharp = () => <SVGHomeBlindsClosed_20_sharp />;
export const IconHomeBlindsClosed24sharp = () => <SVGHomeBlindsClosed_24_sharp />;
export const IconHomeBlindsClosed20filled = () => <SVGHomeBlindsClosed_20_filled />;
export const IconHomeBlindsClosed24filled = () => <SVGHomeBlindsClosed_24_filled />;
export const IconHomeBlindsClosed20round = () => <SVGHomeBlindsClosed_20_round />;
export const IconHomeBlindsClosed24round = () => <SVGHomeBlindsClosed_24_round />;
