import React from "react";
import SVGHomeRollerShadesClosed_20_outlined from '../../svg/home/HomeRollerShadesClosed/20_outlined.svg';
import SVGHomeRollerShadesClosed_24_outlined from '../../svg/home/HomeRollerShadesClosed/24_outlined.svg';
import SVGHomeRollerShadesClosed_20_twotone from '../../svg/home/HomeRollerShadesClosed/20_twotone.svg';
import SVGHomeRollerShadesClosed_24_twotone from '../../svg/home/HomeRollerShadesClosed/24_twotone.svg';
import SVGHomeRollerShadesClosed_20_sharp from '../../svg/home/HomeRollerShadesClosed/20_sharp.svg';
import SVGHomeRollerShadesClosed_24_sharp from '../../svg/home/HomeRollerShadesClosed/24_sharp.svg';
import SVGHomeRollerShadesClosed_20_filled from '../../svg/home/HomeRollerShadesClosed/20_filled.svg';
import SVGHomeRollerShadesClosed_24_filled from '../../svg/home/HomeRollerShadesClosed/24_filled.svg';
import SVGHomeRollerShadesClosed_20_round from '../../svg/home/HomeRollerShadesClosed/20_round.svg';
import SVGHomeRollerShadesClosed_24_round from '../../svg/home/HomeRollerShadesClosed/24_round.svg';

export const IconHomeRollerShadesClosed20outlined = () => <SVGHomeRollerShadesClosed_20_outlined />;
export const IconHomeRollerShadesClosed24outlined = () => <SVGHomeRollerShadesClosed_24_outlined />;
export const IconHomeRollerShadesClosed20twotone = () => <SVGHomeRollerShadesClosed_20_twotone />;
export const IconHomeRollerShadesClosed24twotone = () => <SVGHomeRollerShadesClosed_24_twotone />;
export const IconHomeRollerShadesClosed20sharp = () => <SVGHomeRollerShadesClosed_20_sharp />;
export const IconHomeRollerShadesClosed24sharp = () => <SVGHomeRollerShadesClosed_24_sharp />;
export const IconHomeRollerShadesClosed20filled = () => <SVGHomeRollerShadesClosed_20_filled />;
export const IconHomeRollerShadesClosed24filled = () => <SVGHomeRollerShadesClosed_24_filled />;
export const IconHomeRollerShadesClosed20round = () => <SVGHomeRollerShadesClosed_20_round />;
export const IconHomeRollerShadesClosed24round = () => <SVGHomeRollerShadesClosed_24_round />;
