import React from "react";
import SVGHomeSensorOccupied_20_outlined from '../../svg/home/HomeSensorOccupied/20_outlined.svg';
import SVGHomeSensorOccupied_24_outlined from '../../svg/home/HomeSensorOccupied/24_outlined.svg';
import SVGHomeSensorOccupied_20_twotone from '../../svg/home/HomeSensorOccupied/20_twotone.svg';
import SVGHomeSensorOccupied_24_twotone from '../../svg/home/HomeSensorOccupied/24_twotone.svg';
import SVGHomeSensorOccupied_20_sharp from '../../svg/home/HomeSensorOccupied/20_sharp.svg';
import SVGHomeSensorOccupied_24_sharp from '../../svg/home/HomeSensorOccupied/24_sharp.svg';
import SVGHomeSensorOccupied_20_filled from '../../svg/home/HomeSensorOccupied/20_filled.svg';
import SVGHomeSensorOccupied_24_filled from '../../svg/home/HomeSensorOccupied/24_filled.svg';
import SVGHomeSensorOccupied_20_round from '../../svg/home/HomeSensorOccupied/20_round.svg';
import SVGHomeSensorOccupied_24_round from '../../svg/home/HomeSensorOccupied/24_round.svg';

export const IconHomeSensorOccupied20outlined = () => <SVGHomeSensorOccupied_20_outlined />;
export const IconHomeSensorOccupied24outlined = () => <SVGHomeSensorOccupied_24_outlined />;
export const IconHomeSensorOccupied20twotone = () => <SVGHomeSensorOccupied_20_twotone />;
export const IconHomeSensorOccupied24twotone = () => <SVGHomeSensorOccupied_24_twotone />;
export const IconHomeSensorOccupied20sharp = () => <SVGHomeSensorOccupied_20_sharp />;
export const IconHomeSensorOccupied24sharp = () => <SVGHomeSensorOccupied_24_sharp />;
export const IconHomeSensorOccupied20filled = () => <SVGHomeSensorOccupied_20_filled />;
export const IconHomeSensorOccupied24filled = () => <SVGHomeSensorOccupied_24_filled />;
export const IconHomeSensorOccupied20round = () => <SVGHomeSensorOccupied_20_round />;
export const IconHomeSensorOccupied24round = () => <SVGHomeSensorOccupied_24_round />;
