import React from "react";
import SVGHomeElectricBolt_20_outlined from '../../svg/home/HomeElectricBolt/20_outlined.svg';
import SVGHomeElectricBolt_24_outlined from '../../svg/home/HomeElectricBolt/24_outlined.svg';
import SVGHomeElectricBolt_20_twotone from '../../svg/home/HomeElectricBolt/20_twotone.svg';
import SVGHomeElectricBolt_24_twotone from '../../svg/home/HomeElectricBolt/24_twotone.svg';
import SVGHomeElectricBolt_20_sharp from '../../svg/home/HomeElectricBolt/20_sharp.svg';
import SVGHomeElectricBolt_24_sharp from '../../svg/home/HomeElectricBolt/24_sharp.svg';
import SVGHomeElectricBolt_20_filled from '../../svg/home/HomeElectricBolt/20_filled.svg';
import SVGHomeElectricBolt_24_filled from '../../svg/home/HomeElectricBolt/24_filled.svg';
import SVGHomeElectricBolt_20_round from '../../svg/home/HomeElectricBolt/20_round.svg';
import SVGHomeElectricBolt_24_round from '../../svg/home/HomeElectricBolt/24_round.svg';

export const IconHomeElectricBolt20outlined = () => <SVGHomeElectricBolt_20_outlined />;
export const IconHomeElectricBolt24outlined = () => <SVGHomeElectricBolt_24_outlined />;
export const IconHomeElectricBolt20twotone = () => <SVGHomeElectricBolt_20_twotone />;
export const IconHomeElectricBolt24twotone = () => <SVGHomeElectricBolt_24_twotone />;
export const IconHomeElectricBolt20sharp = () => <SVGHomeElectricBolt_20_sharp />;
export const IconHomeElectricBolt24sharp = () => <SVGHomeElectricBolt_24_sharp />;
export const IconHomeElectricBolt20filled = () => <SVGHomeElectricBolt_20_filled />;
export const IconHomeElectricBolt24filled = () => <SVGHomeElectricBolt_24_filled />;
export const IconHomeElectricBolt20round = () => <SVGHomeElectricBolt_20_round />;
export const IconHomeElectricBolt24round = () => <SVGHomeElectricBolt_24_round />;
