import React from "react";
import SVGHomeNestCamWiredStand_20_outlined from '../../svg/home/HomeNestCamWiredStand/20_outlined.svg';
import SVGHomeNestCamWiredStand_24_outlined from '../../svg/home/HomeNestCamWiredStand/24_outlined.svg';
import SVGHomeNestCamWiredStand_20_twotone from '../../svg/home/HomeNestCamWiredStand/20_twotone.svg';
import SVGHomeNestCamWiredStand_24_twotone from '../../svg/home/HomeNestCamWiredStand/24_twotone.svg';
import SVGHomeNestCamWiredStand_20_sharp from '../../svg/home/HomeNestCamWiredStand/20_sharp.svg';
import SVGHomeNestCamWiredStand_24_sharp from '../../svg/home/HomeNestCamWiredStand/24_sharp.svg';
import SVGHomeNestCamWiredStand_20_filled from '../../svg/home/HomeNestCamWiredStand/20_filled.svg';
import SVGHomeNestCamWiredStand_24_filled from '../../svg/home/HomeNestCamWiredStand/24_filled.svg';
import SVGHomeNestCamWiredStand_20_round from '../../svg/home/HomeNestCamWiredStand/20_round.svg';
import SVGHomeNestCamWiredStand_24_round from '../../svg/home/HomeNestCamWiredStand/24_round.svg';

export const IconHomeNestCamWiredStand20outlined = () => <SVGHomeNestCamWiredStand_20_outlined />;
export const IconHomeNestCamWiredStand24outlined = () => <SVGHomeNestCamWiredStand_24_outlined />;
export const IconHomeNestCamWiredStand20twotone = () => <SVGHomeNestCamWiredStand_20_twotone />;
export const IconHomeNestCamWiredStand24twotone = () => <SVGHomeNestCamWiredStand_24_twotone />;
export const IconHomeNestCamWiredStand20sharp = () => <SVGHomeNestCamWiredStand_20_sharp />;
export const IconHomeNestCamWiredStand24sharp = () => <SVGHomeNestCamWiredStand_24_sharp />;
export const IconHomeNestCamWiredStand20filled = () => <SVGHomeNestCamWiredStand_20_filled />;
export const IconHomeNestCamWiredStand24filled = () => <SVGHomeNestCamWiredStand_24_filled />;
export const IconHomeNestCamWiredStand20round = () => <SVGHomeNestCamWiredStand_20_round />;
export const IconHomeNestCamWiredStand24round = () => <SVGHomeNestCamWiredStand_24_round />;
