import React from "react";
import SVGContentAmpStories_20_outlined from '../../svg/content/ContentAmpStories/20_outlined.svg';
import SVGContentAmpStories_24_outlined from '../../svg/content/ContentAmpStories/24_outlined.svg';
import SVGContentAmpStories_20_twotone from '../../svg/content/ContentAmpStories/20_twotone.svg';
import SVGContentAmpStories_24_twotone from '../../svg/content/ContentAmpStories/24_twotone.svg';
import SVGContentAmpStories_20_sharp from '../../svg/content/ContentAmpStories/20_sharp.svg';
import SVGContentAmpStories_24_sharp from '../../svg/content/ContentAmpStories/24_sharp.svg';
import SVGContentAmpStories_20_filled from '../../svg/content/ContentAmpStories/20_filled.svg';
import SVGContentAmpStories_24_filled from '../../svg/content/ContentAmpStories/24_filled.svg';
import SVGContentAmpStories_20_round from '../../svg/content/ContentAmpStories/20_round.svg';
import SVGContentAmpStories_24_round from '../../svg/content/ContentAmpStories/24_round.svg';

export const IconContentAmpStories20outlined = () => <SVGContentAmpStories_20_outlined />;
export const IconContentAmpStories24outlined = () => <SVGContentAmpStories_24_outlined />;
export const IconContentAmpStories20twotone = () => <SVGContentAmpStories_20_twotone />;
export const IconContentAmpStories24twotone = () => <SVGContentAmpStories_24_twotone />;
export const IconContentAmpStories20sharp = () => <SVGContentAmpStories_20_sharp />;
export const IconContentAmpStories24sharp = () => <SVGContentAmpStories_24_sharp />;
export const IconContentAmpStories20filled = () => <SVGContentAmpStories_20_filled />;
export const IconContentAmpStories24filled = () => <SVGContentAmpStories_24_filled />;
export const IconContentAmpStories20round = () => <SVGContentAmpStories_20_round />;
export const IconContentAmpStories24round = () => <SVGContentAmpStories_24_round />;
