import React from "react";
import SVGContentFilterListOff_20_outlined from '../../svg/content/ContentFilterListOff/20_outlined.svg';
import SVGContentFilterListOff_24_outlined from '../../svg/content/ContentFilterListOff/24_outlined.svg';
import SVGContentFilterListOff_20_twotone from '../../svg/content/ContentFilterListOff/20_twotone.svg';
import SVGContentFilterListOff_24_twotone from '../../svg/content/ContentFilterListOff/24_twotone.svg';
import SVGContentFilterListOff_20_sharp from '../../svg/content/ContentFilterListOff/20_sharp.svg';
import SVGContentFilterListOff_24_sharp from '../../svg/content/ContentFilterListOff/24_sharp.svg';
import SVGContentFilterListOff_20_filled from '../../svg/content/ContentFilterListOff/20_filled.svg';
import SVGContentFilterListOff_24_filled from '../../svg/content/ContentFilterListOff/24_filled.svg';
import SVGContentFilterListOff_20_round from '../../svg/content/ContentFilterListOff/20_round.svg';
import SVGContentFilterListOff_24_round from '../../svg/content/ContentFilterListOff/24_round.svg';

export const IconContentFilterListOff20outlined = () => <SVGContentFilterListOff_20_outlined />;
export const IconContentFilterListOff24outlined = () => <SVGContentFilterListOff_24_outlined />;
export const IconContentFilterListOff20twotone = () => <SVGContentFilterListOff_20_twotone />;
export const IconContentFilterListOff24twotone = () => <SVGContentFilterListOff_24_twotone />;
export const IconContentFilterListOff20sharp = () => <SVGContentFilterListOff_20_sharp />;
export const IconContentFilterListOff24sharp = () => <SVGContentFilterListOff_24_sharp />;
export const IconContentFilterListOff20filled = () => <SVGContentFilterListOff_20_filled />;
export const IconContentFilterListOff24filled = () => <SVGContentFilterListOff_24_filled />;
export const IconContentFilterListOff20round = () => <SVGContentFilterListOff_20_round />;
export const IconContentFilterListOff24round = () => <SVGContentFilterListOff_24_round />;
