import React from "react";
import SVGContentFlagCircle_20_outlined from '../../svg/content/ContentFlagCircle/20_outlined.svg';
import SVGContentFlagCircle_24_outlined from '../../svg/content/ContentFlagCircle/24_outlined.svg';
import SVGContentFlagCircle_20_twotone from '../../svg/content/ContentFlagCircle/20_twotone.svg';
import SVGContentFlagCircle_24_twotone from '../../svg/content/ContentFlagCircle/24_twotone.svg';
import SVGContentFlagCircle_20_sharp from '../../svg/content/ContentFlagCircle/20_sharp.svg';
import SVGContentFlagCircle_24_sharp from '../../svg/content/ContentFlagCircle/24_sharp.svg';
import SVGContentFlagCircle_20_filled from '../../svg/content/ContentFlagCircle/20_filled.svg';
import SVGContentFlagCircle_24_filled from '../../svg/content/ContentFlagCircle/24_filled.svg';
import SVGContentFlagCircle_20_round from '../../svg/content/ContentFlagCircle/20_round.svg';
import SVGContentFlagCircle_24_round from '../../svg/content/ContentFlagCircle/24_round.svg';

export const IconContentFlagCircle20outlined = () => <SVGContentFlagCircle_20_outlined />;
export const IconContentFlagCircle24outlined = () => <SVGContentFlagCircle_24_outlined />;
export const IconContentFlagCircle20twotone = () => <SVGContentFlagCircle_20_twotone />;
export const IconContentFlagCircle24twotone = () => <SVGContentFlagCircle_24_twotone />;
export const IconContentFlagCircle20sharp = () => <SVGContentFlagCircle_20_sharp />;
export const IconContentFlagCircle24sharp = () => <SVGContentFlagCircle_24_sharp />;
export const IconContentFlagCircle20filled = () => <SVGContentFlagCircle_20_filled />;
export const IconContentFlagCircle24filled = () => <SVGContentFlagCircle_24_filled />;
export const IconContentFlagCircle20round = () => <SVGContentFlagCircle_20_round />;
export const IconContentFlagCircle24round = () => <SVGContentFlagCircle_24_round />;
