import React from "react";
import SVGContentPolicy_20_outlined from '../../svg/content/ContentPolicy/20_outlined.svg';
import SVGContentPolicy_24_outlined from '../../svg/content/ContentPolicy/24_outlined.svg';
import SVGContentPolicy_20_twotone from '../../svg/content/ContentPolicy/20_twotone.svg';
import SVGContentPolicy_24_twotone from '../../svg/content/ContentPolicy/24_twotone.svg';
import SVGContentPolicy_20_sharp from '../../svg/content/ContentPolicy/20_sharp.svg';
import SVGContentPolicy_24_sharp from '../../svg/content/ContentPolicy/24_sharp.svg';
import SVGContentPolicy_20_filled from '../../svg/content/ContentPolicy/20_filled.svg';
import SVGContentPolicy_24_filled from '../../svg/content/ContentPolicy/24_filled.svg';
import SVGContentPolicy_20_round from '../../svg/content/ContentPolicy/20_round.svg';
import SVGContentPolicy_24_round from '../../svg/content/ContentPolicy/24_round.svg';

export const IconContentPolicy20outlined = () => <SVGContentPolicy_20_outlined />;
export const IconContentPolicy24outlined = () => <SVGContentPolicy_24_outlined />;
export const IconContentPolicy20twotone = () => <SVGContentPolicy_20_twotone />;
export const IconContentPolicy24twotone = () => <SVGContentPolicy_24_twotone />;
export const IconContentPolicy20sharp = () => <SVGContentPolicy_20_sharp />;
export const IconContentPolicy24sharp = () => <SVGContentPolicy_24_sharp />;
export const IconContentPolicy20filled = () => <SVGContentPolicy_20_filled />;
export const IconContentPolicy24filled = () => <SVGContentPolicy_24_filled />;
export const IconContentPolicy20round = () => <SVGContentPolicy_20_round />;
export const IconContentPolicy24round = () => <SVGContentPolicy_24_round />;
