import React from "react";
import SVGContentSquareFoot_20_outlined from '../../svg/content/ContentSquareFoot/20_outlined.svg';
import SVGContentSquareFoot_24_outlined from '../../svg/content/ContentSquareFoot/24_outlined.svg';
import SVGContentSquareFoot_20_twotone from '../../svg/content/ContentSquareFoot/20_twotone.svg';
import SVGContentSquareFoot_24_twotone from '../../svg/content/ContentSquareFoot/24_twotone.svg';
import SVGContentSquareFoot_20_sharp from '../../svg/content/ContentSquareFoot/20_sharp.svg';
import SVGContentSquareFoot_24_sharp from '../../svg/content/ContentSquareFoot/24_sharp.svg';
import SVGContentSquareFoot_20_filled from '../../svg/content/ContentSquareFoot/20_filled.svg';
import SVGContentSquareFoot_24_filled from '../../svg/content/ContentSquareFoot/24_filled.svg';
import SVGContentSquareFoot_20_round from '../../svg/content/ContentSquareFoot/20_round.svg';
import SVGContentSquareFoot_24_round from '../../svg/content/ContentSquareFoot/24_round.svg';

export const IconContentSquareFoot20outlined = () => <SVGContentSquareFoot_20_outlined />;
export const IconContentSquareFoot24outlined = () => <SVGContentSquareFoot_24_outlined />;
export const IconContentSquareFoot20twotone = () => <SVGContentSquareFoot_20_twotone />;
export const IconContentSquareFoot24twotone = () => <SVGContentSquareFoot_24_twotone />;
export const IconContentSquareFoot20sharp = () => <SVGContentSquareFoot_20_sharp />;
export const IconContentSquareFoot24sharp = () => <SVGContentSquareFoot_24_sharp />;
export const IconContentSquareFoot20filled = () => <SVGContentSquareFoot_20_filled />;
export const IconContentSquareFoot24filled = () => <SVGContentSquareFoot_24_filled />;
export const IconContentSquareFoot20round = () => <SVGContentSquareFoot_20_round />;
export const IconContentSquareFoot24round = () => <SVGContentSquareFoot_24_round />;
