import React from "react";
import SVGContentInventory2_20_outlined from '../../svg/content/ContentInventory2/20_outlined.svg';
import SVGContentInventory2_24_outlined from '../../svg/content/ContentInventory2/24_outlined.svg';
import SVGContentInventory2_20_twotone from '../../svg/content/ContentInventory2/20_twotone.svg';
import SVGContentInventory2_24_twotone from '../../svg/content/ContentInventory2/24_twotone.svg';
import SVGContentInventory2_20_sharp from '../../svg/content/ContentInventory2/20_sharp.svg';
import SVGContentInventory2_24_sharp from '../../svg/content/ContentInventory2/24_sharp.svg';
import SVGContentInventory2_20_filled from '../../svg/content/ContentInventory2/20_filled.svg';
import SVGContentInventory2_24_filled from '../../svg/content/ContentInventory2/24_filled.svg';
import SVGContentInventory2_20_round from '../../svg/content/ContentInventory2/20_round.svg';
import SVGContentInventory2_24_round from '../../svg/content/ContentInventory2/24_round.svg';

export const IconContentInventory220outlined = () => <SVGContentInventory2_20_outlined />;
export const IconContentInventory224outlined = () => <SVGContentInventory2_24_outlined />;
export const IconContentInventory220twotone = () => <SVGContentInventory2_20_twotone />;
export const IconContentInventory224twotone = () => <SVGContentInventory2_24_twotone />;
export const IconContentInventory220sharp = () => <SVGContentInventory2_20_sharp />;
export const IconContentInventory224sharp = () => <SVGContentInventory2_24_sharp />;
export const IconContentInventory220filled = () => <SVGContentInventory2_20_filled />;
export const IconContentInventory224filled = () => <SVGContentInventory2_24_filled />;
export const IconContentInventory220round = () => <SVGContentInventory2_20_round />;
export const IconContentInventory224round = () => <SVGContentInventory2_24_round />;
