import React from "react";
import SVGEditorAutoGraph_20_outlined from '../../svg/editor/EditorAutoGraph/20_outlined.svg';
import SVGEditorAutoGraph_24_outlined from '../../svg/editor/EditorAutoGraph/24_outlined.svg';
import SVGEditorAutoGraph_20_twotone from '../../svg/editor/EditorAutoGraph/20_twotone.svg';
import SVGEditorAutoGraph_24_twotone from '../../svg/editor/EditorAutoGraph/24_twotone.svg';
import SVGEditorAutoGraph_20_sharp from '../../svg/editor/EditorAutoGraph/20_sharp.svg';
import SVGEditorAutoGraph_24_sharp from '../../svg/editor/EditorAutoGraph/24_sharp.svg';
import SVGEditorAutoGraph_20_filled from '../../svg/editor/EditorAutoGraph/20_filled.svg';
import SVGEditorAutoGraph_24_filled from '../../svg/editor/EditorAutoGraph/24_filled.svg';
import SVGEditorAutoGraph_20_round from '../../svg/editor/EditorAutoGraph/20_round.svg';
import SVGEditorAutoGraph_24_round from '../../svg/editor/EditorAutoGraph/24_round.svg';

export const IconEditorAutoGraph20outlined = () => <SVGEditorAutoGraph_20_outlined />;
export const IconEditorAutoGraph24outlined = () => <SVGEditorAutoGraph_24_outlined />;
export const IconEditorAutoGraph20twotone = () => <SVGEditorAutoGraph_20_twotone />;
export const IconEditorAutoGraph24twotone = () => <SVGEditorAutoGraph_24_twotone />;
export const IconEditorAutoGraph20sharp = () => <SVGEditorAutoGraph_20_sharp />;
export const IconEditorAutoGraph24sharp = () => <SVGEditorAutoGraph_24_sharp />;
export const IconEditorAutoGraph20filled = () => <SVGEditorAutoGraph_20_filled />;
export const IconEditorAutoGraph24filled = () => <SVGEditorAutoGraph_24_filled />;
export const IconEditorAutoGraph20round = () => <SVGEditorAutoGraph_20_round />;
export const IconEditorAutoGraph24round = () => <SVGEditorAutoGraph_24_round />;
