import React from "react";
import SVGEditorShapeLine_20_outlined from '../../svg/editor/EditorShapeLine/20_outlined.svg';
import SVGEditorShapeLine_24_outlined from '../../svg/editor/EditorShapeLine/24_outlined.svg';
import SVGEditorShapeLine_20_twotone from '../../svg/editor/EditorShapeLine/20_twotone.svg';
import SVGEditorShapeLine_24_twotone from '../../svg/editor/EditorShapeLine/24_twotone.svg';
import SVGEditorShapeLine_20_sharp from '../../svg/editor/EditorShapeLine/20_sharp.svg';
import SVGEditorShapeLine_24_sharp from '../../svg/editor/EditorShapeLine/24_sharp.svg';
import SVGEditorShapeLine_20_filled from '../../svg/editor/EditorShapeLine/20_filled.svg';
import SVGEditorShapeLine_24_filled from '../../svg/editor/EditorShapeLine/24_filled.svg';
import SVGEditorShapeLine_20_round from '../../svg/editor/EditorShapeLine/20_round.svg';
import SVGEditorShapeLine_24_round from '../../svg/editor/EditorShapeLine/24_round.svg';

export const IconEditorShapeLine20outlined = () => <SVGEditorShapeLine_20_outlined />;
export const IconEditorShapeLine24outlined = () => <SVGEditorShapeLine_24_outlined />;
export const IconEditorShapeLine20twotone = () => <SVGEditorShapeLine_20_twotone />;
export const IconEditorShapeLine24twotone = () => <SVGEditorShapeLine_24_twotone />;
export const IconEditorShapeLine20sharp = () => <SVGEditorShapeLine_20_sharp />;
export const IconEditorShapeLine24sharp = () => <SVGEditorShapeLine_24_sharp />;
export const IconEditorShapeLine20filled = () => <SVGEditorShapeLine_20_filled />;
export const IconEditorShapeLine24filled = () => <SVGEditorShapeLine_24_filled />;
export const IconEditorShapeLine20round = () => <SVGEditorShapeLine_20_round />;
export const IconEditorShapeLine24round = () => <SVGEditorShapeLine_24_round />;
