import React from "react";
import SVGEditorMoveUp_20_outlined from '../../svg/editor/EditorMoveUp/20_outlined.svg';
import SVGEditorMoveUp_24_outlined from '../../svg/editor/EditorMoveUp/24_outlined.svg';
import SVGEditorMoveUp_20_twotone from '../../svg/editor/EditorMoveUp/20_twotone.svg';
import SVGEditorMoveUp_24_twotone from '../../svg/editor/EditorMoveUp/24_twotone.svg';
import SVGEditorMoveUp_20_sharp from '../../svg/editor/EditorMoveUp/20_sharp.svg';
import SVGEditorMoveUp_24_sharp from '../../svg/editor/EditorMoveUp/24_sharp.svg';
import SVGEditorMoveUp_20_filled from '../../svg/editor/EditorMoveUp/20_filled.svg';
import SVGEditorMoveUp_24_filled from '../../svg/editor/EditorMoveUp/24_filled.svg';
import SVGEditorMoveUp_20_round from '../../svg/editor/EditorMoveUp/20_round.svg';
import SVGEditorMoveUp_24_round from '../../svg/editor/EditorMoveUp/24_round.svg';

export const IconEditorMoveUp20outlined = () => <SVGEditorMoveUp_20_outlined />;
export const IconEditorMoveUp24outlined = () => <SVGEditorMoveUp_24_outlined />;
export const IconEditorMoveUp20twotone = () => <SVGEditorMoveUp_20_twotone />;
export const IconEditorMoveUp24twotone = () => <SVGEditorMoveUp_24_twotone />;
export const IconEditorMoveUp20sharp = () => <SVGEditorMoveUp_20_sharp />;
export const IconEditorMoveUp24sharp = () => <SVGEditorMoveUp_24_sharp />;
export const IconEditorMoveUp20filled = () => <SVGEditorMoveUp_20_filled />;
export const IconEditorMoveUp24filled = () => <SVGEditorMoveUp_24_filled />;
export const IconEditorMoveUp20round = () => <SVGEditorMoveUp_20_round />;
export const IconEditorMoveUp24round = () => <SVGEditorMoveUp_24_round />;
