import React from "react";
import SVGEditorCandlestickChart_20_outlined from '../../svg/editor/EditorCandlestickChart/20_outlined.svg';
import SVGEditorCandlestickChart_24_outlined from '../../svg/editor/EditorCandlestickChart/24_outlined.svg';
import SVGEditorCandlestickChart_20_twotone from '../../svg/editor/EditorCandlestickChart/20_twotone.svg';
import SVGEditorCandlestickChart_24_twotone from '../../svg/editor/EditorCandlestickChart/24_twotone.svg';
import SVGEditorCandlestickChart_20_sharp from '../../svg/editor/EditorCandlestickChart/20_sharp.svg';
import SVGEditorCandlestickChart_24_sharp from '../../svg/editor/EditorCandlestickChart/24_sharp.svg';
import SVGEditorCandlestickChart_20_filled from '../../svg/editor/EditorCandlestickChart/20_filled.svg';
import SVGEditorCandlestickChart_24_filled from '../../svg/editor/EditorCandlestickChart/24_filled.svg';
import SVGEditorCandlestickChart_20_round from '../../svg/editor/EditorCandlestickChart/20_round.svg';
import SVGEditorCandlestickChart_24_round from '../../svg/editor/EditorCandlestickChart/24_round.svg';

export const IconEditorCandlestickChart20outlined = () => <SVGEditorCandlestickChart_20_outlined />;
export const IconEditorCandlestickChart24outlined = () => <SVGEditorCandlestickChart_24_outlined />;
export const IconEditorCandlestickChart20twotone = () => <SVGEditorCandlestickChart_20_twotone />;
export const IconEditorCandlestickChart24twotone = () => <SVGEditorCandlestickChart_24_twotone />;
export const IconEditorCandlestickChart20sharp = () => <SVGEditorCandlestickChart_20_sharp />;
export const IconEditorCandlestickChart24sharp = () => <SVGEditorCandlestickChart_24_sharp />;
export const IconEditorCandlestickChart20filled = () => <SVGEditorCandlestickChart_20_filled />;
export const IconEditorCandlestickChart24filled = () => <SVGEditorCandlestickChart_24_filled />;
export const IconEditorCandlestickChart20round = () => <SVGEditorCandlestickChart_20_round />;
export const IconEditorCandlestickChart24round = () => <SVGEditorCandlestickChart_24_round />;
