import React from "react";
import SVGEditorFormatColorText_20_outlined from '../../svg/editor/EditorFormatColorText/20_outlined.svg';
import SVGEditorFormatColorText_24_outlined from '../../svg/editor/EditorFormatColorText/24_outlined.svg';
import SVGEditorFormatColorText_20_twotone from '../../svg/editor/EditorFormatColorText/20_twotone.svg';
import SVGEditorFormatColorText_24_twotone from '../../svg/editor/EditorFormatColorText/24_twotone.svg';
import SVGEditorFormatColorText_20_sharp from '../../svg/editor/EditorFormatColorText/20_sharp.svg';
import SVGEditorFormatColorText_24_sharp from '../../svg/editor/EditorFormatColorText/24_sharp.svg';
import SVGEditorFormatColorText_20_filled from '../../svg/editor/EditorFormatColorText/20_filled.svg';
import SVGEditorFormatColorText_24_filled from '../../svg/editor/EditorFormatColorText/24_filled.svg';
import SVGEditorFormatColorText_20_round from '../../svg/editor/EditorFormatColorText/20_round.svg';
import SVGEditorFormatColorText_24_round from '../../svg/editor/EditorFormatColorText/24_round.svg';

export const IconEditorFormatColorText20outlined = () => <SVGEditorFormatColorText_20_outlined />;
export const IconEditorFormatColorText24outlined = () => <SVGEditorFormatColorText_24_outlined />;
export const IconEditorFormatColorText20twotone = () => <SVGEditorFormatColorText_20_twotone />;
export const IconEditorFormatColorText24twotone = () => <SVGEditorFormatColorText_24_twotone />;
export const IconEditorFormatColorText20sharp = () => <SVGEditorFormatColorText_20_sharp />;
export const IconEditorFormatColorText24sharp = () => <SVGEditorFormatColorText_24_sharp />;
export const IconEditorFormatColorText20filled = () => <SVGEditorFormatColorText_20_filled />;
export const IconEditorFormatColorText24filled = () => <SVGEditorFormatColorText_24_filled />;
export const IconEditorFormatColorText20round = () => <SVGEditorFormatColorText_20_round />;
export const IconEditorFormatColorText24round = () => <SVGEditorFormatColorText_24_round />;
