import React from "react";
import SVGEditorSubscript_20_outlined from '../../svg/editor/EditorSubscript/20_outlined.svg';
import SVGEditorSubscript_24_outlined from '../../svg/editor/EditorSubscript/24_outlined.svg';
import SVGEditorSubscript_20_twotone from '../../svg/editor/EditorSubscript/20_twotone.svg';
import SVGEditorSubscript_24_twotone from '../../svg/editor/EditorSubscript/24_twotone.svg';
import SVGEditorSubscript_20_sharp from '../../svg/editor/EditorSubscript/20_sharp.svg';
import SVGEditorSubscript_24_sharp from '../../svg/editor/EditorSubscript/24_sharp.svg';
import SVGEditorSubscript_20_filled from '../../svg/editor/EditorSubscript/20_filled.svg';
import SVGEditorSubscript_24_filled from '../../svg/editor/EditorSubscript/24_filled.svg';
import SVGEditorSubscript_20_round from '../../svg/editor/EditorSubscript/20_round.svg';
import SVGEditorSubscript_24_round from '../../svg/editor/EditorSubscript/24_round.svg';

export const IconEditorSubscript20outlined = () => <SVGEditorSubscript_20_outlined />;
export const IconEditorSubscript24outlined = () => <SVGEditorSubscript_24_outlined />;
export const IconEditorSubscript20twotone = () => <SVGEditorSubscript_20_twotone />;
export const IconEditorSubscript24twotone = () => <SVGEditorSubscript_24_twotone />;
export const IconEditorSubscript20sharp = () => <SVGEditorSubscript_20_sharp />;
export const IconEditorSubscript24sharp = () => <SVGEditorSubscript_24_sharp />;
export const IconEditorSubscript20filled = () => <SVGEditorSubscript_20_filled />;
export const IconEditorSubscript24filled = () => <SVGEditorSubscript_24_filled />;
export const IconEditorSubscript20round = () => <SVGEditorSubscript_20_round />;
export const IconEditorSubscript24round = () => <SVGEditorSubscript_24_round />;
