import React from "react";
import SVGEditorTypeSpecimen_20_outlined from '../../svg/editor/EditorTypeSpecimen/20_outlined.svg';
import SVGEditorTypeSpecimen_24_outlined from '../../svg/editor/EditorTypeSpecimen/24_outlined.svg';
import SVGEditorTypeSpecimen_20_twotone from '../../svg/editor/EditorTypeSpecimen/20_twotone.svg';
import SVGEditorTypeSpecimen_24_twotone from '../../svg/editor/EditorTypeSpecimen/24_twotone.svg';
import SVGEditorTypeSpecimen_20_sharp from '../../svg/editor/EditorTypeSpecimen/20_sharp.svg';
import SVGEditorTypeSpecimen_24_sharp from '../../svg/editor/EditorTypeSpecimen/24_sharp.svg';
import SVGEditorTypeSpecimen_20_filled from '../../svg/editor/EditorTypeSpecimen/20_filled.svg';
import SVGEditorTypeSpecimen_24_filled from '../../svg/editor/EditorTypeSpecimen/24_filled.svg';
import SVGEditorTypeSpecimen_20_round from '../../svg/editor/EditorTypeSpecimen/20_round.svg';
import SVGEditorTypeSpecimen_24_round from '../../svg/editor/EditorTypeSpecimen/24_round.svg';

export const IconEditorTypeSpecimen20outlined = () => <SVGEditorTypeSpecimen_20_outlined />;
export const IconEditorTypeSpecimen24outlined = () => <SVGEditorTypeSpecimen_24_outlined />;
export const IconEditorTypeSpecimen20twotone = () => <SVGEditorTypeSpecimen_20_twotone />;
export const IconEditorTypeSpecimen24twotone = () => <SVGEditorTypeSpecimen_24_twotone />;
export const IconEditorTypeSpecimen20sharp = () => <SVGEditorTypeSpecimen_20_sharp />;
export const IconEditorTypeSpecimen24sharp = () => <SVGEditorTypeSpecimen_24_sharp />;
export const IconEditorTypeSpecimen20filled = () => <SVGEditorTypeSpecimen_20_filled />;
export const IconEditorTypeSpecimen24filled = () => <SVGEditorTypeSpecimen_24_filled />;
export const IconEditorTypeSpecimen20round = () => <SVGEditorTypeSpecimen_20_round />;
export const IconEditorTypeSpecimen24round = () => <SVGEditorTypeSpecimen_24_round />;
