import React from "react";
import SVGEditorModeEditOutline_20_outlined from '../../svg/editor/EditorModeEditOutline/20_outlined.svg';
import SVGEditorModeEditOutline_24_outlined from '../../svg/editor/EditorModeEditOutline/24_outlined.svg';
import SVGEditorModeEditOutline_20_twotone from '../../svg/editor/EditorModeEditOutline/20_twotone.svg';
import SVGEditorModeEditOutline_24_twotone from '../../svg/editor/EditorModeEditOutline/24_twotone.svg';
import SVGEditorModeEditOutline_20_sharp from '../../svg/editor/EditorModeEditOutline/20_sharp.svg';
import SVGEditorModeEditOutline_24_sharp from '../../svg/editor/EditorModeEditOutline/24_sharp.svg';
import SVGEditorModeEditOutline_20_filled from '../../svg/editor/EditorModeEditOutline/20_filled.svg';
import SVGEditorModeEditOutline_24_filled from '../../svg/editor/EditorModeEditOutline/24_filled.svg';
import SVGEditorModeEditOutline_20_round from '../../svg/editor/EditorModeEditOutline/20_round.svg';
import SVGEditorModeEditOutline_24_round from '../../svg/editor/EditorModeEditOutline/24_round.svg';

export const IconEditorModeEditOutline20outlined = () => <SVGEditorModeEditOutline_20_outlined />;
export const IconEditorModeEditOutline24outlined = () => <SVGEditorModeEditOutline_24_outlined />;
export const IconEditorModeEditOutline20twotone = () => <SVGEditorModeEditOutline_20_twotone />;
export const IconEditorModeEditOutline24twotone = () => <SVGEditorModeEditOutline_24_twotone />;
export const IconEditorModeEditOutline20sharp = () => <SVGEditorModeEditOutline_20_sharp />;
export const IconEditorModeEditOutline24sharp = () => <SVGEditorModeEditOutline_24_sharp />;
export const IconEditorModeEditOutline20filled = () => <SVGEditorModeEditOutline_20_filled />;
export const IconEditorModeEditOutline24filled = () => <SVGEditorModeEditOutline_24_filled />;
export const IconEditorModeEditOutline20round = () => <SVGEditorModeEditOutline_20_round />;
export const IconEditorModeEditOutline24round = () => <SVGEditorModeEditOutline_24_round />;
