import React from "react";
import SVGEditorFormatColorFill_20_outlined from '../../svg/editor/EditorFormatColorFill/20_outlined.svg';
import SVGEditorFormatColorFill_24_outlined from '../../svg/editor/EditorFormatColorFill/24_outlined.svg';
import SVGEditorFormatColorFill_20_twotone from '../../svg/editor/EditorFormatColorFill/20_twotone.svg';
import SVGEditorFormatColorFill_24_twotone from '../../svg/editor/EditorFormatColorFill/24_twotone.svg';
import SVGEditorFormatColorFill_20_sharp from '../../svg/editor/EditorFormatColorFill/20_sharp.svg';
import SVGEditorFormatColorFill_24_sharp from '../../svg/editor/EditorFormatColorFill/24_sharp.svg';
import SVGEditorFormatColorFill_20_filled from '../../svg/editor/EditorFormatColorFill/20_filled.svg';
import SVGEditorFormatColorFill_24_filled from '../../svg/editor/EditorFormatColorFill/24_filled.svg';
import SVGEditorFormatColorFill_20_round from '../../svg/editor/EditorFormatColorFill/20_round.svg';
import SVGEditorFormatColorFill_24_round from '../../svg/editor/EditorFormatColorFill/24_round.svg';

export const IconEditorFormatColorFill20outlined = () => <SVGEditorFormatColorFill_20_outlined />;
export const IconEditorFormatColorFill24outlined = () => <SVGEditorFormatColorFill_24_outlined />;
export const IconEditorFormatColorFill20twotone = () => <SVGEditorFormatColorFill_20_twotone />;
export const IconEditorFormatColorFill24twotone = () => <SVGEditorFormatColorFill_24_twotone />;
export const IconEditorFormatColorFill20sharp = () => <SVGEditorFormatColorFill_20_sharp />;
export const IconEditorFormatColorFill24sharp = () => <SVGEditorFormatColorFill_24_sharp />;
export const IconEditorFormatColorFill20filled = () => <SVGEditorFormatColorFill_20_filled />;
export const IconEditorFormatColorFill24filled = () => <SVGEditorFormatColorFill_24_filled />;
export const IconEditorFormatColorFill20round = () => <SVGEditorFormatColorFill_20_round />;
export const IconEditorFormatColorFill24round = () => <SVGEditorFormatColorFill_24_round />;
