import React from "react";
import SVGEditorLineAxis_20_outlined from '../../svg/editor/EditorLineAxis/20_outlined.svg';
import SVGEditorLineAxis_24_outlined from '../../svg/editor/EditorLineAxis/24_outlined.svg';
import SVGEditorLineAxis_20_twotone from '../../svg/editor/EditorLineAxis/20_twotone.svg';
import SVGEditorLineAxis_24_twotone from '../../svg/editor/EditorLineAxis/24_twotone.svg';
import SVGEditorLineAxis_20_sharp from '../../svg/editor/EditorLineAxis/20_sharp.svg';
import SVGEditorLineAxis_24_sharp from '../../svg/editor/EditorLineAxis/24_sharp.svg';
import SVGEditorLineAxis_20_filled from '../../svg/editor/EditorLineAxis/20_filled.svg';
import SVGEditorLineAxis_24_filled from '../../svg/editor/EditorLineAxis/24_filled.svg';
import SVGEditorLineAxis_20_round from '../../svg/editor/EditorLineAxis/20_round.svg';
import SVGEditorLineAxis_24_round from '../../svg/editor/EditorLineAxis/24_round.svg';

export const IconEditorLineAxis20outlined = () => <SVGEditorLineAxis_20_outlined />;
export const IconEditorLineAxis24outlined = () => <SVGEditorLineAxis_24_outlined />;
export const IconEditorLineAxis20twotone = () => <SVGEditorLineAxis_20_twotone />;
export const IconEditorLineAxis24twotone = () => <SVGEditorLineAxis_24_twotone />;
export const IconEditorLineAxis20sharp = () => <SVGEditorLineAxis_20_sharp />;
export const IconEditorLineAxis24sharp = () => <SVGEditorLineAxis_24_sharp />;
export const IconEditorLineAxis20filled = () => <SVGEditorLineAxis_20_filled />;
export const IconEditorLineAxis24filled = () => <SVGEditorLineAxis_24_filled />;
export const IconEditorLineAxis20round = () => <SVGEditorLineAxis_20_round />;
export const IconEditorLineAxis24round = () => <SVGEditorLineAxis_24_round />;
