import React from "react";
import SVGEditorTextIncrease_20_outlined from '../../svg/editor/EditorTextIncrease/20_outlined.svg';
import SVGEditorTextIncrease_24_outlined from '../../svg/editor/EditorTextIncrease/24_outlined.svg';
import SVGEditorTextIncrease_20_twotone from '../../svg/editor/EditorTextIncrease/20_twotone.svg';
import SVGEditorTextIncrease_24_twotone from '../../svg/editor/EditorTextIncrease/24_twotone.svg';
import SVGEditorTextIncrease_20_sharp from '../../svg/editor/EditorTextIncrease/20_sharp.svg';
import SVGEditorTextIncrease_24_sharp from '../../svg/editor/EditorTextIncrease/24_sharp.svg';
import SVGEditorTextIncrease_20_filled from '../../svg/editor/EditorTextIncrease/20_filled.svg';
import SVGEditorTextIncrease_24_filled from '../../svg/editor/EditorTextIncrease/24_filled.svg';
import SVGEditorTextIncrease_20_round from '../../svg/editor/EditorTextIncrease/20_round.svg';
import SVGEditorTextIncrease_24_round from '../../svg/editor/EditorTextIncrease/24_round.svg';

export const IconEditorTextIncrease20outlined = () => <SVGEditorTextIncrease_20_outlined />;
export const IconEditorTextIncrease24outlined = () => <SVGEditorTextIncrease_24_outlined />;
export const IconEditorTextIncrease20twotone = () => <SVGEditorTextIncrease_20_twotone />;
export const IconEditorTextIncrease24twotone = () => <SVGEditorTextIncrease_24_twotone />;
export const IconEditorTextIncrease20sharp = () => <SVGEditorTextIncrease_20_sharp />;
export const IconEditorTextIncrease24sharp = () => <SVGEditorTextIncrease_24_sharp />;
export const IconEditorTextIncrease20filled = () => <SVGEditorTextIncrease_20_filled />;
export const IconEditorTextIncrease24filled = () => <SVGEditorTextIncrease_24_filled />;
export const IconEditorTextIncrease20round = () => <SVGEditorTextIncrease_20_round />;
export const IconEditorTextIncrease24round = () => <SVGEditorTextIncrease_24_round />;
