import React from "react";
import SVGActionNextPlan_20_outlined from '../../svg/action/ActionNextPlan/20_outlined.svg';
import SVGActionNextPlan_24_outlined from '../../svg/action/ActionNextPlan/24_outlined.svg';
import SVGActionNextPlan_20_twotone from '../../svg/action/ActionNextPlan/20_twotone.svg';
import SVGActionNextPlan_24_twotone from '../../svg/action/ActionNextPlan/24_twotone.svg';
import SVGActionNextPlan_20_sharp from '../../svg/action/ActionNextPlan/20_sharp.svg';
import SVGActionNextPlan_24_sharp from '../../svg/action/ActionNextPlan/24_sharp.svg';
import SVGActionNextPlan_20_filled from '../../svg/action/ActionNextPlan/20_filled.svg';
import SVGActionNextPlan_24_filled from '../../svg/action/ActionNextPlan/24_filled.svg';
import SVGActionNextPlan_20_round from '../../svg/action/ActionNextPlan/20_round.svg';
import SVGActionNextPlan_24_round from '../../svg/action/ActionNextPlan/24_round.svg';

export const IconActionNextPlan20outlined = () => <SVGActionNextPlan_20_outlined />;
export const IconActionNextPlan24outlined = () => <SVGActionNextPlan_24_outlined />;
export const IconActionNextPlan20twotone = () => <SVGActionNextPlan_20_twotone />;
export const IconActionNextPlan24twotone = () => <SVGActionNextPlan_24_twotone />;
export const IconActionNextPlan20sharp = () => <SVGActionNextPlan_20_sharp />;
export const IconActionNextPlan24sharp = () => <SVGActionNextPlan_24_sharp />;
export const IconActionNextPlan20filled = () => <SVGActionNextPlan_20_filled />;
export const IconActionNextPlan24filled = () => <SVGActionNextPlan_24_filled />;
export const IconActionNextPlan20round = () => <SVGActionNextPlan_20_round />;
export const IconActionNextPlan24round = () => <SVGActionNextPlan_24_round />;
