import React from "react";
import SVGActionLockClock_20_outlined from '../../svg/action/ActionLockClock/20_outlined.svg';
import SVGActionLockClock_24_outlined from '../../svg/action/ActionLockClock/24_outlined.svg';
import SVGActionLockClock_20_twotone from '../../svg/action/ActionLockClock/20_twotone.svg';
import SVGActionLockClock_24_twotone from '../../svg/action/ActionLockClock/24_twotone.svg';
import SVGActionLockClock_20_sharp from '../../svg/action/ActionLockClock/20_sharp.svg';
import SVGActionLockClock_24_sharp from '../../svg/action/ActionLockClock/24_sharp.svg';
import SVGActionLockClock_20_filled from '../../svg/action/ActionLockClock/20_filled.svg';
import SVGActionLockClock_24_filled from '../../svg/action/ActionLockClock/24_filled.svg';
import SVGActionLockClock_20_round from '../../svg/action/ActionLockClock/20_round.svg';
import SVGActionLockClock_24_round from '../../svg/action/ActionLockClock/24_round.svg';

export const IconActionLockClock20outlined = () => <SVGActionLockClock_20_outlined />;
export const IconActionLockClock24outlined = () => <SVGActionLockClock_24_outlined />;
export const IconActionLockClock20twotone = () => <SVGActionLockClock_20_twotone />;
export const IconActionLockClock24twotone = () => <SVGActionLockClock_24_twotone />;
export const IconActionLockClock20sharp = () => <SVGActionLockClock_20_sharp />;
export const IconActionLockClock24sharp = () => <SVGActionLockClock_24_sharp />;
export const IconActionLockClock20filled = () => <SVGActionLockClock_20_filled />;
export const IconActionLockClock24filled = () => <SVGActionLockClock_24_filled />;
export const IconActionLockClock20round = () => <SVGActionLockClock_20_round />;
export const IconActionLockClock24round = () => <SVGActionLockClock_24_round />;
