import React from "react";
import SVGActionAdsClick_20_outlined from '../../svg/action/ActionAdsClick/20_outlined.svg';
import SVGActionAdsClick_24_outlined from '../../svg/action/ActionAdsClick/24_outlined.svg';
import SVGActionAdsClick_20_twotone from '../../svg/action/ActionAdsClick/20_twotone.svg';
import SVGActionAdsClick_24_twotone from '../../svg/action/ActionAdsClick/24_twotone.svg';
import SVGActionAdsClick_20_sharp from '../../svg/action/ActionAdsClick/20_sharp.svg';
import SVGActionAdsClick_24_sharp from '../../svg/action/ActionAdsClick/24_sharp.svg';
import SVGActionAdsClick_20_filled from '../../svg/action/ActionAdsClick/20_filled.svg';
import SVGActionAdsClick_24_filled from '../../svg/action/ActionAdsClick/24_filled.svg';
import SVGActionAdsClick_20_round from '../../svg/action/ActionAdsClick/20_round.svg';
import SVGActionAdsClick_24_round from '../../svg/action/ActionAdsClick/24_round.svg';

export const IconActionAdsClick20outlined = () => <SVGActionAdsClick_20_outlined />;
export const IconActionAdsClick24outlined = () => <SVGActionAdsClick_24_outlined />;
export const IconActionAdsClick20twotone = () => <SVGActionAdsClick_20_twotone />;
export const IconActionAdsClick24twotone = () => <SVGActionAdsClick_24_twotone />;
export const IconActionAdsClick20sharp = () => <SVGActionAdsClick_20_sharp />;
export const IconActionAdsClick24sharp = () => <SVGActionAdsClick_24_sharp />;
export const IconActionAdsClick20filled = () => <SVGActionAdsClick_20_filled />;
export const IconActionAdsClick24filled = () => <SVGActionAdsClick_24_filled />;
export const IconActionAdsClick20round = () => <SVGActionAdsClick_20_round />;
export const IconActionAdsClick24round = () => <SVGActionAdsClick_24_round />;
