import React from "react";
import SVGActionBookmarkRemove_20_outlined from '../../svg/action/ActionBookmarkRemove/20_outlined.svg';
import SVGActionBookmarkRemove_24_outlined from '../../svg/action/ActionBookmarkRemove/24_outlined.svg';
import SVGActionBookmarkRemove_20_twotone from '../../svg/action/ActionBookmarkRemove/20_twotone.svg';
import SVGActionBookmarkRemove_24_twotone from '../../svg/action/ActionBookmarkRemove/24_twotone.svg';
import SVGActionBookmarkRemove_20_sharp from '../../svg/action/ActionBookmarkRemove/20_sharp.svg';
import SVGActionBookmarkRemove_24_sharp from '../../svg/action/ActionBookmarkRemove/24_sharp.svg';
import SVGActionBookmarkRemove_20_filled from '../../svg/action/ActionBookmarkRemove/20_filled.svg';
import SVGActionBookmarkRemove_24_filled from '../../svg/action/ActionBookmarkRemove/24_filled.svg';
import SVGActionBookmarkRemove_20_round from '../../svg/action/ActionBookmarkRemove/20_round.svg';
import SVGActionBookmarkRemove_24_round from '../../svg/action/ActionBookmarkRemove/24_round.svg';

export const IconActionBookmarkRemove20outlined = () => <SVGActionBookmarkRemove_20_outlined />;
export const IconActionBookmarkRemove24outlined = () => <SVGActionBookmarkRemove_24_outlined />;
export const IconActionBookmarkRemove20twotone = () => <SVGActionBookmarkRemove_20_twotone />;
export const IconActionBookmarkRemove24twotone = () => <SVGActionBookmarkRemove_24_twotone />;
export const IconActionBookmarkRemove20sharp = () => <SVGActionBookmarkRemove_20_sharp />;
export const IconActionBookmarkRemove24sharp = () => <SVGActionBookmarkRemove_24_sharp />;
export const IconActionBookmarkRemove20filled = () => <SVGActionBookmarkRemove_20_filled />;
export const IconActionBookmarkRemove24filled = () => <SVGActionBookmarkRemove_24_filled />;
export const IconActionBookmarkRemove20round = () => <SVGActionBookmarkRemove_20_round />;
export const IconActionBookmarkRemove24round = () => <SVGActionBookmarkRemove_24_round />;
