import React from "react";
import SVGActionSendAndArchive_20_outlined from '../../svg/action/ActionSendAndArchive/20_outlined.svg';
import SVGActionSendAndArchive_24_outlined from '../../svg/action/ActionSendAndArchive/24_outlined.svg';
import SVGActionSendAndArchive_20_twotone from '../../svg/action/ActionSendAndArchive/20_twotone.svg';
import SVGActionSendAndArchive_24_twotone from '../../svg/action/ActionSendAndArchive/24_twotone.svg';
import SVGActionSendAndArchive_20_sharp from '../../svg/action/ActionSendAndArchive/20_sharp.svg';
import SVGActionSendAndArchive_24_sharp from '../../svg/action/ActionSendAndArchive/24_sharp.svg';
import SVGActionSendAndArchive_20_filled from '../../svg/action/ActionSendAndArchive/20_filled.svg';
import SVGActionSendAndArchive_24_filled from '../../svg/action/ActionSendAndArchive/24_filled.svg';
import SVGActionSendAndArchive_20_round from '../../svg/action/ActionSendAndArchive/20_round.svg';
import SVGActionSendAndArchive_24_round from '../../svg/action/ActionSendAndArchive/24_round.svg';

export const IconActionSendAndArchive20outlined = () => <SVGActionSendAndArchive_20_outlined />;
export const IconActionSendAndArchive24outlined = () => <SVGActionSendAndArchive_24_outlined />;
export const IconActionSendAndArchive20twotone = () => <SVGActionSendAndArchive_20_twotone />;
export const IconActionSendAndArchive24twotone = () => <SVGActionSendAndArchive_24_twotone />;
export const IconActionSendAndArchive20sharp = () => <SVGActionSendAndArchive_20_sharp />;
export const IconActionSendAndArchive24sharp = () => <SVGActionSendAndArchive_24_sharp />;
export const IconActionSendAndArchive20filled = () => <SVGActionSendAndArchive_20_filled />;
export const IconActionSendAndArchive24filled = () => <SVGActionSendAndArchive_24_filled />;
export const IconActionSendAndArchive20round = () => <SVGActionSendAndArchive_20_round />;
export const IconActionSendAndArchive24round = () => <SVGActionSendAndArchive_24_round />;
