import React from "react";
import SVGActionSwipeRight_20_outlined from '../../svg/action/ActionSwipeRight/20_outlined.svg';
import SVGActionSwipeRight_24_outlined from '../../svg/action/ActionSwipeRight/24_outlined.svg';
import SVGActionSwipeRight_20_twotone from '../../svg/action/ActionSwipeRight/20_twotone.svg';
import SVGActionSwipeRight_24_twotone from '../../svg/action/ActionSwipeRight/24_twotone.svg';
import SVGActionSwipeRight_20_sharp from '../../svg/action/ActionSwipeRight/20_sharp.svg';
import SVGActionSwipeRight_24_sharp from '../../svg/action/ActionSwipeRight/24_sharp.svg';
import SVGActionSwipeRight_20_filled from '../../svg/action/ActionSwipeRight/20_filled.svg';
import SVGActionSwipeRight_24_filled from '../../svg/action/ActionSwipeRight/24_filled.svg';
import SVGActionSwipeRight_20_round from '../../svg/action/ActionSwipeRight/20_round.svg';
import SVGActionSwipeRight_24_round from '../../svg/action/ActionSwipeRight/24_round.svg';

export const IconActionSwipeRight20outlined = () => <SVGActionSwipeRight_20_outlined />;
export const IconActionSwipeRight24outlined = () => <SVGActionSwipeRight_24_outlined />;
export const IconActionSwipeRight20twotone = () => <SVGActionSwipeRight_20_twotone />;
export const IconActionSwipeRight24twotone = () => <SVGActionSwipeRight_24_twotone />;
export const IconActionSwipeRight20sharp = () => <SVGActionSwipeRight_20_sharp />;
export const IconActionSwipeRight24sharp = () => <SVGActionSwipeRight_24_sharp />;
export const IconActionSwipeRight20filled = () => <SVGActionSwipeRight_20_filled />;
export const IconActionSwipeRight24filled = () => <SVGActionSwipeRight_24_filled />;
export const IconActionSwipeRight20round = () => <SVGActionSwipeRight_20_round />;
export const IconActionSwipeRight24round = () => <SVGActionSwipeRight_24_round />;
