import React from "react";
import SVGActionShoppingCartCheckout_20_outlined from '../../svg/action/ActionShoppingCartCheckout/20_outlined.svg';
import SVGActionShoppingCartCheckout_24_outlined from '../../svg/action/ActionShoppingCartCheckout/24_outlined.svg';
import SVGActionShoppingCartCheckout_20_twotone from '../../svg/action/ActionShoppingCartCheckout/20_twotone.svg';
import SVGActionShoppingCartCheckout_24_twotone from '../../svg/action/ActionShoppingCartCheckout/24_twotone.svg';
import SVGActionShoppingCartCheckout_20_sharp from '../../svg/action/ActionShoppingCartCheckout/20_sharp.svg';
import SVGActionShoppingCartCheckout_24_sharp from '../../svg/action/ActionShoppingCartCheckout/24_sharp.svg';
import SVGActionShoppingCartCheckout_20_filled from '../../svg/action/ActionShoppingCartCheckout/20_filled.svg';
import SVGActionShoppingCartCheckout_24_filled from '../../svg/action/ActionShoppingCartCheckout/24_filled.svg';
import SVGActionShoppingCartCheckout_20_round from '../../svg/action/ActionShoppingCartCheckout/20_round.svg';
import SVGActionShoppingCartCheckout_24_round from '../../svg/action/ActionShoppingCartCheckout/24_round.svg';

export const IconActionShoppingCartCheckout20outlined = () => <SVGActionShoppingCartCheckout_20_outlined />;
export const IconActionShoppingCartCheckout24outlined = () => <SVGActionShoppingCartCheckout_24_outlined />;
export const IconActionShoppingCartCheckout20twotone = () => <SVGActionShoppingCartCheckout_20_twotone />;
export const IconActionShoppingCartCheckout24twotone = () => <SVGActionShoppingCartCheckout_24_twotone />;
export const IconActionShoppingCartCheckout20sharp = () => <SVGActionShoppingCartCheckout_20_sharp />;
export const IconActionShoppingCartCheckout24sharp = () => <SVGActionShoppingCartCheckout_24_sharp />;
export const IconActionShoppingCartCheckout20filled = () => <SVGActionShoppingCartCheckout_20_filled />;
export const IconActionShoppingCartCheckout24filled = () => <SVGActionShoppingCartCheckout_24_filled />;
export const IconActionShoppingCartCheckout20round = () => <SVGActionShoppingCartCheckout_20_round />;
export const IconActionShoppingCartCheckout24round = () => <SVGActionShoppingCartCheckout_24_round />;
