import React from "react";
import SVGActionDensitySmall_20_outlined from '../../svg/action/ActionDensitySmall/20_outlined.svg';
import SVGActionDensitySmall_24_outlined from '../../svg/action/ActionDensitySmall/24_outlined.svg';
import SVGActionDensitySmall_20_twotone from '../../svg/action/ActionDensitySmall/20_twotone.svg';
import SVGActionDensitySmall_24_twotone from '../../svg/action/ActionDensitySmall/24_twotone.svg';
import SVGActionDensitySmall_20_sharp from '../../svg/action/ActionDensitySmall/20_sharp.svg';
import SVGActionDensitySmall_24_sharp from '../../svg/action/ActionDensitySmall/24_sharp.svg';
import SVGActionDensitySmall_20_filled from '../../svg/action/ActionDensitySmall/20_filled.svg';
import SVGActionDensitySmall_24_filled from '../../svg/action/ActionDensitySmall/24_filled.svg';
import SVGActionDensitySmall_20_round from '../../svg/action/ActionDensitySmall/20_round.svg';
import SVGActionDensitySmall_24_round from '../../svg/action/ActionDensitySmall/24_round.svg';

export const IconActionDensitySmall20outlined = () => <SVGActionDensitySmall_20_outlined />;
export const IconActionDensitySmall24outlined = () => <SVGActionDensitySmall_24_outlined />;
export const IconActionDensitySmall20twotone = () => <SVGActionDensitySmall_20_twotone />;
export const IconActionDensitySmall24twotone = () => <SVGActionDensitySmall_24_twotone />;
export const IconActionDensitySmall20sharp = () => <SVGActionDensitySmall_20_sharp />;
export const IconActionDensitySmall24sharp = () => <SVGActionDensitySmall_24_sharp />;
export const IconActionDensitySmall20filled = () => <SVGActionDensitySmall_20_filled />;
export const IconActionDensitySmall24filled = () => <SVGActionDensitySmall_24_filled />;
export const IconActionDensitySmall20round = () => <SVGActionDensitySmall_20_round />;
export const IconActionDensitySmall24round = () => <SVGActionDensitySmall_24_round />;
