import React from "react";
import SVGActionArrowCircleUp_20_outlined from '../../svg/action/ActionArrowCircleUp/20_outlined.svg';
import SVGActionArrowCircleUp_24_outlined from '../../svg/action/ActionArrowCircleUp/24_outlined.svg';
import SVGActionArrowCircleUp_20_twotone from '../../svg/action/ActionArrowCircleUp/20_twotone.svg';
import SVGActionArrowCircleUp_24_twotone from '../../svg/action/ActionArrowCircleUp/24_twotone.svg';
import SVGActionArrowCircleUp_20_sharp from '../../svg/action/ActionArrowCircleUp/20_sharp.svg';
import SVGActionArrowCircleUp_24_sharp from '../../svg/action/ActionArrowCircleUp/24_sharp.svg';
import SVGActionArrowCircleUp_20_filled from '../../svg/action/ActionArrowCircleUp/20_filled.svg';
import SVGActionArrowCircleUp_24_filled from '../../svg/action/ActionArrowCircleUp/24_filled.svg';
import SVGActionArrowCircleUp_20_round from '../../svg/action/ActionArrowCircleUp/20_round.svg';
import SVGActionArrowCircleUp_24_round from '../../svg/action/ActionArrowCircleUp/24_round.svg';

export const IconActionArrowCircleUp20outlined = () => <SVGActionArrowCircleUp_20_outlined />;
export const IconActionArrowCircleUp24outlined = () => <SVGActionArrowCircleUp_24_outlined />;
export const IconActionArrowCircleUp20twotone = () => <SVGActionArrowCircleUp_20_twotone />;
export const IconActionArrowCircleUp24twotone = () => <SVGActionArrowCircleUp_24_twotone />;
export const IconActionArrowCircleUp20sharp = () => <SVGActionArrowCircleUp_20_sharp />;
export const IconActionArrowCircleUp24sharp = () => <SVGActionArrowCircleUp_24_sharp />;
export const IconActionArrowCircleUp20filled = () => <SVGActionArrowCircleUp_20_filled />;
export const IconActionArrowCircleUp24filled = () => <SVGActionArrowCircleUp_24_filled />;
export const IconActionArrowCircleUp20round = () => <SVGActionArrowCircleUp_20_round />;
export const IconActionArrowCircleUp24round = () => <SVGActionArrowCircleUp_24_round />;
