import React from "react";
import SVGActionCreditCardOff_20_outlined from '../../svg/action/ActionCreditCardOff/20_outlined.svg';
import SVGActionCreditCardOff_24_outlined from '../../svg/action/ActionCreditCardOff/24_outlined.svg';
import SVGActionCreditCardOff_20_twotone from '../../svg/action/ActionCreditCardOff/20_twotone.svg';
import SVGActionCreditCardOff_24_twotone from '../../svg/action/ActionCreditCardOff/24_twotone.svg';
import SVGActionCreditCardOff_20_sharp from '../../svg/action/ActionCreditCardOff/20_sharp.svg';
import SVGActionCreditCardOff_24_sharp from '../../svg/action/ActionCreditCardOff/24_sharp.svg';
import SVGActionCreditCardOff_20_filled from '../../svg/action/ActionCreditCardOff/20_filled.svg';
import SVGActionCreditCardOff_24_filled from '../../svg/action/ActionCreditCardOff/24_filled.svg';
import SVGActionCreditCardOff_20_round from '../../svg/action/ActionCreditCardOff/20_round.svg';
import SVGActionCreditCardOff_24_round from '../../svg/action/ActionCreditCardOff/24_round.svg';

export const IconActionCreditCardOff20outlined = () => <SVGActionCreditCardOff_20_outlined />;
export const IconActionCreditCardOff24outlined = () => <SVGActionCreditCardOff_24_outlined />;
export const IconActionCreditCardOff20twotone = () => <SVGActionCreditCardOff_20_twotone />;
export const IconActionCreditCardOff24twotone = () => <SVGActionCreditCardOff_24_twotone />;
export const IconActionCreditCardOff20sharp = () => <SVGActionCreditCardOff_20_sharp />;
export const IconActionCreditCardOff24sharp = () => <SVGActionCreditCardOff_24_sharp />;
export const IconActionCreditCardOff20filled = () => <SVGActionCreditCardOff_20_filled />;
export const IconActionCreditCardOff24filled = () => <SVGActionCreditCardOff_24_filled />;
export const IconActionCreditCardOff20round = () => <SVGActionCreditCardOff_20_round />;
export const IconActionCreditCardOff24round = () => <SVGActionCreditCardOff_24_round />;
