import React from "react";
import SVGActionGifBox_20_outlined from '../../svg/action/ActionGifBox/20_outlined.svg';
import SVGActionGifBox_24_outlined from '../../svg/action/ActionGifBox/24_outlined.svg';
import SVGActionGifBox_20_twotone from '../../svg/action/ActionGifBox/20_twotone.svg';
import SVGActionGifBox_24_twotone from '../../svg/action/ActionGifBox/24_twotone.svg';
import SVGActionGifBox_20_sharp from '../../svg/action/ActionGifBox/20_sharp.svg';
import SVGActionGifBox_24_sharp from '../../svg/action/ActionGifBox/24_sharp.svg';
import SVGActionGifBox_20_filled from '../../svg/action/ActionGifBox/20_filled.svg';
import SVGActionGifBox_24_filled from '../../svg/action/ActionGifBox/24_filled.svg';
import SVGActionGifBox_20_round from '../../svg/action/ActionGifBox/20_round.svg';
import SVGActionGifBox_24_round from '../../svg/action/ActionGifBox/24_round.svg';

export const IconActionGifBox20outlined = () => <SVGActionGifBox_20_outlined />;
export const IconActionGifBox24outlined = () => <SVGActionGifBox_24_outlined />;
export const IconActionGifBox20twotone = () => <SVGActionGifBox_20_twotone />;
export const IconActionGifBox24twotone = () => <SVGActionGifBox_24_twotone />;
export const IconActionGifBox20sharp = () => <SVGActionGifBox_20_sharp />;
export const IconActionGifBox24sharp = () => <SVGActionGifBox_24_sharp />;
export const IconActionGifBox20filled = () => <SVGActionGifBox_20_filled />;
export const IconActionGifBox24filled = () => <SVGActionGifBox_24_filled />;
export const IconActionGifBox20round = () => <SVGActionGifBox_20_round />;
export const IconActionGifBox24round = () => <SVGActionGifBox_24_round />;
