import React from "react";
import SVGActionViewSidebar_20_outlined from '../../svg/action/ActionViewSidebar/20_outlined.svg';
import SVGActionViewSidebar_24_outlined from '../../svg/action/ActionViewSidebar/24_outlined.svg';
import SVGActionViewSidebar_20_twotone from '../../svg/action/ActionViewSidebar/20_twotone.svg';
import SVGActionViewSidebar_24_twotone from '../../svg/action/ActionViewSidebar/24_twotone.svg';
import SVGActionViewSidebar_20_sharp from '../../svg/action/ActionViewSidebar/20_sharp.svg';
import SVGActionViewSidebar_24_sharp from '../../svg/action/ActionViewSidebar/24_sharp.svg';
import SVGActionViewSidebar_20_filled from '../../svg/action/ActionViewSidebar/20_filled.svg';
import SVGActionViewSidebar_24_filled from '../../svg/action/ActionViewSidebar/24_filled.svg';
import SVGActionViewSidebar_20_round from '../../svg/action/ActionViewSidebar/20_round.svg';
import SVGActionViewSidebar_24_round from '../../svg/action/ActionViewSidebar/24_round.svg';

export const IconActionViewSidebar20outlined = () => <SVGActionViewSidebar_20_outlined />;
export const IconActionViewSidebar24outlined = () => <SVGActionViewSidebar_24_outlined />;
export const IconActionViewSidebar20twotone = () => <SVGActionViewSidebar_20_twotone />;
export const IconActionViewSidebar24twotone = () => <SVGActionViewSidebar_24_twotone />;
export const IconActionViewSidebar20sharp = () => <SVGActionViewSidebar_20_sharp />;
export const IconActionViewSidebar24sharp = () => <SVGActionViewSidebar_24_sharp />;
export const IconActionViewSidebar20filled = () => <SVGActionViewSidebar_20_filled />;
export const IconActionViewSidebar24filled = () => <SVGActionViewSidebar_24_filled />;
export const IconActionViewSidebar20round = () => <SVGActionViewSidebar_20_round />;
export const IconActionViewSidebar24round = () => <SVGActionViewSidebar_24_round />;
