import React from "react";
import SVGActionSyncAlt_20_outlined from '../../svg/action/ActionSyncAlt/20_outlined.svg';
import SVGActionSyncAlt_24_outlined from '../../svg/action/ActionSyncAlt/24_outlined.svg';
import SVGActionSyncAlt_20_twotone from '../../svg/action/ActionSyncAlt/20_twotone.svg';
import SVGActionSyncAlt_24_twotone from '../../svg/action/ActionSyncAlt/24_twotone.svg';
import SVGActionSyncAlt_20_sharp from '../../svg/action/ActionSyncAlt/20_sharp.svg';
import SVGActionSyncAlt_24_sharp from '../../svg/action/ActionSyncAlt/24_sharp.svg';
import SVGActionSyncAlt_20_filled from '../../svg/action/ActionSyncAlt/20_filled.svg';
import SVGActionSyncAlt_24_filled from '../../svg/action/ActionSyncAlt/24_filled.svg';
import SVGActionSyncAlt_20_round from '../../svg/action/ActionSyncAlt/20_round.svg';
import SVGActionSyncAlt_24_round from '../../svg/action/ActionSyncAlt/24_round.svg';

export const IconActionSyncAlt20outlined = () => <SVGActionSyncAlt_20_outlined />;
export const IconActionSyncAlt24outlined = () => <SVGActionSyncAlt_24_outlined />;
export const IconActionSyncAlt20twotone = () => <SVGActionSyncAlt_20_twotone />;
export const IconActionSyncAlt24twotone = () => <SVGActionSyncAlt_24_twotone />;
export const IconActionSyncAlt20sharp = () => <SVGActionSyncAlt_20_sharp />;
export const IconActionSyncAlt24sharp = () => <SVGActionSyncAlt_24_sharp />;
export const IconActionSyncAlt20filled = () => <SVGActionSyncAlt_20_filled />;
export const IconActionSyncAlt24filled = () => <SVGActionSyncAlt_24_filled />;
export const IconActionSyncAlt20round = () => <SVGActionSyncAlt_20_round />;
export const IconActionSyncAlt24round = () => <SVGActionSyncAlt_24_round />;
