import React from "react";
import SVGActionLockReset_20_outlined from '../../svg/action/ActionLockReset/20_outlined.svg';
import SVGActionLockReset_24_outlined from '../../svg/action/ActionLockReset/24_outlined.svg';
import SVGActionLockReset_20_twotone from '../../svg/action/ActionLockReset/20_twotone.svg';
import SVGActionLockReset_24_twotone from '../../svg/action/ActionLockReset/24_twotone.svg';
import SVGActionLockReset_20_sharp from '../../svg/action/ActionLockReset/20_sharp.svg';
import SVGActionLockReset_24_sharp from '../../svg/action/ActionLockReset/24_sharp.svg';
import SVGActionLockReset_20_filled from '../../svg/action/ActionLockReset/20_filled.svg';
import SVGActionLockReset_24_filled from '../../svg/action/ActionLockReset/24_filled.svg';
import SVGActionLockReset_20_round from '../../svg/action/ActionLockReset/20_round.svg';
import SVGActionLockReset_24_round from '../../svg/action/ActionLockReset/24_round.svg';

export const IconActionLockReset20outlined = () => <SVGActionLockReset_20_outlined />;
export const IconActionLockReset24outlined = () => <SVGActionLockReset_24_outlined />;
export const IconActionLockReset20twotone = () => <SVGActionLockReset_20_twotone />;
export const IconActionLockReset24twotone = () => <SVGActionLockReset_24_twotone />;
export const IconActionLockReset20sharp = () => <SVGActionLockReset_20_sharp />;
export const IconActionLockReset24sharp = () => <SVGActionLockReset_24_sharp />;
export const IconActionLockReset20filled = () => <SVGActionLockReset_20_filled />;
export const IconActionLockReset24filled = () => <SVGActionLockReset_24_filled />;
export const IconActionLockReset20round = () => <SVGActionLockReset_20_round />;
export const IconActionLockReset24round = () => <SVGActionLockReset_24_round />;
