import React from "react";
import SVGActionHlsOff_20_outlined from '../../svg/action/ActionHlsOff/20_outlined.svg';
import SVGActionHlsOff_24_outlined from '../../svg/action/ActionHlsOff/24_outlined.svg';
import SVGActionHlsOff_20_twotone from '../../svg/action/ActionHlsOff/20_twotone.svg';
import SVGActionHlsOff_24_twotone from '../../svg/action/ActionHlsOff/24_twotone.svg';
import SVGActionHlsOff_20_sharp from '../../svg/action/ActionHlsOff/20_sharp.svg';
import SVGActionHlsOff_24_sharp from '../../svg/action/ActionHlsOff/24_sharp.svg';
import SVGActionHlsOff_20_filled from '../../svg/action/ActionHlsOff/20_filled.svg';
import SVGActionHlsOff_24_filled from '../../svg/action/ActionHlsOff/24_filled.svg';
import SVGActionHlsOff_20_round from '../../svg/action/ActionHlsOff/20_round.svg';
import SVGActionHlsOff_24_round from '../../svg/action/ActionHlsOff/24_round.svg';

export const IconActionHlsOff20outlined = () => <SVGActionHlsOff_20_outlined />;
export const IconActionHlsOff24outlined = () => <SVGActionHlsOff_24_outlined />;
export const IconActionHlsOff20twotone = () => <SVGActionHlsOff_20_twotone />;
export const IconActionHlsOff24twotone = () => <SVGActionHlsOff_24_twotone />;
export const IconActionHlsOff20sharp = () => <SVGActionHlsOff_20_sharp />;
export const IconActionHlsOff24sharp = () => <SVGActionHlsOff_24_sharp />;
export const IconActionHlsOff20filled = () => <SVGActionHlsOff_20_filled />;
export const IconActionHlsOff24filled = () => <SVGActionHlsOff_24_filled />;
export const IconActionHlsOff20round = () => <SVGActionHlsOff_20_round />;
export const IconActionHlsOff24round = () => <SVGActionHlsOff_24_round />;
