import React from "react";
import SVGActionCss_20_outlined from '../../svg/action/ActionCss/20_outlined.svg';
import SVGActionCss_24_outlined from '../../svg/action/ActionCss/24_outlined.svg';
import SVGActionCss_20_twotone from '../../svg/action/ActionCss/20_twotone.svg';
import SVGActionCss_24_twotone from '../../svg/action/ActionCss/24_twotone.svg';
import SVGActionCss_20_sharp from '../../svg/action/ActionCss/20_sharp.svg';
import SVGActionCss_24_sharp from '../../svg/action/ActionCss/24_sharp.svg';
import SVGActionCss_20_filled from '../../svg/action/ActionCss/20_filled.svg';
import SVGActionCss_24_filled from '../../svg/action/ActionCss/24_filled.svg';
import SVGActionCss_20_round from '../../svg/action/ActionCss/20_round.svg';
import SVGActionCss_24_round from '../../svg/action/ActionCss/24_round.svg';

export const IconActionCss20outlined = () => <SVGActionCss_20_outlined />;
export const IconActionCss24outlined = () => <SVGActionCss_24_outlined />;
export const IconActionCss20twotone = () => <SVGActionCss_20_twotone />;
export const IconActionCss24twotone = () => <SVGActionCss_24_twotone />;
export const IconActionCss20sharp = () => <SVGActionCss_20_sharp />;
export const IconActionCss24sharp = () => <SVGActionCss_24_sharp />;
export const IconActionCss20filled = () => <SVGActionCss_20_filled />;
export const IconActionCss24filled = () => <SVGActionCss_24_filled />;
export const IconActionCss20round = () => <SVGActionCss_20_round />;
export const IconActionCss24round = () => <SVGActionCss_24_round />;
