import React from "react";
import SVGActionSwipeRightAlt_20_outlined from '../../svg/action/ActionSwipeRightAlt/20_outlined.svg';
import SVGActionSwipeRightAlt_24_outlined from '../../svg/action/ActionSwipeRightAlt/24_outlined.svg';
import SVGActionSwipeRightAlt_20_twotone from '../../svg/action/ActionSwipeRightAlt/20_twotone.svg';
import SVGActionSwipeRightAlt_24_twotone from '../../svg/action/ActionSwipeRightAlt/24_twotone.svg';
import SVGActionSwipeRightAlt_20_sharp from '../../svg/action/ActionSwipeRightAlt/20_sharp.svg';
import SVGActionSwipeRightAlt_24_sharp from '../../svg/action/ActionSwipeRightAlt/24_sharp.svg';
import SVGActionSwipeRightAlt_20_filled from '../../svg/action/ActionSwipeRightAlt/20_filled.svg';
import SVGActionSwipeRightAlt_24_filled from '../../svg/action/ActionSwipeRightAlt/24_filled.svg';
import SVGActionSwipeRightAlt_20_round from '../../svg/action/ActionSwipeRightAlt/20_round.svg';
import SVGActionSwipeRightAlt_24_round from '../../svg/action/ActionSwipeRightAlt/24_round.svg';

export const IconActionSwipeRightAlt20outlined = () => <SVGActionSwipeRightAlt_20_outlined />;
export const IconActionSwipeRightAlt24outlined = () => <SVGActionSwipeRightAlt_24_outlined />;
export const IconActionSwipeRightAlt20twotone = () => <SVGActionSwipeRightAlt_20_twotone />;
export const IconActionSwipeRightAlt24twotone = () => <SVGActionSwipeRightAlt_24_twotone />;
export const IconActionSwipeRightAlt20sharp = () => <SVGActionSwipeRightAlt_20_sharp />;
export const IconActionSwipeRightAlt24sharp = () => <SVGActionSwipeRightAlt_24_sharp />;
export const IconActionSwipeRightAlt20filled = () => <SVGActionSwipeRightAlt_20_filled />;
export const IconActionSwipeRightAlt24filled = () => <SVGActionSwipeRightAlt_24_filled />;
export const IconActionSwipeRightAlt20round = () => <SVGActionSwipeRightAlt_20_round />;
export const IconActionSwipeRightAlt24round = () => <SVGActionSwipeRightAlt_24_round />;
