import React from "react";
import SVGActionLightbulbCircle_20_outlined from '../../svg/action/ActionLightbulbCircle/20_outlined.svg';
import SVGActionLightbulbCircle_24_outlined from '../../svg/action/ActionLightbulbCircle/24_outlined.svg';
import SVGActionLightbulbCircle_20_twotone from '../../svg/action/ActionLightbulbCircle/20_twotone.svg';
import SVGActionLightbulbCircle_24_twotone from '../../svg/action/ActionLightbulbCircle/24_twotone.svg';
import SVGActionLightbulbCircle_20_sharp from '../../svg/action/ActionLightbulbCircle/20_sharp.svg';
import SVGActionLightbulbCircle_24_sharp from '../../svg/action/ActionLightbulbCircle/24_sharp.svg';
import SVGActionLightbulbCircle_20_filled from '../../svg/action/ActionLightbulbCircle/20_filled.svg';
import SVGActionLightbulbCircle_24_filled from '../../svg/action/ActionLightbulbCircle/24_filled.svg';
import SVGActionLightbulbCircle_20_round from '../../svg/action/ActionLightbulbCircle/20_round.svg';
import SVGActionLightbulbCircle_24_round from '../../svg/action/ActionLightbulbCircle/24_round.svg';

export const IconActionLightbulbCircle20outlined = () => <SVGActionLightbulbCircle_20_outlined />;
export const IconActionLightbulbCircle24outlined = () => <SVGActionLightbulbCircle_24_outlined />;
export const IconActionLightbulbCircle20twotone = () => <SVGActionLightbulbCircle_20_twotone />;
export const IconActionLightbulbCircle24twotone = () => <SVGActionLightbulbCircle_24_twotone />;
export const IconActionLightbulbCircle20sharp = () => <SVGActionLightbulbCircle_20_sharp />;
export const IconActionLightbulbCircle24sharp = () => <SVGActionLightbulbCircle_24_sharp />;
export const IconActionLightbulbCircle20filled = () => <SVGActionLightbulbCircle_20_filled />;
export const IconActionLightbulbCircle24filled = () => <SVGActionLightbulbCircle_24_filled />;
export const IconActionLightbulbCircle20round = () => <SVGActionLightbulbCircle_20_round />;
export const IconActionLightbulbCircle24round = () => <SVGActionLightbulbCircle_24_round />;
