import React from "react";
import SVGActionHistoryToggleOff_20_outlined from '../../svg/action/ActionHistoryToggleOff/20_outlined.svg';
import SVGActionHistoryToggleOff_24_outlined from '../../svg/action/ActionHistoryToggleOff/24_outlined.svg';
import SVGActionHistoryToggleOff_20_twotone from '../../svg/action/ActionHistoryToggleOff/20_twotone.svg';
import SVGActionHistoryToggleOff_24_twotone from '../../svg/action/ActionHistoryToggleOff/24_twotone.svg';
import SVGActionHistoryToggleOff_20_sharp from '../../svg/action/ActionHistoryToggleOff/20_sharp.svg';
import SVGActionHistoryToggleOff_24_sharp from '../../svg/action/ActionHistoryToggleOff/24_sharp.svg';
import SVGActionHistoryToggleOff_20_filled from '../../svg/action/ActionHistoryToggleOff/20_filled.svg';
import SVGActionHistoryToggleOff_24_filled from '../../svg/action/ActionHistoryToggleOff/24_filled.svg';
import SVGActionHistoryToggleOff_20_round from '../../svg/action/ActionHistoryToggleOff/20_round.svg';
import SVGActionHistoryToggleOff_24_round from '../../svg/action/ActionHistoryToggleOff/24_round.svg';

export const IconActionHistoryToggleOff20outlined = () => <SVGActionHistoryToggleOff_20_outlined />;
export const IconActionHistoryToggleOff24outlined = () => <SVGActionHistoryToggleOff_24_outlined />;
export const IconActionHistoryToggleOff20twotone = () => <SVGActionHistoryToggleOff_20_twotone />;
export const IconActionHistoryToggleOff24twotone = () => <SVGActionHistoryToggleOff_24_twotone />;
export const IconActionHistoryToggleOff20sharp = () => <SVGActionHistoryToggleOff_20_sharp />;
export const IconActionHistoryToggleOff24sharp = () => <SVGActionHistoryToggleOff_24_sharp />;
export const IconActionHistoryToggleOff20filled = () => <SVGActionHistoryToggleOff_20_filled />;
export const IconActionHistoryToggleOff24filled = () => <SVGActionHistoryToggleOff_24_filled />;
export const IconActionHistoryToggleOff20round = () => <SVGActionHistoryToggleOff_20_round />;
export const IconActionHistoryToggleOff24round = () => <SVGActionHistoryToggleOff_24_round />;
