import React from "react";
import SVGActionEditCalendar_20_outlined from '../../svg/action/ActionEditCalendar/20_outlined.svg';
import SVGActionEditCalendar_24_outlined from '../../svg/action/ActionEditCalendar/24_outlined.svg';
import SVGActionEditCalendar_20_twotone from '../../svg/action/ActionEditCalendar/20_twotone.svg';
import SVGActionEditCalendar_24_twotone from '../../svg/action/ActionEditCalendar/24_twotone.svg';
import SVGActionEditCalendar_20_sharp from '../../svg/action/ActionEditCalendar/20_sharp.svg';
import SVGActionEditCalendar_24_sharp from '../../svg/action/ActionEditCalendar/24_sharp.svg';
import SVGActionEditCalendar_20_filled from '../../svg/action/ActionEditCalendar/20_filled.svg';
import SVGActionEditCalendar_24_filled from '../../svg/action/ActionEditCalendar/24_filled.svg';
import SVGActionEditCalendar_20_round from '../../svg/action/ActionEditCalendar/20_round.svg';
import SVGActionEditCalendar_24_round from '../../svg/action/ActionEditCalendar/24_round.svg';

export const IconActionEditCalendar20outlined = () => <SVGActionEditCalendar_20_outlined />;
export const IconActionEditCalendar24outlined = () => <SVGActionEditCalendar_24_outlined />;
export const IconActionEditCalendar20twotone = () => <SVGActionEditCalendar_20_twotone />;
export const IconActionEditCalendar24twotone = () => <SVGActionEditCalendar_24_twotone />;
export const IconActionEditCalendar20sharp = () => <SVGActionEditCalendar_20_sharp />;
export const IconActionEditCalendar24sharp = () => <SVGActionEditCalendar_24_sharp />;
export const IconActionEditCalendar20filled = () => <SVGActionEditCalendar_20_filled />;
export const IconActionEditCalendar24filled = () => <SVGActionEditCalendar_24_filled />;
export const IconActionEditCalendar20round = () => <SVGActionEditCalendar_20_round />;
export const IconActionEditCalendar24round = () => <SVGActionEditCalendar_24_round />;
