import React from "react";
import SVGActionCurrencyExchange_20_outlined from '../../svg/action/ActionCurrencyExchange/20_outlined.svg';
import SVGActionCurrencyExchange_24_outlined from '../../svg/action/ActionCurrencyExchange/24_outlined.svg';
import SVGActionCurrencyExchange_20_twotone from '../../svg/action/ActionCurrencyExchange/20_twotone.svg';
import SVGActionCurrencyExchange_24_twotone from '../../svg/action/ActionCurrencyExchange/24_twotone.svg';
import SVGActionCurrencyExchange_20_sharp from '../../svg/action/ActionCurrencyExchange/20_sharp.svg';
import SVGActionCurrencyExchange_24_sharp from '../../svg/action/ActionCurrencyExchange/24_sharp.svg';
import SVGActionCurrencyExchange_20_filled from '../../svg/action/ActionCurrencyExchange/20_filled.svg';
import SVGActionCurrencyExchange_24_filled from '../../svg/action/ActionCurrencyExchange/24_filled.svg';
import SVGActionCurrencyExchange_20_round from '../../svg/action/ActionCurrencyExchange/20_round.svg';
import SVGActionCurrencyExchange_24_round from '../../svg/action/ActionCurrencyExchange/24_round.svg';

export const IconActionCurrencyExchange20outlined = () => <SVGActionCurrencyExchange_20_outlined />;
export const IconActionCurrencyExchange24outlined = () => <SVGActionCurrencyExchange_24_outlined />;
export const IconActionCurrencyExchange20twotone = () => <SVGActionCurrencyExchange_20_twotone />;
export const IconActionCurrencyExchange24twotone = () => <SVGActionCurrencyExchange_24_twotone />;
export const IconActionCurrencyExchange20sharp = () => <SVGActionCurrencyExchange_20_sharp />;
export const IconActionCurrencyExchange24sharp = () => <SVGActionCurrencyExchange_24_sharp />;
export const IconActionCurrencyExchange20filled = () => <SVGActionCurrencyExchange_20_filled />;
export const IconActionCurrencyExchange24filled = () => <SVGActionCurrencyExchange_24_filled />;
export const IconActionCurrencyExchange20round = () => <SVGActionCurrencyExchange_20_round />;
export const IconActionCurrencyExchange24round = () => <SVGActionCurrencyExchange_24_round />;
