import React from "react";
import SVGActionPending_20_outlined from '../../svg/action/ActionPending/20_outlined.svg';
import SVGActionPending_24_outlined from '../../svg/action/ActionPending/24_outlined.svg';
import SVGActionPending_20_twotone from '../../svg/action/ActionPending/20_twotone.svg';
import SVGActionPending_24_twotone from '../../svg/action/ActionPending/24_twotone.svg';
import SVGActionPending_20_sharp from '../../svg/action/ActionPending/20_sharp.svg';
import SVGActionPending_24_sharp from '../../svg/action/ActionPending/24_sharp.svg';
import SVGActionPending_20_filled from '../../svg/action/ActionPending/20_filled.svg';
import SVGActionPending_24_filled from '../../svg/action/ActionPending/24_filled.svg';
import SVGActionPending_20_round from '../../svg/action/ActionPending/20_round.svg';
import SVGActionPending_24_round from '../../svg/action/ActionPending/24_round.svg';

export const IconActionPending20outlined = () => <SVGActionPending_20_outlined />;
export const IconActionPending24outlined = () => <SVGActionPending_24_outlined />;
export const IconActionPending20twotone = () => <SVGActionPending_20_twotone />;
export const IconActionPending24twotone = () => <SVGActionPending_24_twotone />;
export const IconActionPending20sharp = () => <SVGActionPending_20_sharp />;
export const IconActionPending24sharp = () => <SVGActionPending_24_sharp />;
export const IconActionPending20filled = () => <SVGActionPending_20_filled />;
export const IconActionPending24filled = () => <SVGActionPending_24_filled />;
export const IconActionPending20round = () => <SVGActionPending_20_round />;
export const IconActionPending24round = () => <SVGActionPending_24_round />;
