import React from "react";
import SVGActionLogin_20_outlined from '../../svg/action/ActionLogin/20_outlined.svg';
import SVGActionLogin_24_outlined from '../../svg/action/ActionLogin/24_outlined.svg';
import SVGActionLogin_20_twotone from '../../svg/action/ActionLogin/20_twotone.svg';
import SVGActionLogin_24_twotone from '../../svg/action/ActionLogin/24_twotone.svg';
import SVGActionLogin_20_sharp from '../../svg/action/ActionLogin/20_sharp.svg';
import SVGActionLogin_24_sharp from '../../svg/action/ActionLogin/24_sharp.svg';
import SVGActionLogin_20_filled from '../../svg/action/ActionLogin/20_filled.svg';
import SVGActionLogin_24_filled from '../../svg/action/ActionLogin/24_filled.svg';
import SVGActionLogin_20_round from '../../svg/action/ActionLogin/20_round.svg';
import SVGActionLogin_24_round from '../../svg/action/ActionLogin/24_round.svg';

export const IconActionLogin20outlined = () => <SVGActionLogin_20_outlined />;
export const IconActionLogin24outlined = () => <SVGActionLogin_24_outlined />;
export const IconActionLogin20twotone = () => <SVGActionLogin_20_twotone />;
export const IconActionLogin24twotone = () => <SVGActionLogin_24_twotone />;
export const IconActionLogin20sharp = () => <SVGActionLogin_20_sharp />;
export const IconActionLogin24sharp = () => <SVGActionLogin_24_sharp />;
export const IconActionLogin20filled = () => <SVGActionLogin_20_filled />;
export const IconActionLogin24filled = () => <SVGActionLogin_24_filled />;
export const IconActionLogin20round = () => <SVGActionLogin_20_round />;
export const IconActionLogin24round = () => <SVGActionLogin_24_round />;
