import React from "react";
import SVGActionAddHome_20_outlined from '../../svg/action/ActionAddHome/20_outlined.svg';
import SVGActionAddHome_24_outlined from '../../svg/action/ActionAddHome/24_outlined.svg';
import SVGActionAddHome_20_twotone from '../../svg/action/ActionAddHome/20_twotone.svg';
import SVGActionAddHome_24_twotone from '../../svg/action/ActionAddHome/24_twotone.svg';
import SVGActionAddHome_20_sharp from '../../svg/action/ActionAddHome/20_sharp.svg';
import SVGActionAddHome_24_sharp from '../../svg/action/ActionAddHome/24_sharp.svg';
import SVGActionAddHome_20_filled from '../../svg/action/ActionAddHome/20_filled.svg';
import SVGActionAddHome_24_filled from '../../svg/action/ActionAddHome/24_filled.svg';
import SVGActionAddHome_20_round from '../../svg/action/ActionAddHome/20_round.svg';
import SVGActionAddHome_24_round from '../../svg/action/ActionAddHome/24_round.svg';

export const IconActionAddHome20outlined = () => <SVGActionAddHome_20_outlined />;
export const IconActionAddHome24outlined = () => <SVGActionAddHome_24_outlined />;
export const IconActionAddHome20twotone = () => <SVGActionAddHome_20_twotone />;
export const IconActionAddHome24twotone = () => <SVGActionAddHome_24_twotone />;
export const IconActionAddHome20sharp = () => <SVGActionAddHome_20_sharp />;
export const IconActionAddHome24sharp = () => <SVGActionAddHome_24_sharp />;
export const IconActionAddHome20filled = () => <SVGActionAddHome_20_filled />;
export const IconActionAddHome24filled = () => <SVGActionAddHome_24_filled />;
export const IconActionAddHome20round = () => <SVGActionAddHome_20_round />;
export const IconActionAddHome24round = () => <SVGActionAddHome_24_round />;
