import React from "react";
import SVGActionQuickreply_20_outlined from '../../svg/action/ActionQuickreply/20_outlined.svg';
import SVGActionQuickreply_24_outlined from '../../svg/action/ActionQuickreply/24_outlined.svg';
import SVGActionQuickreply_20_twotone from '../../svg/action/ActionQuickreply/20_twotone.svg';
import SVGActionQuickreply_24_twotone from '../../svg/action/ActionQuickreply/24_twotone.svg';
import SVGActionQuickreply_20_sharp from '../../svg/action/ActionQuickreply/20_sharp.svg';
import SVGActionQuickreply_24_sharp from '../../svg/action/ActionQuickreply/24_sharp.svg';
import SVGActionQuickreply_20_filled from '../../svg/action/ActionQuickreply/20_filled.svg';
import SVGActionQuickreply_24_filled from '../../svg/action/ActionQuickreply/24_filled.svg';
import SVGActionQuickreply_20_round from '../../svg/action/ActionQuickreply/20_round.svg';
import SVGActionQuickreply_24_round from '../../svg/action/ActionQuickreply/24_round.svg';

export const IconActionQuickreply20outlined = () => <SVGActionQuickreply_20_outlined />;
export const IconActionQuickreply24outlined = () => <SVGActionQuickreply_24_outlined />;
export const IconActionQuickreply20twotone = () => <SVGActionQuickreply_20_twotone />;
export const IconActionQuickreply24twotone = () => <SVGActionQuickreply_24_twotone />;
export const IconActionQuickreply20sharp = () => <SVGActionQuickreply_20_sharp />;
export const IconActionQuickreply24sharp = () => <SVGActionQuickreply_24_sharp />;
export const IconActionQuickreply20filled = () => <SVGActionQuickreply_20_filled />;
export const IconActionQuickreply24filled = () => <SVGActionQuickreply_24_filled />;
export const IconActionQuickreply20round = () => <SVGActionQuickreply_20_round />;
export const IconActionQuickreply24round = () => <SVGActionQuickreply_24_round />;
