import React from "react";
import SVGActionContactless_20_outlined from '../../svg/action/ActionContactless/20_outlined.svg';
import SVGActionContactless_24_outlined from '../../svg/action/ActionContactless/24_outlined.svg';
import SVGActionContactless_20_twotone from '../../svg/action/ActionContactless/20_twotone.svg';
import SVGActionContactless_24_twotone from '../../svg/action/ActionContactless/24_twotone.svg';
import SVGActionContactless_20_sharp from '../../svg/action/ActionContactless/20_sharp.svg';
import SVGActionContactless_24_sharp from '../../svg/action/ActionContactless/24_sharp.svg';
import SVGActionContactless_20_filled from '../../svg/action/ActionContactless/20_filled.svg';
import SVGActionContactless_24_filled from '../../svg/action/ActionContactless/24_filled.svg';
import SVGActionContactless_20_round from '../../svg/action/ActionContactless/20_round.svg';
import SVGActionContactless_24_round from '../../svg/action/ActionContactless/24_round.svg';

export const IconActionContactless20outlined = () => <SVGActionContactless_20_outlined />;
export const IconActionContactless24outlined = () => <SVGActionContactless_24_outlined />;
export const IconActionContactless20twotone = () => <SVGActionContactless_20_twotone />;
export const IconActionContactless24twotone = () => <SVGActionContactless_24_twotone />;
export const IconActionContactless20sharp = () => <SVGActionContactless_20_sharp />;
export const IconActionContactless24sharp = () => <SVGActionContactless_24_sharp />;
export const IconActionContactless20filled = () => <SVGActionContactless_20_filled />;
export const IconActionContactless24filled = () => <SVGActionContactless_24_filled />;
export const IconActionContactless20round = () => <SVGActionContactless_20_round />;
export const IconActionContactless24round = () => <SVGActionContactless_24_round />;
