import React from "react";
import SVGActionCancelScheduleSend_20_outlined from '../../svg/action/ActionCancelScheduleSend/20_outlined.svg';
import SVGActionCancelScheduleSend_24_outlined from '../../svg/action/ActionCancelScheduleSend/24_outlined.svg';
import SVGActionCancelScheduleSend_20_twotone from '../../svg/action/ActionCancelScheduleSend/20_twotone.svg';
import SVGActionCancelScheduleSend_24_twotone from '../../svg/action/ActionCancelScheduleSend/24_twotone.svg';
import SVGActionCancelScheduleSend_20_sharp from '../../svg/action/ActionCancelScheduleSend/20_sharp.svg';
import SVGActionCancelScheduleSend_24_sharp from '../../svg/action/ActionCancelScheduleSend/24_sharp.svg';
import SVGActionCancelScheduleSend_20_filled from '../../svg/action/ActionCancelScheduleSend/20_filled.svg';
import SVGActionCancelScheduleSend_24_filled from '../../svg/action/ActionCancelScheduleSend/24_filled.svg';
import SVGActionCancelScheduleSend_20_round from '../../svg/action/ActionCancelScheduleSend/20_round.svg';
import SVGActionCancelScheduleSend_24_round from '../../svg/action/ActionCancelScheduleSend/24_round.svg';

export const IconActionCancelScheduleSend20outlined = () => <SVGActionCancelScheduleSend_20_outlined />;
export const IconActionCancelScheduleSend24outlined = () => <SVGActionCancelScheduleSend_24_outlined />;
export const IconActionCancelScheduleSend20twotone = () => <SVGActionCancelScheduleSend_20_twotone />;
export const IconActionCancelScheduleSend24twotone = () => <SVGActionCancelScheduleSend_24_twotone />;
export const IconActionCancelScheduleSend20sharp = () => <SVGActionCancelScheduleSend_20_sharp />;
export const IconActionCancelScheduleSend24sharp = () => <SVGActionCancelScheduleSend_24_sharp />;
export const IconActionCancelScheduleSend20filled = () => <SVGActionCancelScheduleSend_20_filled />;
export const IconActionCancelScheduleSend24filled = () => <SVGActionCancelScheduleSend_24_filled />;
export const IconActionCancelScheduleSend20round = () => <SVGActionCancelScheduleSend_20_round />;
export const IconActionCancelScheduleSend24round = () => <SVGActionCancelScheduleSend_24_round />;
