import React from "react";
import SVGActionSatelliteAlt_20_outlined from '../../svg/action/ActionSatelliteAlt/20_outlined.svg';
import SVGActionSatelliteAlt_24_outlined from '../../svg/action/ActionSatelliteAlt/24_outlined.svg';
import SVGActionSatelliteAlt_20_twotone from '../../svg/action/ActionSatelliteAlt/20_twotone.svg';
import SVGActionSatelliteAlt_24_twotone from '../../svg/action/ActionSatelliteAlt/24_twotone.svg';
import SVGActionSatelliteAlt_20_sharp from '../../svg/action/ActionSatelliteAlt/20_sharp.svg';
import SVGActionSatelliteAlt_24_sharp from '../../svg/action/ActionSatelliteAlt/24_sharp.svg';
import SVGActionSatelliteAlt_20_filled from '../../svg/action/ActionSatelliteAlt/20_filled.svg';
import SVGActionSatelliteAlt_24_filled from '../../svg/action/ActionSatelliteAlt/24_filled.svg';
import SVGActionSatelliteAlt_20_round from '../../svg/action/ActionSatelliteAlt/20_round.svg';
import SVGActionSatelliteAlt_24_round from '../../svg/action/ActionSatelliteAlt/24_round.svg';

export const IconActionSatelliteAlt20outlined = () => <SVGActionSatelliteAlt_20_outlined />;
export const IconActionSatelliteAlt24outlined = () => <SVGActionSatelliteAlt_24_outlined />;
export const IconActionSatelliteAlt20twotone = () => <SVGActionSatelliteAlt_20_twotone />;
export const IconActionSatelliteAlt24twotone = () => <SVGActionSatelliteAlt_24_twotone />;
export const IconActionSatelliteAlt20sharp = () => <SVGActionSatelliteAlt_20_sharp />;
export const IconActionSatelliteAlt24sharp = () => <SVGActionSatelliteAlt_24_sharp />;
export const IconActionSatelliteAlt20filled = () => <SVGActionSatelliteAlt_20_filled />;
export const IconActionSatelliteAlt24filled = () => <SVGActionSatelliteAlt_24_filled />;
export const IconActionSatelliteAlt20round = () => <SVGActionSatelliteAlt_20_round />;
export const IconActionSatelliteAlt24round = () => <SVGActionSatelliteAlt_24_round />;
