import React from "react";
import SVGActionArrowCircleDown_20_outlined from '../../svg/action/ActionArrowCircleDown/20_outlined.svg';
import SVGActionArrowCircleDown_24_outlined from '../../svg/action/ActionArrowCircleDown/24_outlined.svg';
import SVGActionArrowCircleDown_20_twotone from '../../svg/action/ActionArrowCircleDown/20_twotone.svg';
import SVGActionArrowCircleDown_24_twotone from '../../svg/action/ActionArrowCircleDown/24_twotone.svg';
import SVGActionArrowCircleDown_20_sharp from '../../svg/action/ActionArrowCircleDown/20_sharp.svg';
import SVGActionArrowCircleDown_24_sharp from '../../svg/action/ActionArrowCircleDown/24_sharp.svg';
import SVGActionArrowCircleDown_20_filled from '../../svg/action/ActionArrowCircleDown/20_filled.svg';
import SVGActionArrowCircleDown_24_filled from '../../svg/action/ActionArrowCircleDown/24_filled.svg';
import SVGActionArrowCircleDown_20_round from '../../svg/action/ActionArrowCircleDown/20_round.svg';
import SVGActionArrowCircleDown_24_round from '../../svg/action/ActionArrowCircleDown/24_round.svg';

export const IconActionArrowCircleDown20outlined = () => <SVGActionArrowCircleDown_20_outlined />;
export const IconActionArrowCircleDown24outlined = () => <SVGActionArrowCircleDown_24_outlined />;
export const IconActionArrowCircleDown20twotone = () => <SVGActionArrowCircleDown_20_twotone />;
export const IconActionArrowCircleDown24twotone = () => <SVGActionArrowCircleDown_24_twotone />;
export const IconActionArrowCircleDown20sharp = () => <SVGActionArrowCircleDown_20_sharp />;
export const IconActionArrowCircleDown24sharp = () => <SVGActionArrowCircleDown_24_sharp />;
export const IconActionArrowCircleDown20filled = () => <SVGActionArrowCircleDown_20_filled />;
export const IconActionArrowCircleDown24filled = () => <SVGActionArrowCircleDown_24_filled />;
export const IconActionArrowCircleDown20round = () => <SVGActionArrowCircleDown_20_round />;
export const IconActionArrowCircleDown24round = () => <SVGActionArrowCircleDown_24_round />;
