import React from "react";
import SVGActionSavings_20_outlined from '../../svg/action/ActionSavings/20_outlined.svg';
import SVGActionSavings_24_outlined from '../../svg/action/ActionSavings/24_outlined.svg';
import SVGActionSavings_20_twotone from '../../svg/action/ActionSavings/20_twotone.svg';
import SVGActionSavings_24_twotone from '../../svg/action/ActionSavings/24_twotone.svg';
import SVGActionSavings_20_sharp from '../../svg/action/ActionSavings/20_sharp.svg';
import SVGActionSavings_24_sharp from '../../svg/action/ActionSavings/24_sharp.svg';
import SVGActionSavings_20_filled from '../../svg/action/ActionSavings/20_filled.svg';
import SVGActionSavings_24_filled from '../../svg/action/ActionSavings/24_filled.svg';
import SVGActionSavings_20_round from '../../svg/action/ActionSavings/20_round.svg';
import SVGActionSavings_24_round from '../../svg/action/ActionSavings/24_round.svg';

export const IconActionSavings20outlined = () => <SVGActionSavings_20_outlined />;
export const IconActionSavings24outlined = () => <SVGActionSavings_24_outlined />;
export const IconActionSavings20twotone = () => <SVGActionSavings_20_twotone />;
export const IconActionSavings24twotone = () => <SVGActionSavings_24_twotone />;
export const IconActionSavings20sharp = () => <SVGActionSavings_20_sharp />;
export const IconActionSavings24sharp = () => <SVGActionSavings_24_sharp />;
export const IconActionSavings20filled = () => <SVGActionSavings_20_filled />;
export const IconActionSavings24filled = () => <SVGActionSavings_24_filled />;
export const IconActionSavings20round = () => <SVGActionSavings_20_round />;
export const IconActionSavings24round = () => <SVGActionSavings_24_round />;
