import React from "react";
import SVGActionCommentBank_20_outlined from '../../svg/action/ActionCommentBank/20_outlined.svg';
import SVGActionCommentBank_24_outlined from '../../svg/action/ActionCommentBank/24_outlined.svg';
import SVGActionCommentBank_20_twotone from '../../svg/action/ActionCommentBank/20_twotone.svg';
import SVGActionCommentBank_24_twotone from '../../svg/action/ActionCommentBank/24_twotone.svg';
import SVGActionCommentBank_20_sharp from '../../svg/action/ActionCommentBank/20_sharp.svg';
import SVGActionCommentBank_24_sharp from '../../svg/action/ActionCommentBank/24_sharp.svg';
import SVGActionCommentBank_20_filled from '../../svg/action/ActionCommentBank/20_filled.svg';
import SVGActionCommentBank_24_filled from '../../svg/action/ActionCommentBank/24_filled.svg';
import SVGActionCommentBank_20_round from '../../svg/action/ActionCommentBank/20_round.svg';
import SVGActionCommentBank_24_round from '../../svg/action/ActionCommentBank/24_round.svg';

export const IconActionCommentBank20outlined = () => <SVGActionCommentBank_20_outlined />;
export const IconActionCommentBank24outlined = () => <SVGActionCommentBank_24_outlined />;
export const IconActionCommentBank20twotone = () => <SVGActionCommentBank_20_twotone />;
export const IconActionCommentBank24twotone = () => <SVGActionCommentBank_24_twotone />;
export const IconActionCommentBank20sharp = () => <SVGActionCommentBank_20_sharp />;
export const IconActionCommentBank24sharp = () => <SVGActionCommentBank_24_sharp />;
export const IconActionCommentBank20filled = () => <SVGActionCommentBank_20_filled />;
export const IconActionCommentBank24filled = () => <SVGActionCommentBank_24_filled />;
export const IconActionCommentBank20round = () => <SVGActionCommentBank_20_round />;
export const IconActionCommentBank24round = () => <SVGActionCommentBank_24_round />;
