import React from "react";
import SVGActionMarkAsUnread_20_outlined from '../../svg/action/ActionMarkAsUnread/20_outlined.svg';
import SVGActionMarkAsUnread_24_outlined from '../../svg/action/ActionMarkAsUnread/24_outlined.svg';
import SVGActionMarkAsUnread_20_twotone from '../../svg/action/ActionMarkAsUnread/20_twotone.svg';
import SVGActionMarkAsUnread_24_twotone from '../../svg/action/ActionMarkAsUnread/24_twotone.svg';
import SVGActionMarkAsUnread_20_sharp from '../../svg/action/ActionMarkAsUnread/20_sharp.svg';
import SVGActionMarkAsUnread_24_sharp from '../../svg/action/ActionMarkAsUnread/24_sharp.svg';
import SVGActionMarkAsUnread_20_filled from '../../svg/action/ActionMarkAsUnread/20_filled.svg';
import SVGActionMarkAsUnread_24_filled from '../../svg/action/ActionMarkAsUnread/24_filled.svg';
import SVGActionMarkAsUnread_20_round from '../../svg/action/ActionMarkAsUnread/20_round.svg';
import SVGActionMarkAsUnread_24_round from '../../svg/action/ActionMarkAsUnread/24_round.svg';

export const IconActionMarkAsUnread20outlined = () => <SVGActionMarkAsUnread_20_outlined />;
export const IconActionMarkAsUnread24outlined = () => <SVGActionMarkAsUnread_24_outlined />;
export const IconActionMarkAsUnread20twotone = () => <SVGActionMarkAsUnread_20_twotone />;
export const IconActionMarkAsUnread24twotone = () => <SVGActionMarkAsUnread_24_twotone />;
export const IconActionMarkAsUnread20sharp = () => <SVGActionMarkAsUnread_20_sharp />;
export const IconActionMarkAsUnread24sharp = () => <SVGActionMarkAsUnread_24_sharp />;
export const IconActionMarkAsUnread20filled = () => <SVGActionMarkAsUnread_20_filled />;
export const IconActionMarkAsUnread24filled = () => <SVGActionMarkAsUnread_24_filled />;
export const IconActionMarkAsUnread20round = () => <SVGActionMarkAsUnread_20_round />;
export const IconActionMarkAsUnread24round = () => <SVGActionMarkAsUnread_24_round />;
