import React from "react";
import SVGActionWidthNormal_20_outlined from '../../svg/action/ActionWidthNormal/20_outlined.svg';
import SVGActionWidthNormal_24_outlined from '../../svg/action/ActionWidthNormal/24_outlined.svg';
import SVGActionWidthNormal_20_twotone from '../../svg/action/ActionWidthNormal/20_twotone.svg';
import SVGActionWidthNormal_24_twotone from '../../svg/action/ActionWidthNormal/24_twotone.svg';
import SVGActionWidthNormal_20_sharp from '../../svg/action/ActionWidthNormal/20_sharp.svg';
import SVGActionWidthNormal_24_sharp from '../../svg/action/ActionWidthNormal/24_sharp.svg';
import SVGActionWidthNormal_20_filled from '../../svg/action/ActionWidthNormal/20_filled.svg';
import SVGActionWidthNormal_24_filled from '../../svg/action/ActionWidthNormal/24_filled.svg';
import SVGActionWidthNormal_20_round from '../../svg/action/ActionWidthNormal/20_round.svg';
import SVGActionWidthNormal_24_round from '../../svg/action/ActionWidthNormal/24_round.svg';

export const IconActionWidthNormal20outlined = () => <SVGActionWidthNormal_20_outlined />;
export const IconActionWidthNormal24outlined = () => <SVGActionWidthNormal_24_outlined />;
export const IconActionWidthNormal20twotone = () => <SVGActionWidthNormal_20_twotone />;
export const IconActionWidthNormal24twotone = () => <SVGActionWidthNormal_24_twotone />;
export const IconActionWidthNormal20sharp = () => <SVGActionWidthNormal_20_sharp />;
export const IconActionWidthNormal24sharp = () => <SVGActionWidthNormal_24_sharp />;
export const IconActionWidthNormal20filled = () => <SVGActionWidthNormal_20_filled />;
export const IconActionWidthNormal24filled = () => <SVGActionWidthNormal_24_filled />;
export const IconActionWidthNormal20round = () => <SVGActionWidthNormal_20_round />;
export const IconActionWidthNormal24round = () => <SVGActionWidthNormal_24_round />;
