import React from "react";
import SVGActionPinch_20_outlined from '../../svg/action/ActionPinch/20_outlined.svg';
import SVGActionPinch_24_outlined from '../../svg/action/ActionPinch/24_outlined.svg';
import SVGActionPinch_20_twotone from '../../svg/action/ActionPinch/20_twotone.svg';
import SVGActionPinch_24_twotone from '../../svg/action/ActionPinch/24_twotone.svg';
import SVGActionPinch_20_sharp from '../../svg/action/ActionPinch/20_sharp.svg';
import SVGActionPinch_24_sharp from '../../svg/action/ActionPinch/24_sharp.svg';
import SVGActionPinch_20_filled from '../../svg/action/ActionPinch/20_filled.svg';
import SVGActionPinch_24_filled from '../../svg/action/ActionPinch/24_filled.svg';
import SVGActionPinch_20_round from '../../svg/action/ActionPinch/20_round.svg';
import SVGActionPinch_24_round from '../../svg/action/ActionPinch/24_round.svg';

export const IconActionPinch20outlined = () => <SVGActionPinch_20_outlined />;
export const IconActionPinch24outlined = () => <SVGActionPinch_24_outlined />;
export const IconActionPinch20twotone = () => <SVGActionPinch_20_twotone />;
export const IconActionPinch24twotone = () => <SVGActionPinch_24_twotone />;
export const IconActionPinch20sharp = () => <SVGActionPinch_20_sharp />;
export const IconActionPinch24sharp = () => <SVGActionPinch_24_sharp />;
export const IconActionPinch20filled = () => <SVGActionPinch_20_filled />;
export const IconActionPinch24filled = () => <SVGActionPinch_24_filled />;
export const IconActionPinch20round = () => <SVGActionPinch_20_round />;
export const IconActionPinch24round = () => <SVGActionPinch_24_round />;
