import React from "react";
import SVGActionDensityMedium_20_outlined from '../../svg/action/ActionDensityMedium/20_outlined.svg';
import SVGActionDensityMedium_24_outlined from '../../svg/action/ActionDensityMedium/24_outlined.svg';
import SVGActionDensityMedium_20_twotone from '../../svg/action/ActionDensityMedium/20_twotone.svg';
import SVGActionDensityMedium_24_twotone from '../../svg/action/ActionDensityMedium/24_twotone.svg';
import SVGActionDensityMedium_20_sharp from '../../svg/action/ActionDensityMedium/20_sharp.svg';
import SVGActionDensityMedium_24_sharp from '../../svg/action/ActionDensityMedium/24_sharp.svg';
import SVGActionDensityMedium_20_filled from '../../svg/action/ActionDensityMedium/20_filled.svg';
import SVGActionDensityMedium_24_filled from '../../svg/action/ActionDensityMedium/24_filled.svg';
import SVGActionDensityMedium_20_round from '../../svg/action/ActionDensityMedium/20_round.svg';
import SVGActionDensityMedium_24_round from '../../svg/action/ActionDensityMedium/24_round.svg';

export const IconActionDensityMedium20outlined = () => <SVGActionDensityMedium_20_outlined />;
export const IconActionDensityMedium24outlined = () => <SVGActionDensityMedium_24_outlined />;
export const IconActionDensityMedium20twotone = () => <SVGActionDensityMedium_20_twotone />;
export const IconActionDensityMedium24twotone = () => <SVGActionDensityMedium_24_twotone />;
export const IconActionDensityMedium20sharp = () => <SVGActionDensityMedium_20_sharp />;
export const IconActionDensityMedium24sharp = () => <SVGActionDensityMedium_24_sharp />;
export const IconActionDensityMedium20filled = () => <SVGActionDensityMedium_20_filled />;
export const IconActionDensityMedium24filled = () => <SVGActionDensityMedium_24_filled />;
export const IconActionDensityMedium20round = () => <SVGActionDensityMedium_20_round />;
export const IconActionDensityMedium24round = () => <SVGActionDensityMedium_24_round />;
