import React from "react";
import SVGActionViewCarousel_20_outlined from '../../svg/action/ActionViewCarousel/20_outlined.svg';
import SVGActionViewCarousel_24_outlined from '../../svg/action/ActionViewCarousel/24_outlined.svg';
import SVGActionViewCarousel_20_twotone from '../../svg/action/ActionViewCarousel/20_twotone.svg';
import SVGActionViewCarousel_24_twotone from '../../svg/action/ActionViewCarousel/24_twotone.svg';
import SVGActionViewCarousel_20_sharp from '../../svg/action/ActionViewCarousel/20_sharp.svg';
import SVGActionViewCarousel_24_sharp from '../../svg/action/ActionViewCarousel/24_sharp.svg';
import SVGActionViewCarousel_20_filled from '../../svg/action/ActionViewCarousel/20_filled.svg';
import SVGActionViewCarousel_24_filled from '../../svg/action/ActionViewCarousel/24_filled.svg';
import SVGActionViewCarousel_20_round from '../../svg/action/ActionViewCarousel/20_round.svg';
import SVGActionViewCarousel_24_round from '../../svg/action/ActionViewCarousel/24_round.svg';

export const IconActionViewCarousel20outlined = () => <SVGActionViewCarousel_20_outlined />;
export const IconActionViewCarousel24outlined = () => <SVGActionViewCarousel_24_outlined />;
export const IconActionViewCarousel20twotone = () => <SVGActionViewCarousel_20_twotone />;
export const IconActionViewCarousel24twotone = () => <SVGActionViewCarousel_24_twotone />;
export const IconActionViewCarousel20sharp = () => <SVGActionViewCarousel_20_sharp />;
export const IconActionViewCarousel24sharp = () => <SVGActionViewCarousel_24_sharp />;
export const IconActionViewCarousel20filled = () => <SVGActionViewCarousel_20_filled />;
export const IconActionViewCarousel24filled = () => <SVGActionViewCarousel_24_filled />;
export const IconActionViewCarousel20round = () => <SVGActionViewCarousel_20_round />;
export const IconActionViewCarousel24round = () => <SVGActionViewCarousel_24_round />;
