import React from "react";
import SVGActionSpaceDashboard_20_outlined from '../../svg/action/ActionSpaceDashboard/20_outlined.svg';
import SVGActionSpaceDashboard_24_outlined from '../../svg/action/ActionSpaceDashboard/24_outlined.svg';
import SVGActionSpaceDashboard_20_twotone from '../../svg/action/ActionSpaceDashboard/20_twotone.svg';
import SVGActionSpaceDashboard_24_twotone from '../../svg/action/ActionSpaceDashboard/24_twotone.svg';
import SVGActionSpaceDashboard_20_sharp from '../../svg/action/ActionSpaceDashboard/20_sharp.svg';
import SVGActionSpaceDashboard_24_sharp from '../../svg/action/ActionSpaceDashboard/24_sharp.svg';
import SVGActionSpaceDashboard_20_filled from '../../svg/action/ActionSpaceDashboard/20_filled.svg';
import SVGActionSpaceDashboard_24_filled from '../../svg/action/ActionSpaceDashboard/24_filled.svg';
import SVGActionSpaceDashboard_20_round from '../../svg/action/ActionSpaceDashboard/20_round.svg';
import SVGActionSpaceDashboard_24_round from '../../svg/action/ActionSpaceDashboard/24_round.svg';

export const IconActionSpaceDashboard20outlined = () => <SVGActionSpaceDashboard_20_outlined />;
export const IconActionSpaceDashboard24outlined = () => <SVGActionSpaceDashboard_24_outlined />;
export const IconActionSpaceDashboard20twotone = () => <SVGActionSpaceDashboard_20_twotone />;
export const IconActionSpaceDashboard24twotone = () => <SVGActionSpaceDashboard_24_twotone />;
export const IconActionSpaceDashboard20sharp = () => <SVGActionSpaceDashboard_20_sharp />;
export const IconActionSpaceDashboard24sharp = () => <SVGActionSpaceDashboard_24_sharp />;
export const IconActionSpaceDashboard20filled = () => <SVGActionSpaceDashboard_20_filled />;
export const IconActionSpaceDashboard24filled = () => <SVGActionSpaceDashboard_24_filled />;
export const IconActionSpaceDashboard20round = () => <SVGActionSpaceDashboard_20_round />;
export const IconActionSpaceDashboard24round = () => <SVGActionSpaceDashboard_24_round />;
