import React from "react";
import SVGActionJoinInner_20_outlined from '../../svg/action/ActionJoinInner/20_outlined.svg';
import SVGActionJoinInner_24_outlined from '../../svg/action/ActionJoinInner/24_outlined.svg';
import SVGActionJoinInner_20_twotone from '../../svg/action/ActionJoinInner/20_twotone.svg';
import SVGActionJoinInner_24_twotone from '../../svg/action/ActionJoinInner/24_twotone.svg';
import SVGActionJoinInner_20_sharp from '../../svg/action/ActionJoinInner/20_sharp.svg';
import SVGActionJoinInner_24_sharp from '../../svg/action/ActionJoinInner/24_sharp.svg';
import SVGActionJoinInner_20_filled from '../../svg/action/ActionJoinInner/20_filled.svg';
import SVGActionJoinInner_24_filled from '../../svg/action/ActionJoinInner/24_filled.svg';
import SVGActionJoinInner_20_round from '../../svg/action/ActionJoinInner/20_round.svg';
import SVGActionJoinInner_24_round from '../../svg/action/ActionJoinInner/24_round.svg';

export const IconActionJoinInner20outlined = () => <SVGActionJoinInner_20_outlined />;
export const IconActionJoinInner24outlined = () => <SVGActionJoinInner_24_outlined />;
export const IconActionJoinInner20twotone = () => <SVGActionJoinInner_20_twotone />;
export const IconActionJoinInner24twotone = () => <SVGActionJoinInner_24_twotone />;
export const IconActionJoinInner20sharp = () => <SVGActionJoinInner_20_sharp />;
export const IconActionJoinInner24sharp = () => <SVGActionJoinInner_24_sharp />;
export const IconActionJoinInner20filled = () => <SVGActionJoinInner_20_filled />;
export const IconActionJoinInner24filled = () => <SVGActionJoinInner_24_filled />;
export const IconActionJoinInner20round = () => <SVGActionJoinInner_20_round />;
export const IconActionJoinInner24round = () => <SVGActionJoinInner_24_round />;
