import React from "react";
import SVGActionEventRepeat_20_outlined from '../../svg/action/ActionEventRepeat/20_outlined.svg';
import SVGActionEventRepeat_24_outlined from '../../svg/action/ActionEventRepeat/24_outlined.svg';
import SVGActionEventRepeat_20_twotone from '../../svg/action/ActionEventRepeat/20_twotone.svg';
import SVGActionEventRepeat_24_twotone from '../../svg/action/ActionEventRepeat/24_twotone.svg';
import SVGActionEventRepeat_20_sharp from '../../svg/action/ActionEventRepeat/20_sharp.svg';
import SVGActionEventRepeat_24_sharp from '../../svg/action/ActionEventRepeat/24_sharp.svg';
import SVGActionEventRepeat_20_filled from '../../svg/action/ActionEventRepeat/20_filled.svg';
import SVGActionEventRepeat_24_filled from '../../svg/action/ActionEventRepeat/24_filled.svg';
import SVGActionEventRepeat_20_round from '../../svg/action/ActionEventRepeat/20_round.svg';
import SVGActionEventRepeat_24_round from '../../svg/action/ActionEventRepeat/24_round.svg';

export const IconActionEventRepeat20outlined = () => <SVGActionEventRepeat_20_outlined />;
export const IconActionEventRepeat24outlined = () => <SVGActionEventRepeat_24_outlined />;
export const IconActionEventRepeat20twotone = () => <SVGActionEventRepeat_20_twotone />;
export const IconActionEventRepeat24twotone = () => <SVGActionEventRepeat_24_twotone />;
export const IconActionEventRepeat20sharp = () => <SVGActionEventRepeat_20_sharp />;
export const IconActionEventRepeat24sharp = () => <SVGActionEventRepeat_24_sharp />;
export const IconActionEventRepeat20filled = () => <SVGActionEventRepeat_20_filled />;
export const IconActionEventRepeat24filled = () => <SVGActionEventRepeat_24_filled />;
export const IconActionEventRepeat20round = () => <SVGActionEventRepeat_20_round />;
export const IconActionEventRepeat24round = () => <SVGActionEventRepeat_24_round />;
