import React from "react";
import SVGActionViewComfyAlt_20_outlined from '../../svg/action/ActionViewComfyAlt/20_outlined.svg';
import SVGActionViewComfyAlt_24_outlined from '../../svg/action/ActionViewComfyAlt/24_outlined.svg';
import SVGActionViewComfyAlt_20_twotone from '../../svg/action/ActionViewComfyAlt/20_twotone.svg';
import SVGActionViewComfyAlt_24_twotone from '../../svg/action/ActionViewComfyAlt/24_twotone.svg';
import SVGActionViewComfyAlt_20_sharp from '../../svg/action/ActionViewComfyAlt/20_sharp.svg';
import SVGActionViewComfyAlt_24_sharp from '../../svg/action/ActionViewComfyAlt/24_sharp.svg';
import SVGActionViewComfyAlt_20_filled from '../../svg/action/ActionViewComfyAlt/20_filled.svg';
import SVGActionViewComfyAlt_24_filled from '../../svg/action/ActionViewComfyAlt/24_filled.svg';
import SVGActionViewComfyAlt_20_round from '../../svg/action/ActionViewComfyAlt/20_round.svg';
import SVGActionViewComfyAlt_24_round from '../../svg/action/ActionViewComfyAlt/24_round.svg';

export const IconActionViewComfyAlt20outlined = () => <SVGActionViewComfyAlt_20_outlined />;
export const IconActionViewComfyAlt24outlined = () => <SVGActionViewComfyAlt_24_outlined />;
export const IconActionViewComfyAlt20twotone = () => <SVGActionViewComfyAlt_20_twotone />;
export const IconActionViewComfyAlt24twotone = () => <SVGActionViewComfyAlt_24_twotone />;
export const IconActionViewComfyAlt20sharp = () => <SVGActionViewComfyAlt_20_sharp />;
export const IconActionViewComfyAlt24sharp = () => <SVGActionViewComfyAlt_24_sharp />;
export const IconActionViewComfyAlt20filled = () => <SVGActionViewComfyAlt_20_filled />;
export const IconActionViewComfyAlt24filled = () => <SVGActionViewComfyAlt_24_filled />;
export const IconActionViewComfyAlt20round = () => <SVGActionViewComfyAlt_20_round />;
export const IconActionViewComfyAlt24round = () => <SVGActionViewComfyAlt_24_round />;
