import React from "react";
import SVGActionSwipeVertical_20_outlined from '../../svg/action/ActionSwipeVertical/20_outlined.svg';
import SVGActionSwipeVertical_24_outlined from '../../svg/action/ActionSwipeVertical/24_outlined.svg';
import SVGActionSwipeVertical_20_twotone from '../../svg/action/ActionSwipeVertical/20_twotone.svg';
import SVGActionSwipeVertical_24_twotone from '../../svg/action/ActionSwipeVertical/24_twotone.svg';
import SVGActionSwipeVertical_20_sharp from '../../svg/action/ActionSwipeVertical/20_sharp.svg';
import SVGActionSwipeVertical_24_sharp from '../../svg/action/ActionSwipeVertical/24_sharp.svg';
import SVGActionSwipeVertical_20_filled from '../../svg/action/ActionSwipeVertical/20_filled.svg';
import SVGActionSwipeVertical_24_filled from '../../svg/action/ActionSwipeVertical/24_filled.svg';
import SVGActionSwipeVertical_20_round from '../../svg/action/ActionSwipeVertical/20_round.svg';
import SVGActionSwipeVertical_24_round from '../../svg/action/ActionSwipeVertical/24_round.svg';

export const IconActionSwipeVertical20outlined = () => <SVGActionSwipeVertical_20_outlined />;
export const IconActionSwipeVertical24outlined = () => <SVGActionSwipeVertical_24_outlined />;
export const IconActionSwipeVertical20twotone = () => <SVGActionSwipeVertical_20_twotone />;
export const IconActionSwipeVertical24twotone = () => <SVGActionSwipeVertical_24_twotone />;
export const IconActionSwipeVertical20sharp = () => <SVGActionSwipeVertical_20_sharp />;
export const IconActionSwipeVertical24sharp = () => <SVGActionSwipeVertical_24_sharp />;
export const IconActionSwipeVertical20filled = () => <SVGActionSwipeVertical_20_filled />;
export const IconActionSwipeVertical24filled = () => <SVGActionSwipeVertical_24_filled />;
export const IconActionSwipeVertical20round = () => <SVGActionSwipeVertical_20_round />;
export const IconActionSwipeVertical24round = () => <SVGActionSwipeVertical_24_round />;
