import React from "react";
import SVGActionSwipeDownAlt_20_outlined from '../../svg/action/ActionSwipeDownAlt/20_outlined.svg';
import SVGActionSwipeDownAlt_24_outlined from '../../svg/action/ActionSwipeDownAlt/24_outlined.svg';
import SVGActionSwipeDownAlt_20_twotone from '../../svg/action/ActionSwipeDownAlt/20_twotone.svg';
import SVGActionSwipeDownAlt_24_twotone from '../../svg/action/ActionSwipeDownAlt/24_twotone.svg';
import SVGActionSwipeDownAlt_20_sharp from '../../svg/action/ActionSwipeDownAlt/20_sharp.svg';
import SVGActionSwipeDownAlt_24_sharp from '../../svg/action/ActionSwipeDownAlt/24_sharp.svg';
import SVGActionSwipeDownAlt_20_filled from '../../svg/action/ActionSwipeDownAlt/20_filled.svg';
import SVGActionSwipeDownAlt_24_filled from '../../svg/action/ActionSwipeDownAlt/24_filled.svg';
import SVGActionSwipeDownAlt_20_round from '../../svg/action/ActionSwipeDownAlt/20_round.svg';
import SVGActionSwipeDownAlt_24_round from '../../svg/action/ActionSwipeDownAlt/24_round.svg';

export const IconActionSwipeDownAlt20outlined = () => <SVGActionSwipeDownAlt_20_outlined />;
export const IconActionSwipeDownAlt24outlined = () => <SVGActionSwipeDownAlt_24_outlined />;
export const IconActionSwipeDownAlt20twotone = () => <SVGActionSwipeDownAlt_20_twotone />;
export const IconActionSwipeDownAlt24twotone = () => <SVGActionSwipeDownAlt_24_twotone />;
export const IconActionSwipeDownAlt20sharp = () => <SVGActionSwipeDownAlt_20_sharp />;
export const IconActionSwipeDownAlt24sharp = () => <SVGActionSwipeDownAlt_24_sharp />;
export const IconActionSwipeDownAlt20filled = () => <SVGActionSwipeDownAlt_20_filled />;
export const IconActionSwipeDownAlt24filled = () => <SVGActionSwipeDownAlt_24_filled />;
export const IconActionSwipeDownAlt20round = () => <SVGActionSwipeDownAlt_20_round />;
export const IconActionSwipeDownAlt24round = () => <SVGActionSwipeDownAlt_24_round />;
