import React from "react";
import SVGActionGeneratingTokens_20_outlined from '../../svg/action/ActionGeneratingTokens/20_outlined.svg';
import SVGActionGeneratingTokens_24_outlined from '../../svg/action/ActionGeneratingTokens/24_outlined.svg';
import SVGActionGeneratingTokens_20_twotone from '../../svg/action/ActionGeneratingTokens/20_twotone.svg';
import SVGActionGeneratingTokens_24_twotone from '../../svg/action/ActionGeneratingTokens/24_twotone.svg';
import SVGActionGeneratingTokens_20_sharp from '../../svg/action/ActionGeneratingTokens/20_sharp.svg';
import SVGActionGeneratingTokens_24_sharp from '../../svg/action/ActionGeneratingTokens/24_sharp.svg';
import SVGActionGeneratingTokens_20_filled from '../../svg/action/ActionGeneratingTokens/20_filled.svg';
import SVGActionGeneratingTokens_24_filled from '../../svg/action/ActionGeneratingTokens/24_filled.svg';
import SVGActionGeneratingTokens_20_round from '../../svg/action/ActionGeneratingTokens/20_round.svg';
import SVGActionGeneratingTokens_24_round from '../../svg/action/ActionGeneratingTokens/24_round.svg';

export const IconActionGeneratingTokens20outlined = () => <SVGActionGeneratingTokens_20_outlined />;
export const IconActionGeneratingTokens24outlined = () => <SVGActionGeneratingTokens_24_outlined />;
export const IconActionGeneratingTokens20twotone = () => <SVGActionGeneratingTokens_20_twotone />;
export const IconActionGeneratingTokens24twotone = () => <SVGActionGeneratingTokens_24_twotone />;
export const IconActionGeneratingTokens20sharp = () => <SVGActionGeneratingTokens_20_sharp />;
export const IconActionGeneratingTokens24sharp = () => <SVGActionGeneratingTokens_24_sharp />;
export const IconActionGeneratingTokens20filled = () => <SVGActionGeneratingTokens_20_filled />;
export const IconActionGeneratingTokens24filled = () => <SVGActionGeneratingTokens_24_filled />;
export const IconActionGeneratingTokens20round = () => <SVGActionGeneratingTokens_20_round />;
export const IconActionGeneratingTokens24round = () => <SVGActionGeneratingTokens_24_round />;
