import React from "react";
import SVGActionGrading_20_outlined from '../../svg/action/ActionGrading/20_outlined.svg';
import SVGActionGrading_24_outlined from '../../svg/action/ActionGrading/24_outlined.svg';
import SVGActionGrading_20_twotone from '../../svg/action/ActionGrading/20_twotone.svg';
import SVGActionGrading_24_twotone from '../../svg/action/ActionGrading/24_twotone.svg';
import SVGActionGrading_20_sharp from '../../svg/action/ActionGrading/20_sharp.svg';
import SVGActionGrading_24_sharp from '../../svg/action/ActionGrading/24_sharp.svg';
import SVGActionGrading_20_filled from '../../svg/action/ActionGrading/20_filled.svg';
import SVGActionGrading_24_filled from '../../svg/action/ActionGrading/24_filled.svg';
import SVGActionGrading_20_round from '../../svg/action/ActionGrading/20_round.svg';
import SVGActionGrading_24_round from '../../svg/action/ActionGrading/24_round.svg';

export const IconActionGrading20outlined = () => <SVGActionGrading_20_outlined />;
export const IconActionGrading24outlined = () => <SVGActionGrading_24_outlined />;
export const IconActionGrading20twotone = () => <SVGActionGrading_20_twotone />;
export const IconActionGrading24twotone = () => <SVGActionGrading_24_twotone />;
export const IconActionGrading20sharp = () => <SVGActionGrading_20_sharp />;
export const IconActionGrading24sharp = () => <SVGActionGrading_24_sharp />;
export const IconActionGrading20filled = () => <SVGActionGrading_20_filled />;
export const IconActionGrading24filled = () => <SVGActionGrading_24_filled />;
export const IconActionGrading20round = () => <SVGActionGrading_20_round />;
export const IconActionGrading24round = () => <SVGActionGrading_24_round />;
