import React from "react";
import SVGActionBalance_20_outlined from '../../svg/action/ActionBalance/20_outlined.svg';
import SVGActionBalance_24_outlined from '../../svg/action/ActionBalance/24_outlined.svg';
import SVGActionBalance_20_twotone from '../../svg/action/ActionBalance/20_twotone.svg';
import SVGActionBalance_24_twotone from '../../svg/action/ActionBalance/24_twotone.svg';
import SVGActionBalance_20_sharp from '../../svg/action/ActionBalance/20_sharp.svg';
import SVGActionBalance_24_sharp from '../../svg/action/ActionBalance/24_sharp.svg';
import SVGActionBalance_20_filled from '../../svg/action/ActionBalance/20_filled.svg';
import SVGActionBalance_24_filled from '../../svg/action/ActionBalance/24_filled.svg';
import SVGActionBalance_20_round from '../../svg/action/ActionBalance/20_round.svg';
import SVGActionBalance_24_round from '../../svg/action/ActionBalance/24_round.svg';

export const IconActionBalance20outlined = () => <SVGActionBalance_20_outlined />;
export const IconActionBalance24outlined = () => <SVGActionBalance_24_outlined />;
export const IconActionBalance20twotone = () => <SVGActionBalance_20_twotone />;
export const IconActionBalance24twotone = () => <SVGActionBalance_24_twotone />;
export const IconActionBalance20sharp = () => <SVGActionBalance_20_sharp />;
export const IconActionBalance24sharp = () => <SVGActionBalance_24_sharp />;
export const IconActionBalance20filled = () => <SVGActionBalance_20_filled />;
export const IconActionBalance24filled = () => <SVGActionBalance_24_filled />;
export const IconActionBalance20round = () => <SVGActionBalance_20_round />;
export const IconActionBalance24round = () => <SVGActionBalance_24_round />;
