import React from "react";
import SVGActionAssuredWorkload_20_outlined from '../../svg/action/ActionAssuredWorkload/20_outlined.svg';
import SVGActionAssuredWorkload_24_outlined from '../../svg/action/ActionAssuredWorkload/24_outlined.svg';
import SVGActionAssuredWorkload_20_twotone from '../../svg/action/ActionAssuredWorkload/20_twotone.svg';
import SVGActionAssuredWorkload_24_twotone from '../../svg/action/ActionAssuredWorkload/24_twotone.svg';
import SVGActionAssuredWorkload_20_sharp from '../../svg/action/ActionAssuredWorkload/20_sharp.svg';
import SVGActionAssuredWorkload_24_sharp from '../../svg/action/ActionAssuredWorkload/24_sharp.svg';
import SVGActionAssuredWorkload_20_filled from '../../svg/action/ActionAssuredWorkload/20_filled.svg';
import SVGActionAssuredWorkload_24_filled from '../../svg/action/ActionAssuredWorkload/24_filled.svg';
import SVGActionAssuredWorkload_20_round from '../../svg/action/ActionAssuredWorkload/20_round.svg';
import SVGActionAssuredWorkload_24_round from '../../svg/action/ActionAssuredWorkload/24_round.svg';

export const IconActionAssuredWorkload20outlined = () => <SVGActionAssuredWorkload_20_outlined />;
export const IconActionAssuredWorkload24outlined = () => <SVGActionAssuredWorkload_24_outlined />;
export const IconActionAssuredWorkload20twotone = () => <SVGActionAssuredWorkload_20_twotone />;
export const IconActionAssuredWorkload24twotone = () => <SVGActionAssuredWorkload_24_twotone />;
export const IconActionAssuredWorkload20sharp = () => <SVGActionAssuredWorkload_20_sharp />;
export const IconActionAssuredWorkload24sharp = () => <SVGActionAssuredWorkload_24_sharp />;
export const IconActionAssuredWorkload20filled = () => <SVGActionAssuredWorkload_20_filled />;
export const IconActionAssuredWorkload24filled = () => <SVGActionAssuredWorkload_24_filled />;
export const IconActionAssuredWorkload20round = () => <SVGActionAssuredWorkload_20_round />;
export const IconActionAssuredWorkload24round = () => <SVGActionAssuredWorkload_24_round />;
