import React from "react";
import SVGSocialPsychology_20_outlined from '../../svg/social/SocialPsychology/20_outlined.svg';
import SVGSocialPsychology_24_outlined from '../../svg/social/SocialPsychology/24_outlined.svg';
import SVGSocialPsychology_20_twotone from '../../svg/social/SocialPsychology/20_twotone.svg';
import SVGSocialPsychology_24_twotone from '../../svg/social/SocialPsychology/24_twotone.svg';
import SVGSocialPsychology_20_sharp from '../../svg/social/SocialPsychology/20_sharp.svg';
import SVGSocialPsychology_24_sharp from '../../svg/social/SocialPsychology/24_sharp.svg';
import SVGSocialPsychology_20_filled from '../../svg/social/SocialPsychology/20_filled.svg';
import SVGSocialPsychology_24_filled from '../../svg/social/SocialPsychology/24_filled.svg';
import SVGSocialPsychology_20_round from '../../svg/social/SocialPsychology/20_round.svg';
import SVGSocialPsychology_24_round from '../../svg/social/SocialPsychology/24_round.svg';

export const IconSocialPsychology20outlined = () => <SVGSocialPsychology_20_outlined />;
export const IconSocialPsychology24outlined = () => <SVGSocialPsychology_24_outlined />;
export const IconSocialPsychology20twotone = () => <SVGSocialPsychology_20_twotone />;
export const IconSocialPsychology24twotone = () => <SVGSocialPsychology_24_twotone />;
export const IconSocialPsychology20sharp = () => <SVGSocialPsychology_20_sharp />;
export const IconSocialPsychology24sharp = () => <SVGSocialPsychology_24_sharp />;
export const IconSocialPsychology20filled = () => <SVGSocialPsychology_20_filled />;
export const IconSocialPsychology24filled = () => <SVGSocialPsychology_24_filled />;
export const IconSocialPsychology20round = () => <SVGSocialPsychology_20_round />;
export const IconSocialPsychology24round = () => <SVGSocialPsychology_24_round />;
