import React from "react";
import SVGSocialFireplace_20_outlined from '../../svg/social/SocialFireplace/20_outlined.svg';
import SVGSocialFireplace_24_outlined from '../../svg/social/SocialFireplace/24_outlined.svg';
import SVGSocialFireplace_20_twotone from '../../svg/social/SocialFireplace/20_twotone.svg';
import SVGSocialFireplace_24_twotone from '../../svg/social/SocialFireplace/24_twotone.svg';
import SVGSocialFireplace_20_sharp from '../../svg/social/SocialFireplace/20_sharp.svg';
import SVGSocialFireplace_24_sharp from '../../svg/social/SocialFireplace/24_sharp.svg';
import SVGSocialFireplace_20_filled from '../../svg/social/SocialFireplace/20_filled.svg';
import SVGSocialFireplace_24_filled from '../../svg/social/SocialFireplace/24_filled.svg';
import SVGSocialFireplace_20_round from '../../svg/social/SocialFireplace/20_round.svg';
import SVGSocialFireplace_24_round from '../../svg/social/SocialFireplace/24_round.svg';

export const IconSocialFireplace20outlined = () => <SVGSocialFireplace_20_outlined />;
export const IconSocialFireplace24outlined = () => <SVGSocialFireplace_24_outlined />;
export const IconSocialFireplace20twotone = () => <SVGSocialFireplace_20_twotone />;
export const IconSocialFireplace24twotone = () => <SVGSocialFireplace_24_twotone />;
export const IconSocialFireplace20sharp = () => <SVGSocialFireplace_20_sharp />;
export const IconSocialFireplace24sharp = () => <SVGSocialFireplace_24_sharp />;
export const IconSocialFireplace20filled = () => <SVGSocialFireplace_20_filled />;
export const IconSocialFireplace24filled = () => <SVGSocialFireplace_24_filled />;
export const IconSocialFireplace20round = () => <SVGSocialFireplace_20_round />;
export const IconSocialFireplace24round = () => <SVGSocialFireplace_24_round />;
