import React from "react";
import SVGSocialNotificationAdd_20_outlined from '../../svg/social/SocialNotificationAdd/20_outlined.svg';
import SVGSocialNotificationAdd_24_outlined from '../../svg/social/SocialNotificationAdd/24_outlined.svg';
import SVGSocialNotificationAdd_20_twotone from '../../svg/social/SocialNotificationAdd/20_twotone.svg';
import SVGSocialNotificationAdd_24_twotone from '../../svg/social/SocialNotificationAdd/24_twotone.svg';
import SVGSocialNotificationAdd_20_sharp from '../../svg/social/SocialNotificationAdd/20_sharp.svg';
import SVGSocialNotificationAdd_24_sharp from '../../svg/social/SocialNotificationAdd/24_sharp.svg';
import SVGSocialNotificationAdd_20_filled from '../../svg/social/SocialNotificationAdd/20_filled.svg';
import SVGSocialNotificationAdd_24_filled from '../../svg/social/SocialNotificationAdd/24_filled.svg';
import SVGSocialNotificationAdd_20_round from '../../svg/social/SocialNotificationAdd/20_round.svg';
import SVGSocialNotificationAdd_24_round from '../../svg/social/SocialNotificationAdd/24_round.svg';

export const IconSocialNotificationAdd20outlined = () => <SVGSocialNotificationAdd_20_outlined />;
export const IconSocialNotificationAdd24outlined = () => <SVGSocialNotificationAdd_24_outlined />;
export const IconSocialNotificationAdd20twotone = () => <SVGSocialNotificationAdd_20_twotone />;
export const IconSocialNotificationAdd24twotone = () => <SVGSocialNotificationAdd_24_twotone />;
export const IconSocialNotificationAdd20sharp = () => <SVGSocialNotificationAdd_20_sharp />;
export const IconSocialNotificationAdd24sharp = () => <SVGSocialNotificationAdd_24_sharp />;
export const IconSocialNotificationAdd20filled = () => <SVGSocialNotificationAdd_20_filled />;
export const IconSocialNotificationAdd24filled = () => <SVGSocialNotificationAdd_24_filled />;
export const IconSocialNotificationAdd20round = () => <SVGSocialNotificationAdd_20_round />;
export const IconSocialNotificationAdd24round = () => <SVGSocialNotificationAdd_24_round />;
