import React from "react";
import SVGSocialPix_20_outlined from '../../svg/social/SocialPix/20_outlined.svg';
import SVGSocialPix_24_outlined from '../../svg/social/SocialPix/24_outlined.svg';
import SVGSocialPix_20_twotone from '../../svg/social/SocialPix/20_twotone.svg';
import SVGSocialPix_24_twotone from '../../svg/social/SocialPix/24_twotone.svg';
import SVGSocialPix_20_sharp from '../../svg/social/SocialPix/20_sharp.svg';
import SVGSocialPix_24_sharp from '../../svg/social/SocialPix/24_sharp.svg';
import SVGSocialPix_20_filled from '../../svg/social/SocialPix/20_filled.svg';
import SVGSocialPix_24_filled from '../../svg/social/SocialPix/24_filled.svg';
import SVGSocialPix_20_round from '../../svg/social/SocialPix/20_round.svg';
import SVGSocialPix_24_round from '../../svg/social/SocialPix/24_round.svg';

export const IconSocialPix20outlined = () => <SVGSocialPix_20_outlined />;
export const IconSocialPix24outlined = () => <SVGSocialPix_24_outlined />;
export const IconSocialPix20twotone = () => <SVGSocialPix_20_twotone />;
export const IconSocialPix24twotone = () => <SVGSocialPix_24_twotone />;
export const IconSocialPix20sharp = () => <SVGSocialPix_20_sharp />;
export const IconSocialPix24sharp = () => <SVGSocialPix_24_sharp />;
export const IconSocialPix20filled = () => <SVGSocialPix_20_filled />;
export const IconSocialPix24filled = () => <SVGSocialPix_24_filled />;
export const IconSocialPix20round = () => <SVGSocialPix_20_round />;
export const IconSocialPix24round = () => <SVGSocialPix_24_round />;
