import React from "react";
import SVGSocialSelfImprovement_20_outlined from '../../svg/social/SocialSelfImprovement/20_outlined.svg';
import SVGSocialSelfImprovement_24_outlined from '../../svg/social/SocialSelfImprovement/24_outlined.svg';
import SVGSocialSelfImprovement_20_twotone from '../../svg/social/SocialSelfImprovement/20_twotone.svg';
import SVGSocialSelfImprovement_24_twotone from '../../svg/social/SocialSelfImprovement/24_twotone.svg';
import SVGSocialSelfImprovement_20_sharp from '../../svg/social/SocialSelfImprovement/20_sharp.svg';
import SVGSocialSelfImprovement_24_sharp from '../../svg/social/SocialSelfImprovement/24_sharp.svg';
import SVGSocialSelfImprovement_20_filled from '../../svg/social/SocialSelfImprovement/20_filled.svg';
import SVGSocialSelfImprovement_24_filled from '../../svg/social/SocialSelfImprovement/24_filled.svg';
import SVGSocialSelfImprovement_20_round from '../../svg/social/SocialSelfImprovement/20_round.svg';
import SVGSocialSelfImprovement_24_round from '../../svg/social/SocialSelfImprovement/24_round.svg';

export const IconSocialSelfImprovement20outlined = () => <SVGSocialSelfImprovement_20_outlined />;
export const IconSocialSelfImprovement24outlined = () => <SVGSocialSelfImprovement_24_outlined />;
export const IconSocialSelfImprovement20twotone = () => <SVGSocialSelfImprovement_20_twotone />;
export const IconSocialSelfImprovement24twotone = () => <SVGSocialSelfImprovement_24_twotone />;
export const IconSocialSelfImprovement20sharp = () => <SVGSocialSelfImprovement_20_sharp />;
export const IconSocialSelfImprovement24sharp = () => <SVGSocialSelfImprovement_24_sharp />;
export const IconSocialSelfImprovement20filled = () => <SVGSocialSelfImprovement_20_filled />;
export const IconSocialSelfImprovement24filled = () => <SVGSocialSelfImprovement_24_filled />;
export const IconSocialSelfImprovement20round = () => <SVGSocialSelfImprovement_20_round />;
export const IconSocialSelfImprovement24round = () => <SVGSocialSelfImprovement_24_round />;
