import React from "react";
import SVGSocialSportsSoccer_20_outlined from '../../svg/social/SocialSportsSoccer/20_outlined.svg';
import SVGSocialSportsSoccer_24_outlined from '../../svg/social/SocialSportsSoccer/24_outlined.svg';
import SVGSocialSportsSoccer_20_twotone from '../../svg/social/SocialSportsSoccer/20_twotone.svg';
import SVGSocialSportsSoccer_24_twotone from '../../svg/social/SocialSportsSoccer/24_twotone.svg';
import SVGSocialSportsSoccer_20_sharp from '../../svg/social/SocialSportsSoccer/20_sharp.svg';
import SVGSocialSportsSoccer_24_sharp from '../../svg/social/SocialSportsSoccer/24_sharp.svg';
import SVGSocialSportsSoccer_20_filled from '../../svg/social/SocialSportsSoccer/20_filled.svg';
import SVGSocialSportsSoccer_24_filled from '../../svg/social/SocialSportsSoccer/24_filled.svg';
import SVGSocialSportsSoccer_20_round from '../../svg/social/SocialSportsSoccer/20_round.svg';
import SVGSocialSportsSoccer_24_round from '../../svg/social/SocialSportsSoccer/24_round.svg';

export const IconSocialSportsSoccer20outlined = () => <SVGSocialSportsSoccer_20_outlined />;
export const IconSocialSportsSoccer24outlined = () => <SVGSocialSportsSoccer_24_outlined />;
export const IconSocialSportsSoccer20twotone = () => <SVGSocialSportsSoccer_20_twotone />;
export const IconSocialSportsSoccer24twotone = () => <SVGSocialSportsSoccer_24_twotone />;
export const IconSocialSportsSoccer20sharp = () => <SVGSocialSportsSoccer_20_sharp />;
export const IconSocialSportsSoccer24sharp = () => <SVGSocialSportsSoccer_24_sharp />;
export const IconSocialSportsSoccer20filled = () => <SVGSocialSportsSoccer_20_filled />;
export const IconSocialSportsSoccer24filled = () => <SVGSocialSportsSoccer_24_filled />;
export const IconSocialSportsSoccer20round = () => <SVGSocialSportsSoccer_20_round />;
export const IconSocialSportsSoccer24round = () => <SVGSocialSportsSoccer_24_round />;
