import React from "react";
import SVGSocialDeck_20_outlined from '../../svg/social/SocialDeck/20_outlined.svg';
import SVGSocialDeck_24_outlined from '../../svg/social/SocialDeck/24_outlined.svg';
import SVGSocialDeck_20_twotone from '../../svg/social/SocialDeck/20_twotone.svg';
import SVGSocialDeck_24_twotone from '../../svg/social/SocialDeck/24_twotone.svg';
import SVGSocialDeck_20_sharp from '../../svg/social/SocialDeck/20_sharp.svg';
import SVGSocialDeck_24_sharp from '../../svg/social/SocialDeck/24_sharp.svg';
import SVGSocialDeck_20_filled from '../../svg/social/SocialDeck/20_filled.svg';
import SVGSocialDeck_24_filled from '../../svg/social/SocialDeck/24_filled.svg';
import SVGSocialDeck_20_round from '../../svg/social/SocialDeck/20_round.svg';
import SVGSocialDeck_24_round from '../../svg/social/SocialDeck/24_round.svg';

export const IconSocialDeck20outlined = () => <SVGSocialDeck_20_outlined />;
export const IconSocialDeck24outlined = () => <SVGSocialDeck_24_outlined />;
export const IconSocialDeck20twotone = () => <SVGSocialDeck_20_twotone />;
export const IconSocialDeck24twotone = () => <SVGSocialDeck_24_twotone />;
export const IconSocialDeck20sharp = () => <SVGSocialDeck_20_sharp />;
export const IconSocialDeck24sharp = () => <SVGSocialDeck_24_sharp />;
export const IconSocialDeck20filled = () => <SVGSocialDeck_20_filled />;
export const IconSocialDeck24filled = () => <SVGSocialDeck_24_filled />;
export const IconSocialDeck20round = () => <SVGSocialDeck_20_round />;
export const IconSocialDeck24round = () => <SVGSocialDeck_24_round />;
