import React from "react";
import SVGSocial18UpRating_20_outlined from '../../svg/social/Social18UpRating/20_outlined.svg';
import SVGSocial18UpRating_24_outlined from '../../svg/social/Social18UpRating/24_outlined.svg';
import SVGSocial18UpRating_20_twotone from '../../svg/social/Social18UpRating/20_twotone.svg';
import SVGSocial18UpRating_24_twotone from '../../svg/social/Social18UpRating/24_twotone.svg';
import SVGSocial18UpRating_20_sharp from '../../svg/social/Social18UpRating/20_sharp.svg';
import SVGSocial18UpRating_24_sharp from '../../svg/social/Social18UpRating/24_sharp.svg';
import SVGSocial18UpRating_20_filled from '../../svg/social/Social18UpRating/20_filled.svg';
import SVGSocial18UpRating_24_filled from '../../svg/social/Social18UpRating/24_filled.svg';
import SVGSocial18UpRating_20_round from '../../svg/social/Social18UpRating/20_round.svg';
import SVGSocial18UpRating_24_round from '../../svg/social/Social18UpRating/24_round.svg';

export const IconSocial18UpRating20outlined = () => <SVGSocial18UpRating_20_outlined />;
export const IconSocial18UpRating24outlined = () => <SVGSocial18UpRating_24_outlined />;
export const IconSocial18UpRating20twotone = () => <SVGSocial18UpRating_20_twotone />;
export const IconSocial18UpRating24twotone = () => <SVGSocial18UpRating_24_twotone />;
export const IconSocial18UpRating20sharp = () => <SVGSocial18UpRating_20_sharp />;
export const IconSocial18UpRating24sharp = () => <SVGSocial18UpRating_24_sharp />;
export const IconSocial18UpRating20filled = () => <SVGSocial18UpRating_20_filled />;
export const IconSocial18UpRating24filled = () => <SVGSocial18UpRating_24_filled />;
export const IconSocial18UpRating20round = () => <SVGSocial18UpRating_20_round />;
export const IconSocial18UpRating24round = () => <SVGSocial18UpRating_24_round />;
