import React from "react";
import SVGSocialSportsMartialArts_20_outlined from '../../svg/social/SocialSportsMartialArts/20_outlined.svg';
import SVGSocialSportsMartialArts_24_outlined from '../../svg/social/SocialSportsMartialArts/24_outlined.svg';
import SVGSocialSportsMartialArts_20_twotone from '../../svg/social/SocialSportsMartialArts/20_twotone.svg';
import SVGSocialSportsMartialArts_24_twotone from '../../svg/social/SocialSportsMartialArts/24_twotone.svg';
import SVGSocialSportsMartialArts_20_sharp from '../../svg/social/SocialSportsMartialArts/20_sharp.svg';
import SVGSocialSportsMartialArts_24_sharp from '../../svg/social/SocialSportsMartialArts/24_sharp.svg';
import SVGSocialSportsMartialArts_20_filled from '../../svg/social/SocialSportsMartialArts/20_filled.svg';
import SVGSocialSportsMartialArts_24_filled from '../../svg/social/SocialSportsMartialArts/24_filled.svg';
import SVGSocialSportsMartialArts_20_round from '../../svg/social/SocialSportsMartialArts/20_round.svg';
import SVGSocialSportsMartialArts_24_round from '../../svg/social/SocialSportsMartialArts/24_round.svg';

export const IconSocialSportsMartialArts20outlined = () => <SVGSocialSportsMartialArts_20_outlined />;
export const IconSocialSportsMartialArts24outlined = () => <SVGSocialSportsMartialArts_24_outlined />;
export const IconSocialSportsMartialArts20twotone = () => <SVGSocialSportsMartialArts_20_twotone />;
export const IconSocialSportsMartialArts24twotone = () => <SVGSocialSportsMartialArts_24_twotone />;
export const IconSocialSportsMartialArts20sharp = () => <SVGSocialSportsMartialArts_20_sharp />;
export const IconSocialSportsMartialArts24sharp = () => <SVGSocialSportsMartialArts_24_sharp />;
export const IconSocialSportsMartialArts20filled = () => <SVGSocialSportsMartialArts_20_filled />;
export const IconSocialSportsMartialArts24filled = () => <SVGSocialSportsMartialArts_24_filled />;
export const IconSocialSportsMartialArts20round = () => <SVGSocialSportsMartialArts_20_round />;
export const IconSocialSportsMartialArts24round = () => <SVGSocialSportsMartialArts_24_round />;
