import React from "react";
import SVGSocialSkateboarding_20_outlined from '../../svg/social/SocialSkateboarding/20_outlined.svg';
import SVGSocialSkateboarding_24_outlined from '../../svg/social/SocialSkateboarding/24_outlined.svg';
import SVGSocialSkateboarding_20_twotone from '../../svg/social/SocialSkateboarding/20_twotone.svg';
import SVGSocialSkateboarding_24_twotone from '../../svg/social/SocialSkateboarding/24_twotone.svg';
import SVGSocialSkateboarding_20_sharp from '../../svg/social/SocialSkateboarding/20_sharp.svg';
import SVGSocialSkateboarding_24_sharp from '../../svg/social/SocialSkateboarding/24_sharp.svg';
import SVGSocialSkateboarding_20_filled from '../../svg/social/SocialSkateboarding/20_filled.svg';
import SVGSocialSkateboarding_24_filled from '../../svg/social/SocialSkateboarding/24_filled.svg';
import SVGSocialSkateboarding_20_round from '../../svg/social/SocialSkateboarding/20_round.svg';
import SVGSocialSkateboarding_24_round from '../../svg/social/SocialSkateboarding/24_round.svg';

export const IconSocialSkateboarding20outlined = () => <SVGSocialSkateboarding_20_outlined />;
export const IconSocialSkateboarding24outlined = () => <SVGSocialSkateboarding_24_outlined />;
export const IconSocialSkateboarding20twotone = () => <SVGSocialSkateboarding_20_twotone />;
export const IconSocialSkateboarding24twotone = () => <SVGSocialSkateboarding_24_twotone />;
export const IconSocialSkateboarding20sharp = () => <SVGSocialSkateboarding_20_sharp />;
export const IconSocialSkateboarding24sharp = () => <SVGSocialSkateboarding_24_sharp />;
export const IconSocialSkateboarding20filled = () => <SVGSocialSkateboarding_20_filled />;
export const IconSocialSkateboarding24filled = () => <SVGSocialSkateboarding_24_filled />;
export const IconSocialSkateboarding20round = () => <SVGSocialSkateboarding_20_round />;
export const IconSocialSkateboarding24round = () => <SVGSocialSkateboarding_24_round />;
