import React from "react";
import SVGSocialGroupAdd_20_outlined from '../../svg/social/SocialGroupAdd/20_outlined.svg';
import SVGSocialGroupAdd_24_outlined from '../../svg/social/SocialGroupAdd/24_outlined.svg';
import SVGSocialGroupAdd_20_twotone from '../../svg/social/SocialGroupAdd/20_twotone.svg';
import SVGSocialGroupAdd_24_twotone from '../../svg/social/SocialGroupAdd/24_twotone.svg';
import SVGSocialGroupAdd_20_sharp from '../../svg/social/SocialGroupAdd/20_sharp.svg';
import SVGSocialGroupAdd_24_sharp from '../../svg/social/SocialGroupAdd/24_sharp.svg';
import SVGSocialGroupAdd_20_filled from '../../svg/social/SocialGroupAdd/20_filled.svg';
import SVGSocialGroupAdd_24_filled from '../../svg/social/SocialGroupAdd/24_filled.svg';
import SVGSocialGroupAdd_20_round from '../../svg/social/SocialGroupAdd/20_round.svg';
import SVGSocialGroupAdd_24_round from '../../svg/social/SocialGroupAdd/24_round.svg';

export const IconSocialGroupAdd20outlined = () => <SVGSocialGroupAdd_20_outlined />;
export const IconSocialGroupAdd24outlined = () => <SVGSocialGroupAdd_24_outlined />;
export const IconSocialGroupAdd20twotone = () => <SVGSocialGroupAdd_20_twotone />;
export const IconSocialGroupAdd24twotone = () => <SVGSocialGroupAdd_24_twotone />;
export const IconSocialGroupAdd20sharp = () => <SVGSocialGroupAdd_20_sharp />;
export const IconSocialGroupAdd24sharp = () => <SVGSocialGroupAdd_24_sharp />;
export const IconSocialGroupAdd20filled = () => <SVGSocialGroupAdd_20_filled />;
export const IconSocialGroupAdd24filled = () => <SVGSocialGroupAdd_24_filled />;
export const IconSocialGroupAdd20round = () => <SVGSocialGroupAdd_20_round />;
export const IconSocialGroupAdd24round = () => <SVGSocialGroupAdd_24_round />;
