import React from "react";
import SVGSocialFace3_20_outlined from '../../svg/social/SocialFace3/20_outlined.svg';
import SVGSocialFace3_24_outlined from '../../svg/social/SocialFace3/24_outlined.svg';
import SVGSocialFace3_20_twotone from '../../svg/social/SocialFace3/20_twotone.svg';
import SVGSocialFace3_24_twotone from '../../svg/social/SocialFace3/24_twotone.svg';
import SVGSocialFace3_20_sharp from '../../svg/social/SocialFace3/20_sharp.svg';
import SVGSocialFace3_24_sharp from '../../svg/social/SocialFace3/24_sharp.svg';
import SVGSocialFace3_20_filled from '../../svg/social/SocialFace3/20_filled.svg';
import SVGSocialFace3_24_filled from '../../svg/social/SocialFace3/24_filled.svg';
import SVGSocialFace3_20_round from '../../svg/social/SocialFace3/20_round.svg';
import SVGSocialFace3_24_round from '../../svg/social/SocialFace3/24_round.svg';

export const IconSocialFace320outlined = () => <SVGSocialFace3_20_outlined />;
export const IconSocialFace324outlined = () => <SVGSocialFace3_24_outlined />;
export const IconSocialFace320twotone = () => <SVGSocialFace3_20_twotone />;
export const IconSocialFace324twotone = () => <SVGSocialFace3_24_twotone />;
export const IconSocialFace320sharp = () => <SVGSocialFace3_20_sharp />;
export const IconSocialFace324sharp = () => <SVGSocialFace3_24_sharp />;
export const IconSocialFace320filled = () => <SVGSocialFace3_20_filled />;
export const IconSocialFace324filled = () => <SVGSocialFace3_24_filled />;
export const IconSocialFace320round = () => <SVGSocialFace3_20_round />;
export const IconSocialFace324round = () => <SVGSocialFace3_24_round />;
