import React from "react";
import SVGSocialIceSkating_20_outlined from '../../svg/social/SocialIceSkating/20_outlined.svg';
import SVGSocialIceSkating_24_outlined from '../../svg/social/SocialIceSkating/24_outlined.svg';
import SVGSocialIceSkating_20_twotone from '../../svg/social/SocialIceSkating/20_twotone.svg';
import SVGSocialIceSkating_24_twotone from '../../svg/social/SocialIceSkating/24_twotone.svg';
import SVGSocialIceSkating_20_sharp from '../../svg/social/SocialIceSkating/20_sharp.svg';
import SVGSocialIceSkating_24_sharp from '../../svg/social/SocialIceSkating/24_sharp.svg';
import SVGSocialIceSkating_20_filled from '../../svg/social/SocialIceSkating/20_filled.svg';
import SVGSocialIceSkating_24_filled from '../../svg/social/SocialIceSkating/24_filled.svg';
import SVGSocialIceSkating_20_round from '../../svg/social/SocialIceSkating/20_round.svg';
import SVGSocialIceSkating_24_round from '../../svg/social/SocialIceSkating/24_round.svg';

export const IconSocialIceSkating20outlined = () => <SVGSocialIceSkating_20_outlined />;
export const IconSocialIceSkating24outlined = () => <SVGSocialIceSkating_24_outlined />;
export const IconSocialIceSkating20twotone = () => <SVGSocialIceSkating_20_twotone />;
export const IconSocialIceSkating24twotone = () => <SVGSocialIceSkating_24_twotone />;
export const IconSocialIceSkating20sharp = () => <SVGSocialIceSkating_20_sharp />;
export const IconSocialIceSkating24sharp = () => <SVGSocialIceSkating_24_sharp />;
export const IconSocialIceSkating20filled = () => <SVGSocialIceSkating_20_filled />;
export const IconSocialIceSkating24filled = () => <SVGSocialIceSkating_24_filled />;
export const IconSocialIceSkating20round = () => <SVGSocialIceSkating_20_round />;
export const IconSocialIceSkating24round = () => <SVGSocialIceSkating_24_round />;
