import React from "react";
import SVGSocialFlood_20_outlined from '../../svg/social/SocialFlood/20_outlined.svg';
import SVGSocialFlood_24_outlined from '../../svg/social/SocialFlood/24_outlined.svg';
import SVGSocialFlood_20_twotone from '../../svg/social/SocialFlood/20_twotone.svg';
import SVGSocialFlood_24_twotone from '../../svg/social/SocialFlood/24_twotone.svg';
import SVGSocialFlood_20_sharp from '../../svg/social/SocialFlood/20_sharp.svg';
import SVGSocialFlood_24_sharp from '../../svg/social/SocialFlood/24_sharp.svg';
import SVGSocialFlood_20_filled from '../../svg/social/SocialFlood/20_filled.svg';
import SVGSocialFlood_24_filled from '../../svg/social/SocialFlood/24_filled.svg';
import SVGSocialFlood_20_round from '../../svg/social/SocialFlood/20_round.svg';
import SVGSocialFlood_24_round from '../../svg/social/SocialFlood/24_round.svg';

export const IconSocialFlood20outlined = () => <SVGSocialFlood_20_outlined />;
export const IconSocialFlood24outlined = () => <SVGSocialFlood_24_outlined />;
export const IconSocialFlood20twotone = () => <SVGSocialFlood_20_twotone />;
export const IconSocialFlood24twotone = () => <SVGSocialFlood_24_twotone />;
export const IconSocialFlood20sharp = () => <SVGSocialFlood_20_sharp />;
export const IconSocialFlood24sharp = () => <SVGSocialFlood_24_sharp />;
export const IconSocialFlood20filled = () => <SVGSocialFlood_20_filled />;
export const IconSocialFlood24filled = () => <SVGSocialFlood_24_filled />;
export const IconSocialFlood20round = () => <SVGSocialFlood_20_round />;
export const IconSocialFlood24round = () => <SVGSocialFlood_24_round />;
