import React from "react";
import SVGSocialTransgender_20_outlined from '../../svg/social/SocialTransgender/20_outlined.svg';
import SVGSocialTransgender_24_outlined from '../../svg/social/SocialTransgender/24_outlined.svg';
import SVGSocialTransgender_20_twotone from '../../svg/social/SocialTransgender/20_twotone.svg';
import SVGSocialTransgender_24_twotone from '../../svg/social/SocialTransgender/24_twotone.svg';
import SVGSocialTransgender_20_sharp from '../../svg/social/SocialTransgender/20_sharp.svg';
import SVGSocialTransgender_24_sharp from '../../svg/social/SocialTransgender/24_sharp.svg';
import SVGSocialTransgender_20_filled from '../../svg/social/SocialTransgender/20_filled.svg';
import SVGSocialTransgender_24_filled from '../../svg/social/SocialTransgender/24_filled.svg';
import SVGSocialTransgender_20_round from '../../svg/social/SocialTransgender/20_round.svg';
import SVGSocialTransgender_24_round from '../../svg/social/SocialTransgender/24_round.svg';

export const IconSocialTransgender20outlined = () => <SVGSocialTransgender_20_outlined />;
export const IconSocialTransgender24outlined = () => <SVGSocialTransgender_24_outlined />;
export const IconSocialTransgender20twotone = () => <SVGSocialTransgender_20_twotone />;
export const IconSocialTransgender24twotone = () => <SVGSocialTransgender_24_twotone />;
export const IconSocialTransgender20sharp = () => <SVGSocialTransgender_20_sharp />;
export const IconSocialTransgender24sharp = () => <SVGSocialTransgender_24_sharp />;
export const IconSocialTransgender20filled = () => <SVGSocialTransgender_20_filled />;
export const IconSocialTransgender24filled = () => <SVGSocialTransgender_24_filled />;
export const IconSocialTransgender20round = () => <SVGSocialTransgender_20_round />;
export const IconSocialTransgender24round = () => <SVGSocialTransgender_24_round />;
