import React from "react";
import SVGSocialThunderstorm_20_outlined from '../../svg/social/SocialThunderstorm/20_outlined.svg';
import SVGSocialThunderstorm_24_outlined from '../../svg/social/SocialThunderstorm/24_outlined.svg';
import SVGSocialThunderstorm_20_twotone from '../../svg/social/SocialThunderstorm/20_twotone.svg';
import SVGSocialThunderstorm_24_twotone from '../../svg/social/SocialThunderstorm/24_twotone.svg';
import SVGSocialThunderstorm_20_sharp from '../../svg/social/SocialThunderstorm/20_sharp.svg';
import SVGSocialThunderstorm_24_sharp from '../../svg/social/SocialThunderstorm/24_sharp.svg';
import SVGSocialThunderstorm_20_filled from '../../svg/social/SocialThunderstorm/20_filled.svg';
import SVGSocialThunderstorm_24_filled from '../../svg/social/SocialThunderstorm/24_filled.svg';
import SVGSocialThunderstorm_20_round from '../../svg/social/SocialThunderstorm/20_round.svg';
import SVGSocialThunderstorm_24_round from '../../svg/social/SocialThunderstorm/24_round.svg';

export const IconSocialThunderstorm20outlined = () => <SVGSocialThunderstorm_20_outlined />;
export const IconSocialThunderstorm24outlined = () => <SVGSocialThunderstorm_24_outlined />;
export const IconSocialThunderstorm20twotone = () => <SVGSocialThunderstorm_20_twotone />;
export const IconSocialThunderstorm24twotone = () => <SVGSocialThunderstorm_24_twotone />;
export const IconSocialThunderstorm20sharp = () => <SVGSocialThunderstorm_20_sharp />;
export const IconSocialThunderstorm24sharp = () => <SVGSocialThunderstorm_24_sharp />;
export const IconSocialThunderstorm20filled = () => <SVGSocialThunderstorm_20_filled />;
export const IconSocialThunderstorm24filled = () => <SVGSocialThunderstorm_24_filled />;
export const IconSocialThunderstorm20round = () => <SVGSocialThunderstorm_20_round />;
export const IconSocialThunderstorm24round = () => <SVGSocialThunderstorm_24_round />;
