import React from "react";
import SVGSocialSports_20_outlined from '../../svg/social/SocialSports/20_outlined.svg';
import SVGSocialSports_24_outlined from '../../svg/social/SocialSports/24_outlined.svg';
import SVGSocialSports_20_twotone from '../../svg/social/SocialSports/20_twotone.svg';
import SVGSocialSports_24_twotone from '../../svg/social/SocialSports/24_twotone.svg';
import SVGSocialSports_20_sharp from '../../svg/social/SocialSports/20_sharp.svg';
import SVGSocialSports_24_sharp from '../../svg/social/SocialSports/24_sharp.svg';
import SVGSocialSports_20_filled from '../../svg/social/SocialSports/20_filled.svg';
import SVGSocialSports_24_filled from '../../svg/social/SocialSports/24_filled.svg';
import SVGSocialSports_20_round from '../../svg/social/SocialSports/20_round.svg';
import SVGSocialSports_24_round from '../../svg/social/SocialSports/24_round.svg';

export const IconSocialSports20outlined = () => <SVGSocialSports_20_outlined />;
export const IconSocialSports24outlined = () => <SVGSocialSports_24_outlined />;
export const IconSocialSports20twotone = () => <SVGSocialSports_20_twotone />;
export const IconSocialSports24twotone = () => <SVGSocialSports_24_twotone />;
export const IconSocialSports20sharp = () => <SVGSocialSports_20_sharp />;
export const IconSocialSports24sharp = () => <SVGSocialSports_24_sharp />;
export const IconSocialSports20filled = () => <SVGSocialSports_20_filled />;
export const IconSocialSports24filled = () => <SVGSocialSports_24_filled />;
export const IconSocialSports20round = () => <SVGSocialSports_20_round />;
export const IconSocialSports24round = () => <SVGSocialSports_24_round />;
