import React from "react";
import SVGSocialPiano_20_outlined from '../../svg/social/SocialPiano/20_outlined.svg';
import SVGSocialPiano_24_outlined from '../../svg/social/SocialPiano/24_outlined.svg';
import SVGSocialPiano_20_twotone from '../../svg/social/SocialPiano/20_twotone.svg';
import SVGSocialPiano_24_twotone from '../../svg/social/SocialPiano/24_twotone.svg';
import SVGSocialPiano_20_sharp from '../../svg/social/SocialPiano/20_sharp.svg';
import SVGSocialPiano_24_sharp from '../../svg/social/SocialPiano/24_sharp.svg';
import SVGSocialPiano_20_filled from '../../svg/social/SocialPiano/20_filled.svg';
import SVGSocialPiano_24_filled from '../../svg/social/SocialPiano/24_filled.svg';
import SVGSocialPiano_20_round from '../../svg/social/SocialPiano/20_round.svg';
import SVGSocialPiano_24_round from '../../svg/social/SocialPiano/24_round.svg';

export const IconSocialPiano20outlined = () => <SVGSocialPiano_20_outlined />;
export const IconSocialPiano24outlined = () => <SVGSocialPiano_24_outlined />;
export const IconSocialPiano20twotone = () => <SVGSocialPiano_20_twotone />;
export const IconSocialPiano24twotone = () => <SVGSocialPiano_24_twotone />;
export const IconSocialPiano20sharp = () => <SVGSocialPiano_20_sharp />;
export const IconSocialPiano24sharp = () => <SVGSocialPiano_24_sharp />;
export const IconSocialPiano20filled = () => <SVGSocialPiano_20_filled />;
export const IconSocialPiano24filled = () => <SVGSocialPiano_24_filled />;
export const IconSocialPiano20round = () => <SVGSocialPiano_20_round />;
export const IconSocialPiano24round = () => <SVGSocialPiano_24_round />;
