import React from "react";
import SVGSocialSportsFootball_20_outlined from '../../svg/social/SocialSportsFootball/20_outlined.svg';
import SVGSocialSportsFootball_24_outlined from '../../svg/social/SocialSportsFootball/24_outlined.svg';
import SVGSocialSportsFootball_20_twotone from '../../svg/social/SocialSportsFootball/20_twotone.svg';
import SVGSocialSportsFootball_24_twotone from '../../svg/social/SocialSportsFootball/24_twotone.svg';
import SVGSocialSportsFootball_20_sharp from '../../svg/social/SocialSportsFootball/20_sharp.svg';
import SVGSocialSportsFootball_24_sharp from '../../svg/social/SocialSportsFootball/24_sharp.svg';
import SVGSocialSportsFootball_20_filled from '../../svg/social/SocialSportsFootball/20_filled.svg';
import SVGSocialSportsFootball_24_filled from '../../svg/social/SocialSportsFootball/24_filled.svg';
import SVGSocialSportsFootball_20_round from '../../svg/social/SocialSportsFootball/20_round.svg';
import SVGSocialSportsFootball_24_round from '../../svg/social/SocialSportsFootball/24_round.svg';

export const IconSocialSportsFootball20outlined = () => <SVGSocialSportsFootball_20_outlined />;
export const IconSocialSportsFootball24outlined = () => <SVGSocialSportsFootball_24_outlined />;
export const IconSocialSportsFootball20twotone = () => <SVGSocialSportsFootball_20_twotone />;
export const IconSocialSportsFootball24twotone = () => <SVGSocialSportsFootball_24_twotone />;
export const IconSocialSportsFootball20sharp = () => <SVGSocialSportsFootball_20_sharp />;
export const IconSocialSportsFootball24sharp = () => <SVGSocialSportsFootball_24_sharp />;
export const IconSocialSportsFootball20filled = () => <SVGSocialSportsFootball_20_filled />;
export const IconSocialSportsFootball24filled = () => <SVGSocialSportsFootball_24_filled />;
export const IconSocialSportsFootball20round = () => <SVGSocialSportsFootball_20_round />;
export const IconSocialSportsFootball24round = () => <SVGSocialSportsFootball_24_round />;
