import React from "react";
import SVGSocialHive_20_outlined from '../../svg/social/SocialHive/20_outlined.svg';
import SVGSocialHive_24_outlined from '../../svg/social/SocialHive/24_outlined.svg';
import SVGSocialHive_20_twotone from '../../svg/social/SocialHive/20_twotone.svg';
import SVGSocialHive_24_twotone from '../../svg/social/SocialHive/24_twotone.svg';
import SVGSocialHive_20_sharp from '../../svg/social/SocialHive/20_sharp.svg';
import SVGSocialHive_24_sharp from '../../svg/social/SocialHive/24_sharp.svg';
import SVGSocialHive_20_filled from '../../svg/social/SocialHive/20_filled.svg';
import SVGSocialHive_24_filled from '../../svg/social/SocialHive/24_filled.svg';
import SVGSocialHive_20_round from '../../svg/social/SocialHive/20_round.svg';
import SVGSocialHive_24_round from '../../svg/social/SocialHive/24_round.svg';

export const IconSocialHive20outlined = () => <SVGSocialHive_20_outlined />;
export const IconSocialHive24outlined = () => <SVGSocialHive_24_outlined />;
export const IconSocialHive20twotone = () => <SVGSocialHive_20_twotone />;
export const IconSocialHive24twotone = () => <SVGSocialHive_24_twotone />;
export const IconSocialHive20sharp = () => <SVGSocialHive_20_sharp />;
export const IconSocialHive24sharp = () => <SVGSocialHive_24_sharp />;
export const IconSocialHive20filled = () => <SVGSocialHive_20_filled />;
export const IconSocialHive24filled = () => <SVGSocialHive_24_filled />;
export const IconSocialHive20round = () => <SVGSocialHive_20_round />;
export const IconSocialHive24round = () => <SVGSocialHive_24_round />;
