import React from "react";
import SVGSocialSingleBed_20_outlined from '../../svg/social/SocialSingleBed/20_outlined.svg';
import SVGSocialSingleBed_24_outlined from '../../svg/social/SocialSingleBed/24_outlined.svg';
import SVGSocialSingleBed_20_twotone from '../../svg/social/SocialSingleBed/20_twotone.svg';
import SVGSocialSingleBed_24_twotone from '../../svg/social/SocialSingleBed/24_twotone.svg';
import SVGSocialSingleBed_20_sharp from '../../svg/social/SocialSingleBed/20_sharp.svg';
import SVGSocialSingleBed_24_sharp from '../../svg/social/SocialSingleBed/24_sharp.svg';
import SVGSocialSingleBed_20_filled from '../../svg/social/SocialSingleBed/20_filled.svg';
import SVGSocialSingleBed_24_filled from '../../svg/social/SocialSingleBed/24_filled.svg';
import SVGSocialSingleBed_20_round from '../../svg/social/SocialSingleBed/20_round.svg';
import SVGSocialSingleBed_24_round from '../../svg/social/SocialSingleBed/24_round.svg';

export const IconSocialSingleBed20outlined = () => <SVGSocialSingleBed_20_outlined />;
export const IconSocialSingleBed24outlined = () => <SVGSocialSingleBed_24_outlined />;
export const IconSocialSingleBed20twotone = () => <SVGSocialSingleBed_20_twotone />;
export const IconSocialSingleBed24twotone = () => <SVGSocialSingleBed_24_twotone />;
export const IconSocialSingleBed20sharp = () => <SVGSocialSingleBed_20_sharp />;
export const IconSocialSingleBed24sharp = () => <SVGSocialSingleBed_24_sharp />;
export const IconSocialSingleBed20filled = () => <SVGSocialSingleBed_20_filled />;
export const IconSocialSingleBed24filled = () => <SVGSocialSingleBed_24_filled />;
export const IconSocialSingleBed20round = () => <SVGSocialSingleBed_20_round />;
export const IconSocialSingleBed24round = () => <SVGSocialSingleBed_24_round />;
