import React from "react";
import SVGSocialMilitaryTech_20_outlined from '../../svg/social/SocialMilitaryTech/20_outlined.svg';
import SVGSocialMilitaryTech_24_outlined from '../../svg/social/SocialMilitaryTech/24_outlined.svg';
import SVGSocialMilitaryTech_20_twotone from '../../svg/social/SocialMilitaryTech/20_twotone.svg';
import SVGSocialMilitaryTech_24_twotone from '../../svg/social/SocialMilitaryTech/24_twotone.svg';
import SVGSocialMilitaryTech_20_sharp from '../../svg/social/SocialMilitaryTech/20_sharp.svg';
import SVGSocialMilitaryTech_24_sharp from '../../svg/social/SocialMilitaryTech/24_sharp.svg';
import SVGSocialMilitaryTech_20_filled from '../../svg/social/SocialMilitaryTech/20_filled.svg';
import SVGSocialMilitaryTech_24_filled from '../../svg/social/SocialMilitaryTech/24_filled.svg';
import SVGSocialMilitaryTech_20_round from '../../svg/social/SocialMilitaryTech/20_round.svg';
import SVGSocialMilitaryTech_24_round from '../../svg/social/SocialMilitaryTech/24_round.svg';

export const IconSocialMilitaryTech20outlined = () => <SVGSocialMilitaryTech_20_outlined />;
export const IconSocialMilitaryTech24outlined = () => <SVGSocialMilitaryTech_24_outlined />;
export const IconSocialMilitaryTech20twotone = () => <SVGSocialMilitaryTech_20_twotone />;
export const IconSocialMilitaryTech24twotone = () => <SVGSocialMilitaryTech_24_twotone />;
export const IconSocialMilitaryTech20sharp = () => <SVGSocialMilitaryTech_20_sharp />;
export const IconSocialMilitaryTech24sharp = () => <SVGSocialMilitaryTech_24_sharp />;
export const IconSocialMilitaryTech20filled = () => <SVGSocialMilitaryTech_20_filled />;
export const IconSocialMilitaryTech24filled = () => <SVGSocialMilitaryTech_24_filled />;
export const IconSocialMilitaryTech20round = () => <SVGSocialMilitaryTech_20_round />;
export const IconSocialMilitaryTech24round = () => <SVGSocialMilitaryTech_24_round />;
