import React from "react";
import SVGSocialCatchingPokemon_20_outlined from '../../svg/social/SocialCatchingPokemon/20_outlined.svg';
import SVGSocialCatchingPokemon_24_outlined from '../../svg/social/SocialCatchingPokemon/24_outlined.svg';
import SVGSocialCatchingPokemon_20_twotone from '../../svg/social/SocialCatchingPokemon/20_twotone.svg';
import SVGSocialCatchingPokemon_24_twotone from '../../svg/social/SocialCatchingPokemon/24_twotone.svg';
import SVGSocialCatchingPokemon_20_sharp from '../../svg/social/SocialCatchingPokemon/20_sharp.svg';
import SVGSocialCatchingPokemon_24_sharp from '../../svg/social/SocialCatchingPokemon/24_sharp.svg';
import SVGSocialCatchingPokemon_20_filled from '../../svg/social/SocialCatchingPokemon/20_filled.svg';
import SVGSocialCatchingPokemon_24_filled from '../../svg/social/SocialCatchingPokemon/24_filled.svg';
import SVGSocialCatchingPokemon_20_round from '../../svg/social/SocialCatchingPokemon/20_round.svg';
import SVGSocialCatchingPokemon_24_round from '../../svg/social/SocialCatchingPokemon/24_round.svg';

export const IconSocialCatchingPokemon20outlined = () => <SVGSocialCatchingPokemon_20_outlined />;
export const IconSocialCatchingPokemon24outlined = () => <SVGSocialCatchingPokemon_24_outlined />;
export const IconSocialCatchingPokemon20twotone = () => <SVGSocialCatchingPokemon_20_twotone />;
export const IconSocialCatchingPokemon24twotone = () => <SVGSocialCatchingPokemon_24_twotone />;
export const IconSocialCatchingPokemon20sharp = () => <SVGSocialCatchingPokemon_20_sharp />;
export const IconSocialCatchingPokemon24sharp = () => <SVGSocialCatchingPokemon_24_sharp />;
export const IconSocialCatchingPokemon20filled = () => <SVGSocialCatchingPokemon_20_filled />;
export const IconSocialCatchingPokemon24filled = () => <SVGSocialCatchingPokemon_24_filled />;
export const IconSocialCatchingPokemon20round = () => <SVGSocialCatchingPokemon_20_round />;
export const IconSocialCatchingPokemon24round = () => <SVGSocialCatchingPokemon_24_round />;
