import React from "react";
import SVGSocialPerson4_20_outlined from '../../svg/social/SocialPerson4/20_outlined.svg';
import SVGSocialPerson4_24_outlined from '../../svg/social/SocialPerson4/24_outlined.svg';
import SVGSocialPerson4_20_twotone from '../../svg/social/SocialPerson4/20_twotone.svg';
import SVGSocialPerson4_24_twotone from '../../svg/social/SocialPerson4/24_twotone.svg';
import SVGSocialPerson4_20_sharp from '../../svg/social/SocialPerson4/20_sharp.svg';
import SVGSocialPerson4_24_sharp from '../../svg/social/SocialPerson4/24_sharp.svg';
import SVGSocialPerson4_20_filled from '../../svg/social/SocialPerson4/20_filled.svg';
import SVGSocialPerson4_24_filled from '../../svg/social/SocialPerson4/24_filled.svg';
import SVGSocialPerson4_20_round from '../../svg/social/SocialPerson4/20_round.svg';
import SVGSocialPerson4_24_round from '../../svg/social/SocialPerson4/24_round.svg';

export const IconSocialPerson420outlined = () => <SVGSocialPerson4_20_outlined />;
export const IconSocialPerson424outlined = () => <SVGSocialPerson4_24_outlined />;
export const IconSocialPerson420twotone = () => <SVGSocialPerson4_20_twotone />;
export const IconSocialPerson424twotone = () => <SVGSocialPerson4_24_twotone />;
export const IconSocialPerson420sharp = () => <SVGSocialPerson4_20_sharp />;
export const IconSocialPerson424sharp = () => <SVGSocialPerson4_24_sharp />;
export const IconSocialPerson420filled = () => <SVGSocialPerson4_20_filled />;
export const IconSocialPerson424filled = () => <SVGSocialPerson4_24_filled />;
export const IconSocialPerson420round = () => <SVGSocialPerson4_20_round />;
export const IconSocialPerson424round = () => <SVGSocialPerson4_24_round />;
