import React from "react";
import SVGSocialWoman_20_outlined from '../../svg/social/SocialWoman/20_outlined.svg';
import SVGSocialWoman_24_outlined from '../../svg/social/SocialWoman/24_outlined.svg';
import SVGSocialWoman_20_twotone from '../../svg/social/SocialWoman/20_twotone.svg';
import SVGSocialWoman_24_twotone from '../../svg/social/SocialWoman/24_twotone.svg';
import SVGSocialWoman_20_sharp from '../../svg/social/SocialWoman/20_sharp.svg';
import SVGSocialWoman_24_sharp from '../../svg/social/SocialWoman/24_sharp.svg';
import SVGSocialWoman_20_filled from '../../svg/social/SocialWoman/20_filled.svg';
import SVGSocialWoman_24_filled from '../../svg/social/SocialWoman/24_filled.svg';
import SVGSocialWoman_20_round from '../../svg/social/SocialWoman/20_round.svg';
import SVGSocialWoman_24_round from '../../svg/social/SocialWoman/24_round.svg';

export const IconSocialWoman20outlined = () => <SVGSocialWoman_20_outlined />;
export const IconSocialWoman24outlined = () => <SVGSocialWoman_24_outlined />;
export const IconSocialWoman20twotone = () => <SVGSocialWoman_20_twotone />;
export const IconSocialWoman24twotone = () => <SVGSocialWoman_24_twotone />;
export const IconSocialWoman20sharp = () => <SVGSocialWoman_20_sharp />;
export const IconSocialWoman24sharp = () => <SVGSocialWoman_24_sharp />;
export const IconSocialWoman20filled = () => <SVGSocialWoman_20_filled />;
export const IconSocialWoman24filled = () => <SVGSocialWoman_24_filled />;
export const IconSocialWoman20round = () => <SVGSocialWoman_20_round />;
export const IconSocialWoman24round = () => <SVGSocialWoman_24_round />;
