import React from "react";
import SVGSocialFitbit_20_outlined from '../../svg/social/SocialFitbit/20_outlined.svg';
import SVGSocialFitbit_24_outlined from '../../svg/social/SocialFitbit/24_outlined.svg';
import SVGSocialFitbit_20_twotone from '../../svg/social/SocialFitbit/20_twotone.svg';
import SVGSocialFitbit_24_twotone from '../../svg/social/SocialFitbit/24_twotone.svg';
import SVGSocialFitbit_20_sharp from '../../svg/social/SocialFitbit/20_sharp.svg';
import SVGSocialFitbit_24_sharp from '../../svg/social/SocialFitbit/24_sharp.svg';
import SVGSocialFitbit_20_filled from '../../svg/social/SocialFitbit/20_filled.svg';
import SVGSocialFitbit_24_filled from '../../svg/social/SocialFitbit/24_filled.svg';
import SVGSocialFitbit_20_round from '../../svg/social/SocialFitbit/20_round.svg';
import SVGSocialFitbit_24_round from '../../svg/social/SocialFitbit/24_round.svg';

export const IconSocialFitbit20outlined = () => <SVGSocialFitbit_20_outlined />;
export const IconSocialFitbit24outlined = () => <SVGSocialFitbit_24_outlined />;
export const IconSocialFitbit20twotone = () => <SVGSocialFitbit_20_twotone />;
export const IconSocialFitbit24twotone = () => <SVGSocialFitbit_24_twotone />;
export const IconSocialFitbit20sharp = () => <SVGSocialFitbit_20_sharp />;
export const IconSocialFitbit24sharp = () => <SVGSocialFitbit_24_sharp />;
export const IconSocialFitbit20filled = () => <SVGSocialFitbit_20_filled />;
export const IconSocialFitbit24filled = () => <SVGSocialFitbit_24_filled />;
export const IconSocialFitbit20round = () => <SVGSocialFitbit_20_round />;
export const IconSocialFitbit24round = () => <SVGSocialFitbit_24_round />;
