import React from "react";
import SVGSocialGirl_20_outlined from '../../svg/social/SocialGirl/20_outlined.svg';
import SVGSocialGirl_24_outlined from '../../svg/social/SocialGirl/24_outlined.svg';
import SVGSocialGirl_20_twotone from '../../svg/social/SocialGirl/20_twotone.svg';
import SVGSocialGirl_24_twotone from '../../svg/social/SocialGirl/24_twotone.svg';
import SVGSocialGirl_20_sharp from '../../svg/social/SocialGirl/20_sharp.svg';
import SVGSocialGirl_24_sharp from '../../svg/social/SocialGirl/24_sharp.svg';
import SVGSocialGirl_20_filled from '../../svg/social/SocialGirl/20_filled.svg';
import SVGSocialGirl_24_filled from '../../svg/social/SocialGirl/24_filled.svg';
import SVGSocialGirl_20_round from '../../svg/social/SocialGirl/20_round.svg';
import SVGSocialGirl_24_round from '../../svg/social/SocialGirl/24_round.svg';

export const IconSocialGirl20outlined = () => <SVGSocialGirl_20_outlined />;
export const IconSocialGirl24outlined = () => <SVGSocialGirl_24_outlined />;
export const IconSocialGirl20twotone = () => <SVGSocialGirl_20_twotone />;
export const IconSocialGirl24twotone = () => <SVGSocialGirl_24_twotone />;
export const IconSocialGirl20sharp = () => <SVGSocialGirl_20_sharp />;
export const IconSocialGirl24sharp = () => <SVGSocialGirl_24_sharp />;
export const IconSocialGirl20filled = () => <SVGSocialGirl_20_filled />;
export const IconSocialGirl24filled = () => <SVGSocialGirl_24_filled />;
export const IconSocialGirl20round = () => <SVGSocialGirl_20_round />;
export const IconSocialGirl24round = () => <SVGSocialGirl_24_round />;
