import React from "react";
import SVGSocialPersonOff_20_outlined from '../../svg/social/SocialPersonOff/20_outlined.svg';
import SVGSocialPersonOff_24_outlined from '../../svg/social/SocialPersonOff/24_outlined.svg';
import SVGSocialPersonOff_20_twotone from '../../svg/social/SocialPersonOff/20_twotone.svg';
import SVGSocialPersonOff_24_twotone from '../../svg/social/SocialPersonOff/24_twotone.svg';
import SVGSocialPersonOff_20_sharp from '../../svg/social/SocialPersonOff/20_sharp.svg';
import SVGSocialPersonOff_24_sharp from '../../svg/social/SocialPersonOff/24_sharp.svg';
import SVGSocialPersonOff_20_filled from '../../svg/social/SocialPersonOff/20_filled.svg';
import SVGSocialPersonOff_24_filled from '../../svg/social/SocialPersonOff/24_filled.svg';
import SVGSocialPersonOff_20_round from '../../svg/social/SocialPersonOff/20_round.svg';
import SVGSocialPersonOff_24_round from '../../svg/social/SocialPersonOff/24_round.svg';

export const IconSocialPersonOff20outlined = () => <SVGSocialPersonOff_20_outlined />;
export const IconSocialPersonOff24outlined = () => <SVGSocialPersonOff_24_outlined />;
export const IconSocialPersonOff20twotone = () => <SVGSocialPersonOff_20_twotone />;
export const IconSocialPersonOff24twotone = () => <SVGSocialPersonOff_24_twotone />;
export const IconSocialPersonOff20sharp = () => <SVGSocialPersonOff_20_sharp />;
export const IconSocialPersonOff24sharp = () => <SVGSocialPersonOff_24_sharp />;
export const IconSocialPersonOff20filled = () => <SVGSocialPersonOff_20_filled />;
export const IconSocialPersonOff24filled = () => <SVGSocialPersonOff_24_filled />;
export const IconSocialPersonOff20round = () => <SVGSocialPersonOff_20_round />;
export const IconSocialPersonOff24round = () => <SVGSocialPersonOff_24_round />;
