import React from "react";
import SVGSocialEngineering_20_outlined from '../../svg/social/SocialEngineering/20_outlined.svg';
import SVGSocialEngineering_24_outlined from '../../svg/social/SocialEngineering/24_outlined.svg';
import SVGSocialEngineering_20_twotone from '../../svg/social/SocialEngineering/20_twotone.svg';
import SVGSocialEngineering_24_twotone from '../../svg/social/SocialEngineering/24_twotone.svg';
import SVGSocialEngineering_20_sharp from '../../svg/social/SocialEngineering/20_sharp.svg';
import SVGSocialEngineering_24_sharp from '../../svg/social/SocialEngineering/24_sharp.svg';
import SVGSocialEngineering_20_filled from '../../svg/social/SocialEngineering/20_filled.svg';
import SVGSocialEngineering_24_filled from '../../svg/social/SocialEngineering/24_filled.svg';
import SVGSocialEngineering_20_round from '../../svg/social/SocialEngineering/20_round.svg';
import SVGSocialEngineering_24_round from '../../svg/social/SocialEngineering/24_round.svg';

export const IconSocialEngineering20outlined = () => <SVGSocialEngineering_20_outlined />;
export const IconSocialEngineering24outlined = () => <SVGSocialEngineering_24_outlined />;
export const IconSocialEngineering20twotone = () => <SVGSocialEngineering_20_twotone />;
export const IconSocialEngineering24twotone = () => <SVGSocialEngineering_24_twotone />;
export const IconSocialEngineering20sharp = () => <SVGSocialEngineering_20_sharp />;
export const IconSocialEngineering24sharp = () => <SVGSocialEngineering_24_sharp />;
export const IconSocialEngineering20filled = () => <SVGSocialEngineering_20_filled />;
export const IconSocialEngineering24filled = () => <SVGSocialEngineering_24_filled />;
export const IconSocialEngineering20round = () => <SVGSocialEngineering_20_round />;
export const IconSocialEngineering24round = () => <SVGSocialEngineering_24_round />;
