import React from "react";
import SVGSocialTornado_20_outlined from '../../svg/social/SocialTornado/20_outlined.svg';
import SVGSocialTornado_24_outlined from '../../svg/social/SocialTornado/24_outlined.svg';
import SVGSocialTornado_20_twotone from '../../svg/social/SocialTornado/20_twotone.svg';
import SVGSocialTornado_24_twotone from '../../svg/social/SocialTornado/24_twotone.svg';
import SVGSocialTornado_20_sharp from '../../svg/social/SocialTornado/20_sharp.svg';
import SVGSocialTornado_24_sharp from '../../svg/social/SocialTornado/24_sharp.svg';
import SVGSocialTornado_20_filled from '../../svg/social/SocialTornado/20_filled.svg';
import SVGSocialTornado_24_filled from '../../svg/social/SocialTornado/24_filled.svg';
import SVGSocialTornado_20_round from '../../svg/social/SocialTornado/20_round.svg';
import SVGSocialTornado_24_round from '../../svg/social/SocialTornado/24_round.svg';

export const IconSocialTornado20outlined = () => <SVGSocialTornado_20_outlined />;
export const IconSocialTornado24outlined = () => <SVGSocialTornado_24_outlined />;
export const IconSocialTornado20twotone = () => <SVGSocialTornado_20_twotone />;
export const IconSocialTornado24twotone = () => <SVGSocialTornado_24_twotone />;
export const IconSocialTornado20sharp = () => <SVGSocialTornado_20_sharp />;
export const IconSocialTornado24sharp = () => <SVGSocialTornado_24_sharp />;
export const IconSocialTornado20filled = () => <SVGSocialTornado_20_filled />;
export const IconSocialTornado24filled = () => <SVGSocialTornado_24_filled />;
export const IconSocialTornado20round = () => <SVGSocialTornado_20_round />;
export const IconSocialTornado24round = () => <SVGSocialTornado_24_round />;
