import React from "react";
import SVGSocialMan2_20_outlined from '../../svg/social/SocialMan2/20_outlined.svg';
import SVGSocialMan2_24_outlined from '../../svg/social/SocialMan2/24_outlined.svg';
import SVGSocialMan2_20_twotone from '../../svg/social/SocialMan2/20_twotone.svg';
import SVGSocialMan2_24_twotone from '../../svg/social/SocialMan2/24_twotone.svg';
import SVGSocialMan2_20_sharp from '../../svg/social/SocialMan2/20_sharp.svg';
import SVGSocialMan2_24_sharp from '../../svg/social/SocialMan2/24_sharp.svg';
import SVGSocialMan2_20_filled from '../../svg/social/SocialMan2/20_filled.svg';
import SVGSocialMan2_24_filled from '../../svg/social/SocialMan2/24_filled.svg';
import SVGSocialMan2_20_round from '../../svg/social/SocialMan2/20_round.svg';
import SVGSocialMan2_24_round from '../../svg/social/SocialMan2/24_round.svg';

export const IconSocialMan220outlined = () => <SVGSocialMan2_20_outlined />;
export const IconSocialMan224outlined = () => <SVGSocialMan2_24_outlined />;
export const IconSocialMan220twotone = () => <SVGSocialMan2_20_twotone />;
export const IconSocialMan224twotone = () => <SVGSocialMan2_24_twotone />;
export const IconSocialMan220sharp = () => <SVGSocialMan2_20_sharp />;
export const IconSocialMan224sharp = () => <SVGSocialMan2_24_sharp />;
export const IconSocialMan220filled = () => <SVGSocialMan2_20_filled />;
export const IconSocialMan224filled = () => <SVGSocialMan2_24_filled />;
export const IconSocialMan220round = () => <SVGSocialMan2_20_round />;
export const IconSocialMan224round = () => <SVGSocialMan2_24_round />;
