import React from "react";
import SVGSocialWavingHand_20_outlined from '../../svg/social/SocialWavingHand/20_outlined.svg';
import SVGSocialWavingHand_24_outlined from '../../svg/social/SocialWavingHand/24_outlined.svg';
import SVGSocialWavingHand_20_twotone from '../../svg/social/SocialWavingHand/20_twotone.svg';
import SVGSocialWavingHand_24_twotone from '../../svg/social/SocialWavingHand/24_twotone.svg';
import SVGSocialWavingHand_20_sharp from '../../svg/social/SocialWavingHand/20_sharp.svg';
import SVGSocialWavingHand_24_sharp from '../../svg/social/SocialWavingHand/24_sharp.svg';
import SVGSocialWavingHand_20_filled from '../../svg/social/SocialWavingHand/20_filled.svg';
import SVGSocialWavingHand_24_filled from '../../svg/social/SocialWavingHand/24_filled.svg';
import SVGSocialWavingHand_20_round from '../../svg/social/SocialWavingHand/20_round.svg';
import SVGSocialWavingHand_24_round from '../../svg/social/SocialWavingHand/24_round.svg';

export const IconSocialWavingHand20outlined = () => <SVGSocialWavingHand_20_outlined />;
export const IconSocialWavingHand24outlined = () => <SVGSocialWavingHand_24_outlined />;
export const IconSocialWavingHand20twotone = () => <SVGSocialWavingHand_20_twotone />;
export const IconSocialWavingHand24twotone = () => <SVGSocialWavingHand_24_twotone />;
export const IconSocialWavingHand20sharp = () => <SVGSocialWavingHand_20_sharp />;
export const IconSocialWavingHand24sharp = () => <SVGSocialWavingHand_24_sharp />;
export const IconSocialWavingHand20filled = () => <SVGSocialWavingHand_20_filled />;
export const IconSocialWavingHand24filled = () => <SVGSocialWavingHand_24_filled />;
export const IconSocialWavingHand20round = () => <SVGSocialWavingHand_20_round />;
export const IconSocialWavingHand24round = () => <SVGSocialWavingHand_24_round />;
