import React from "react";
import SVGSocialSportsEsports_20_outlined from '../../svg/social/SocialSportsEsports/20_outlined.svg';
import SVGSocialSportsEsports_24_outlined from '../../svg/social/SocialSportsEsports/24_outlined.svg';
import SVGSocialSportsEsports_20_twotone from '../../svg/social/SocialSportsEsports/20_twotone.svg';
import SVGSocialSportsEsports_24_twotone from '../../svg/social/SocialSportsEsports/24_twotone.svg';
import SVGSocialSportsEsports_20_sharp from '../../svg/social/SocialSportsEsports/20_sharp.svg';
import SVGSocialSportsEsports_24_sharp from '../../svg/social/SocialSportsEsports/24_sharp.svg';
import SVGSocialSportsEsports_20_filled from '../../svg/social/SocialSportsEsports/20_filled.svg';
import SVGSocialSportsEsports_24_filled from '../../svg/social/SocialSportsEsports/24_filled.svg';
import SVGSocialSportsEsports_20_round from '../../svg/social/SocialSportsEsports/20_round.svg';
import SVGSocialSportsEsports_24_round from '../../svg/social/SocialSportsEsports/24_round.svg';

export const IconSocialSportsEsports20outlined = () => <SVGSocialSportsEsports_20_outlined />;
export const IconSocialSportsEsports24outlined = () => <SVGSocialSportsEsports_24_outlined />;
export const IconSocialSportsEsports20twotone = () => <SVGSocialSportsEsports_20_twotone />;
export const IconSocialSportsEsports24twotone = () => <SVGSocialSportsEsports_24_twotone />;
export const IconSocialSportsEsports20sharp = () => <SVGSocialSportsEsports_20_sharp />;
export const IconSocialSportsEsports24sharp = () => <SVGSocialSportsEsports_24_sharp />;
export const IconSocialSportsEsports20filled = () => <SVGSocialSportsEsports_20_filled />;
export const IconSocialSportsEsports24filled = () => <SVGSocialSportsEsports_24_filled />;
export const IconSocialSportsEsports20round = () => <SVGSocialSportsEsports_20_round />;
export const IconSocialSportsEsports24round = () => <SVGSocialSportsEsports_24_round />;
