import React from "react";
import SVGSocialArchitecture_20_outlined from '../../svg/social/SocialArchitecture/20_outlined.svg';
import SVGSocialArchitecture_24_outlined from '../../svg/social/SocialArchitecture/24_outlined.svg';
import SVGSocialArchitecture_20_twotone from '../../svg/social/SocialArchitecture/20_twotone.svg';
import SVGSocialArchitecture_24_twotone from '../../svg/social/SocialArchitecture/24_twotone.svg';
import SVGSocialArchitecture_20_sharp from '../../svg/social/SocialArchitecture/20_sharp.svg';
import SVGSocialArchitecture_24_sharp from '../../svg/social/SocialArchitecture/24_sharp.svg';
import SVGSocialArchitecture_20_filled from '../../svg/social/SocialArchitecture/20_filled.svg';
import SVGSocialArchitecture_24_filled from '../../svg/social/SocialArchitecture/24_filled.svg';
import SVGSocialArchitecture_20_round from '../../svg/social/SocialArchitecture/20_round.svg';
import SVGSocialArchitecture_24_round from '../../svg/social/SocialArchitecture/24_round.svg';

export const IconSocialArchitecture20outlined = () => <SVGSocialArchitecture_20_outlined />;
export const IconSocialArchitecture24outlined = () => <SVGSocialArchitecture_24_outlined />;
export const IconSocialArchitecture20twotone = () => <SVGSocialArchitecture_20_twotone />;
export const IconSocialArchitecture24twotone = () => <SVGSocialArchitecture_24_twotone />;
export const IconSocialArchitecture20sharp = () => <SVGSocialArchitecture_20_sharp />;
export const IconSocialArchitecture24sharp = () => <SVGSocialArchitecture_24_sharp />;
export const IconSocialArchitecture20filled = () => <SVGSocialArchitecture_20_filled />;
export const IconSocialArchitecture24filled = () => <SVGSocialArchitecture_24_filled />;
export const IconSocialArchitecture20round = () => <SVGSocialArchitecture_20_round />;
export const IconSocialArchitecture24round = () => <SVGSocialArchitecture_24_round />;
