import React from "react";
import SVGSocialSurfing_20_outlined from '../../svg/social/SocialSurfing/20_outlined.svg';
import SVGSocialSurfing_24_outlined from '../../svg/social/SocialSurfing/24_outlined.svg';
import SVGSocialSurfing_20_twotone from '../../svg/social/SocialSurfing/20_twotone.svg';
import SVGSocialSurfing_24_twotone from '../../svg/social/SocialSurfing/24_twotone.svg';
import SVGSocialSurfing_20_sharp from '../../svg/social/SocialSurfing/20_sharp.svg';
import SVGSocialSurfing_24_sharp from '../../svg/social/SocialSurfing/24_sharp.svg';
import SVGSocialSurfing_20_filled from '../../svg/social/SocialSurfing/20_filled.svg';
import SVGSocialSurfing_24_filled from '../../svg/social/SocialSurfing/24_filled.svg';
import SVGSocialSurfing_20_round from '../../svg/social/SocialSurfing/20_round.svg';
import SVGSocialSurfing_24_round from '../../svg/social/SocialSurfing/24_round.svg';

export const IconSocialSurfing20outlined = () => <SVGSocialSurfing_20_outlined />;
export const IconSocialSurfing24outlined = () => <SVGSocialSurfing_24_outlined />;
export const IconSocialSurfing20twotone = () => <SVGSocialSurfing_20_twotone />;
export const IconSocialSurfing24twotone = () => <SVGSocialSurfing_24_twotone />;
export const IconSocialSurfing20sharp = () => <SVGSocialSurfing_20_sharp />;
export const IconSocialSurfing24sharp = () => <SVGSocialSurfing_24_sharp />;
export const IconSocialSurfing20filled = () => <SVGSocialSurfing_20_filled />;
export const IconSocialSurfing24filled = () => <SVGSocialSurfing_24_filled />;
export const IconSocialSurfing20round = () => <SVGSocialSurfing_20_round />;
export const IconSocialSurfing24round = () => <SVGSocialSurfing_24_round />;
