import React from "react";
import SVGSocialEmojiNature_20_outlined from '../../svg/social/SocialEmojiNature/20_outlined.svg';
import SVGSocialEmojiNature_24_outlined from '../../svg/social/SocialEmojiNature/24_outlined.svg';
import SVGSocialEmojiNature_20_twotone from '../../svg/social/SocialEmojiNature/20_twotone.svg';
import SVGSocialEmojiNature_24_twotone from '../../svg/social/SocialEmojiNature/24_twotone.svg';
import SVGSocialEmojiNature_20_sharp from '../../svg/social/SocialEmojiNature/20_sharp.svg';
import SVGSocialEmojiNature_24_sharp from '../../svg/social/SocialEmojiNature/24_sharp.svg';
import SVGSocialEmojiNature_20_filled from '../../svg/social/SocialEmojiNature/20_filled.svg';
import SVGSocialEmojiNature_24_filled from '../../svg/social/SocialEmojiNature/24_filled.svg';
import SVGSocialEmojiNature_20_round from '../../svg/social/SocialEmojiNature/20_round.svg';
import SVGSocialEmojiNature_24_round from '../../svg/social/SocialEmojiNature/24_round.svg';

export const IconSocialEmojiNature20outlined = () => <SVGSocialEmojiNature_20_outlined />;
export const IconSocialEmojiNature24outlined = () => <SVGSocialEmojiNature_24_outlined />;
export const IconSocialEmojiNature20twotone = () => <SVGSocialEmojiNature_20_twotone />;
export const IconSocialEmojiNature24twotone = () => <SVGSocialEmojiNature_24_twotone />;
export const IconSocialEmojiNature20sharp = () => <SVGSocialEmojiNature_20_sharp />;
export const IconSocialEmojiNature24sharp = () => <SVGSocialEmojiNature_24_sharp />;
export const IconSocialEmojiNature20filled = () => <SVGSocialEmojiNature_20_filled />;
export const IconSocialEmojiNature24filled = () => <SVGSocialEmojiNature_24_filled />;
export const IconSocialEmojiNature20round = () => <SVGSocialEmojiNature_20_round />;
export const IconSocialEmojiNature24round = () => <SVGSocialEmojiNature_24_round />;
