import React from "react";
import SVGSocialLandslide_20_outlined from '../../svg/social/SocialLandslide/20_outlined.svg';
import SVGSocialLandslide_24_outlined from '../../svg/social/SocialLandslide/24_outlined.svg';
import SVGSocialLandslide_20_twotone from '../../svg/social/SocialLandslide/20_twotone.svg';
import SVGSocialLandslide_24_twotone from '../../svg/social/SocialLandslide/24_twotone.svg';
import SVGSocialLandslide_20_sharp from '../../svg/social/SocialLandslide/20_sharp.svg';
import SVGSocialLandslide_24_sharp from '../../svg/social/SocialLandslide/24_sharp.svg';
import SVGSocialLandslide_20_filled from '../../svg/social/SocialLandslide/20_filled.svg';
import SVGSocialLandslide_24_filled from '../../svg/social/SocialLandslide/24_filled.svg';
import SVGSocialLandslide_20_round from '../../svg/social/SocialLandslide/20_round.svg';
import SVGSocialLandslide_24_round from '../../svg/social/SocialLandslide/24_round.svg';

export const IconSocialLandslide20outlined = () => <SVGSocialLandslide_20_outlined />;
export const IconSocialLandslide24outlined = () => <SVGSocialLandslide_24_outlined />;
export const IconSocialLandslide20twotone = () => <SVGSocialLandslide_20_twotone />;
export const IconSocialLandslide24twotone = () => <SVGSocialLandslide_24_twotone />;
export const IconSocialLandslide20sharp = () => <SVGSocialLandslide_20_sharp />;
export const IconSocialLandslide24sharp = () => <SVGSocialLandslide_24_sharp />;
export const IconSocialLandslide20filled = () => <SVGSocialLandslide_20_filled />;
export const IconSocialLandslide24filled = () => <SVGSocialLandslide_24_filled />;
export const IconSocialLandslide20round = () => <SVGSocialLandslide_20_round />;
export const IconSocialLandslide24round = () => <SVGSocialLandslide_24_round />;
