import React from "react";
import SVGSocialRealEstateAgent_20_outlined from '../../svg/social/SocialRealEstateAgent/20_outlined.svg';
import SVGSocialRealEstateAgent_24_outlined from '../../svg/social/SocialRealEstateAgent/24_outlined.svg';
import SVGSocialRealEstateAgent_20_twotone from '../../svg/social/SocialRealEstateAgent/20_twotone.svg';
import SVGSocialRealEstateAgent_24_twotone from '../../svg/social/SocialRealEstateAgent/24_twotone.svg';
import SVGSocialRealEstateAgent_20_sharp from '../../svg/social/SocialRealEstateAgent/20_sharp.svg';
import SVGSocialRealEstateAgent_24_sharp from '../../svg/social/SocialRealEstateAgent/24_sharp.svg';
import SVGSocialRealEstateAgent_20_filled from '../../svg/social/SocialRealEstateAgent/20_filled.svg';
import SVGSocialRealEstateAgent_24_filled from '../../svg/social/SocialRealEstateAgent/24_filled.svg';
import SVGSocialRealEstateAgent_20_round from '../../svg/social/SocialRealEstateAgent/20_round.svg';
import SVGSocialRealEstateAgent_24_round from '../../svg/social/SocialRealEstateAgent/24_round.svg';

export const IconSocialRealEstateAgent20outlined = () => <SVGSocialRealEstateAgent_20_outlined />;
export const IconSocialRealEstateAgent24outlined = () => <SVGSocialRealEstateAgent_24_outlined />;
export const IconSocialRealEstateAgent20twotone = () => <SVGSocialRealEstateAgent_20_twotone />;
export const IconSocialRealEstateAgent24twotone = () => <SVGSocialRealEstateAgent_24_twotone />;
export const IconSocialRealEstateAgent20sharp = () => <SVGSocialRealEstateAgent_20_sharp />;
export const IconSocialRealEstateAgent24sharp = () => <SVGSocialRealEstateAgent_24_sharp />;
export const IconSocialRealEstateAgent20filled = () => <SVGSocialRealEstateAgent_20_filled />;
export const IconSocialRealEstateAgent24filled = () => <SVGSocialRealEstateAgent_24_filled />;
export const IconSocialRealEstateAgent20round = () => <SVGSocialRealEstateAgent_20_round />;
export const IconSocialRealEstateAgent24round = () => <SVGSocialRealEstateAgent_24_round />;
