import React from "react";
import SVGSocialVaccines_20_outlined from '../../svg/social/SocialVaccines/20_outlined.svg';
import SVGSocialVaccines_24_outlined from '../../svg/social/SocialVaccines/24_outlined.svg';
import SVGSocialVaccines_20_twotone from '../../svg/social/SocialVaccines/20_twotone.svg';
import SVGSocialVaccines_24_twotone from '../../svg/social/SocialVaccines/24_twotone.svg';
import SVGSocialVaccines_20_sharp from '../../svg/social/SocialVaccines/20_sharp.svg';
import SVGSocialVaccines_24_sharp from '../../svg/social/SocialVaccines/24_sharp.svg';
import SVGSocialVaccines_20_filled from '../../svg/social/SocialVaccines/20_filled.svg';
import SVGSocialVaccines_24_filled from '../../svg/social/SocialVaccines/24_filled.svg';
import SVGSocialVaccines_20_round from '../../svg/social/SocialVaccines/20_round.svg';
import SVGSocialVaccines_24_round from '../../svg/social/SocialVaccines/24_round.svg';

export const IconSocialVaccines20outlined = () => <SVGSocialVaccines_20_outlined />;
export const IconSocialVaccines24outlined = () => <SVGSocialVaccines_24_outlined />;
export const IconSocialVaccines20twotone = () => <SVGSocialVaccines_20_twotone />;
export const IconSocialVaccines24twotone = () => <SVGSocialVaccines_24_twotone />;
export const IconSocialVaccines20sharp = () => <SVGSocialVaccines_20_sharp />;
export const IconSocialVaccines24sharp = () => <SVGSocialVaccines_24_sharp />;
export const IconSocialVaccines20filled = () => <SVGSocialVaccines_20_filled />;
export const IconSocialVaccines24filled = () => <SVGSocialVaccines_24_filled />;
export const IconSocialVaccines20round = () => <SVGSocialVaccines_20_round />;
export const IconSocialVaccines24round = () => <SVGSocialVaccines_24_round />;
