import React from "react";
import SVGSocialEmojiFoodBeverage_20_outlined from '../../svg/social/SocialEmojiFoodBeverage/20_outlined.svg';
import SVGSocialEmojiFoodBeverage_24_outlined from '../../svg/social/SocialEmojiFoodBeverage/24_outlined.svg';
import SVGSocialEmojiFoodBeverage_20_twotone from '../../svg/social/SocialEmojiFoodBeverage/20_twotone.svg';
import SVGSocialEmojiFoodBeverage_24_twotone from '../../svg/social/SocialEmojiFoodBeverage/24_twotone.svg';
import SVGSocialEmojiFoodBeverage_20_sharp from '../../svg/social/SocialEmojiFoodBeverage/20_sharp.svg';
import SVGSocialEmojiFoodBeverage_24_sharp from '../../svg/social/SocialEmojiFoodBeverage/24_sharp.svg';
import SVGSocialEmojiFoodBeverage_20_filled from '../../svg/social/SocialEmojiFoodBeverage/20_filled.svg';
import SVGSocialEmojiFoodBeverage_24_filled from '../../svg/social/SocialEmojiFoodBeverage/24_filled.svg';
import SVGSocialEmojiFoodBeverage_20_round from '../../svg/social/SocialEmojiFoodBeverage/20_round.svg';
import SVGSocialEmojiFoodBeverage_24_round from '../../svg/social/SocialEmojiFoodBeverage/24_round.svg';

export const IconSocialEmojiFoodBeverage20outlined = () => <SVGSocialEmojiFoodBeverage_20_outlined />;
export const IconSocialEmojiFoodBeverage24outlined = () => <SVGSocialEmojiFoodBeverage_24_outlined />;
export const IconSocialEmojiFoodBeverage20twotone = () => <SVGSocialEmojiFoodBeverage_20_twotone />;
export const IconSocialEmojiFoodBeverage24twotone = () => <SVGSocialEmojiFoodBeverage_24_twotone />;
export const IconSocialEmojiFoodBeverage20sharp = () => <SVGSocialEmojiFoodBeverage_20_sharp />;
export const IconSocialEmojiFoodBeverage24sharp = () => <SVGSocialEmojiFoodBeverage_24_sharp />;
export const IconSocialEmojiFoodBeverage20filled = () => <SVGSocialEmojiFoodBeverage_20_filled />;
export const IconSocialEmojiFoodBeverage24filled = () => <SVGSocialEmojiFoodBeverage_24_filled />;
export const IconSocialEmojiFoodBeverage20round = () => <SVGSocialEmojiFoodBeverage_20_round />;
export const IconSocialEmojiFoodBeverage24round = () => <SVGSocialEmojiFoodBeverage_24_round />;
