import React from "react";
import SVGSocialEmojiSymbols_20_outlined from '../../svg/social/SocialEmojiSymbols/20_outlined.svg';
import SVGSocialEmojiSymbols_24_outlined from '../../svg/social/SocialEmojiSymbols/24_outlined.svg';
import SVGSocialEmojiSymbols_20_twotone from '../../svg/social/SocialEmojiSymbols/20_twotone.svg';
import SVGSocialEmojiSymbols_24_twotone from '../../svg/social/SocialEmojiSymbols/24_twotone.svg';
import SVGSocialEmojiSymbols_20_sharp from '../../svg/social/SocialEmojiSymbols/20_sharp.svg';
import SVGSocialEmojiSymbols_24_sharp from '../../svg/social/SocialEmojiSymbols/24_sharp.svg';
import SVGSocialEmojiSymbols_20_filled from '../../svg/social/SocialEmojiSymbols/20_filled.svg';
import SVGSocialEmojiSymbols_24_filled from '../../svg/social/SocialEmojiSymbols/24_filled.svg';
import SVGSocialEmojiSymbols_20_round from '../../svg/social/SocialEmojiSymbols/20_round.svg';
import SVGSocialEmojiSymbols_24_round from '../../svg/social/SocialEmojiSymbols/24_round.svg';

export const IconSocialEmojiSymbols20outlined = () => <SVGSocialEmojiSymbols_20_outlined />;
export const IconSocialEmojiSymbols24outlined = () => <SVGSocialEmojiSymbols_24_outlined />;
export const IconSocialEmojiSymbols20twotone = () => <SVGSocialEmojiSymbols_20_twotone />;
export const IconSocialEmojiSymbols24twotone = () => <SVGSocialEmojiSymbols_24_twotone />;
export const IconSocialEmojiSymbols20sharp = () => <SVGSocialEmojiSymbols_20_sharp />;
export const IconSocialEmojiSymbols24sharp = () => <SVGSocialEmojiSymbols_24_sharp />;
export const IconSocialEmojiSymbols20filled = () => <SVGSocialEmojiSymbols_20_filled />;
export const IconSocialEmojiSymbols24filled = () => <SVGSocialEmojiSymbols_24_filled />;
export const IconSocialEmojiSymbols20round = () => <SVGSocialEmojiSymbols_20_round />;
export const IconSocialEmojiSymbols24round = () => <SVGSocialEmojiSymbols_24_round />;
