import React from "react";
import SVGAv5G_20_outlined from '../../svg/av/Av5G/20_outlined.svg';
import SVGAv5G_24_outlined from '../../svg/av/Av5G/24_outlined.svg';
import SVGAv5G_20_twotone from '../../svg/av/Av5G/20_twotone.svg';
import SVGAv5G_24_twotone from '../../svg/av/Av5G/24_twotone.svg';
import SVGAv5G_20_sharp from '../../svg/av/Av5G/20_sharp.svg';
import SVGAv5G_24_sharp from '../../svg/av/Av5G/24_sharp.svg';
import SVGAv5G_20_filled from '../../svg/av/Av5G/20_filled.svg';
import SVGAv5G_24_filled from '../../svg/av/Av5G/24_filled.svg';
import SVGAv5G_20_round from '../../svg/av/Av5G/20_round.svg';
import SVGAv5G_24_round from '../../svg/av/Av5G/24_round.svg';

export const IconAv5G20outlined = () => <SVGAv5G_20_outlined />;
export const IconAv5G24outlined = () => <SVGAv5G_24_outlined />;
export const IconAv5G20twotone = () => <SVGAv5G_20_twotone />;
export const IconAv5G24twotone = () => <SVGAv5G_24_twotone />;
export const IconAv5G20sharp = () => <SVGAv5G_20_sharp />;
export const IconAv5G24sharp = () => <SVGAv5G_24_sharp />;
export const IconAv5G20filled = () => <SVGAv5G_20_filled />;
export const IconAv5G24filled = () => <SVGAv5G_24_filled />;
export const IconAv5G20round = () => <SVGAv5G_20_round />;
export const IconAv5G24round = () => <SVGAv5G_24_round />;
