import React from "react";
import SVGAvInterpreterMode_20_outlined from '../../svg/av/AvInterpreterMode/20_outlined.svg';
import SVGAvInterpreterMode_24_outlined from '../../svg/av/AvInterpreterMode/24_outlined.svg';
import SVGAvInterpreterMode_20_twotone from '../../svg/av/AvInterpreterMode/20_twotone.svg';
import SVGAvInterpreterMode_24_twotone from '../../svg/av/AvInterpreterMode/24_twotone.svg';
import SVGAvInterpreterMode_20_sharp from '../../svg/av/AvInterpreterMode/20_sharp.svg';
import SVGAvInterpreterMode_24_sharp from '../../svg/av/AvInterpreterMode/24_sharp.svg';
import SVGAvInterpreterMode_20_filled from '../../svg/av/AvInterpreterMode/20_filled.svg';
import SVGAvInterpreterMode_24_filled from '../../svg/av/AvInterpreterMode/24_filled.svg';
import SVGAvInterpreterMode_20_round from '../../svg/av/AvInterpreterMode/20_round.svg';
import SVGAvInterpreterMode_24_round from '../../svg/av/AvInterpreterMode/24_round.svg';

export const IconAvInterpreterMode20outlined = () => <SVGAvInterpreterMode_20_outlined />;
export const IconAvInterpreterMode24outlined = () => <SVGAvInterpreterMode_24_outlined />;
export const IconAvInterpreterMode20twotone = () => <SVGAvInterpreterMode_20_twotone />;
export const IconAvInterpreterMode24twotone = () => <SVGAvInterpreterMode_24_twotone />;
export const IconAvInterpreterMode20sharp = () => <SVGAvInterpreterMode_20_sharp />;
export const IconAvInterpreterMode24sharp = () => <SVGAvInterpreterMode_24_sharp />;
export const IconAvInterpreterMode20filled = () => <SVGAvInterpreterMode_20_filled />;
export const IconAvInterpreterMode24filled = () => <SVGAvInterpreterMode_24_filled />;
export const IconAvInterpreterMode20round = () => <SVGAvInterpreterMode_20_round />;
export const IconAvInterpreterMode24round = () => <SVGAvInterpreterMode_24_round />;
