import React from "react";
import SVGAvLibraryAddCheck_20_outlined from '../../svg/av/AvLibraryAddCheck/20_outlined.svg';
import SVGAvLibraryAddCheck_24_outlined from '../../svg/av/AvLibraryAddCheck/24_outlined.svg';
import SVGAvLibraryAddCheck_20_twotone from '../../svg/av/AvLibraryAddCheck/20_twotone.svg';
import SVGAvLibraryAddCheck_24_twotone from '../../svg/av/AvLibraryAddCheck/24_twotone.svg';
import SVGAvLibraryAddCheck_20_sharp from '../../svg/av/AvLibraryAddCheck/20_sharp.svg';
import SVGAvLibraryAddCheck_24_sharp from '../../svg/av/AvLibraryAddCheck/24_sharp.svg';
import SVGAvLibraryAddCheck_20_filled from '../../svg/av/AvLibraryAddCheck/20_filled.svg';
import SVGAvLibraryAddCheck_24_filled from '../../svg/av/AvLibraryAddCheck/24_filled.svg';
import SVGAvLibraryAddCheck_20_round from '../../svg/av/AvLibraryAddCheck/20_round.svg';
import SVGAvLibraryAddCheck_24_round from '../../svg/av/AvLibraryAddCheck/24_round.svg';

export const IconAvLibraryAddCheck20outlined = () => <SVGAvLibraryAddCheck_20_outlined />;
export const IconAvLibraryAddCheck24outlined = () => <SVGAvLibraryAddCheck_24_outlined />;
export const IconAvLibraryAddCheck20twotone = () => <SVGAvLibraryAddCheck_20_twotone />;
export const IconAvLibraryAddCheck24twotone = () => <SVGAvLibraryAddCheck_24_twotone />;
export const IconAvLibraryAddCheck20sharp = () => <SVGAvLibraryAddCheck_20_sharp />;
export const IconAvLibraryAddCheck24sharp = () => <SVGAvLibraryAddCheck_24_sharp />;
export const IconAvLibraryAddCheck20filled = () => <SVGAvLibraryAddCheck_20_filled />;
export const IconAvLibraryAddCheck24filled = () => <SVGAvLibraryAddCheck_24_filled />;
export const IconAvLibraryAddCheck20round = () => <SVGAvLibraryAddCheck_20_round />;
export const IconAvLibraryAddCheck24round = () => <SVGAvLibraryAddCheck_24_round />;
