import React from "react";
import SVGAvPlaylistPlay_20_outlined from '../../svg/av/AvPlaylistPlay/20_outlined.svg';
import SVGAvPlaylistPlay_24_outlined from '../../svg/av/AvPlaylistPlay/24_outlined.svg';
import SVGAvPlaylistPlay_20_twotone from '../../svg/av/AvPlaylistPlay/20_twotone.svg';
import SVGAvPlaylistPlay_24_twotone from '../../svg/av/AvPlaylistPlay/24_twotone.svg';
import SVGAvPlaylistPlay_20_sharp from '../../svg/av/AvPlaylistPlay/20_sharp.svg';
import SVGAvPlaylistPlay_24_sharp from '../../svg/av/AvPlaylistPlay/24_sharp.svg';
import SVGAvPlaylistPlay_20_filled from '../../svg/av/AvPlaylistPlay/20_filled.svg';
import SVGAvPlaylistPlay_24_filled from '../../svg/av/AvPlaylistPlay/24_filled.svg';
import SVGAvPlaylistPlay_20_round from '../../svg/av/AvPlaylistPlay/20_round.svg';
import SVGAvPlaylistPlay_24_round from '../../svg/av/AvPlaylistPlay/24_round.svg';

export const IconAvPlaylistPlay20outlined = () => <SVGAvPlaylistPlay_20_outlined />;
export const IconAvPlaylistPlay24outlined = () => <SVGAvPlaylistPlay_24_outlined />;
export const IconAvPlaylistPlay20twotone = () => <SVGAvPlaylistPlay_20_twotone />;
export const IconAvPlaylistPlay24twotone = () => <SVGAvPlaylistPlay_24_twotone />;
export const IconAvPlaylistPlay20sharp = () => <SVGAvPlaylistPlay_20_sharp />;
export const IconAvPlaylistPlay24sharp = () => <SVGAvPlaylistPlay_24_sharp />;
export const IconAvPlaylistPlay20filled = () => <SVGAvPlaylistPlay_20_filled />;
export const IconAvPlaylistPlay24filled = () => <SVGAvPlaylistPlay_24_filled />;
export const IconAvPlaylistPlay20round = () => <SVGAvPlaylistPlay_20_round />;
export const IconAvPlaylistPlay24round = () => <SVGAvPlaylistPlay_24_round />;
