import React from "react";
import SVGAvPlaylistRemove_24_round from '../../svg/av/AvPlaylistRemove/24_round.svg';
import SVGAvPlaylistRemove_20_round from '../../svg/av/AvPlaylistRemove/20_round.svg';
import SVGAvPlaylistRemove_24_twotone from '../../svg/av/AvPlaylistRemove/24_twotone.svg';
import SVGAvPlaylistRemove_20_twotone from '../../svg/av/AvPlaylistRemove/20_twotone.svg';
import SVGAvPlaylistRemove_24_filled from '../../svg/av/AvPlaylistRemove/24_filled.svg';
import SVGAvPlaylistRemove_20_filled from '../../svg/av/AvPlaylistRemove/20_filled.svg';
import SVGAvPlaylistRemove_24_outlined from '../../svg/av/AvPlaylistRemove/24_outlined.svg';
import SVGAvPlaylistRemove_20_outlined from '../../svg/av/AvPlaylistRemove/20_outlined.svg';
import SVGAvPlaylistRemove_24_sharp from '../../svg/av/AvPlaylistRemove/24_sharp.svg';
import SVGAvPlaylistRemove_20_sharp from '../../svg/av/AvPlaylistRemove/20_sharp.svg';

export const IconAvPlaylistRemove24round = () => <SVGAvPlaylistRemove_24_round />;
export const IconAvPlaylistRemove20round = () => <SVGAvPlaylistRemove_20_round />;
export const IconAvPlaylistRemove24twotone = () => <SVGAvPlaylistRemove_24_twotone />;
export const IconAvPlaylistRemove20twotone = () => <SVGAvPlaylistRemove_20_twotone />;
export const IconAvPlaylistRemove24filled = () => <SVGAvPlaylistRemove_24_filled />;
export const IconAvPlaylistRemove20filled = () => <SVGAvPlaylistRemove_20_filled />;
export const IconAvPlaylistRemove24outlined = () => <SVGAvPlaylistRemove_24_outlined />;
export const IconAvPlaylistRemove20outlined = () => <SVGAvPlaylistRemove_20_outlined />;
export const IconAvPlaylistRemove24sharp = () => <SVGAvPlaylistRemove_24_sharp />;
export const IconAvPlaylistRemove20sharp = () => <SVGAvPlaylistRemove_20_sharp />;
