import React from "react";
import SVGAvPlaylistAddCheck_20_outlined from '../../svg/av/AvPlaylistAddCheck/20_outlined.svg';
import SVGAvPlaylistAddCheck_24_outlined from '../../svg/av/AvPlaylistAddCheck/24_outlined.svg';
import SVGAvPlaylistAddCheck_20_twotone from '../../svg/av/AvPlaylistAddCheck/20_twotone.svg';
import SVGAvPlaylistAddCheck_24_twotone from '../../svg/av/AvPlaylistAddCheck/24_twotone.svg';
import SVGAvPlaylistAddCheck_20_sharp from '../../svg/av/AvPlaylistAddCheck/20_sharp.svg';
import SVGAvPlaylistAddCheck_24_sharp from '../../svg/av/AvPlaylistAddCheck/24_sharp.svg';
import SVGAvPlaylistAddCheck_20_filled from '../../svg/av/AvPlaylistAddCheck/20_filled.svg';
import SVGAvPlaylistAddCheck_24_filled from '../../svg/av/AvPlaylistAddCheck/24_filled.svg';
import SVGAvPlaylistAddCheck_20_round from '../../svg/av/AvPlaylistAddCheck/20_round.svg';
import SVGAvPlaylistAddCheck_24_round from '../../svg/av/AvPlaylistAddCheck/24_round.svg';

export const IconAvPlaylistAddCheck20outlined = () => <SVGAvPlaylistAddCheck_20_outlined />;
export const IconAvPlaylistAddCheck24outlined = () => <SVGAvPlaylistAddCheck_24_outlined />;
export const IconAvPlaylistAddCheck20twotone = () => <SVGAvPlaylistAddCheck_20_twotone />;
export const IconAvPlaylistAddCheck24twotone = () => <SVGAvPlaylistAddCheck_24_twotone />;
export const IconAvPlaylistAddCheck20sharp = () => <SVGAvPlaylistAddCheck_20_sharp />;
export const IconAvPlaylistAddCheck24sharp = () => <SVGAvPlaylistAddCheck_24_sharp />;
export const IconAvPlaylistAddCheck20filled = () => <SVGAvPlaylistAddCheck_20_filled />;
export const IconAvPlaylistAddCheck24filled = () => <SVGAvPlaylistAddCheck_24_filled />;
export const IconAvPlaylistAddCheck20round = () => <SVGAvPlaylistAddCheck_20_round />;
export const IconAvPlaylistAddCheck24round = () => <SVGAvPlaylistAddCheck_24_round />;
