import React from "react";
import SVGAvStopCircle_24_round from '../../svg/av/AvStopCircle/24_round.svg';
import SVGAvStopCircle_20_round from '../../svg/av/AvStopCircle/20_round.svg';
import SVGAvStopCircle_24_twotone from '../../svg/av/AvStopCircle/24_twotone.svg';
import SVGAvStopCircle_20_twotone from '../../svg/av/AvStopCircle/20_twotone.svg';
import SVGAvStopCircle_24_filled from '../../svg/av/AvStopCircle/24_filled.svg';
import SVGAvStopCircle_20_filled from '../../svg/av/AvStopCircle/20_filled.svg';
import SVGAvStopCircle_24_outlined from '../../svg/av/AvStopCircle/24_outlined.svg';
import SVGAvStopCircle_20_outlined from '../../svg/av/AvStopCircle/20_outlined.svg';
import SVGAvStopCircle_24_sharp from '../../svg/av/AvStopCircle/24_sharp.svg';
import SVGAvStopCircle_20_sharp from '../../svg/av/AvStopCircle/20_sharp.svg';

export const IconAvStopCircle24round = () => <SVGAvStopCircle_24_round />;
export const IconAvStopCircle20round = () => <SVGAvStopCircle_20_round />;
export const IconAvStopCircle24twotone = () => <SVGAvStopCircle_24_twotone />;
export const IconAvStopCircle20twotone = () => <SVGAvStopCircle_20_twotone />;
export const IconAvStopCircle24filled = () => <SVGAvStopCircle_24_filled />;
export const IconAvStopCircle20filled = () => <SVGAvStopCircle_20_filled />;
export const IconAvStopCircle24outlined = () => <SVGAvStopCircle_24_outlined />;
export const IconAvStopCircle20outlined = () => <SVGAvStopCircle_20_outlined />;
export const IconAvStopCircle24sharp = () => <SVGAvStopCircle_24_sharp />;
export const IconAvStopCircle20sharp = () => <SVGAvStopCircle_20_sharp />;
