import React from "react";
import SVGAvVideoSettings_24_round from '../../svg/av/AvVideoSettings/24_round.svg';
import SVGAvVideoSettings_20_round from '../../svg/av/AvVideoSettings/20_round.svg';
import SVGAvVideoSettings_24_twotone from '../../svg/av/AvVideoSettings/24_twotone.svg';
import SVGAvVideoSettings_20_twotone from '../../svg/av/AvVideoSettings/20_twotone.svg';
import SVGAvVideoSettings_24_filled from '../../svg/av/AvVideoSettings/24_filled.svg';
import SVGAvVideoSettings_20_filled from '../../svg/av/AvVideoSettings/20_filled.svg';
import SVGAvVideoSettings_24_outlined from '../../svg/av/AvVideoSettings/24_outlined.svg';
import SVGAvVideoSettings_20_outlined from '../../svg/av/AvVideoSettings/20_outlined.svg';
import SVGAvVideoSettings_24_sharp from '../../svg/av/AvVideoSettings/24_sharp.svg';
import SVGAvVideoSettings_20_sharp from '../../svg/av/AvVideoSettings/20_sharp.svg';

export const IconAvVideoSettings24round = () => <SVGAvVideoSettings_24_round />;
export const IconAvVideoSettings20round = () => <SVGAvVideoSettings_20_round />;
export const IconAvVideoSettings24twotone = () => <SVGAvVideoSettings_24_twotone />;
export const IconAvVideoSettings20twotone = () => <SVGAvVideoSettings_20_twotone />;
export const IconAvVideoSettings24filled = () => <SVGAvVideoSettings_24_filled />;
export const IconAvVideoSettings20filled = () => <SVGAvVideoSettings_20_filled />;
export const IconAvVideoSettings24outlined = () => <SVGAvVideoSettings_24_outlined />;
export const IconAvVideoSettings20outlined = () => <SVGAvVideoSettings_20_outlined />;
export const IconAvVideoSettings24sharp = () => <SVGAvVideoSettings_24_sharp />;
export const IconAvVideoSettings20sharp = () => <SVGAvVideoSettings_20_sharp />;
